// Generated once; each tool's file is hand-written content. Keep the import list in step with toolsMeta.ts.
import type { ToolContent } from './types'
export type { ToolContent } from './types'
export { isFilled } from './types'

import { mergePdf } from './merge-pdf'
import { splitPdf } from './split-pdf'
import { organizePdf } from './organize-pdf'
import { rotatePdf } from './rotate-pdf'
import { deletePages } from './delete-pages'
import { extractPages } from './extract-pages'
import { compressPdf } from './compress-pdf'
import { repairPdf } from './repair-pdf'
import { ocrPdf } from './ocr-pdf'
import { pdfReader } from './pdf-reader'
import { pdfToJpg } from './pdf-to-jpg'
import { jpgToPdf } from './jpg-to-pdf'
import { wordToPdf } from './word-to-pdf'
import { excelToPdf } from './excel-to-pdf'
import { htmlToPdf } from './html-to-pdf'
import { pdfToText } from './pdf-to-text'
import { pdfToWord } from './pdf-to-word'
import { pdfToExcel } from './pdf-to-excel'
import { pdfToPpt } from './pdf-to-ppt'
import { pptToPdf } from './ppt-to-pdf'
import { epubToPdf } from './epub-to-pdf'
import { mobiToPdf } from './mobi-to-pdf'
import { signPdf } from './sign-pdf'
import { addWatermark } from './add-watermark'
import { pageNumbers } from './page-numbers'
import { editMetadata } from './edit-metadata'
import { flattenPdf } from './flatten-pdf'
import { removeMetadata } from './remove-metadata'
import { qrCode } from './qr-code'
import { editPdf } from './edit-pdf'
import { cropPdf } from './crop-pdf'
import { pdfForms } from './pdf-forms'
import { redactPdf } from './redact-pdf'
import { comparePdf } from './compare-pdf'
import { scanToPdf } from './scan-to-pdf'
import { pdfToMarkdown } from './pdf-to-markdown'
import { protectPdf } from './protect-pdf'
import { unlockPdf } from './unlock-pdf'
import { pdfToPdfa } from './pdf-to-pdfa'
import { imageConverter } from './image-converter'
import { compressImage } from './compress-image'
import { createZip } from './create-zip'
import { extractZip } from './extract-zip'
import { ebookConverter } from './ebook-converter'

const ALL: ToolContent[] = [mergePdf, splitPdf, organizePdf, rotatePdf, deletePages, extractPages, compressPdf, repairPdf, ocrPdf, pdfReader, pdfToJpg, jpgToPdf, wordToPdf, excelToPdf, htmlToPdf, pdfToText, pdfToWord, pdfToExcel, pdfToPpt, pptToPdf, epubToPdf, mobiToPdf, signPdf, addWatermark, pageNumbers, editMetadata, flattenPdf, removeMetadata, qrCode, editPdf, cropPdf, pdfForms, redactPdf, comparePdf, scanToPdf, pdfToMarkdown, protectPdf, unlockPdf, pdfToPdfa, imageConverter, compressImage, createZip, extractZip, ebookConverter]

export const TOOL_CONTENT: Record<string, ToolContent> = Object.fromEntries(ALL.map((c) => [c.slug, c]))
export const toolContent = (slug: string): ToolContent | undefined => TOOL_CONTENT[slug]
