/**
 * Admin login and session tokens: `pxa_<base64url(JSON)>.<base64url(HMAC-SHA256)>`.
 *
 * Deliberately separate from token.ts. An entitlement proves somebody paid; an admin session can
 * commit to the repository and deploy the site. Different secret, different prefix, different
 * validation, so one can never be presented as the other.
 *
 * Pure Web Crypto, no env access, so it unit-tests under Node. Never log a password or a token.
 */

export interface AdminClaims {
  v: 1
  sub: 'admin'
  iat: number
  exp: number
}

const PREFIX = 'pxa_'
const enc = new TextEncoder()
const dec = new TextDecoder()

/** Twelve hours: long enough to write a post, short enough that a stolen token expires the same day. */
export const SESSION_TTL_SEC = 12 * 60 * 60
const PBKDF2_ITERATIONS = 200_000

export const now = (): number => Math.floor(Date.now() / 1000)

function b64(bytes: Uint8Array): string {
  let bin = ''
  for (const b of bytes) bin += String.fromCharCode(b)
  return btoa(bin)
}
const b64url = (bytes: Uint8Array): string => b64(bytes).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '')

function fromB64(s: string): Uint8Array<ArrayBuffer> {
  const bin = atob(s)
  const out = new Uint8Array(bin.length)
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i)
  return out
}
function fromB64url(s: string): Uint8Array<ArrayBuffer> {
  if (!/^[A-Za-z0-9_-]*$/.test(s)) throw new Error('bad base64url')
  return fromB64(s.replace(/-/g, '+').replace(/_/g, '/') + '='.repeat((4 - (s.length % 4)) % 4))
}

// ---------------------------------------------------------------- password

/** `pbkdf2$<iterations>$<salt b64>$<hash b64>`. Generated by scripts/admin-password.mjs. */
export async function hashPassword(password: string, salt?: Uint8Array, iterations = PBKDF2_ITERATIONS): Promise<string> {
  const s = salt ?? crypto.getRandomValues(new Uint8Array(16))
  const key = await crypto.subtle.importKey('raw', enc.encode(password), 'PBKDF2', false, ['deriveBits'])
  const bits = await crypto.subtle.deriveBits({ name: 'PBKDF2', salt: s, iterations, hash: 'SHA-256' }, key, 256)
  return `pbkdf2$${iterations}$${b64(s)}$${b64(new Uint8Array(bits))}`
}

/**
 * Compares in constant time. A plain `===` on the derived hash leaks how many leading bytes were
 * right, which is enough to reconstruct it one byte at a time given enough attempts.
 */
export async function verifyPassword(password: string, stored: string): Promise<boolean> {
  const parts = stored.split('$')
  if (parts.length !== 4 || parts[0] !== 'pbkdf2') return false
  const iterations = Number(parts[1])
  if (!Number.isInteger(iterations) || iterations < 1000 || iterations > 5_000_000) return false
  let salt: Uint8Array
  let expected: Uint8Array
  try {
    salt = fromB64(parts[2])
    expected = fromB64(parts[3])
  } catch {
    return false
  }
  const candidate = await hashPassword(password, salt, iterations)
  const got = fromB64(candidate.split('$')[3])
  if (got.length !== expected.length) return false
  let diff = 0
  for (let i = 0; i < got.length; i++) diff |= got[i] ^ expected[i]
  return diff === 0
}

// ---------------------------------------------------------------- session

async function hmacKey(secret: string, usage: 'sign' | 'verify'): Promise<CryptoKey> {
  return crypto.subtle.importKey('raw', enc.encode(secret), { name: 'HMAC', hash: 'SHA-256' }, false, [usage])
}

export async function mintSession(secret: string, ttlSec = SESSION_TTL_SEC): Promise<string> {
  const iat = now()
  const payload: AdminClaims = { v: 1, sub: 'admin', iat, exp: iat + ttlSec }
  const body = b64url(enc.encode(JSON.stringify(payload)))
  const sig = await crypto.subtle.sign('HMAC', await hmacKey(secret, 'sign'), enc.encode(body))
  return `${PREFIX}${body}.${b64url(new Uint8Array(sig))}`
}

/**
 * Constant-time signature check, then shape and expiry. `minIat` lets every outstanding session be
 * revoked at once by moving a watermark forward, which is what you want after a laptop goes missing.
 */
export async function verifySession(secret: string, token: string, minIat = 0): Promise<AdminClaims | null> {
  if (typeof token !== 'string' || !token.startsWith(PREFIX) || token.length > 4096) return null
  const rest = token.slice(PREFIX.length)
  const dot = rest.indexOf('.')
  if (dot <= 0 || dot === rest.length - 1) return null
  const body = rest.slice(0, dot)
  let sig: Uint8Array<ArrayBuffer>
  try {
    sig = fromB64url(rest.slice(dot + 1))
  } catch {
    return null
  }
  if (!(await crypto.subtle.verify('HMAC', await hmacKey(secret, 'verify'), sig, enc.encode(body)))) return null

  let claims: Partial<AdminClaims>
  try {
    claims = JSON.parse(dec.decode(fromB64url(body))) as Partial<AdminClaims>
  } catch {
    return null
  }
  if (!claims || claims.v !== 1 || claims.sub !== 'admin') return null
  if (typeof claims.iat !== 'number' || typeof claims.exp !== 'number') return null
  const t = now()
  if (claims.exp <= t || claims.iat < minIat) return null
  return claims as AdminClaims
}
