import type { OutFormat } from '../features/files/engines'

export type ToolAlias = {
  slug: string
  baseSlug: string
  source?: string
  target?: OutFormat
  name: string
  metaTitle: string
  metaDescription: string
  answer: string
  keywords: string[]
  defaultOption?: { key: string; value: string }
}

/** Search-intent landing pages for real image-conversion paths supported by Image Converter. */
export const TOOL_ALIASES: ToolAlias[] = [
  {
    slug: 'heic-to-jpg',
    baseSlug: 'image-converter',
    source: 'HEIC',
    target: 'jpg',
    name: 'HEIC to JPG Converter',
    metaTitle: 'HEIC to JPG Converter, Free and Private Online',
    metaDescription: 'Convert HEIC and HEIF photos to JPG in your browser. No upload, no sign-up, batch conversion, correct rotation, and a ZIP download.',
    answer: 'Convert iPhone HEIC or HEIF photos to JPG in your browser. PrintxPDF decodes the image, respects its rotation, and downloads JPG files without uploading your photos or requiring an account.',
    keywords: ['heic to jpg', 'heic to jpg converter', 'convert heic to jpeg', 'heif to jpg', 'iphone photo to jpg', 'heic to jpg windows'],
  },
  {
    slug: 'heic-to-png',
    baseSlug: 'image-converter',
    source: 'HEIC',
    target: 'png',
    name: 'HEIC to PNG Converter',
    metaTitle: 'HEIC to PNG Converter, Free in Your Browser',
    metaDescription: 'Convert HEIC and HEIF photos to PNG locally in your browser. Keep exact pixels, fix rotation, batch files, and download without uploading photos.',
    answer: 'Turn HEIC or HEIF photos from an iPhone into PNG files in your browser. PNG keeps every pixel, and the conversion stays on your device with no upload or account.',
    keywords: ['heic to png', 'heic to png converter', 'heif to png', 'convert iphone photo to png', 'heic png online'],
  },
  {
    slug: 'heic-to-webp',
    baseSlug: 'image-converter',
    source: 'HEIC',
    target: 'webp',
    name: 'HEIC to WebP Converter',
    metaTitle: 'HEIC to WebP Converter, Free and No Upload',
    metaDescription: 'Convert HEIC and HEIF photos to WebP in your browser. Make smaller web images, keep rotation correct, and process batches privately.',
    answer: 'Convert iPhone HEIC photos to smaller WebP images for websites and apps. PrintxPDF processes them in your browser, lets you choose quality, and never uploads the originals.',
    keywords: ['heic to webp', 'heic to webp converter', 'heif to webp', 'iphone photo webp', 'convert heic for website'],
  },
  {
    slug: 'png-to-jpg',
    baseSlug: 'image-converter',
    source: 'PNG',
    target: 'jpg',
    name: 'PNG to JPG Converter',
    metaTitle: 'PNG to JPG Converter, Free Online and Private',
    metaDescription: 'Convert PNG images to JPG in your browser. Choose quality, turn transparency white, batch files, and download without uploading anything.',
    answer: 'Convert PNG screenshots, graphics, and photos to JPG with a quality setting in your browser. Transparent areas become white because JPG cannot store transparency, and your files stay on your device.',
    keywords: ['png to jpg', 'png to jpg converter', 'convert png to jpeg', 'png to jpg online', 'png image converter'],
  },
  {
    slug: 'jpg-to-png',
    baseSlug: 'image-converter',
    source: 'JPG',
    target: 'png',
    name: 'JPG to PNG Converter',
    metaTitle: 'JPG to PNG Converter, Free in Your Browser',
    metaDescription: 'Convert JPG and JPEG images to PNG in your browser. Process batches locally, keep exact output pixels, and download without an upload.',
    answer: 'Convert JPG or JPEG photos into PNG files in your browser. PNG is useful for screenshots, graphics, and editing workflows, and PrintxPDF keeps the conversion local to your device.',
    keywords: ['jpg to png', 'jpg to png converter', 'jpeg to png', 'convert jpg online', 'jpg png converter'],
  },
  {
    slug: 'webp-to-jpg',
    baseSlug: 'image-converter',
    source: 'WebP',
    target: 'jpg',
    name: 'WebP to JPG Converter',
    metaTitle: 'WebP to JPG Converter, Free and Private',
    metaDescription: 'Convert WebP images to JPG in your browser. Choose quality, batch files, and download compatible JPGs without uploading your images.',
    answer: 'Convert WebP images into widely compatible JPG files for forms, email, printing, and older apps. Choose quality and process the images locally in your browser.',
    keywords: ['webp to jpg', 'webp to jpg converter', 'convert webp to jpeg', 'webp jpg online', 'webp image converter'],
  },
  {
    slug: 'webp-to-png',
    baseSlug: 'image-converter',
    source: 'WebP',
    target: 'png',
    name: 'WebP to PNG Converter',
    metaTitle: 'WebP to PNG Converter, Free Online',
    metaDescription: 'Convert WebP images to PNG in your browser. Keep transparency, process batches, and download without uploading your files.',
    answer: 'Convert WebP graphics and images to PNG when you need broad editing support or a lossless file. The conversion runs in your browser and can keep transparency.',
    keywords: ['webp to png', 'webp to png converter', 'convert webp image to png', 'webp png online', 'webp transparency'],
  },
  {
    slug: 'svg-to-png',
    baseSlug: 'image-converter',
    source: 'SVG',
    target: 'png',
    name: 'SVG to PNG Converter',
    metaTitle: 'SVG to PNG Converter, Free in Your Browser',
    metaDescription: 'Convert SVG logos and drawings to PNG at the size you choose. Keep transparency or add white, with no upload and no sign-up.',
    answer: 'Turn an SVG logo, icon, or drawing into a PNG at an exact width or scale. PrintxPDF rasterises it in your browser, so you control the pixels and your source file stays private.',
    keywords: ['svg to png', 'svg to png converter', 'convert svg to png', 'svg png online', 'svg logo to png'],
  },
  {
    slug: 'svg-to-jpg',
    baseSlug: 'image-converter',
    source: 'SVG',
    target: 'jpg',
    name: 'SVG to JPG Converter',
    metaTitle: 'SVG to JPG Converter, Free and Simple',
    metaDescription: 'Convert SVG logos and drawings to JPG in your browser. Choose the size and quality, with transparent areas rendered white.',
    answer: 'Convert an SVG logo or drawing into a JPG for forms, email, or apps that do not accept vector files. Choose the output size and quality, and transparent areas become white.',
    keywords: ['svg to jpg', 'svg to jpg converter', 'convert svg to jpeg', 'svg jpg online', 'svg logo to jpg'],
  },
  {
    slug: 'pdf-to-png', baseSlug: 'pdf-to-jpg', name: 'PDF to PNG Converter',
    metaTitle: 'PDF to PNG Converter, Free Online',
    metaDescription: 'Convert PDF pages to PNG images in your browser. Choose page quality, export selected pages, and keep your file on your device.',
    answer: 'Convert every page of a PDF into a PNG image for screenshots, documents, slides, or transparent graphics. Choose the resolution and download the pages in your browser.',
    keywords: ['pdf to png', 'pdf to png converter', 'convert pdf to png', 'pdf page to png', 'pdf png online'],
    defaultOption: { key: 'format', value: 'png' },
  },
  {
    slug: 'docx-to-pdf', baseSlug: 'word-to-pdf', name: 'DOCX to PDF Converter',
    metaTitle: 'DOCX to PDF Converter, Free Online',
    metaDescription: 'Convert DOCX Word files to PDF in your browser. Keep text, images and links in a shareable file without uploading the document.',
    answer: 'Turn a DOCX Word document into a PDF that is easier to share, print, and open on any device. The conversion runs in your browser and keeps the document on your computer.',
    keywords: ['docx to pdf', 'docx to pdf converter', 'convert docx to pdf', 'word document to pdf', 'docx pdf online'],
  },
  {
    slug: 'xlsx-to-pdf', baseSlug: 'excel-to-pdf', name: 'XLSX to PDF Converter',
    metaTitle: 'XLSX to PDF Converter, Free Online',
    metaDescription: 'Convert XLSX spreadsheets to PDF in your browser. Export sheets for sharing or printing without uploading your workbook.',
    answer: 'Convert an XLSX Excel workbook into a PDF for sharing, printing, or filing. PrintxPDF reads the sheets in your browser and creates a clean PDF without an account.',
    keywords: ['xlsx to pdf', 'xlsx to pdf converter', 'convert xlsx to pdf', 'excel workbook to pdf', 'spreadsheet to pdf'],
  },
  {
    slug: 'pptx-to-pdf', baseSlug: 'ppt-to-pdf', name: 'PPTX to PDF Converter',
    metaTitle: 'PPTX to PDF Converter, Free Online',
    metaDescription: 'Convert PPTX PowerPoint presentations to PDF securely. Upload one deck, get a shareable PDF, and let the server delete the source after conversion.',
    answer: 'Convert a PPTX PowerPoint presentation into a PDF that is ready to present, print, or send. The server handles the conversion over HTTPS and deletes the source after it returns the PDF.',
    keywords: ['pptx to pdf', 'pptx to pdf converter', 'convert powerpoint to pdf', 'powerpoint presentation to pdf', 'pptx pdf online'],
  },
  {
    slug: 'pdf-to-pptx', baseSlug: 'pdf-to-ppt', name: 'PDF to PPTX Converter',
    metaTitle: 'PDF to PPTX Converter, Free Online',
    metaDescription: 'Convert PDF files to editable PowerPoint PPTX slides. Secure server conversion returns a deck and deletes the uploaded PDF after the job.',
    answer: 'Turn a PDF into a PPTX PowerPoint deck with editable text boxes where the layout can be reconstructed. The file is converted securely and deleted after the result is returned.',
    keywords: ['pdf to pptx', 'pdf to powerpoint', 'pdf to pptx converter', 'convert pdf to powerpoint', 'pdf slides online'],
  },
  {
    slug: 'pdf-to-docx', baseSlug: 'pdf-to-word', name: 'PDF to DOCX Converter',
    metaTitle: 'PDF to DOCX Converter, Free Online',
    metaDescription: 'Convert PDF text into an editable DOCX Word file in your browser. Keep the words, then tidy layout where your document needs it.',
    answer: 'Convert a text-based PDF into a DOCX Word document you can edit. This browser tool prioritises readable text and warns when the original PDF layout, images, or columns cannot be preserved.',
    keywords: ['pdf to docx', 'pdf to docx converter', 'convert pdf to word', 'pdf editable word', 'pdf word online'],
  },
  {
    slug: 'pdf-to-xlsx', baseSlug: 'pdf-to-excel', name: 'PDF to XLSX Converter',
    metaTitle: 'PDF to XLSX Converter, Free Online',
    metaDescription: 'Extract text from PDF pages into an XLSX workbook. Each page becomes a sheet, with no upload and no account required.',
    answer: 'Extract text from a PDF into an XLSX spreadsheet. Each page becomes a worksheet and wide gaps or tabs become cells, which is useful for simple tables and lists.',
    keywords: ['pdf to xlsx', 'pdf to xlsx converter', 'convert pdf to excel', 'pdf spreadsheet converter', 'pdf table to xlsx'],
  },
  {
    slug: 'password-protect-pdf', baseSlug: 'protect-pdf', name: 'Password Protect PDF',
    metaTitle: 'Password Protect PDF, Free Online',
    metaDescription: 'Add a password and strong encryption to a PDF. Secure server conversion deletes the file after returning the protected document.',
    answer: 'Password protect a PDF with strong encryption and optional print or copy restrictions. The protected file is returned over HTTPS, and the uploaded source is deleted after conversion.',
    keywords: ['password protect pdf', 'protect pdf with password', 'encrypt pdf online', 'lock pdf with password', 'pdf password tool'],
  },
  {
    slug: 'remove-pdf-password', baseSlug: 'unlock-pdf', name: 'Remove PDF Password',
    metaTitle: 'Remove PDF Password, Free Online',
    metaDescription: 'Remove a password from a PDF you are allowed to open. Secure conversion returns an unlocked copy and deletes the uploaded file.',
    answer: 'Remove an opening password or usage restriction from a PDF you are authorised to use. Enter the current password when needed, then download the unlocked copy.',
    keywords: ['remove pdf password', 'unlock pdf', 'remove password from pdf', 'decrypt pdf online', 'pdf password remover'],
  },
  {
    slug: 'fillable-pdf', baseSlug: 'pdf-forms', name: 'Fillable PDF Form Filler',
    metaTitle: 'Fillable PDF Form Filler, Free Online',
    metaDescription: 'Fill and save interactive PDF forms in your browser. Type into detected fields, review the answers, and download without uploading the file.',
    answer: 'Fill interactive PDF form fields in your browser, review the answers, and download a completed copy. Your form stays on your device until you choose to save it.',
    keywords: ['fillable pdf', 'fill pdf form', 'pdf form filler', 'fill out pdf online', 'fillable form online'],
  },
  {
    slug: 'annotate-pdf', baseSlug: 'edit-pdf', name: 'Annotate PDF Online',
    metaTitle: 'Annotate PDF Online, Free in Your Browser',
    metaDescription: 'Annotate a PDF with text, shapes, images, and freehand marks. Edit a local copy in your browser and download the finished file.',
    answer: 'Annotate a PDF with notes, text, shapes, pictures, and freehand drawing. Everything is placed on your local copy in the browser, then saved as a downloadable PDF.',
    keywords: ['annotate pdf', 'annotate pdf online', 'pdf markup tool', 'add notes to pdf', 'draw on pdf online'],
  },
  {
    slug: 'extract-text-from-pdf', baseSlug: 'pdf-to-text', name: 'Extract Text from PDF',
    metaTitle: 'Extract Text from PDF, Free Online',
    metaDescription: 'Extract selectable text from a PDF into a TXT file. Run it in your browser, search the result, and keep the original document private.',
    answer: 'Extract selectable text from every page of a PDF into a plain TXT file. The tool keeps the reading order as well as it can and runs locally without uploading the document.',
    keywords: ['extract text from pdf', 'pdf text extractor', 'copy text from pdf', 'pdf to txt', 'extract pdf text online'],
  },
  {
    slug: 'wifi-qr-code', baseSlug: 'qr-code', name: 'WiFi QR Code Generator',
    metaTitle: 'WiFi QR Code Generator, Free and Printable',
    metaDescription: 'Create a WiFi QR code for guests to scan. Choose the network type, size, and colours, then download PNG, SVG, or print-ready PDF.',
    answer: 'Create a scannable WiFi QR code with your network name, password, and security type. Download a crisp SVG, PNG, or print-ready PDF without sending the details to a server.',
    keywords: ['wifi qr code', 'wifi qr code generator', 'wireless password qr', 'guest wifi qr code', 'wifi qr printable'],
    defaultOption: { key: 'kind', value: 'wifi' },
  },
  {
    slug: 'vcard-qr-code', baseSlug: 'qr-code', name: 'vCard QR Code Generator',
    metaTitle: 'vCard QR Code Generator, Free Contact QR',
    metaDescription: 'Create a QR code for a contact card with name, phone, email, and website. Download SVG, PNG, or PDF for cards and signs.',
    answer: 'Create a contact-card QR code that opens a vCard on a phone. Add a name, organisation, phone, email, and website, then download a print-ready SVG, PNG, or PDF.',
    keywords: ['vcard qr code', 'contact qr code', 'business card qr code', 'qr code contact generator', 'digital business card qr'],
    defaultOption: { key: 'kind', value: 'vcard' },
  },
  {
    slug: 'epub-to-mobi', baseSlug: 'ebook-converter', name: 'EPUB to MOBI Converter',
    metaTitle: 'EPUB to MOBI Converter, Free Online',
    metaDescription: 'Convert EPUB ebooks to MOBI for older Kindle readers. Secure server conversion returns the ebook and deletes the uploaded source.',
    answer: 'Convert an EPUB ebook to MOBI for older Kindle software and readers. Choose MOBI in the ebook converter, upload the book securely, and download the result when it is ready.',
    keywords: ['epub to mobi', 'epub to mobi converter', 'convert epub for kindle', 'epub kindle converter', 'ebook to mobi'],
    defaultOption: { key: 'to', value: 'mobi' },
  },
  {
    slug: 'mobi-to-epub', baseSlug: 'ebook-converter', name: 'MOBI to EPUB Converter',
    metaTitle: 'MOBI to EPUB Converter, Free Online',
    metaDescription: 'Convert MOBI ebooks to EPUB for Apple Books, Kobo, and other readers. Secure server conversion deletes the source after the result is returned.',
    answer: 'Convert a MOBI ebook to EPUB for Apple Books, Kobo, Android readers, and modern ebook apps. The server converts the file securely and deletes the source after delivery.',
    keywords: ['mobi to epub', 'mobi to epub converter', 'convert kindle book to epub', 'mobi ebook converter', 'kindle to epub'],
    defaultOption: { key: 'to', value: 'epub' },
  },
  {
    slug: 'azw3-to-epub', baseSlug: 'ebook-converter', name: 'AZW3 to EPUB Converter',
    metaTitle: 'AZW3 to EPUB Converter, Free Online',
    metaDescription: 'Convert AZW3 ebooks to EPUB for compatible readers. Upload securely, choose EPUB, and download the converted book after the server job finishes.',
    answer: 'Convert an AZW3 ebook to EPUB when you need to read it in a non-Kindle app. Select EPUB, send the file over HTTPS, and download the converted book when ready.',
    keywords: ['azw3 to epub', 'azw3 to epub converter', 'convert azw3 ebook', 'kindle azw3 converter', 'azw3 ebook to epub'],
    defaultOption: { key: 'to', value: 'epub' },
  },
]

const ALIASES = new Map(TOOL_ALIASES.map((alias) => [alias.slug, alias]))
export const toolAliasBySlug = (slug: string) => ALIASES.get(slug)
