import type { OutFormat } from '../features/files/engines'

export type ToolAlias = {
  slug: string
  baseSlug: string
  source?: string
  target?: OutFormat
  name: string
  metaTitle: string
  metaDescription: string
  answer: string
  keywords: string[]
  defaultOption?: { key: string; value: string }
}

/** Search-intent landing pages for real image-conversion paths supported by Image Converter. */
export const TOOL_ALIASES: ToolAlias[] = [
  {
    slug: 'heic-to-jpg',
    baseSlug: 'image-converter',
    source: 'HEIC',
    target: 'jpg',
    name: 'HEIC to JPG Converter',
    metaTitle: 'HEIC to JPG Converter, Free and Private Online',
    metaDescription: 'Convert HEIC and HEIF photos to JPG in your browser. No upload, no sign-up, batch conversion, correct rotation, and a ZIP download.',
    answer: 'Convert iPhone HEIC or HEIF photos to JPG in your browser. PrintxPDF decodes the image, respects its rotation, and downloads JPG files without uploading your photos or requiring an account.',
    keywords: ['heic to jpg', 'heic to jpg converter', 'convert heic to jpeg', 'heif to jpg', 'iphone photo to jpg', 'heic to jpg windows'],
  },
  {
    slug: 'heic-to-png',
    baseSlug: 'image-converter',
    source: 'HEIC',
    target: 'png',
    name: 'HEIC to PNG Converter',
    metaTitle: 'HEIC to PNG Converter, Free in Your Browser',
    metaDescription: 'Convert HEIC and HEIF photos to PNG locally in your browser. Keep exact pixels, fix rotation, batch files, and download without uploading photos.',
    answer: 'Turn HEIC or HEIF photos from an iPhone into PNG files in your browser. PNG keeps every pixel, and the conversion stays on your device with no upload or account.',
    keywords: ['heic to png', 'heic to png converter', 'heif to png', 'convert iphone photo to png', 'heic png online'],
  },
  {
    slug: 'heic-to-webp',
    baseSlug: 'image-converter',
    source: 'HEIC',
    target: 'webp',
    name: 'HEIC to WebP Converter',
    metaTitle: 'HEIC to WebP Converter, Free and No Upload',
    metaDescription: 'Convert HEIC and HEIF photos to WebP in your browser. Make smaller web images, keep rotation correct, and process batches privately.',
    answer: 'Convert iPhone HEIC photos to smaller WebP images for websites and apps. PrintxPDF processes them in your browser, lets you choose quality, and never uploads the originals.',
    keywords: ['heic to webp', 'heic to webp converter', 'heif to webp', 'iphone photo webp', 'convert heic for website'],
  },
  {
    slug: 'png-to-jpg',
    baseSlug: 'image-converter',
    source: 'PNG',
    target: 'jpg',
    name: 'PNG to JPG Converter',
    metaTitle: 'PNG to JPG Converter, Free Online and Private',
    metaDescription: 'Convert PNG images to JPG in your browser. Choose quality, turn transparency white, batch files, and download without uploading anything.',
    answer: 'Convert PNG screenshots, graphics, and photos to JPG with a quality setting in your browser. Transparent areas become white because JPG cannot store transparency, and your files stay on your device.',
    keywords: ['png to jpg', 'png to jpg converter', 'convert png to jpeg', 'png to jpg online', 'png image converter'],
  },
  {
    slug: 'jpg-to-png',
    baseSlug: 'image-converter',
    source: 'JPG',
    target: 'png',
    name: 'JPG to PNG Converter',
    metaTitle: 'JPG to PNG Converter, Free in Your Browser',
    metaDescription: 'Convert JPG and JPEG images to PNG in your browser. Process batches locally, keep exact output pixels, and download without an upload.',
    answer: 'Convert JPG or JPEG photos into PNG files in your browser. PNG is useful for screenshots, graphics, and editing workflows, and PrintxPDF keeps the conversion local to your device.',
    keywords: ['jpg to png', 'jpg to png converter', 'jpeg to png', 'convert jpg online', 'jpg png converter'],
  },
  {
    slug: 'webp-to-jpg',
    baseSlug: 'image-converter',
    source: 'WebP',
    target: 'jpg',
    name: 'WebP to JPG Converter',
    metaTitle: 'WebP to JPG Converter, Free and Private',
    metaDescription: 'Convert WebP images to JPG in your browser. Choose quality, batch files, and download compatible JPGs without uploading your images.',
    answer: 'Convert WebP images into widely compatible JPG files for forms, email, printing, and older apps. Choose quality and process the images locally in your browser.',
    keywords: ['webp to jpg', 'webp to jpg converter', 'convert webp to jpeg', 'webp jpg online', 'webp image converter'],
  },
  {
    slug: 'webp-to-png',
    baseSlug: 'image-converter',
    source: 'WebP',
    target: 'png',
    name: 'WebP to PNG Converter',
    metaTitle: 'WebP to PNG Converter, Free Online',
    metaDescription: 'Convert WebP images to PNG in your browser. Keep transparency, process batches, and download without uploading your files.',
    answer: 'Convert WebP graphics and images to PNG when you need broad editing support or a lossless file. The conversion runs in your browser and can keep transparency.',
    keywords: ['webp to png', 'webp to png converter', 'convert webp image to png', 'webp png online', 'webp transparency'],
  },
  {
    slug: 'svg-to-png',
    baseSlug: 'image-converter',
    source: 'SVG',
    target: 'png',
    name: 'SVG to PNG Converter',
    metaTitle: 'SVG to PNG Converter, Free in Your Browser',
    metaDescription: 'Convert SVG logos and drawings to PNG at the size you choose. Keep transparency or add white, with no upload and no sign-up.',
    answer: 'Turn an SVG logo, icon, or drawing into a PNG at an exact width or scale. PrintxPDF rasterises it in your browser, so you control the pixels and your source file stays private.',
    keywords: ['svg to png', 'svg to png converter', 'convert svg to png', 'svg png online', 'svg logo to png'],
  },
  {
    slug: 'svg-to-jpg',
    baseSlug: 'image-converter',
    source: 'SVG',
    target: 'jpg',
    name: 'SVG to JPG Converter',
    metaTitle: 'SVG to JPG Converter, Free and Simple',
    metaDescription: 'Convert SVG logos and drawings to JPG in your browser. Choose the size and quality, with transparent areas rendered white.',
    answer: 'Convert an SVG logo or drawing into a JPG for forms, email, or apps that do not accept vector files. Choose the output size and quality, and transparent areas become white.',
    keywords: ['svg to jpg', 'svg to jpg converter', 'convert svg to jpeg', 'svg jpg online', 'svg logo to jpg'],
  },
  {
    slug: 'pdf-to-png', baseSlug: 'pdf-to-jpg', name: 'PDF to PNG Converter',
    metaTitle: 'PDF to PNG Converter, Free Online',
    metaDescription: 'Convert PDF pages to PNG images in your browser. Choose page quality, export selected pages, and keep your file on your device.',
    answer: 'Convert every page of a PDF into a PNG image for screenshots, documents, slides, or transparent graphics. Choose the resolution and download the pages in your browser.',
    keywords: ['pdf to png', 'pdf to png converter', 'convert pdf to png', 'pdf page to png', 'pdf png online'],
    defaultOption: { key: 'format', value: 'png' },
  },
  {
    slug: 'docx-to-pdf', baseSlug: 'word-to-pdf', name: 'DOCX to PDF Converter',
    metaTitle: 'DOCX to PDF Converter, Free Online',
    metaDescription: 'Convert DOCX Word files to PDF in your browser. Keep text, images and links in a shareable file without uploading the document.',
    answer: 'Turn a DOCX Word document into a PDF that is easier to share, print, and open on any device. The conversion runs in your browser and keeps the document on your computer.',
    keywords: ['docx to pdf', 'docx to pdf converter', 'convert docx to pdf', 'word document to pdf', 'docx pdf online'],
  },
  {
    slug: 'xlsx-to-pdf', baseSlug: 'excel-to-pdf', name: 'XLSX to PDF Converter',
    metaTitle: 'XLSX to PDF Converter, Free Online',
    metaDescription: 'Convert XLSX spreadsheets to PDF in your browser. Export sheets for sharing or printing without uploading your workbook.',
    answer: 'Convert an XLSX Excel workbook into a PDF for sharing, printing, or filing. PrintxPDF reads the sheets in your browser and creates a clean PDF without an account.',
    keywords: ['xlsx to pdf', 'xlsx to pdf converter', 'convert xlsx to pdf', 'excel workbook to pdf', 'spreadsheet to pdf'],
  },
  {
    slug: 'pptx-to-pdf', baseSlug: 'ppt-to-pdf', name: 'PPTX to PDF Converter',
    metaTitle: 'PPTX to PDF Converter, Free Online',
    metaDescription: 'Convert PPTX PowerPoint presentations to PDF securely. Upload one deck, get a shareable PDF, and let the server delete the source after conversion.',
    answer: 'Convert a PPTX PowerPoint presentation into a PDF that is ready to present, print, or send. The server handles the conversion over HTTPS and deletes the source after it returns the PDF.',
    keywords: ['pptx to pdf', 'pptx to pdf converter', 'convert powerpoint to pdf', 'powerpoint presentation to pdf', 'pptx pdf online'],
  },
  {
    slug: 'pdf-to-pptx', baseSlug: 'pdf-to-ppt', name: 'PDF to PPTX Converter',
    metaTitle: 'PDF to PPTX Converter, Free Online',
    metaDescription: 'Convert PDF files to editable PowerPoint PPTX slides. Secure server conversion returns a deck and deletes the uploaded PDF after the job.',
    answer: 'Turn a PDF into a PPTX PowerPoint deck with editable text boxes where the layout can be reconstructed. The file is converted securely and deleted after the result is returned.',
    keywords: ['pdf to pptx', 'pdf to powerpoint', 'pdf to pptx converter', 'convert pdf to powerpoint', 'pdf slides online'],
  },
  {
    slug: 'pdf-to-docx', baseSlug: 'pdf-to-word', name: 'PDF to DOCX Converter',
    metaTitle: 'PDF to DOCX Converter, Free Online',
    metaDescription: 'Convert PDF text into an editable DOCX Word file in your browser. Keep the words, then tidy layout where your document needs it.',
    answer: 'Convert a text-based PDF into a DOCX Word document you can edit. This browser tool prioritises readable text and warns when the original PDF layout, images, or columns cannot be preserved.',
    keywords: ['pdf to docx', 'pdf to docx converter', 'convert pdf to word', 'pdf editable word', 'pdf word online'],
  },
  {
    slug: 'pdf-to-xlsx', baseSlug: 'pdf-to-excel', name: 'PDF to XLSX Converter',
    metaTitle: 'PDF to XLSX Converter, Free Online',
    metaDescription: 'Extract text from PDF pages into an XLSX workbook. Each page becomes a sheet, with no upload and no account required.',
    answer: 'Extract text from a PDF into an XLSX spreadsheet. Each page becomes a worksheet and wide gaps or tabs become cells, which is useful for simple tables and lists.',
    keywords: ['pdf to xlsx', 'pdf to xlsx converter', 'convert pdf to excel', 'pdf spreadsheet converter', 'pdf table to xlsx'],
  },
  {
    slug: 'password-protect-pdf', baseSlug: 'protect-pdf', name: 'Password Protect PDF',
    metaTitle: 'Password Protect PDF, Free Online',
    metaDescription: 'Add a password and strong encryption to a PDF. Secure server conversion deletes the file after returning the protected document.',
    answer: 'Password protect a PDF with strong encryption and optional print or copy restrictions. The protected file is returned over HTTPS, and the uploaded source is deleted after conversion.',
    keywords: ['password protect pdf', 'protect pdf with password', 'encrypt pdf online', 'lock pdf with password', 'pdf password tool'],
  },
  {
    slug: 'remove-pdf-password', baseSlug: 'unlock-pdf', name: 'Remove PDF Password',
    metaTitle: 'Remove PDF Password, Free Online',
    metaDescription: 'Remove a password from a PDF you are allowed to open. Secure conversion returns an unlocked copy and deletes the uploaded file.',
    answer: 'Remove an opening password or usage restriction from a PDF you are authorised to use. Enter the current password when needed, then download the unlocked copy.',
    keywords: ['remove pdf password', 'unlock pdf', 'remove password from pdf', 'decrypt pdf online', 'pdf password remover'],
  },
  {
    slug: 'fillable-pdf', baseSlug: 'pdf-forms', name: 'Fillable PDF Form Filler',
    metaTitle: 'Fillable PDF Form Filler, Free Online',
    metaDescription: 'Fill and save interactive PDF forms in your browser. Type into detected fields, review the answers, and download without uploading the file.',
    answer: 'Fill interactive PDF form fields in your browser, review the answers, and download a completed copy. Your form stays on your device until you choose to save it.',
    keywords: ['fillable pdf', 'fill pdf form', 'pdf form filler', 'fill out pdf online', 'fillable form online'],
  },
  {
    slug: 'annotate-pdf', baseSlug: 'edit-pdf', name: 'Annotate PDF Online',
    metaTitle: 'Annotate PDF Online, Free in Your Browser',
    metaDescription: 'Annotate a PDF with text, shapes, images, and freehand marks. Edit a local copy in your browser and download the finished file.',
    answer: 'Annotate a PDF with notes, text, shapes, pictures, and freehand drawing. Everything is placed on your local copy in the browser, then saved as a downloadable PDF.',
    keywords: ['annotate pdf', 'annotate pdf online', 'pdf markup tool', 'add notes to pdf', 'draw on pdf online'],
  },
  {
    slug: 'extract-text-from-pdf', baseSlug: 'pdf-to-text', name: 'Extract Text from PDF',
    metaTitle: 'Extract Text from PDF, Free Online',
    metaDescription: 'Extract selectable text from a PDF into a TXT file. Run it in your browser, search the result, and keep the original document private.',
    answer: 'Extract selectable text from every page of a PDF into a plain TXT file. The tool keeps the reading order as well as it can and runs locally without uploading the document.',
    keywords: ['extract text from pdf', 'pdf text extractor', 'copy text from pdf', 'pdf to txt', 'extract pdf text online'],
  },
  {
    slug: 'wifi-qr-code', baseSlug: 'qr-code', name: 'WiFi QR Code Generator',
    metaTitle: 'WiFi QR Code Generator, Free and Printable',
    metaDescription: 'Create a WiFi QR code for guests to scan. Choose the network type, size, and colours, then download PNG, SVG, or print-ready PDF.',
    answer: 'Create a scannable WiFi QR code with your network name, password, and security type. Download a crisp SVG, PNG, or print-ready PDF without sending the details to a server.',
    keywords: ['wifi qr code', 'wifi qr code generator', 'wireless password qr', 'guest wifi qr code', 'wifi qr printable'],
    defaultOption: { key: 'kind', value: 'wifi' },
  },
  {
    slug: 'vcard-qr-code', baseSlug: 'qr-code', name: 'vCard QR Code Generator',
    metaTitle: 'vCard QR Code Generator, Free Contact QR',
    metaDescription: 'Create a QR code for a contact card with name, phone, email, and website. Download SVG, PNG, or PDF for cards and signs.',
    answer: 'Create a contact-card QR code that opens a vCard on a phone. Add a name, organisation, phone, email, and website, then download a print-ready SVG, PNG, or PDF.',
    keywords: ['vcard qr code', 'contact qr code', 'business card qr code', 'qr code contact generator', 'digital business card qr'],
    defaultOption: { key: 'kind', value: 'vcard' },
  },
  {
    slug: 'epub-to-mobi', baseSlug: 'ebook-converter', name: 'EPUB to MOBI Converter',
    metaTitle: 'EPUB to MOBI Converter, Free Online',
    metaDescription: 'Convert EPUB ebooks to MOBI for older Kindle readers. Secure server conversion returns the ebook and deletes the uploaded source.',
    answer: 'Convert an EPUB ebook to MOBI for older Kindle software and readers. Choose MOBI in the ebook converter, upload the book securely, and download the result when it is ready.',
    keywords: ['epub to mobi', 'epub to mobi converter', 'convert epub for kindle', 'epub kindle converter', 'ebook to mobi'],
    defaultOption: { key: 'to', value: 'mobi' },
  },
  {
    slug: 'mobi-to-epub', baseSlug: 'ebook-converter', name: 'MOBI to EPUB Converter',
    metaTitle: 'MOBI to EPUB Converter, Free Online',
    metaDescription: 'Convert MOBI ebooks to EPUB for Apple Books, Kobo, and other readers. Secure server conversion deletes the source after the result is returned.',
    answer: 'Convert a MOBI ebook to EPUB for Apple Books, Kobo, Android readers, and modern ebook apps. The server converts the file securely and deletes the source after delivery.',
    keywords: ['mobi to epub', 'mobi to epub converter', 'convert kindle book to epub', 'mobi ebook converter', 'kindle to epub'],
    defaultOption: { key: 'to', value: 'epub' },
  },
  {
    slug: 'azw3-to-epub', baseSlug: 'ebook-converter', name: 'AZW3 to EPUB Converter',
    metaTitle: 'AZW3 to EPUB Converter, Free Online',
    metaDescription: 'Convert AZW3 ebooks to EPUB for compatible readers. Upload securely, choose EPUB, and download the converted book after the server job finishes.',
    answer: 'Convert an AZW3 ebook to EPUB when you need to read it in a non-Kindle app. Select EPUB, send the file over HTTPS, and download the converted book when ready.',
    keywords: ['azw3 to epub', 'azw3 to epub converter', 'convert azw3 ebook', 'kindle azw3 converter', 'azw3 ebook to epub'],
    defaultOption: { key: 'to', value: 'epub' },
  },
  {
    slug: 'epub-to-azw3', baseSlug: 'ebook-converter', name: 'EPUB to AZW3 Converter',
    metaTitle: 'EPUB to AZW3 Converter, Free Online',
    metaDescription: 'Convert EPUB ebooks to AZW3 for Kindle devices. Choose AZW3 in the secure ebook converter and download the result after conversion.',
    answer: 'Convert an EPUB ebook to AZW3 for newer Kindle devices and apps. Select AZW3, upload the book securely, and download the converted file when the server job finishes.',
    keywords: ['epub to azw3', 'epub to azw3 converter', 'convert epub for kindle', 'epub kindle azw3', 'ebook to azw3'],
    defaultOption: { key: 'to', value: 'azw3' },
  },
  {
    slug: 'fb2-to-epub', baseSlug: 'ebook-converter', name: 'FB2 to EPUB Converter',
    metaTitle: 'FB2 to EPUB Converter, Free Online',
    metaDescription: 'Convert FB2 ebooks to EPUB for phones, tablets, Kobo, and Apple Books. Secure conversion returns the EPUB and deletes the source.',
    answer: 'Convert an FB2 ebook to EPUB so it opens in modern reading apps such as Apple Books, Kobo, and Android readers. The source is sent securely and deleted after conversion.',
    keywords: ['fb2 to epub', 'fb2 to epub converter', 'convert fb2 ebook', 'fb2 ebook converter', 'fb2 epub online'],
    defaultOption: { key: 'to', value: 'epub' },
  },
  {
    slug: 'azw3-to-pdf', baseSlug: 'mobi-to-pdf', name: 'AZW3 to PDF Converter',
    metaTitle: 'AZW3 to PDF Converter, Free Online',
    metaDescription: 'Convert AZW3 Kindle ebooks to PDF for printing and offline reading. Secure server conversion returns the PDF and deletes the source.',
    answer: 'Convert an AZW3 Kindle ebook into a fixed-page PDF for printing, quoting, or offline reading. Upload securely and download the PDF after the conversion completes.',
    keywords: ['azw3 to pdf', 'azw3 to pdf converter', 'kindle azw3 to pdf', 'convert azw3 ebook to pdf', 'azw3 pdf online'],
  },
  {
    slug: 'kindle-to-pdf', baseSlug: 'mobi-to-pdf', name: 'Kindle to PDF Converter',
    metaTitle: 'Kindle to PDF Converter, Free Online',
    metaDescription: 'Convert supported Kindle ebook files to PDF for printing or sharing. Secure conversion deletes the source after returning the finished PDF.',
    answer: 'Convert a supported Kindle ebook file such as MOBI, AZW, or AZW3 into a fixed-page PDF. The conversion is secure and the uploaded source is deleted after delivery.',
    keywords: ['kindle to pdf', 'kindle book to pdf', 'kindle pdf converter', 'convert kindle ebook to pdf', 'ebook to pdf kindle'],
  },
  {
    slug: 'compress-jpg', baseSlug: 'compress-image', name: 'Compress JPG Image',
    metaTitle: 'Compress JPG Images, Free and Private',
    metaDescription: 'Compress JPG photos in your browser. Choose quality, preview the size change, and download smaller images without uploading them.',
    answer: 'Make JPG photos smaller for email, forms, and websites. Choose a quality level, preview the result, and download it locally without uploading the original.',
    keywords: ['compress jpg', 'compress jpg image', 'reduce jpg file size', 'jpg compressor online', 'make jpg smaller'],
  },
  {
    slug: 'compress-png', baseSlug: 'compress-image', name: 'Compress PNG Image',
    metaTitle: 'Compress PNG Images, Free in Your Browser',
    metaDescription: 'Compress PNG screenshots, graphics, and logos locally in your browser. Set a size limit and keep your files private.',
    answer: 'Reduce PNG file sizes for websites and sharing while keeping screenshots and graphics sharp. The browser compressor previews the result and never uploads the source.',
    keywords: ['compress png', 'compress png image', 'reduce png file size', 'png compressor online', 'make png smaller'],
  },
  {
    slug: 'compress-webp', baseSlug: 'compress-image', name: 'Compress WebP Image',
    metaTitle: 'Compress WebP Images, Free Online',
    metaDescription: 'Compress WebP images in your browser for faster websites and smaller uploads. Preview the result before downloading.',
    answer: 'Shrink WebP images for faster websites and smaller uploads. Choose quality or a maximum size, compare before and after, and keep the file on your device.',
    keywords: ['compress webp', 'compress webp image', 'reduce webp file size', 'webp compressor', 'make webp smaller'],
  },
  {
    slug: 'resize-image', baseSlug: 'compress-image', name: 'Resize Image Online',
    metaTitle: 'Resize Images Online, Free and Private',
    metaDescription: 'Resize JPG, PNG, WebP, and HEIC images in your browser. Set a maximum size, preview the result, and download privately.',
    answer: 'Resize photos and graphics to a smaller width or height in your browser. PrintxPDF supports common image formats, previews the result, and does not upload your files.',
    keywords: ['resize image', 'resize image online', 'image resizer free', 'resize jpg png', 'reduce image dimensions'],
  },
  {
    slug: 'image-to-text', baseSlug: 'ocr-pdf', name: 'Image to Text Converter',
    metaTitle: 'Image to Text Converter, Free OCR Online',
    metaDescription: 'Extract text from a scanned image or photo with browser OCR. Make words searchable and keep the image on your device.',
    answer: 'Extract readable text from a photo, screenshot, or scanned page with OCR. PrintxPDF recognises the image in your browser and creates a searchable result without uploading it.',
    keywords: ['image to text', 'image to text converter', 'extract text from image', 'ocr image online', 'photo to text'],
  },
  {
    slug: 'electronic-signature-pdf', baseSlug: 'sign-pdf', name: 'Electronic Signature PDF',
    metaTitle: 'Electronic Signature PDF, Free Online',
    metaDescription: 'Add an electronic signature to a PDF by drawing, typing, or uploading it. Place it on the page and download privately.',
    answer: 'Add an electronic signature to a PDF by drawing, typing, or uploading a signature image. Place it where it belongs, add the date, and download the signed copy in your browser.',
    keywords: ['electronic signature pdf', 'esign pdf', 'sign pdf electronically', 'digital signature pdf online', 'e signature document'],
  },
  {
    slug: 'qr-code-svg', baseSlug: 'qr-code', name: 'QR Code SVG Generator',
    metaTitle: 'QR Code SVG Generator, Free and Print Ready',
    metaDescription: 'Generate a scalable QR code SVG for signs, packaging, and print. Set colours and quiet-zone margin, then download without an upload.',
    answer: 'Generate a scalable SVG QR code for print, signs, labels, and packaging. Enter a link or message, set the colours, and download a vector file directly in your browser.',
    keywords: ['qr code svg', 'svg qr code generator', 'vector qr code', 'print qr code svg', 'scalable qr code'],
  },
  {
    slug: 'email-qr-code', baseSlug: 'qr-code', name: 'Email QR Code Generator',
    metaTitle: 'Email QR Code Generator, Free Online',
    metaDescription: 'Create an email QR code with a recipient, subject, and message. Download PNG, SVG, or print-ready PDF without sending the details anywhere.',
    answer: 'Create a QR code that opens a pre-filled email when scanned. Add the recipient, subject, and message, then download PNG, SVG, or PDF from your browser.',
    keywords: ['email qr code', 'email qr code generator', 'mailto qr code', 'qr code for email', 'scan to email qr'],
    defaultOption: { key: 'kind', value: 'email' },
  },
  {
    slug: 'document-scanner', baseSlug: 'scan-to-pdf', name: 'Online Document Scanner',
    metaTitle: 'Online Document Scanner, Free to PDF',
    metaDescription: 'Scan documents with your phone camera or webcam and save multiple pages as a PDF. Adjust contrast locally with no upload.',
    answer: 'Use your phone camera or webcam as an online document scanner. Capture multiple pages, improve contrast, and save one PDF while the images stay in your browser.',
    keywords: ['document scanner online', 'online document scanner', 'scan document to pdf', 'phone document scanner', 'webcam scanner'],
  },
  {
    slug: 'remove-author-from-pdf', baseSlug: 'remove-metadata', name: 'Remove Author from PDF',
    metaTitle: 'Remove Author from PDF Metadata, Free',
    metaDescription: 'Remove the author name and other hidden PDF metadata before sharing. Clean the file in your browser without uploading it.',
    answer: 'Remove the author name, application, dates, and other hidden metadata from a PDF before sharing. The cleaned copy is created in your browser and stays on your device.',
    keywords: ['remove author from pdf', 'delete pdf author', 'pdf author metadata', 'remove name from pdf properties', 'clean pdf metadata'],
  },
  {
    slug: 'number-pdf-pages', baseSlug: 'page-numbers', name: 'Number PDF Pages',
    metaTitle: 'Number PDF Pages, Free Online',
    metaDescription: 'Add page numbers to a PDF with custom position, style, and starting number. Skip the cover and download the numbered file privately.',
    answer: 'Number every page in a PDF with the position, style, and starting number you choose. Leave a cover page blank if needed and download the result in your browser.',
    keywords: ['number pdf pages', 'pdf page numbering', 'add page numbers pdf', 'number pages online', 'pdf page number tool'],
  },
  {
    slug: 'crop-pdf-for-kindle', baseSlug: 'crop-pdf', name: 'Crop PDF for Kindle',
    metaTitle: 'Crop PDF for Kindle, Free Online',
    metaDescription: 'Crop white margins from a PDF for Kindle and small screens. Trim every page in your browser and download the cleaner document.',
    answer: 'Crop excess white margins from a PDF so pages use more of a Kindle or small screen. Auto-trim the document in your browser and download the cropped copy.',
    keywords: ['crop pdf for kindle', 'kindle pdf crop', 'remove margins pdf kindle', 'crop pdf for ereader', 'pdf margins kindle'],
  },
  {
    slug: 'combine-pdf', baseSlug: 'merge-pdf', name: 'Combine PDF Files',
    metaTitle: 'Combine PDF Files, Free Online',
    metaDescription: 'Combine multiple PDF files into one ordered document. Drag pages into place and merge locally without uploading the files.',
    answer: 'Combine multiple PDF files into one ordered document. Add the files, arrange their order, and download the merged PDF while everything stays in your browser.',
    keywords: ['combine pdf', 'combine pdf files', 'join pdf files', 'merge multiple pdfs', 'combine pdf online'],
  },
  {
    slug: 'csv-to-pdf', baseSlug: 'excel-to-pdf', name: 'CSV to PDF Converter',
    metaTitle: 'CSV to PDF Converter, Free Online',
    metaDescription: 'Convert CSV files to a shareable PDF in your browser. Format the spreadsheet output without uploading the data or creating an account.',
    answer: 'Convert a CSV table into a PDF that is easier to send, print, or archive. PrintxPDF reads the file in your browser and creates the PDF without uploading the data.',
    keywords: ['csv to pdf', 'csv to pdf converter', 'convert csv to pdf', 'csv file to pdf', 'spreadsheet csv pdf'],
  },
]

const ALIASES = new Map(TOOL_ALIASES.map((alias) => [alias.slug, alias]))
export const toolAliasBySlug = (slug: string) => ALIASES.get(slug)
