import type { Cluster } from '../types'

export const archiveDocuments: Cluster = {
  slug: 'archive',
  name: 'Archiving documents for the long term',
  title: 'How to make a document that still opens in twenty years',
  metaTitle: 'Archive Documents: PDF/A, Scanning and Formats That Last',
  metaDescription:
    'Make documents that still open decades from now: PDF/A with fonts embedded, clean scans of paper, Markdown for text, and which formats actually survive.',
  intro:
    'A document survives two separate hazards. The bytes have to still be somewhere, and some program has to still know how to read them. Most people worry about the disk and lose the file to the format. These guides cover the four jobs that fix the second problem: converting a PDF into PDF/A so it carries its own fonts, getting paper into a clean digital page, pulling text out into plain Markdown that any editor can read, and choosing formats that will not need their own museum in fifteen years.',
  answer:
    'Store anything where the layout matters as PDF/A, which embeds its fonts and forbids scripts, encryption and outside references. Store anything that is really just text as Markdown or plain UTF-8 text. Scan paper before it fades, run OCR on it, and keep at least two copies in different places.',
  primaryKeyword: 'how to archive documents',
  entities: ['PDF/A', 'ISO 19005', 'ISO 32000', 'Adobe Acrobat', 'Markdown', 'UTF-8', 'Office Open XML', 'veraPDF', 'OCR'],
  icon: '⌛',
  tools: ['pdf-to-pdfa', 'scan-to-pdf', 'pdf-to-markdown', 'ocr-pdf'],
  posts: [
    {
      slug: 'what-is-pdfa',
      cluster: 'archive',
      title: 'What is PDF/A, and when do you actually need it?',
      metaTitle: 'What Is PDF/A? The Archive-Safe PDF Explained',
      metaDescription:
        'PDF/A is the archival version of PDF: fonts embedded, no scripts, no encryption, no outside references. Who requires it, and why an ordinary PDF can rot.',
      published: '2026-02-06',
      updated: '2026-08-21',
      readMinutes: 7,
      intent: 'informational',
      primaryKeyword: 'what is pdf/a',
      secondaryKeywords: ['pdf/a vs pdf', 'convert pdf to pdf/a', 'pdf/a-1b vs pdf/a-2b', 'archival pdf format', 'pdf/a compliance'],
      entities: ['PDF/A', 'ISO 19005', 'ISO 32000', 'Adobe Acrobat', 'veraPDF', 'XMP', 'ICC colour profile', 'Factur-X'],
      answer:
        'PDF/A is a restricted version of PDF made for long-term storage. It must carry every font it uses inside the file, and it cannot contain JavaScript, encryption or links to content stored elsewhere. That means it renders the same way decades later, on a machine that has none of your fonts installed.',
      body: [
        { t: 'p', x: 'A PDF names the fonts a page uses, but it does not have to carry them. If the file only says "this line is set in Helvetica Neue" and the computer opening it in 2046 has never heard of that font, the reader quietly picks something close. The letters change width, the lines rewrap, and the table that fitted neatly on page 4 now runs off the edge. Nothing warns you. PDF/A is the version of PDF that removes that gamble, along with every other way a file can depend on something outside itself.' },
        { t: 'h2', x: 'What PDF/A actually changes' },
        { t: 'p', x: 'PDF/A is not a different file type. The file still ends in .pdf, still opens in any reader, still prints the same. What changes is what the file is allowed to contain. The standard is ISO 19005, and it reads mostly as a list of bans, each one closing off a way the document could stop rendering correctly.' },
        {
          t: 'table',
          caption: 'The main PDF/A rules and the failure each one prevents.',
          head: ['Rule', 'What it means', 'What it prevents'],
          rows: [
            ['Fonts must be embedded', 'Every glyph the document draws is stored inside the file', 'Substituted fonts that change spacing, line breaks and page count'],
            ['No JavaScript', 'An ordinary PDF can run scripts; a PDF/A cannot', 'Pages that need code a future reader refuses to run'],
            ['No encryption', 'The file cannot be password protected in any form', 'A document nobody can open because the password died with someone'],
            ['No external references', 'No streamed video, no linked images, no pointers to other files', 'Empty boxes where content used to be fetched from'],
            ['Colour must be defined', 'An embedded ICC profile or device-independent colour is required', 'Colours drifting between one screen, one printer and the next'],
            ['Metadata as XMP', 'Title, author and dates stored in a documented text format inside the file', 'Catalogue information only one particular program can read'],
            ['No LZW compression', 'An older compression method is disallowed', 'Data that needs a specific legacy decoder to unpack'],
          ],
        },
        { t: 'h2', x: 'Who actually asks for it' },
        { t: 'p', x: 'PDF/A is rarely something you choose for yourself. It is something an organisation asks for, usually in one line of a submission checklist with no explanation attached. The common requesters:' },
        {
          t: 'ul',
          items: [
            '**Courts and electronic filing systems.** Many e-filing portals accept only PDF/A and reject anything else at upload, because a court record has to render identically to a judge in ten years as it did to the clerk today.',
            '**Government submissions.** Planning applications, regulatory filings, tender documents and public records offices frequently specify PDF/A-1b by name.',
            '**Academic journals and universities.** Thesis deposit is the usual one. Most university libraries require the final PDF in PDF/A because they are committing to hold it indefinitely.',
            '**Corporate records retention.** Contracts, audit files and anything with a legal retention period of seven years or more. The auditor cares that the document looks the same each time it is produced.',
            '**Engineering and construction record sets.** As-built drawings outlive the software that drew them by decades.',
            '**Electronic invoicing.** PDF/A-3 is allowed to embed other files, which is how formats like Factur-X put a machine-readable XML invoice inside a human-readable PDF.',
          ],
        },
        { t: 'h2', x: 'The parts and levels, in plain terms' },
        { t: 'p', x: 'PDF/A comes in numbered parts, and each part has conformance levels marked with a letter. The number says which version of PDF it is built on. The letter says how strict the text and structure requirements are.' },
        {
          t: 'table',
          caption: 'PDF/A parts and conformance levels.',
          head: ['Name', 'Built on', 'What it gives you'],
          rows: [
            ['PDF/A-1b', 'PDF 1.4, published 2005', 'The strictest and most widely accepted. No transparency, no layers. "b" means basic: the page will look right.'],
            ['PDF/A-1a', 'PDF 1.4', 'Everything in 1b plus tagging and Unicode mapping, so a screen reader can follow the reading order.'],
            ['PDF/A-2b', 'PDF 1.7, published 2011', 'Allows transparency, layers and JPEG 2000 images. A sensible default for files made by modern software.'],
            ['PDF/A-2u', 'PDF 1.7', '2b plus a guarantee that every glyph maps to a real Unicode character, so the text copies out correctly.'],
            ['PDF/A-3b', 'PDF 1.7, published 2012', '2b plus permission to embed arbitrary files, used almost entirely for e-invoicing.'],
            ['PDF/A-4', 'PDF 2.0, published 2020', 'The newest part. Fine in current software, but older readers and validators know less about it.'],
          ],
        },
        { t: 'p', x: 'If someone has asked for PDF/A without saying which, ask them. If you cannot ask, PDF/A-2b is the safe middle: modern enough to survive a document containing a drop shadow or a transparent logo, strict enough that almost any checker will pass it. If the request came from a court or a national archive, they usually mean PDF/A-1b, and a file with transparency in it will have to be flattened before it converts cleanly.' },
        { t: 'h2', x: 'Converting a PDF to PDF/A' },
        {
          t: 'ol',
          items: [
            'Remove any password first. PDF/A forbids encryption outright, so a protected file cannot be converted until the protection comes off with [unlock PDF](/tools/unlock-pdf).',
            'Run the file through [PDF to PDF/A](/tools/pdf-to-pdfa) and pick the level you were asked for.',
            'Open the result and read the first page, the last page, and any page with a table or a form on it. Font trouble during conversion is the one failure you can see with your own eyes.',
            'Check the document properties in your reader. A converted file states its conformance there, for example "PDF/A-2b".',
            'Keep the original as well as the converted copy, at least until whoever asked for it has accepted it.',
          ],
        },
        { t: 'cta', tool: 'pdf-to-pdfa', x: 'Convert a PDF to PDF/A for a court, a journal or a records system.' },
        { t: 'note', x: 'PDF to PDF/A is one of our server tools, because the conversion needs a font and colour engine far too heavy to run inside a browser tab. The file is uploaded over a secure connection, converted on our server, and deleted the moment it finishes. Free accounts get 5 server conversions a month, Pro and Lifetime 300 each, and API keys 5,000. Files up to 100 MB, two minutes per job. The other tools in this cluster run entirely in your browser and upload nothing at all.' },
        { t: 'h2', x: 'How an ordinary PDF rots' },
        { t: 'p', x: 'There are two failure modes, and only one of them is obvious. The first is font substitution. A PDF that references a font without embedding it renders with whatever the reader can find instead. Metrics differ, so the substitute is wider or narrower, and text that was set to fit a box no longer fits it. Symbol fonts are worse than text fonts: a tick box set in a custom dingbat font can come back as a random letter, which turns a completed checklist into nonsense that still looks deliberate.' },
        { t: 'p', x: 'The second is subtler, and it is why the "u" and "a" levels exist. A font can be embedded as a subset with its own private numbering, where the shape of the letter "a" is stored as glyph 17 with nothing recording that glyph 17 means "a". The page draws perfectly forever. But select the text, copy it, and you get gibberish. No search index, no archive catalogue and no future reader will ever find the document by its own words. It has become a picture of itself.' },
        { t: 'warn', x: 'PDF/A is a promise about rendering, not about content. Converting a scanned page to PDF/A archives the photograph of the text, not the text. If nobody has run [OCR](/tools/ocr-pdf) on it first, the archived file is exactly as unsearchable as it was before. Do the OCR, then convert. [Making a PDF searchable](/blog/ocr/make-pdf-searchable) covers the order and what it costs in file size.' },
        { t: 'h2', x: 'What PDF/A does not do' },
        {
          t: 'ul',
          items: [
            '**It does not stop editing.** PDF/A is not a lock and not a signature. Anyone can open the file and change it, and the result is still a valid PDF/A.',
            '**It does not make anything searchable.** That is OCR, and it is a separate job done first.',
            '**It does not shrink files.** Embedding fonts usually grows them, typically by 50 KB to a few hundred KB per font family. A file that referenced six fonts can gain a megabyte.',
            '**It does not repair damage.** A file with a broken cross-reference table will fail conversion rather than be fixed by it. Run [repair](/tools/repair-pdf) first, convert the repaired copy.',
            '**It does not guarantee acceptance.** Some organisations run their own validator, veraPDF being the common open one, and add house rules on top of the standard, such as a required title in the metadata.',
          ],
        },
        { t: 'p', x: 'The honest summary: PDF/A costs you a conversion step and some file size, and buys you a document that renders the same on a machine that shares nothing with yours. For a receipt, do not bother. For anything you will be asked to produce again in ten years, do it once, now, while you still have the original.' },
      ],
      faqs: [
        { q: 'What is the difference between PDF and PDF/A?', a: 'A PDF/A is a PDF that follows extra rules. It must embed every font it uses, and it cannot contain JavaScript, encryption, audio, video or references to files stored elsewhere. An ordinary PDF may do all of those things, and each one is a way for the file to stop rendering correctly later.' },
        { q: 'Which PDF/A level should I use?', a: 'Use whichever level you were asked for. If nobody said, PDF/A-2b is the safe default: it allows transparency and layers, so modern files convert without being flattened. Courts and national archives usually want PDF/A-1b, which is stricter.' },
        { q: 'Does converting to PDF/A make the file bigger?', a: 'Usually yes. Fonts that were only referenced now have to be stored inside the file, which adds roughly 50 KB to a few hundred KB per font family. Colour profiles add a little more. A text-heavy report might grow by a megabyte.' },
        { q: 'Can a PDF/A file be password protected?', a: 'No. Encryption is banned by the standard, because a password is exactly the kind of outside dependency archiving is meant to remove. Remove the password before converting, and protect the file through where you store it instead.' },
        { q: 'Is a scanned document in PDF/A searchable?', a: 'Only if OCR was run before the conversion. PDF/A preserves whatever the file contained, and a raw scan contains an image of a page, not text. Run OCR first, check the text layer, then convert.' },
      ],
      relatedTools: ['pdf-to-pdfa', 'ocr-pdf', 'repair-pdf'],
      relatedPosts: ['will-this-file-still-open', 'scan-paper-to-pdf', 'make-pdf-searchable'],
    },
    {
      slug: 'scan-paper-to-pdf',
      cluster: 'archive',
      title: 'How to scan paper to PDF with a phone and get a clean result',
      metaTitle: 'How to Scan Paper to PDF With Your Phone',
      metaDescription:
        'Turn phone photos of paper into a straight, evenly lit, readable PDF. Capture mistakes that ruin a scan, how to fix each one, and how to make it searchable.',
      published: '2026-03-12',
      updated: '2026-08-30',
      readMinutes: 7,
      intent: 'howto',
      primaryKeyword: 'scan paper to pdf',
      secondaryKeywords: ['scan documents with phone', 'photo of document to pdf', 'how to scan without a scanner', 'phone scanner pdf', 'scan a page to pdf free'],
      entities: ['DPI', 'A4', 'OCR', 'Adobe Acrobat', 'macOS Preview', 'JPEG', 'Tesseract'],
      answer:
        'Lay the page flat under even light, hold the phone directly above it and parallel to the paper, and let the page fill the frame. Then crop each photo to the page edges and save them as one PDF. Geometry and lighting decide the result; no amount of processing afterwards recovers a shadowed, tilted photo.',
      body: [
        { t: 'p', x: 'A flatbed scanner does three things a phone does not: it holds the page perfectly flat, lights it evenly across its whole surface, and looks at it dead straight. Every bad document photo you have ever taken failed at one of those three. Fix the geometry and the light at the moment you press the button and the software has almost nothing left to do. Get them wrong and no contrast slider will save you, because the information is not in the photograph.' },
        { t: 'h2', x: 'Reading a bad page photo backwards to its cause' },
        {
          t: 'table',
          caption: 'Every common scan fault, what caused it, and the fix at capture time.',
          head: ['What you see', 'Cause', 'Fix'],
          rows: [
            ['The page is a trapezium, wider at the bottom', 'The camera was tilted rather than parallel to the page', 'Hold the phone flat above the page, centred on it, screen parallel to the paper'],
            ['A grey band down one side', 'Your own head and shoulders are between the light and the paper', 'Turn ninety degrees so the light crosses the page rather than coming over your shoulder'],
            ['A bright blob in the middle', 'Flash, or a ceiling light bouncing off coated paper', 'Flash off, and move the light source to one side'],
            ['Sharp at the top, soft at the bottom', 'The phone was close and angled, so only part of the page was in the focal plane', 'Step back, raise the phone, tap the middle of the page to focus'],
            ['Curved lines near the spine', 'A bound book that will not lie flat', 'Press the page down at the gutter, or photograph one page at a time with the book fully open'],
            ['Grey, muddy background instead of white', 'Low light, so the camera raised its sensitivity and added noise', 'Add light rather than brightening the photo afterwards'],
            ['Bowed edges on a page that was flat', 'The ultra-wide lens and its barrel distortion', 'Switch to the main 1x camera'],
          ],
        },
        { t: 'h2', x: 'Taking the photos' },
        {
          t: 'steps',
          items: [
            { h: 'Clear a flat, matt surface', x: 'A wooden table beats a white one, because the contrast at the edge is what the crop tool looks for. Weigh down curled corners with a coin at each side, placed outside the printed area.' },
            { h: 'Get the light across the page', x: 'Daylight from a window with the window to your left or right, never behind you. Two lamps at opposite sides beat one lamp anywhere. Flash off, always: a phone flash sits next to the lens, so it puts its brightest spot exactly where you are looking.' },
            { h: 'Stand over the page, not beside it', x: 'Hold the phone directly above the centre with the screen parallel to the paper. A quick test: if the top edge of the page looks longer than the bottom edge on screen, you are tilted. Straighten until they match.' },
            { h: 'Fill the frame', x: 'Let the page fill the frame with a thin margin of table visible all round. An A4 page at 300 DPI is 2480 by 3508 pixels, about 8.7 megapixels, so a 12 megapixel camera clears it comfortably. Held at twice the distance you get a quarter of the pixels on the page, and OCR starts guessing.' },
            { h: 'Shoot every page the same way', x: 'Do not move the light or change your height between pages. Consistency means one contrast setting works for the whole document instead of twenty individual adjustments.' },
            { h: 'Build the PDF', x: 'Open [scan to PDF](/tools/scan-to-pdf), add the photos in page order, crop each one to the page edges, then set contrast and colour mode. Save the lot as a single PDF.' },
          ],
        },
        { t: 'cta', tool: 'scan-to-pdf', x: 'Turn photos of paper into one clean PDF, entirely in your browser.' },
        { t: 'note', x: 'Scan to PDF runs inside your tab. The photos never leave your computer, no account is needed, and closing the tab is the same as shredding the working copy. That matters more than usual here, because the documents people scan tend to be passports, payslips, medical letters and contracts.' },
        { t: 'h2', x: 'Colour, grey, or black and white' },
        { t: 'p', x: 'This single choice decides both how readable the page is and how big the file is. The rough per-page sizes below assume a full A4 page captured at about 300 DPI.' },
        {
          t: 'table',
          head: ['Mode', 'Best for', 'Rough size per A4 page'],
          rows: [
            ['Black and white', 'Clean printed text, typed letters, forms, anything laser-printed', '20 to 60 KB'],
            ['Greyscale', 'Pencil notes, faint carbon copies, old typewriter pages, photographs of type', '150 to 400 KB'],
            ['Colour', 'Stamps, signatures in coloured ink, highlighting, anything where the colour is part of the evidence', '400 KB to 1.5 MB'],
          ],
        },
        { t: 'tip', x: 'Black and white looks the cleanest and is a one-way door. Thresholding decides pixel by pixel whether something is ink or paper, and a faint pencil annotation or a pale blue stamp simply falls on the paper side and disappears. If a page has anything faint on it that matters, keep the greyscale version instead. You can always threshold later; you cannot un-threshold.' },
        { t: 'h2', x: 'Making the scan searchable' },
        { t: 'p', x: 'A finished scan is still just pictures of pages. Search it and you get nothing, because there is no text in the file to find. [OCR](/tools/ocr-pdf) reads the shapes and writes an invisible text layer underneath the image, so the page still looks like the paper but the words are now selectable and searchable. It runs in your browser too, so the document does not go anywhere.' },
        { t: 'p', x: 'The full walkthrough is in [how to OCR a scanned PDF](/blog/ocr/how-to-ocr-a-scanned-pdf), and if the results come back patchy, [improving OCR accuracy](/blog/ocr/improve-ocr-accuracy) explains what to change. Almost every fix in that guide is a capture fix: straighter, brighter, higher resolution. OCR quality is decided before you take the photo.' },
        { t: 'h2', x: 'What a phone still cannot do' },
        {
          t: 'ul',
          items: [
            '**Tightly bound books.** Text runs into the gutter and curves away from the lens. A phone can get you a readable page but not a straight one, and OCR accuracy drops sharply in the curved centimetre.',
            '**Glossy and laminated pages.** The surface is a mirror. You can move the reflection around but you cannot remove it without a polarising filter.',
            '**Very faint or damaged originals.** Thermal receipts that have gone blank, water-damaged pages, foxed paper. A scanner with real control over exposure will beat a phone here.',
            '**Anything larger than about A3.** Fill the frame with a plan or a poster and you are at 100 DPI or less. Photograph it in overlapping sections instead.',
            '**Accurate colour.** Phone cameras are tuned to make photographs look nice, not to reproduce a specific shade. If the exact colour is the point, you need a scanner and a colour target.',
            '**Thin paper printed both sides.** The reverse shows through. Slide a sheet of black card behind the page and the show-through mostly disappears.',
          ],
        },
        { t: 'p', x: 'Once the scan is straight, readable and searchable, decide where it is going. If it is a personal reference copy, you are finished. If it is going into a records system, a court bundle or a university deposit, convert it to the archival format afterwards: [what PDF/A is](/blog/archive/what-is-pdfa) explains which level to ask for and why a scan needs OCR before it is worth archiving at all.' },
      ],
      faqs: [
        { q: 'What resolution do I need to scan a document?', a: 'Aim for the equivalent of 300 DPI, which for an A4 page means about 2480 by 3508 pixels, or 8.7 megapixels. Any modern phone camera exceeds that if the page fills the frame. Below roughly 200 DPI, OCR accuracy falls off quickly on normal body text.' },
        { q: 'Why do my scanned pages have a grey shadow across them?', a: 'You are standing between the light and the paper. Move so the light comes across the page from the side rather than over your shoulder, or use two lamps at opposite sides of the page so neither can be blocked.' },
        { q: 'Should I use my phone flash when photographing a document?', a: 'No. The flash sits right next to the lens, so it throws its brightest spot into the middle of the frame, exactly where the text is. Use daylight or a lamp placed off to one side.' },
        { q: 'How do I scan a book without breaking the spine?', a: 'Open the book fully, press the page flat at the gutter with your thumb outside the text area, and photograph one page at a time rather than a two-page spread. Expect the centimetre nearest the spine to be curved and to OCR poorly.' },
        { q: 'Is it safe to scan a passport or a payslip in a browser tool?', a: 'With a browser tool the images are processed inside your own tab and never uploaded, so the document does not leave your computer. Check what any tool you use actually does with the file before you feed it identity documents.' },
      ],
      relatedTools: ['scan-to-pdf', 'ocr-pdf', 'pdf-to-pdfa'],
      relatedPosts: ['how-to-ocr-a-scanned-pdf', 'improve-ocr-accuracy', 'what-is-pdfa'],
    },
    {
      slug: 'convert-pdf-to-markdown',
      cluster: 'archive',
      title: 'How to convert a PDF to Markdown',
      metaTitle: 'How to Convert a PDF to Markdown',
      metaDescription:
        'Pull a PDF into plain Markdown text for notes, a wiki or version control. What survives the conversion, what does not, and how to fix the usual three faults.',
      published: '2026-04-17',
      updated: '2026-09-02',
      readMinutes: 6,
      intent: 'howto',
      primaryKeyword: 'convert pdf to markdown',
      secondaryKeywords: ['pdf to markdown converter', 'pdf to md', 'extract text from pdf as markdown', 'pdf to notes', 'pdf to plain text with headings'],
      entities: ['Markdown', 'UTF-8', 'Git', 'Obsidian', 'Notion', 'MediaWiki', 'OCR'],
      answer:
        'Open the PDF in a Markdown converter and download the .md file. Markdown is plain text with a few punctuation marks standing in for formatting, so headings, lists, paragraphs and links carry over. Exact layout, columns and complicated tables do not, because Markdown has no concept of a page.',
      body: [
        { t: 'p', x: 'Markdown is plain text with a handful of punctuation marks standing in for formatting: a # at the start of a line makes a heading, a - makes a bullet, and two asterisks around a word make it **bold**. That is the entire idea. A Markdown file opens in Notepad, in TextEdit, in a notes app, on a wiki, in a code editor and in a chat box, and if every program that understands it vanished tomorrow you could still read the file and know what it said.' },
        { t: 'p', x: 'Converting a PDF to Markdown is therefore a deliberate trade. You are giving up the layout on purpose, to get back something you can edit, search, paste and version-control.' },
        { t: 'h2', x: 'What survives, and what does not' },
        {
          t: 'table',
          caption: 'How each part of a PDF fares on the way to Markdown.',
          head: ['Feature', 'Survives?', 'Why'],
          rows: [
            ['Headings', 'Usually', 'Detected from font size and weight, then written as # and ##. A document that fakes headings with bold body text confuses this.'],
            ['Paragraphs', 'Yes', 'The hard line breaks a PDF uses inside a paragraph are joined back into flowing text.'],
            ['Bullet and numbered lists', 'Usually', 'Recognised from the bullet character and the indent.'],
            ['Bold and italic', 'Usually', 'Read from the font name, so real bold survives. Bold that the renderer faked by drawing the outline twice does not.'],
            ['Links', 'Yes', 'Real link annotations become `[text](url)`. A URL that was only printed as visible text stays as visible text.'],
            ['Simple tables', 'Often', 'A grid of short single-line cells converts into a Markdown table.'],
            ['Complex tables', 'No', 'Merged cells, nested tables and cells that wrap onto three lines have no Markdown equivalent at all.'],
            ['Two-column layouts', 'Often not', 'Text comes out in the order it was stored, which in many PDFs alternates between the columns line by line.'],
            ['Exact page layout', 'No, and that is the point', 'Markdown has no pages, no margins, no fixed positions and no font sizes.'],
            ['Images', 'As a placeholder', 'You get a reference, not a picture. Pull the pictures out separately with [PDF to JPG](/tools/pdf-to-jpg).'],
            ['Headers and footers', 'No', 'Repeated page furniture is dropped, which is nearly always what you want.'],
            ['Footnotes', 'Rarely intact', 'They land as loose text wherever the page ended, detached from their marker.'],
          ],
        },
        { t: 'h2', x: 'Doing the conversion' },
        {
          t: 'steps',
          items: [
            { h: 'Check the PDF actually has text', x: 'Open it in any reader and try to select a sentence with the mouse. If nothing highlights, the file is a scan and there is no text to convert. Run [OCR](/tools/ocr-pdf) first, then come back.' },
            { h: 'Open the converter', x: 'Go to [PDF to Markdown](/tools/pdf-to-markdown) and drop the file in. It is read in your browser, so nothing is uploaded and nothing is stored.' },
            { h: 'Choose one file or one per page', x: 'One combined .md file for an article or a report. One file per page when you are feeding a notes app that wants small notes.' },
            { h: 'Read the first screenful before you download anything', x: 'Ninety percent of conversion problems are visible in the first twenty lines: heading levels wrong, page numbers left in, columns interleaved.' },
            { h: 'Fix the usual three by hand', x: 'Heading levels one step off, a stray line of running header, and any table with merged cells. Everything else is normally fine as it stands.' },
          ],
        },
        { t: 'cta', tool: 'pdf-to-markdown', x: 'Turn a PDF into plain Markdown text you can paste anywhere.' },
        { t: 'h2', x: 'What the output looks like' },
        { t: 'code', x: '# Quarterly report\n\n## Summary\n\nRevenue rose 12 percent against the same quarter last year,\nagainst a target of 9 percent.\n\n- North: up 8 percent\n- South: down 2 percent\n- Online: up 31 percent\n\nSee the [methodology note](/about) for how these are counted.\n\n> All figures are unaudited.' },
        { t: 'p', x: 'That is a complete, valid Markdown document. Nothing in it needs a program to be understood. Compare it to the same content as a PDF, which is a compressed binary file with an index of byte offsets, and you can see why one of these two formats is a better bet for text you plan to keep.' },
        { t: 'h2', x: 'The two-column problem' },
        { t: 'warn', x: 'A two-column journal article is the worst case for any PDF text extraction. Text is read in the order it was written into the file, and plenty of typesetting software writes across both columns line by line rather than finishing one column first. The Markdown then reads as alternating half-sentences. If it happens, [crop](/tools/crop-pdf) the page down to one column, convert, then crop to the other column and convert again. It is two passes instead of one, and it works every time.' },
        { t: 'h2', x: 'Why bother with Markdown at all' },
        {
          t: 'ul',
          items: [
            '**Version control.** A .md file diffs line by line in Git, so you can see exactly which sentence changed between two drafts. A PDF diff shows you that some bytes moved.',
            '**Notes and wikis.** Obsidian, Notion, MediaWiki, most static site generators and most issue trackers all take Markdown directly, with no import step.',
            '**Searching a whole folder.** Plain text files can be searched with any tool on any system, including grep, in a fraction of a second across thousands of documents.',
            '**Pasting into a chat.** Feeding a PDF to an assistant drags along layout noise, page numbers and running headers. Markdown gives it the argument and nothing else.',
            '**Reading on a phone.** Markdown reflows to any screen width. A fixed A4 PDF does not, which is why reading one on a phone means pinching and dragging.',
            '**Outliving the software.** Markdown is text. It has no version, no licence and no vendor, and a file written today will read the same way in fifty years.',
          ],
        },
        { t: 'h2', x: 'Markdown or plain text?' },
        { t: 'p', x: 'If you want the words and nothing else, [PDF to text](/blog/from-pdf/pdf-to-text) is simpler and produces a smaller file. Choose Markdown when the structure matters: when you want the headings to still be headings, the lists to still be lists, and the links to still be clickable when you paste the result somewhere. Choose plain text when you are going to feed the output to something that only cares about the words, such as a search index.' },
        { t: 'p', x: 'One thing to be aware of either way: the converted file inherits none of the original PDF metadata, so the author, title and creation date are gone. If any of that matters for a record, note it at the top of the Markdown file yourself, in a couple of lines. Text files have no hidden fields, which is a strength, but it does mean anything worth keeping has to be written down where you can see it.' },
      ],
      faqs: [
        { q: 'What is Markdown?', a: 'Markdown is plain text with a few punctuation marks used as formatting: # for a heading, - for a bullet, **word** for bold, and `[text](link)` for a link. It opens in any text editor and is readable even when nothing is there to render it.' },
        { q: 'Do tables survive a PDF to Markdown conversion?', a: 'Simple ones usually do. A grid of short single-line cells becomes a Markdown table. Merged cells, nested tables and cells whose text wraps onto several lines have no Markdown equivalent, so they come out as loose text you will need to rebuild.' },
        { q: 'Why is my converted Markdown a jumble of half-sentences?', a: 'The PDF is almost certainly a two-column layout, and the text was stored in the order it was drawn rather than in reading order. Crop the page down to one column, convert that, then repeat for the second column.' },
        { q: 'Can I convert a scanned PDF to Markdown?', a: 'Not directly, because a scan holds pictures of pages rather than text. Run OCR on it first to create a text layer, check that you can select text in the result, then convert that file to Markdown.' },
        { q: 'Is my file uploaded when I convert a PDF to Markdown?', a: 'Not with a browser-based converter. The PDF is read and converted inside your own tab, so the file never leaves your computer and closing the tab removes every trace of it.' },
      ],
      relatedTools: ['pdf-to-markdown', 'pdf-to-text', 'ocr-pdf'],
      relatedPosts: ['pdf-to-text', 'will-this-file-still-open', 'make-pdf-searchable'],
    },
    {
      slug: 'will-this-file-still-open',
      cluster: 'archive',
      title: 'Will this file still open in twenty years?',
      metaTitle: 'Which File Formats Will Still Open in 20 Years?',
      metaDescription:
        'Compare PDF/A, plain PDF, Markdown, plain text, DOCX and app-only formats for long-term survival, and see which documents to convert before it is too late.',
      published: '2026-05-08',
      updated: '2026-09-05',
      readMinutes: 8,
      intent: 'comparison',
      primaryKeyword: 'file formats for long term storage',
      secondaryKeywords: ['best format for archiving documents', 'will pdf still open in the future', 'digital preservation file formats', 'pdf vs docx archiving', 'future proof file format'],
      entities: ['PDF/A', 'ISO 32000', 'Office Open XML', 'Markdown', 'UTF-8', 'TIFF', 'Adobe Flash', 'Library of Congress'],
      answer:
        'Formats that last are open, publicly documented, and ideally readable as text. Plain text and Markdown are the safest, PDF/A is the best choice when layout matters, plain PDF is good but can break on missing fonts, DOCX is workable, and app-only formats last exactly as long as the app.',
      body: [
        { t: 'p', x: 'Two separate things have to hold for a file to open in twenty years. Some program has to still understand the format, and the bytes have to still exist on some working disk. Almost everyone worries about the second and loses documents to the first. Storage fails loudly, with a dead drive and a bad day. Formats fail quietly: the file is right there, the size is right, and nothing will open it.' },
        { t: 'h2', x: 'The formats, ranked by how well they age' },
        {
          t: 'table',
          caption: 'How long each document format is likely to stay readable, and what decides it.',
          head: ['Format', 'Open standard?', 'Readable as text?', 'Outlook'],
          rows: [
            ['Plain text (.txt, UTF-8)', 'Yes', 'Yes, it is nothing but text', 'The safest of all. The only real risk is a mystery character encoding, which is why saving as UTF-8 matters.'],
            ['Markdown (.md)', 'Yes, several documented flavours', 'Yes, and it reads fine unrendered', 'Excellent. Worst case, a future reader sees the # and - marks and understands the document anyway.'],
            ['PDF/A', 'Yes, ISO 19005', 'No, but the specification is public and complete', 'Excellent, and the right answer whenever the layout is part of the record.'],
            ['Plain PDF', 'Yes, ISO 32000', 'No', 'Good, with real failure modes: missing fonts, encryption with a lost password, JavaScript, and links to content that has gone.'],
            ['DOCX', 'Yes, ISO/IEC 29500. It is a ZIP of XML files', 'Partly, once you unzip it', 'Fair. Readable in principle, but the specification is enormous and two programs already render the same file differently today.'],
            ['Legacy .doc, .wpd, .xls binaries', 'No, largely reverse engineered', 'No', 'Poor and getting worse. Support for these is being removed from software, not added.'],
            ['App-only formats', 'No', 'No', 'Worst. The format lives exactly as long as the company keeps shipping the app, and not one day longer.'],
            ['Page images (JPEG, PNG, TIFF)', 'Yes', 'No', 'The picture survives easily. The words do not, unless OCR has been run and the text stored with it.'],
          ],
        },
        { t: 'h2', x: 'The pattern underneath the table' },
        { t: 'p', x: 'The formats that survive share three properties, in order of importance. They are **open**, meaning anyone can implement a reader without permission. They are **documented**, meaning the specification is published and complete enough that someone could write that reader from scratch. And the best of them are **readable as text**, meaning that even with no working software at all, a human can open the file and recover most of the content by eye.' },
        { t: 'quote', x: 'A format you can open in a text editor and half understand will outlive one that needs its own program.' },
        { t: 'p', x: 'This is why plain text beats everything, and why a compressed binary format tied to one company is the worst possible place to leave something you care about. It is also why PDF is good rather than perfect: the specification is public, so readers will keep being written, but the file is binary and can carry dependencies on things that are not inside it. PDF/A exists precisely to remove those dependencies.' },
        { t: 'h2', x: 'What to do with what you already have' },
        {
          t: 'table',
          head: ['What you have', 'Do this', 'Why'],
          rows: [
            ['A contract, invoice, certificate or filing', 'Convert to [PDF/A](/tools/pdf-to-pdfa)', 'The layout and the signature block are part of the record, not decoration'],
            ['Notes, drafts, documentation, a personal wiki', 'Keep as [Markdown](/tools/pdf-to-markdown)', 'Text you will edit again, and want to diff and search'],
            ['A DOCX you will not edit again', 'Export a PDF/A copy, keep the DOCX too', 'The PDF/A fixes how it looks; the DOCX stays editable while software still opens it'],
            ['A pile of paper', '[Scan it](/tools/scan-to-pdf), then [OCR it](/tools/ocr-pdf)', 'Paper fails slowly but it does fail, and thermal receipts fail in about five years'],
            ['Web pages you rely on', '[Archive them as PDF](/blog/save-pdf/archive-web-pages)', 'A link is a promise made by someone else, and roughly a tenth of them break every year'],
            ['Anything in an app-only format', 'Export it now, to PDF and to text', 'Export while the app still runs. After it stops, you are negotiating with a file nobody can read'],
          ],
        },
        { t: 'note', x: 'Converting to PDF/A is the one job here that runs on our server rather than in your browser, because it needs a font and colour engine no tab can hold. The file is uploaded over a secure connection, converted, and deleted the moment it finishes. Free accounts get 5 server conversions a month, Pro and Lifetime 300, API keys 5,000, with a 100 MB limit and two minutes per job. Scanning, OCR and Markdown conversion all run in your browser and upload nothing.' },
        { t: 'h2', x: 'The other half: keeping the bytes' },
        { t: 'p', x: 'Format choice is worth nothing if the file is not there. The rules here are old, boring and effective:' },
        {
          t: 'ul',
          items: [
            '**Three copies, two kinds of storage, one somewhere else.** The laptop, an external disk, and a cloud account is a perfectly good version of this.',
            '**Open the files every couple of years.** Not to check the disk, to check the formats. The year you cannot open something is the year to convert it, while an old machine still can.',
            '**Use folder names and dates, not a database.** A folder called `2026-05 Insurance` will still make sense when the app that organised your library has gone.',
            '**Do not rely on a single account.** Files vanish when a subscription lapses, an email address dies, or a service closes. All three are more common than disk failure.',
            '**Keep a plain text index.** One file listing what is in each folder and why it matters. It costs ten minutes and it is the thing your family or your successor will actually use.',
          ],
        },
        { t: 'warn', x: 'The commonest way a document is lost is not a dead hard disk. It is a folder called "old stuff" on a laptop that got traded in, an account nobody renewed, or a phone that was replaced without checking what was only on it. Storage fails quietly and the loss is discovered years later, when someone needs the thing.' },
        { t: 'h2', x: 'What none of this protects against' },
        {
          t: 'ul',
          items: [
            '**Dead links inside a surviving file.** A perfectly readable document that says "see the appendix at this address" is only as good as that address. Archive what it points at, in the same folder.',
            '**Expired signature certificates.** A digitally signed PDF keeps opening, but the signature can stop validating once the certificate behind it expires or its issuer disappears. The document survives; the proof of who signed it weakens.',
            '**Lost passwords.** An encrypted file is not archived, it is hidden. Remove the password and protect the storage instead.',
            '**Garbage in.** PDF/A faithfully preserves an unreadable scan forever. Fix the document before you archive it, not after.',
            '**Compression damage already done.** A photo saved as JPEG five times has lost detail permanently. No future format recovers it.',
          ],
        },
        { t: 'p', x: 'If you do only one thing after reading this, do a pass over the last three years of documents and sort them into two piles. Anything where the layout is the record goes to [PDF/A](/blog/archive/what-is-pdfa). Anything that is really just words goes to [Markdown or plain text](/blog/archive/convert-pdf-to-markdown). That single sorting exercise, done once, is worth more than any storage strategy, because it fixes the failure nobody sees coming.' },
      ],
      faqs: [
        { q: 'What is the best file format for long-term storage?', a: 'Plain UTF-8 text and Markdown for anything that is essentially words, and PDF/A for anything where the layout, the signature or the page design is part of the record. All three are open, publicly documented, and implementable by anyone.' },
        { q: 'Will PDF files still open in 20 years?', a: 'Almost certainly, because PDF is a published ISO standard and readers will keep being written. The risk is not the format but the contents: a PDF with unembedded fonts, a lost password, or links to content that has disappeared can open and still be wrong.' },
        { q: 'Is DOCX a safe format for archiving?', a: 'It is acceptable but not ideal. DOCX is an open standard and is really a ZIP of XML files, so the content is recoverable. But the specification is huge, and different programs already render the same document differently, so the look of the file is not guaranteed.' },
        { q: 'Should I archive documents as images or as PDFs?', a: 'As PDFs, with a text layer from OCR. An image preserves the picture of the page but none of its words, so you cannot search it, quote it or index it. A searchable PDF gives you both the picture and the text.' },
        { q: 'How often should I check my archived files?', a: 'Open a sample every couple of years. You are not checking the disk, you are checking that current software still reads the formats. The moment something is hard to open is the moment to convert it, while a machine that can still read it exists.' },
      ],
      relatedTools: ['pdf-to-pdfa', 'pdf-to-markdown', 'scan-to-pdf'],
      relatedPosts: ['what-is-pdfa', 'convert-pdf-to-markdown', 'archive-web-pages'],
    },
  ],
}
