import type { Cluster } from '../types'

export const browserExtensions: Cluster = {
  slug: 'extensions',
  name: 'Browser extensions and shortcuts',
  title: 'Print better from your browser: reader modes, extensions and bookmarklets',
  metaTitle: 'Print-Friendly Browser Extensions and Shortcuts',
  metaDescription:
    'Get a clean printout from Chrome, Firefox and Safari using reader modes, keyboard shortcuts, bookmarklets and extensions, plus the permissions to check first.',
  intro:
    'Every browser has a different route to a clean printout. Firefox and Safari ship reader modes that strip a page to text in one keystroke. Chrome does not have a print-ready one, so it needs a bookmarklet, an extension or a web tool. These guides cover the built-in shortcuts first, then what to check before you install anything that can read every page you visit.',
  answer:
    'Firefox and Safari have built-in reader modes that produce clean printouts: press F9 in Firefox or Control-Command-R in Safari, then print. Chrome has no print-ready reader mode, so use a bookmarklet, an extension or a web-based cleaner. Bookmarklets need no permissions and work in every browser.',
  primaryKeyword: 'print friendly browser extension',
  entities: ['Google Chrome', 'Mozilla Firefox', 'Safari', 'Microsoft Edge', 'Chrome Web Store', 'Reader View', 'Manifest V3', 'bookmarklet'],
  icon: '🧩',
  tools: ['html-to-pdf', 'pdf-reader', 'compress-pdf'],
  posts: [
    {
      slug: 'print-friendly-extension-chrome',
      cluster: 'extensions',
      title: 'Print-friendly options for Google Chrome',
      metaTitle: 'Print-Friendly Options for Google Chrome',
      metaDescription:
        'Chrome has no print-ready reader mode. Compare bookmarklets, extensions, DevTools and web tools, and learn which permissions to check before you install.',
      published: '2026-02-24',
      updated: '2026-08-14',
      readMinutes: 7,
      intent: 'howto',
      primaryKeyword: 'print friendly extension chrome',
      secondaryKeywords: ['chrome reader mode print', 'chrome print bookmarklet', 'printer friendly chrome extension', 'chrome extension permissions', 'print web page chrome clean'],
      entities: ['Google Chrome', 'Chrome Web Store', 'Manifest V3', 'Microsoft Edge', 'Brave', 'Chrome DevTools', 'Readability', 'Ctrl+P'],
      answer:
        'Chrome has no print-ready reader mode, so the clean options are a bookmarklet, a Chrome Web Store extension, DevTools, or a web-based cleaner. A bookmarklet is the safest: it is one line of JavaScript in a bookmark, needs no permissions and cannot read pages you do not click it on.',
      body: [
        { t: 'p', x: 'Chrome is the only major browser without a reader mode you can print from. It gained a **Reading mode** side panel in 2023, but that is a narrow panel beside the page, not a replacement for it. Press Ctrl+P while it is open and Chrome prints the cluttered page underneath, ads and all.' },
        { t: 'p', x: 'So getting a clean printout out of Chrome means bringing your own tool. There are four realistic options and they trade off convenience against how much access you hand over.' },
        {
          t: 'table',
          caption: 'Four ways to get a clean printout from Chrome, compared.',
          head: ['Option', 'Setup', 'Permissions it needs', 'Best for'],
          rows: [
            ['Bookmarklet', 'Drag a link to the bookmarks bar, about 10 seconds', 'None. It only runs when you click it.', 'Almost everyone. Works in Chrome, Edge, Brave, Opera, Arc and Vivaldi.'],
            ['Web tool, paste the URL', 'Nothing to install', 'None', 'One-off jobs, locked-down work machines, borrowed computers.'],
            ['Chrome Web Store extension', 'Two clicks plus a permission prompt', 'Usually "read and change all your data on all websites"', 'Daily printing, if you have vetted the publisher.'],
            ['DevTools, delete elements by hand', 'F12, then click and press Delete', 'None', 'Pages that defeat everything else: dashboards, web apps, invoices.'],
          ],
        },
        { t: 'h2', x: 'Option 1: The bookmarklet (works today)' },
        { t: 'p', x: 'A bookmarklet is a bookmark whose address is a small piece of JavaScript instead of a URL. Click it on any page and it opens that page in the cleaner. It installs in seconds, needs no permissions, syncs with your other bookmarks, and cannot do anything at all until you click it.' },
        {
          t: 'steps',
          items: [
            { h: 'Show the bookmarks bar', x: 'Press Ctrl+Shift+B on Windows or Cmd+Shift+B on Mac. You need somewhere to drop it.' },
            { h: 'Open the extensions page', x: 'Go to [the Chrome page](/extensions/chrome) and find the card headed "Works today: the bookmarklet".' },
            { h: 'Drag the button to the bar', x: 'Drag the ⚡ button onto your bookmarks bar. If dragging is awkward, right-click it, copy the link, then create a new bookmark and paste the copied text into the URL field.' },
            { h: 'Try it on a real article', x: 'Open a news article and click the bookmarklet. The cleaner opens in a new tab with that page already loaded.' },
            { h: 'Clean and print', x: 'Delete anything left over by clicking it, set the text size, then press Print or Download PDF.' },
          ],
        },
        { t: 'warn', x: 'To be straight about it: the PrintxPDF extension is **not in the Chrome Web Store yet**. It is a real, working extension, but for now you download the folder from [the extension page](/extensions/chrome) and load it by hand in three steps. If you would rather install nothing, the bookmarklet on the same page works right now, as does pasting a URL into the [web page printer](/print).' },
        { t: 'h2', x: 'Option 2: A Chrome Web Store extension' },
        { t: 'p', x: 'Plenty of genuine print-friendly extensions exist. The question is not whether they work, it is what they can see. An extension that reformats pages needs to read page content, and that permission is the same one a data-harvesting extension needs.' },
        { t: 'p', x: 'Chrome runs on **Manifest V3**, which improved some things but did not change the core bargain: host permissions still mean the extension can read what is on the page.' },
        { t: 'h3', x: 'Check these five things before you click Add' },
        {
          t: 'ol',
          items: [
            '**The permission prompt.** "Read and change all your data on all websites" is the broadest access Chrome grants. For a print tool it is often unnecessary, because it could ask for access only on the tab you click.',
            '**The Privacy practices tab** on the store listing. Publishers must declare what data they collect. A print tool that declares it collects "web history" or "user activity" is telling you it phones home about every page you visit.',
            '**Last updated date.** An extension untouched for three years may still be running old code or may have been quietly sold.',
            '**The publisher.** Click the developer name. A real site, a real privacy policy and a support address are the minimum. Anonymous publishers with a Gmail contact are a risk.',
            '**Reviews from the last few months, not the average.** Extensions get bought and turned into adware after they build an audience. Recent one-star reviews complaining about injected ads or redirects are the warning.',
          ],
        },
        { t: 'tip', x: 'After installing anything, go to `chrome://extensions`, click **Details**, and set **Site access** to **On click**. The extension then does nothing until you click its icon, which for a print tool loses you nothing and removes the standing permission entirely.' },
        { t: 'h2', x: 'Option 3: Delete the clutter with DevTools' },
        { t: 'p', x: 'For a page that beats every automatic tool, remove the junk by hand. Press F12, click the arrow icon at the top left of DevTools, click the ad or sidebar on the page, then press Delete on the highlighted node. Repeat, then print. Nothing is permanent; a reload restores the page.' },
        { t: 'code', x: "// Faster: open the Console tab (Esc toggles it) and paste this.\ndocument.querySelectorAll('nav, aside, footer, iframe, [class*=\"ad-\"], [id*=\"banner\"], [class*=\"promo\"], [class*=\"newsletter\"]')\n  .forEach(el => el.remove());\n// Then press Ctrl+P." },
        { t: 'h2', x: 'Option 4: Squeeze the Chrome print dialog' },
        { t: 'p', x: 'Before reaching for any tool, the dialog itself removes a surprising amount. Press Ctrl+P and open **More settings**.' },
        {
          t: 'ul',
          items: [
            '**Headers and footers** off, to drop the title, URL, date and page number Chrome stamps on every sheet.',
            '**Background graphics** off, which is the default, to skip solid colour blocks and hero images.',
            '**Scale** at 80 or 90 percent to fit more text per sheet.',
            '**Pages** set to a range like `2-3` once you have found your content in the preview.',
            '**Selection only**, which appears in the Pages dropdown when text is highlighted. This is the fastest trick in Chrome and is covered in [printing only selected text](/blog/print/print-selected-text-only).',
          ],
        },
        { t: 'cta', tool: 'html-to-pdf', x: 'Already saved the page as an HTML file? Convert it straight to a PDF in your browser.' },
        { t: 'h2', x: 'What about Edge, Brave and the rest?' },
        { t: 'p', x: 'Every Chromium browser shares Chrome extensions and the same print dialog, so all of the above transfers directly. Edge is the exception worth knowing: it ships **Immersive Reader**, reachable with F9 or the book icon in the address bar, which does what Chrome will not. If you print articles often and you are already on Windows, Edge is the path of least resistance. The full comparison lives in [printing a web page without ads](/blog/print/print-web-page-without-ads).' },
      ],
      faqs: [
        { q: 'Does Chrome have a reader mode?', a: 'Chrome has a Reading mode side panel, opened from the side panel menu, but it is not a page mode. Printing while it is open prints the original cluttered page. For a printable clean view you need a bookmarklet, an extension or a web tool.' },
        { q: 'Is a print extension safe to install?', a: 'It depends entirely on the publisher. Any extension that reformats pages can read them, so check the Privacy practices tab, the last updated date and recent reviews, then restrict it to "On click" site access in chrome://extensions after installing.' },
        { q: 'Do I need an extension to print a web page cleanly?', a: 'No. A bookmarklet does the same job with no permissions, and pasting the URL into a web-based cleaner needs nothing installed at all. An extension only saves you a click, which matters if you print pages many times a day.' },
        { q: 'Does PrintxPDF have a Chrome extension?', a: 'Yes, but it is not in the Chrome Web Store yet. You download a small zipped folder from the extension page and load it through Load unpacked, which takes about a minute. If you would rather not install anything, the bookmarklet on the same page works today in every Chromium browser, and so does pasting a URL into the web page printer.' },
        { q: 'How do I remove an extension that changed my search or added ads?', a: 'Go to chrome://extensions, toggle it off, then click Remove. Afterwards check chrome://settings/searchEngines and your homepage setting, since some extensions leave those changed behind after removal.' },
      ],
      relatedTools: ['html-to-pdf', 'pdf-reader'],
      relatedPosts: ['bookmarklet-vs-extension', 'print-web-page-without-ads', 'print-button-any-website'],
    },
    {
      slug: 'firefox-print-addon',
      cluster: 'extensions',
      title: 'Printing better from Firefox',
      metaTitle: 'How to Print Better From Firefox',
      metaDescription:
        'Firefox Reader View, the print modal, scaling and margins, what happened to Simplify Page, and how to pick a safe print add-on from addons.mozilla.org.',
      published: '2026-03-19',
      updated: '2026-07-30',
      readMinutes: 6,
      intent: 'howto',
      primaryKeyword: 'firefox print add-on',
      secondaryKeywords: ['firefox reader view print', 'firefox simplify page', 'firefox print settings', 'print web page firefox clean', 'firefox print preview'],
      entities: ['Mozilla Firefox', 'Reader View', 'addons.mozilla.org', 'Mozilla', 'Pocket', 'Firefox for Android', 'Manifest V3'],
      answer:
        'Press F9 to switch Firefox into Reader View, which strips ads, menus and sidebars, then press Ctrl+P to print the clean layout. Firefox also exposes scale, margins, headers and footers and selection printing in its print modal, so most jobs need no add-on at all.',
      body: [
        { t: 'p', x: 'Firefox is the best of the mainstream browsers for printing, and almost nobody uses the two features that make it so. Between Reader View and the print modal you can get a clean, well-scaled printout without installing anything.' },
        { t: 'h2', x: 'Reader View is the whole trick' },
        { t: 'p', x: 'Reader View runs a content-extraction pass over the page and re-renders just the article: headline, body text, inline images. Ads, navigation, sidebars, comment walls and sticky headers are all gone before printing is even mentioned.' },
        {
          t: 'steps',
          items: [
            { h: 'Open the article', x: 'Reader View only offers itself on pages it recognises as articles. If the page icon does not appear, the page is a dashboard, a listing or a web app, not an article.' },
            { h: 'Press F9', x: 'On Windows and Linux, F9 or Ctrl+Alt+R toggles Reader View. On macOS use Cmd+Alt+R. You can also click the page icon at the right of the address bar.' },
            { h: 'Set the type', x: 'The left-hand toolbar lets you change the font, the size, the line height and the width. What you set here is what prints, so widen the column and drop the size slightly to fit more per sheet.' },
            { h: 'Print from inside Reader View', x: 'Press Ctrl+P. The print modal previews the reader layout, not the original page.' },
            { h: 'Trim the header and footer', x: 'Untick **Print headers and footers** in the modal so you do not get the URL and date stamped on every page.' },
          ],
        },
        { t: 'note', x: 'Reader View strips images by default only in its narrow modes; article images stay. If you want them gone to save ink, remove them in a printer-friendly view instead, or read [saving ink when printing](/blog/save-ink/save-ink-when-printing).' },
        { t: 'h2', x: 'What happened to Simplify Page' },
        { t: 'p', x: 'If you remember a **Simplify page** checkbox in Firefox print preview, you are not imagining it. The old print preview window carried it, and Firefox 81 replaced that window with the modern in-tab print modal, which dropped the option. Reader View is the official replacement and does the same job better, because you can adjust the type before printing.' },
        { t: 'h2', x: 'The print modal, setting by setting' },
        {
          t: 'table',
          caption: 'Firefox print modal options and what each one is for.',
          head: ['Setting', 'What it does', 'Use it when'],
          rows: [
            ['Pages: All / Odd / Even / Custom', 'Prints a subset of sheets', 'You have found the two pages you want in the preview. Type `2-3`.'],
            ['Selection', 'Prints only highlighted text; appears only when a selection exists', 'You want one paragraph or one table and nothing else.'],
            ['Scale: Fit to page width', 'Shrinks the layout until it fits the paper', 'Wide tables and dashboards that would otherwise be cut off.'],
            ['Scale: percentage', 'Manual zoom, typically 70-90 percent', 'Squeezing a three-page article onto two sheets.'],
            ['Margins: Default / None / Minimum / Custom', 'Controls white space at the sheet edge', 'Minimum recovers real estate. None risks clipping on inkjets.'],
            ['Print headers and footers', 'Adds title, URL, date and page numbers', 'Off for most jobs. On for reference material you will file.'],
            ['Print backgrounds', 'Includes CSS background colours and images', 'Off saves a lot of ink. On if a background image carries content.'],
            ['Print using the system dialog', 'Hands off to the OS print dialog', 'You need duplex, draft quality, stapling or a specific paper tray.'],
          ],
        },
        { t: 'tip', x: 'Firefox remembers most of these choices for the rest of the session, which makes it the fastest browser for printing several articles from the same site in a row.' },
        { t: 'h2', x: 'Choosing an add-on, if you want one' },
        { t: 'p', x: 'Firefox add-ons come from **addons.mozilla.org**, and the review process there is stricter than most. Two labels are worth knowing:' },
        {
          t: 'ul',
          items: [
            '**Recommended** add-ons are manually reviewed by Mozilla staff and monitored for updates. Start here.',
            '**Verified** and unlabelled add-ons pass automated review only. They may be perfectly fine, but you are trusting the publisher rather than Mozilla.',
            'Check the **Permissions** section on the listing before installing, then again in `about:addons` under the add-on Permissions tab afterwards.',
            'An add-on that only needs to reformat the current page should not need access to your browsing history, bookmarks or downloads.',
          ],
        },
        { t: 'warn', x: 'For a print tool specifically, a bookmarklet gives you the same result with no standing permissions at all. There is one on [the extension page](/extensions/chrome), and because it is just a link you keep in your bookmarks bar, it works in Firefox as well. The trade-offs are in [bookmarklet versus extension](/blog/extensions/bookmarklet-vs-extension). To be clear: there is no PrintxPDF add-on for Firefox.' },
        { t: 'h2', x: 'Firefox on Android' },
        { t: 'p', x: 'Firefox for Android keeps Reader View and, unusually for a mobile browser, supports a subset of desktop add-ons. Tap the page icon in the address bar for Reader View, then use the menu to Print or Save as PDF. It is the most capable mobile browser for getting a clean file off a phone.' },
        { t: 'cta', tool: 'pdf-reader', x: 'Saved the article as a PDF? Open it in the browser PDF reader to check it before you print.' },
        { t: 'h2', x: 'When Reader View refuses' },
        { t: 'p', x: 'Reader View needs an article-shaped page. Order confirmations, forum threads, search results, dashboards and single-page apps will not trigger it. For those, paste the URL into the [web page printer](/print) and delete what you do not want, or use the selection trick described in [printing only selected text](/blog/print/print-selected-text-only). If the layout itself is the problem, [web page printing problems](/blog/print/fix-web-page-printing-problems) covers the fixes browser by browser.' },
      ],
      faqs: [
        { q: 'How do I turn on Reader View in Firefox?', a: 'Press F9 or Ctrl+Alt+R on Windows and Linux, or Cmd+Alt+R on macOS. You can also click the page icon at the right of the address bar. The icon only appears on pages Firefox recognises as articles.' },
        { q: 'Where did the Simplify Page option go in Firefox?', a: 'It was removed with the old print preview window in Firefox 81, when the modern in-tab print modal replaced it. Reader View is the official replacement: switch to it with F9, then press Ctrl+P to print the simplified layout.' },
        { q: 'Can I print only part of a page in Firefox?', a: 'Yes. Highlight the text, press Ctrl+P, and choose Selection in the print modal. The option only appears when a selection is active when the modal opens, so do not click elsewhere in between.' },
        { q: 'Do I need an add-on to print cleanly from Firefox?', a: 'No. Reader View plus the print modal handles almost everything without installing anything. An add-on or a bookmarklet is only worth it if you print pages many times a day and want the whole thing on one click.' },
        { q: 'Why does my Firefox printout cut off the right side?', a: 'The page layout is wider than the paper. Set Scale to "Fit to page width" in the print modal, or switch Orientation to landscape. Wide data tables almost always need one or the other.' },
      ],
      relatedTools: ['pdf-reader', 'html-to-pdf'],
      relatedPosts: ['bookmarklet-vs-extension', 'print-web-page-without-ads', 'fix-web-page-printing-problems'],
    },
    {
      slug: 'safari-print-extension',
      cluster: 'extensions',
      title: 'Printing better from Safari on Mac and iPhone',
      metaTitle: 'Printing Better From Safari on Mac and iPhone',
      metaDescription:
        'Safari Reader, Print Selected Text, Save as PDF on Mac and the iPhone share sheet Reader PDF option, plus Markup and how extensions ask for permission.',
      published: '2026-04-13',
      updated: '2026-08-02',
      readMinutes: 6,
      intent: 'howto',
      primaryKeyword: 'safari print extension',
      secondaryKeywords: ['safari reader mode print', 'print selected text safari', 'iphone save webpage as pdf', 'safari save as pdf mac', 'safari extension permissions'],
      entities: ['Safari', 'macOS', 'iOS', 'Safari Reader', 'Markup', 'Preview', 'App Store', 'iCloud Drive', 'Apple'],
      answer:
        'On a Mac, press Control-Command-R for Safari Reader then Command-P to print the clean layout, or use File then Print Selected Text for one passage. On iPhone, tap Share, then Options at the top of the sheet, and choose Reader PDF to save the article without ads.',
      body: [
        { t: 'p', x: 'Safari has the best reader mode of any browser and the best hidden PDF option of any mobile browser. Neither is signposted, so most people never find either.' },
        { t: 'h2', x: 'On a Mac' },
        {
          t: 'table',
          caption: 'Safari printing shortcuts on macOS.',
          head: ['What you want', 'How', 'Notes'],
          rows: [
            ['Clean article view', 'Press ⌃⌘R, or click the ☰ icon at the left of the address bar', 'Only offered on article pages. Choose the font, size and background before printing.'],
            ['Print just one passage', 'Select the text, then **File → Print Selected Text**', 'Safari has no Selection radio button in the print sheet; this menu item is the equivalent.'],
            ['Save as a PDF', 'Press ⌘P, then open the **PDF** menu at the bottom left and choose Save as PDF', 'Text stays selectable and links stay clickable.'],
            ['Check it before printing', 'Same PDF menu, choose **Open in Preview**', 'Preview shows exact pagination so you do not waste a sheet.'],
            ['Always use Reader on a site', 'Right-click the address bar, **Settings for This Website**, tick "Use Reader when available"', 'Per-site and permanent. Ideal for a news site you read daily.'],
          ],
        },
        { t: 'tip', x: 'Safari Reader carries your font and background choices straight into the print output, so a serif face at a slightly larger size gives you a genuinely readable printout rather than a screenshot of a web page.' },
        { t: 'h2', x: 'On iPhone and iPad' },
        { t: 'p', x: 'The share sheet hides a **Reader PDF** option that produces exactly what you want: the article, no navigation, no ads, as a real PDF with selectable text.' },
        {
          t: 'steps',
          items: [
            { h: 'Open the article in Safari', x: 'Let it load fully so images below the fold are fetched.' },
            { h: 'Tap the page settings button', x: 'In the address bar, then choose **Show Reader** if you want to check the clean version first.' },
            { h: 'Tap Share', x: 'The square with the arrow. At the top of the sheet, under the page title, there is a small **Options** row.' },
            { h: 'Tap Options', x: 'Change "Send as" from Automatic to **Reader PDF**. This is the whole trick and it is one tap deep.' },
            { h: 'Choose where it goes', x: 'Save to Files, save to Books, or send it straight to someone. Files plus iCloud Drive keeps it on your Mac too.' },
            { h: 'Or print it', x: 'From the same share sheet choose Print, pick an AirPrint printer, and the Reader layout is what gets sent.' },
          ],
        },
        { t: 'note', x: 'If **Reader PDF** is greyed out, Safari did not detect an article. Plain **PDF** in the same menu saves the full page instead. For receipts and confirmations that is usually what you want anyway.' },
        { t: 'h2', x: 'Markup before you send it' },
        { t: 'p', x: 'From the share sheet, choose **Markup** to draw, highlight or add text on the PDF before saving. It is the fastest way to circle a paragraph on a phone, and the annotations are saved into the PDF itself rather than flattened into an image. Tap Done, then Save File To.' },
        { t: 'h2', x: 'A note on Safari extensions' },
        { t: 'p', x: 'Safari extensions are distributed only through the App Store, wrapped inside a Mac or iOS app. That makes the review process stricter than the Chrome Web Store, and it makes the permission model clearer: when an extension first needs a site, Safari asks and offers **Allow for One Day** or **Allow Always**, per site.' },
        {
          t: 'ul',
          items: [
            'Prefer **Allow for One Day** the first few times. If you never notice its absence, you did not need it.',
            'Review what is installed under **Safari → Settings → Extensions** on Mac, or **Settings → Apps → Safari → Extensions** on iPhone.',
            'Deleting the wrapper app removes the extension. There is no separate uninstall.',
            'Extensions do not sync from Mac to iPhone. You install them separately on each device.',
          ],
        },
        { t: 'warn', x: 'There is no PrintxPDF extension in the App Store. What works in Safari today is the bookmarklet on the [extension page](/extensions/chrome), which is a link you drag to your bookmarks bar and works in any browser, or pasting a URL into the [web page printer](/print).' },
        { t: 'h2', x: 'Bookmarklets on iOS, which is fiddly but works' },
        { t: 'p', x: 'iOS Safari cannot drag a bookmarklet to a bar, but it can still run one. Bookmark any page, then edit that bookmark and replace its address with the bookmarklet code. Open the Bookmarks list on any page and tap it to run. Because bookmarks sync through iCloud, a bookmarklet you set up on your Mac appears on the iPhone by itself, which is by far the easier route. The step-by-step is in [bookmarklet versus extension](/blog/extensions/bookmarklet-vs-extension).' },
        { t: 'cta', tool: 'pdf-reader', x: 'Open the PDF you just saved and check the pagination before sending it to a printer.' },
        { t: 'h2', x: 'When none of it works' },
        { t: 'p', x: 'Reader is unavailable on dashboards, order pages, forum threads and heavy JavaScript apps. For those, take a [full-page screenshot](/blog/save-pdf/full-page-screenshot) or paste the URL into a cleaner and delete the blocks you do not want. The broader browser-by-browser comparison is in [printing a web page without ads](/blog/print/print-web-page-without-ads).' },
      ],
      faqs: [
        { q: 'How do I turn on Reader in Safari?', a: 'On a Mac, press Control-Command-R or click the ☰ icon at the left of the address bar. On iPhone, tap the page settings button in the address bar and choose Show Reader. The option only appears on pages Safari recognises as articles.' },
        { q: 'How do I save a web page as a clean PDF on iPhone?', a: 'Tap Share, then tap Options at the top of the share sheet, and change "Send as" to Reader PDF. Save it to Files or Books. This gives you the article with selectable text and no ads or navigation.' },
        { q: 'Can I print only selected text in Safari?', a: 'Yes, but not from the print sheet. Select the text, then use File then Print Selected Text from the menu bar. If that item is greyed out, click once inside the page body first so Safari knows which frame holds the selection.' },
        { q: 'Are Safari extensions safer than Chrome extensions?', a: 'Generally yes, because they ship through the App Store review process and Safari asks for per-site permission with an Allow for One Day option. That is not a guarantee, so still check the developer and prefer day-limited access.' },
        { q: 'Is there a PrintxPDF extension for Safari?', a: 'No, and none is planned. Use the bookmarklet from the extension page instead: it works on Mac and syncs to iPhone through iCloud bookmarks. Pasting the URL into the web page printer works everywhere too.' },
      ],
      relatedTools: ['pdf-reader', 'compress-pdf'],
      relatedPosts: ['bookmarklet-vs-extension', 'save-webpage-as-pdf-iphone', 'print-web-page-without-ads'],
    },
    {
      slug: 'bookmarklet-vs-extension',
      cluster: 'extensions',
      title: 'Bookmarklet vs browser extension: which should you use?',
      metaTitle: 'Bookmarklet vs Browser Extension: Which to Use',
      metaDescription:
        'Bookmarklets need no permissions and work everywhere; extensions can read every page. Compare privacy, sync and upkeep, then install one in about a minute.',
      published: '2026-05-11',
      updated: '2026-08-20',
      readMinutes: 6,
      intent: 'comparison',
      primaryKeyword: 'bookmarklet vs extension',
      secondaryKeywords: ['what is a bookmarklet', 'how to install a bookmarklet', 'browser extension permissions', 'bookmarklet chrome', 'javascript bookmark'],
      entities: ['JavaScript', 'Chrome Web Store', 'Manifest V3', 'addons.mozilla.org', 'Content Security Policy', 'Firefox Sync', 'iCloud', 'Google Chrome'],
      answer:
        'Use a bookmarklet unless you need something an extension can only do. A bookmarklet is one line of JavaScript stored in a bookmark: it needs no permissions, runs only when you click it, works in every browser, and cannot be sold or updated behind your back. Extensions buy convenience with access.',
      body: [
        { t: 'p', x: 'Both put a button in your browser that does something to the page you are on. The difference is what happens when you are **not** pressing it.' },
        { t: 'p', x: 'An extension is installed software. It sits in the browser, can be granted permission to read and modify every page you visit, and updates itself silently. A bookmarklet is a bookmark whose address happens to be a line of JavaScript. It has no presence, no background process and no permissions. It exists as text until you click it.' },
        {
          t: 'table',
          caption: 'Bookmarklet and extension compared on the things that matter.',
          head: ['', 'Bookmarklet', 'Extension'],
          rows: [
            ['Permissions needed', 'None', 'Usually read and change data on all sites'],
            ['Runs when you are not using it', 'Never', 'Yes, if granted broad host access'],
            ['Install time', 'About 10 seconds', 'Two clicks plus a permission prompt'],
            ['Works in', 'Every browser, desktop and mobile', 'One browser family per package'],
            ['Syncs across your devices', 'Yes, with your bookmarks', 'Only within one browser account'],
            ['Can be updated without telling you', 'No. The code is fixed until you edit it.', 'Yes, automatically'],
            ['Can be sold to a new owner', 'No', 'Yes, and this is a real adware pipeline'],
            ['Keyboard shortcut and toolbar icon', 'No dedicated icon', 'Yes'],
            ['Can act before the page loads', 'No', 'Yes'],
            ['Blocked by strict site policies', 'Occasionally', 'Rarely'],
            ['Works on a locked-down work laptop', 'Usually yes', 'Often blocked by policy'],
          ],
        },
        { t: 'h2', x: 'The permissions argument, plainly' },
        { t: 'p', x: 'The Chrome prompt "read and change all your data on all websites" is not marketing caution. It means the extension can see everything rendered in your tabs: your webmail, your bank statement, the internal wiki at work. Most extensions asking for it are honest and simply need it to do their job. The problem is that the permission survives the publisher.' },
        { t: 'warn', x: 'The known failure mode is not a malicious launch, it is a **quiet handover**. A useful free extension builds an audience for two years, gets bought, and one silent auto-update later it is injecting affiliate links or logging URLs. You approved the permission once, in 2024, and never saw the change.' },
        { t: 'p', x: 'A bookmarklet cannot do that. The code is stored in your own bookmark, in plain text, and it only executes on the page you are looking at when you click it. If you want to know what it does, you can read it in ten seconds.' },
        { t: 'h2', x: 'A real bookmarklet' },
        { t: 'p', x: 'Here is the entire PrintxPDF bookmarklet. It takes the address of the page you are on, URL-encodes it, and opens the cleaner with that page loaded.' },
        { t: 'code', x: "javascript:(function(){\n  window.open(\n    'https://printxpdf.com/print?url=' + encodeURIComponent(location.href)\n  );\n})()" },
        { t: 'p', x: 'That is all of it. No network calls of its own, no storage, no listeners left behind. When you paste it into a bookmark it must be on one line, which is how the ready-made button supplies it.' },
        { t: 'h2', x: 'How to install a bookmarklet' },
        {
          t: 'steps',
          items: [
            { h: 'Show your bookmarks bar', x: 'Ctrl+Shift+B on Windows and Linux, Cmd+Shift+B on macOS. In Safari it is View then Show Favourites Bar.' },
            { h: 'Drag the ready-made button', x: 'Go to [the extensions page](/extensions/chrome) and drag the ⚡ button onto the bar. That is the whole install on desktop.' },
            { h: 'Or create it by hand', x: 'Right-click the bookmarks bar, choose **Add page**, put anything in the Name field, and paste the one-line JavaScript into the URL field. Chrome accepts `javascript:` here even though it strips it from the address bar.' },
            { h: 'In Firefox', x: 'Right-click the bar, choose **Add Bookmark**, and paste the code into the URL field. Firefox may warn about a JavaScript bookmark; that warning is expected.' },
            { h: 'On iPhone or iPad', x: 'You cannot drag. Bookmark any page, then edit that bookmark and replace its address with the code. Open Bookmarks on any page and tap it to run. Easier still: create it on your Mac and let iCloud sync it across.' },
            { h: 'Test it', x: 'Open a normal article and click it. A new tab should open with the cleaner loaded and the article already fetched.' },
          ],
        },
        { t: 'cta', tool: 'html-to-pdf', x: 'Prefer no button at all? Convert a saved HTML file to PDF directly in the browser.' },
        { t: 'h2', x: 'When an extension is genuinely the right answer' },
        {
          t: 'ul',
          items: [
            'You need it to act **before the page renders**, as ad blockers and script blockers must.',
            'You need a **keyboard shortcut** or a toolbar icon with a state, such as a counter or a toggle.',
            'You need it to run on **every page automatically** without a click.',
            'You need **persistent storage**, sync of its own settings, or a background process.',
            'The site uses a strict Content-Security-Policy that stops bookmarklets from running. This is uncommon, and the workaround is to open the tool directly and paste the URL.',
          ],
        },
        { t: 'p', x: 'Reformatting a page for printing needs none of those, which is why a bookmarklet is the honest recommendation here. To be explicit: the extension listings on this site are a **design demo**. Nothing is published in the Chrome Web Store, on addons.mozilla.org or in the App Store, and the install buttons do nothing. The bookmarklet is the working option today.' },
        { t: 'h2', x: 'A third option people forget' },
        { t: 'p', x: 'You do not need a button at all. Pasting a URL into the [web page printer](/print) takes about five seconds and installs nothing, which is the right choice on a borrowed or managed machine. Site owners who want their readers to have a print button can use the [website button](/website-button) instead, so no visitor has to install anything. The browser-specific routes are in [Chrome](/blog/extensions/print-friendly-extension-chrome), [Firefox](/blog/extensions/firefox-print-addon) and [Safari](/blog/extensions/safari-print-extension).' },
      ],
      faqs: [
        { q: 'What is a bookmarklet?', a: 'A bookmark whose address is a small piece of JavaScript instead of a web address. Clicking it runs that code on the page you are currently viewing. It needs no installation, no permissions and no background process, and it works in every browser.' },
        { q: 'Are bookmarklets safe?', a: 'A bookmarklet is exactly as safe as the code inside it, and you can read that code in your bookmark manager at any time. Unlike an extension it cannot update itself, run in the background, or gain access you did not click for.' },
        { q: 'Do bookmarklets work on iPhone?', a: 'Yes, though installing one is fiddly. Bookmark any page, edit the bookmark, and replace its address with the JavaScript. Easier: create it in Safari on a Mac and let iCloud sync it to the phone, then run it from the Bookmarks list.' },
        { q: 'Why does my bookmarklet do nothing on some sites?', a: 'A small number of sites send a strict Content-Security-Policy header that blocks injected scripts. There is no fix from your side. Open the tool directly in a new tab and paste the page URL into it instead.' },
        { q: 'Should I uninstall extensions I already have?', a: 'Audit rather than purge. Open chrome://extensions or about:addons, remove anything you do not recognise or no longer use, and set the rest to on-click site access. Broad standing permissions on forgotten extensions are the real risk.' },
      ],
      relatedTools: ['html-to-pdf', 'pdf-reader'],
      relatedPosts: ['print-friendly-extension-chrome', 'firefox-print-addon', 'print-button-any-website'],
    },
  ],
}
