import type { Cluster } from '../types'

export const compressPdf: Cluster = {
  slug: 'compress-pdf',
  name: 'Compressing PDF files',
  title: 'How to compress a PDF: make files smaller without wrecking them',
  metaTitle: 'How to Compress a PDF for Free (2026 Guide)',
  metaDescription:
    'Compress a PDF in your browser for free. Lossless structural compression, image downsampling, DPI targets, email size limits and why your PDF got so big.',
  intro:
    'A PDF gets big for one of two reasons: it contains large images, or it contains a lot of accumulated structural junk. The fix is different for each. Structural compression rewrites the file — subsets fonts, drops orphaned objects, packs the cross-reference table — and never touches a pixel. Image compression downsamples photos and scans to a target DPI, which is where the real savings live. These guides cover both, plus the email limits that started the problem.',
  answer:
    'Compress a PDF by choosing between two methods. Lossless structural compression subsets fonts and removes unused objects, typically saving 10-30 percent with zero visible change. Image downsampling re-encodes embedded photos at a lower DPI, which can cut a scanned document by 80-95 percent but is not reversible.',
  primaryKeyword: 'how to compress a pdf',
  entities: ['PDF', 'Adobe Acrobat', 'Ghostscript', 'Gmail', 'Microsoft Outlook', 'JPEG', 'Flate', 'DPI', 'macOS Preview'],
  icon: '⇩',
  tools: ['compress-pdf', 'split-pdf', 'pdf-to-jpg', 'repair-pdf'],
  posts: [
    {
      slug: 'how-to-compress-a-pdf',
      cluster: 'compress-pdf',
      title: 'How to compress a PDF file for free',
      metaTitle: 'How to Compress a PDF File for Free',
      metaDescription:
        'Compress a PDF for free in your browser. When lossless structural compression is enough, when to downsample images, and how much each method actually saves.',
      published: '2026-01-22',
      updated: '2026-08-18',
      readMinutes: 7,
      intent: 'howto',
      primaryKeyword: 'how to compress a pdf',
      secondaryKeywords: ['compress pdf free', 'make pdf smaller', 'reduce pdf size', 'shrink pdf file', 'pdf compressor'],
      entities: ['PDF', 'Adobe Acrobat', 'Ghostscript', 'macOS Preview', 'JPEG', 'Flate', 'DPI', 'qpdf'],
      answer:
        'To compress a PDF for free, open it in a browser-based compressor and pick one of two methods. Lossless structural compression subsets fonts and strips unused objects without touching a pixel. Image downsampling re-encodes photos at a lower DPI. Text documents shrink 10-30 percent; scans can drop by 90.',
      body: [
        { t: 'p', x: 'Every PDF compressor on the internet does one of two things, or both. Knowing which one your file needs is the whole game, because applying the wrong one either does nothing or ruins your document.' },
        { t: 'h2', x: 'The two kinds of PDF compression' },
        { t: 'p', x: '**Structural (lossless) compression** rewrites the plumbing of the file. It packs small objects into object streams, replaces the cross-reference table with a compressed cross-reference stream, deletes objects nothing points to any more, and subsets embedded fonts so only the glyphs you actually used are stored. Nothing you can see changes. Every pixel and every character survives exactly.' },
        { t: 'p', x: '**Image (lossy) compression** re-encodes the pictures inside the PDF. It downsamples them to a target resolution and pushes them through JPEG at a chosen quality. This is where the big numbers come from, and it is a one-way door: the discarded pixels are gone.' },
        {
          t: 'table',
          caption: 'What each method does to a typical file.',
          head: ['Method', 'What it changes', 'Typical saving', 'Reversible'],
          rows: [
            ['Font subsetting', 'Stores only the glyphs used', '50 KB - 8 MB per font', 'Yes, visually identical'],
            ['Object streams + xref streams', 'Packs metadata objects together', '5-15 percent', 'Yes'],
            ['Removing orphaned objects', 'Deletes unreferenced data left by edits', '0-40 percent', 'Yes'],
            ['Image downsampling', 'Reduces pixel dimensions to a target DPI', '60-95 percent on scans', 'No'],
            ['JPEG re-encoding', 'Lowers image quality to 60-80', '30-70 percent on photos', 'No'],
            ['Flattening layers and forms', 'Merges annotations into the page', '5-20 percent', 'No'],
          ],
        },
        { t: 'h2', x: 'Compress a PDF in your browser' },
        {
          t: 'steps',
          items: [
            { h: 'Open the compressor', x: 'Go to the [PDF compressor](/tools/compress-pdf) and drop your file on the page. Nothing is uploaded — the file is processed by your own browser, so a confidential contract never leaves your machine.' },
            { h: 'Try lossless first', x: 'Run the structural pass on its own and look at the result. If a 4 MB text document drops to 2.6 MB, stop there. You have paid nothing in quality.' },
            { h: 'Check whether images are the problem', x: 'If lossless barely moved the needle, the weight is in images. Scroll the document: if the pages look like photographs of paper rather than crisp text, it is a scan and image compression is the only lever that matters.' },
            { h: 'Pick a DPI target', x: 'Choose 150 DPI for anything that will be read on screen, 300 DPI if it will be printed, 72 DPI only for throwaway previews. Halving DPI quarters the pixel count, so 300 to 150 removes about 75 percent of the image data.' },
            { h: 'Compare before you commit', x: 'Open the compressed file and zoom to 200 percent on the smallest text on the page. Compression artefacts show up around letter edges before they show anywhere else.' },
            { h: 'Keep the original', x: 'Save the compressed copy under a new name. You cannot un-downsample an image, so the original is your only fallback.' },
          ],
        },
        { t: 'cta', tool: 'compress-pdf', x: 'Compress a PDF in your browser. No upload, no account, no watermark.' },
        { t: 'h2', x: 'Choosing a resolution' },
        {
          t: 'table',
          caption: 'DPI targets and what they are for. Sizes are per A4 page of a colour scan.',
          head: ['Target DPI', 'Pixel size (A4)', 'Approx. size per page', 'Use for'],
          rows: [
            ['600', '4960 × 7016', '3-8 MB', 'Archival masters, fine artwork, OCR of tiny print'],
            ['300', '2480 × 3508', '800 KB - 2 MB', 'Anything that will be printed'],
            ['200', '1654 × 2339', '400-900 KB', 'Good compromise for scanned contracts'],
            ['150', '1240 × 1754', '200-500 KB', 'Screen reading, email, most business documents'],
            ['96', '794 × 1123', '90-200 KB', 'Web preview, thumbnails'],
            ['72', '595 × 842', '60-150 KB', 'On-screen only, never print this'],
          ],
        },
        { t: 'note', x: '300 DPI is the standard for printing because it is roughly the point at which the human eye stops resolving individual dots at normal reading distance. Going above it for a document that will only be emailed is pure waste.' },
        { t: 'h2', x: 'What lossless compression actually removes' },
        {
          t: 'ul',
          items: [
            '**Unused font glyphs.** A full CJK or large OpenType font can be 5-20 MB. If your document uses 40 characters of it, subsetting stores 40 glyphs.',
            '**Orphaned objects.** Editing tools frequently write new objects and leave the old ones behind. Nothing references them, but they still occupy bytes.',
            '**Old revisions.** PDF supports incremental saving, where each save appends to the end of the file instead of rewriting it. A file saved thirty times can carry twenty-nine dead copies of its earlier self.',
            '**Duplicate resources.** The same logo embedded once per page becomes one shared object.',
            '**Uncompressed streams.** Some generators write page content streams with no Flate compression at all. Simply zipping them can halve a file.',
            '**Bloated metadata.** XMP packets, thumbnails and structure trees left behind by design tools.',
          ],
        },
        { t: 'h2', x: 'When compression does almost nothing' },
        { t: 'p', x: 'A clean, text-only PDF exported straight from Word or LaTeX is already near-optimal. Expect 5-15 percent, not 80. If a compressor promises to shrink a 900 KB text PDF to 90 KB, it is rasterising your pages into images, which destroys the text layer and makes the file unsearchable. Check afterwards: press Ctrl+F and search for a word you can see. If nothing is found, your text layer is gone.' },
        { t: 'warn', x: 'Never compress a signed PDF. Any change to the bytes invalidates the digital signature. Compress first, then [sign the PDF](/blog/sign-pdf/how-to-sign-a-pdf) — never the other way around.' },
        { t: 'h2', x: 'Compressing on the desktop' },
        { t: 'p', x: 'If you prefer local tools, three work well:' },
        {
          t: 'ul',
          items: [
            '**macOS Preview** — File → Export, then set Quartz Filter to "Reduce File Size". It is aggressive and slightly crude, but it is already installed.',
            '**Adobe Acrobat Pro** — File → Save as Other → Reduced Size PDF, or Tools → Optimize PDF for per-image-type control over downsampling.',
            '**Ghostscript** — free, scriptable and the engine behind many online compressors.',
          ],
        },
        { t: 'code', x: '# 150 DPI, good for email and screen reading\ngs -sDEVICE=pdfwrite -dCompatibilityLevel=1.7 \\\n   -dPDFSETTINGS=/ebook -dNOPAUSE -dQUIET -dBATCH \\\n   -sOutputFile=small.pdf big.pdf\n\n# /screen = 72 dpi, /ebook = 150 dpi, /printer and /prepress = 300 dpi' },
        { t: 'h2', x: 'If it is still too big' },
        { t: 'p', x: 'Compression has a floor. A 400-page scanned manual is not going to fit in an email no matter what you do. At that point you have two honest options: split it into parts, or send a link. See [reducing a PDF for email](/blog/compress-pdf/reduce-pdf-file-size-for-email) for the size limits of every major mail service, and [why your PDF is so large](/blog/compress-pdf/why-is-my-pdf-so-large) if you want to attack the cause instead of the symptom.' },
        { t: 'cta', tool: 'split-pdf', x: 'Too big even after compressing? Split it into chapters or page ranges instead.' },
      ],
      faqs: [
        { q: 'Does compressing a PDF reduce quality?', a: 'Only if it downsamples images. Structural compression — font subsetting, object streams, removing unused objects — is completely lossless and changes nothing you can see. Image downsampling does lose detail permanently, which is why you should always keep the original file.' },
        { q: 'How much can a PDF be compressed?', a: 'A text-only PDF usually gives 10-30 percent. A colour scan at 600 DPI can drop 90-95 percent when downsampled to 150 DPI. A PDF full of photographs sits in between, typically 40-70 percent depending on the JPEG quality you accept.' },
        { q: 'Is it safe to compress a PDF online?', a: 'It depends entirely on whether the file is uploaded. Most online compressors send your document to a server. A browser-based compressor runs the same algorithms in your own browser tab, so the file never leaves your computer — the safer choice for anything confidential.' },
        { q: 'Why did compressing my PDF make it bigger?', a: 'Usually because the images were already JPEG-compressed and the tool re-encoded them at a higher quality than the original, or because it added a new revision instead of rewriting the file. Run a lossless structural pass instead, which rewrites cleanly.' },
        { q: 'Can I compress a PDF without losing the text layer?', a: 'Yes. Any tool doing genuine PDF compression keeps text as text. If your file comes back unsearchable, the tool rasterised the pages into images. Test by pressing Ctrl+F and searching for a visible word.' },
      ],
      relatedTools: ['compress-pdf', 'split-pdf', 'pdf-to-jpg'],
      relatedPosts: ['reduce-pdf-file-size-for-email', 'why-is-my-pdf-so-large', 'compress-pdf-without-losing-quality'],
    },
    {
      slug: 'reduce-pdf-file-size-for-email',
      cluster: 'compress-pdf',
      title: 'How to reduce a PDF file size for email',
      metaTitle: 'Reduce PDF File Size for Email: Limits + Fixes',
      metaDescription:
        'Attachment limits for Gmail, Outlook, iCloud and Yahoo, why a 24 MB file still bounces, and four ways to get a large PDF into an email that actually sends.',
      published: '2026-02-14',
      updated: '2026-07-30',
      readMinutes: 6,
      intent: 'howto',
      primaryKeyword: 'reduce pdf file size for email',
      secondaryKeywords: ['pdf too large to email', 'gmail attachment limit', 'compress pdf for email', 'email attachment size limit', 'send large pdf'],
      entities: ['Gmail', 'Google Drive', 'Microsoft Outlook', 'OneDrive', 'iCloud Mail', 'WeTransfer', 'Exchange Online', 'Yahoo Mail'],
      answer:
        'Compress the PDF to a 150 DPI target first, which is enough for on-screen reading and usually gets a scan under 5 MB. Gmail and Yahoo cap attachments at 25 MB, Outlook.com and iCloud Mail at 20 MB, and MIME encoding adds about 33 percent, so aim below 18 MB.',
      body: [
        { t: 'p', x: 'The bounce message says "message too large" and gives you no number to work with. Here are the real numbers, and what to do when your file is over them.' },
        { t: 'h2', x: 'Attachment limits by service' },
        {
          t: 'table',
          caption: 'Attachment limits for major mail services, 2026. "Real file size" accounts for MIME encoding overhead.',
          head: ['Service', 'Stated limit', 'Safe real file size', 'Larger files'],
          rows: [
            ['Gmail', '25 MB per message', '~18 MB', 'Auto-offers a Google Drive link'],
            ['Outlook.com', '20 MB per message', '~14 MB', 'OneDrive link'],
            ['Microsoft 365 / Exchange Online', '25 MB default, admin-configurable to 150 MB', '~18 MB unless raised', 'OneDrive or SharePoint link'],
            ['iCloud Mail', '20 MB per message', '~14 MB', 'Mail Drop, up to 5 GB, link expires in 30 days'],
            ['Yahoo Mail', '25 MB per message', '~18 MB', 'Cloud link'],
            ['Proton Mail', '25 MB per message', '~18 MB', 'Proton Drive link'],
            ['Typical corporate gateway', '10 MB', '~7 MB', 'Ask IT, or use a file share'],
            ['WeTransfer (free)', '2 GB per transfer', '2 GB', 'Not email — a download link'],
          ],
        },
        { t: 'note', x: 'Email attachments are encoded in base64 before they travel, which turns every 3 bytes into 4. That is roughly 33 percent overhead. A 24 MB PDF becomes about 32 MB on the wire and will be rejected by a 25 MB limit. This is why your "under the limit" file bounced.' },
        { t: 'warn', x: 'The recipient limit matters too, and you cannot see it. Sending 20 MB from Gmail to someone whose employer caps inbound mail at 10 MB fails silently or bounces hours later. For anything above 10 MB, a link is more reliable than an attachment.' },
        { t: 'h2', x: 'Get the file under the limit' },
        {
          t: 'steps',
          items: [
            { h: 'Check the actual size', x: 'Right-click the file → Properties on Windows, or Get Info on macOS. Use the size in MB, not the "size on disk".' },
            { h: 'Run a lossless pass', x: 'Open the [PDF compressor](/tools/compress-pdf) and compress without downsampling. If that alone clears the limit, you are done and nothing was degraded.' },
            { h: 'Downsample to 150 DPI', x: 'If it is still too big, target 150 DPI. That is sharp on any screen and on most office printers, and it is the single biggest win for scanned documents.' },
            { h: 'Drop colour if the source is text', x: 'A black-and-white scan stored as 24-bit colour is carrying three channels of nothing. Converting to greyscale typically removes another 60 percent.' },
            { h: 'Re-check and send', x: 'Confirm the new size, open the file once to make sure it still reads properly, then attach it.' },
          ],
        },
        { t: 'cta', tool: 'compress-pdf', x: 'Compress the PDF in your browser first — the file never leaves your computer.' },
        { t: 'h2', x: 'Split it instead' },
        { t: 'p', x: 'A 60 MB report will not compress to 18 MB without becoming unreadable. Splitting is the honest alternative: send chapters 1-3 in one mail and 4-6 in another, or send only the pages the recipient asked for. Use [extract pages](/tools/extract-pages) when you need a specific range, or the [splitter](/tools/split-pdf) to cut at chapter boundaries. There is a full walkthrough in [splitting a large PDF for email](/blog/split-pdf/split-large-pdf-for-email).' },
        { t: 'h2', x: 'Send a link instead of a file' },
        {
          t: 'ul',
          items: [
            '**Google Drive** — in Gmail, click the Drive icon in the compose toolbar. Gmail offers this automatically once your attachment exceeds 25 MB. Set sharing to "Anyone with the link" or the recipient gets a permission-request loop.',
            '**OneDrive** — in Outlook, Insert → Link → Browse this computer, then choose "Upload and share". Recipients outside your tenant may need the link set to "Anyone".',
            '**iCloud Mail Drop** — Apple Mail offers this at 20 MB. Files stay available for 30 days and do not count against your iCloud storage.',
            '**WeTransfer** — no account needed on the free tier, 2 GB per transfer, and the recipient gets a plain download page. Good for one-off sends to people outside your organisation.',
          ],
        },
        { t: 'tip', x: 'A shared link also fixes the version problem. If you find a mistake after sending, you replace the file at the link. An attachment sits in the recipient inbox forever in its wrong version.' },
        { t: 'h2', x: 'Before you send anything' },
        { t: 'p', x: 'A PDF carries the author name, the software that made it, and often the full path of the folder it was saved in. If the file is going outside your organisation, [strip the metadata](/blog/pdf-privacy/remove-metadata-from-pdf) first. It takes a few seconds and costs nothing in file size.' },
        { t: 'p', x: 'If the file only got large because it is a scan, the deeper fix is on the scanner: 200 DPI greyscale for text documents, 300 DPI colour only when the colour matters. See [why your PDF is so large](/blog/compress-pdf/why-is-my-pdf-so-large) for the rest of the causes.' },
      ],
      faqs: [
        { q: 'What is the maximum PDF size I can email?', a: 'Gmail and Yahoo allow 25 MB per message, Outlook.com and iCloud Mail 20 MB, and many corporate gateways cap at 10 MB. Because base64 encoding adds about 33 percent, keep the actual file under 18 MB for a 25 MB limit and under 14 MB for a 20 MB limit.' },
        { q: 'Why does my 20 MB PDF fail to send on a 25 MB limit?', a: 'Attachments are base64-encoded for transport, which inflates them by roughly a third. A 20 MB file becomes about 27 MB on the wire. Add the message body and headers and it crosses a 25 MB limit.' },
        { q: 'How do I email a PDF that is 100 MB?', a: 'Do not attach it. Upload it to Google Drive, OneDrive, Dropbox or WeTransfer and send the link. If the recipient insists on an attachment, split the PDF into parts under 18 MB each and send several messages.' },
        { q: 'Does zipping a PDF make it smaller?', a: 'Barely. PDF content streams are already Flate-compressed, so a ZIP typically saves 2-5 percent. Zipping is useful for bundling several files into one attachment, not for reducing size.' },
        { q: 'What DPI should I use for a PDF I am emailing?', a: '150 DPI. It is crisp on any screen, prints acceptably on an office laser printer, and cuts a 600 DPI scan by roughly 94 percent. Use 300 DPI only when the recipient will print the document properly.' },
      ],
      relatedTools: ['compress-pdf', 'split-pdf', 'extract-pages'],
      relatedPosts: ['how-to-compress-a-pdf', 'split-large-pdf-for-email', 'why-is-my-pdf-so-large'],
    },
    {
      slug: 'compress-pdf-without-losing-quality',
      cluster: 'compress-pdf',
      title: 'How to compress a PDF without losing quality',
      metaTitle: 'Compress a PDF Without Losing Quality',
      metaDescription:
        'What lossless PDF compression really means, which DPI target is safe for print and screen, and how to shrink a file without visible damage to text or scans.',
      published: '2026-03-19',
      updated: '2026-08-11',
      readMinutes: 7,
      intent: 'comparison',
      primaryKeyword: 'compress pdf without losing quality',
      secondaryKeywords: ['lossless pdf compression', 'reduce pdf size without quality loss', 'best dpi for pdf', 'compress scanned pdf quality'],
      entities: ['PDF', 'JPEG', 'Flate', 'JBIG2', 'CCITT Group 4', 'Adobe Acrobat', 'Ghostscript', 'DPI'],
      answer:
        'Truly lossless PDF compression means font subsetting, object streams and removing unused objects — it changes nothing visible and saves 10-30 percent. Anything beyond that downsamples images. For documents you will only read on screen, 150 DPI is visually indistinguishable from 300 and saves about 75 percent.',
      body: [
        { t: 'p', x: '"Without losing quality" means two different things depending on what is inside your PDF, and most compression advice confuses them. A text document and a scanned document need opposite treatment.' },
        { t: 'h2', x: 'What lossless actually means in a PDF' },
        { t: 'p', x: 'Lossless is a precise technical claim: decompress the result and you get the original bytes back. In PDF terms, only a handful of operations qualify.' },
        {
          t: 'table',
          caption: 'Genuinely lossless operations versus operations that only look lossless.',
          head: ['Operation', 'Truly lossless', 'What it costs you'],
          rows: [
            ['Font subsetting', 'Yes', 'Nothing, unless someone later edits the text and needs a missing glyph'],
            ['Object streams + compressed xref', 'Yes', 'Nothing. Requires PDF 1.5 or later'],
            ['Removing unreferenced objects', 'Yes', 'Nothing. Removes only data no page points to'],
            ['Re-Flate uncompressed streams', 'Yes', 'Nothing'],
            ['Deduplicating repeated images', 'Yes', 'Nothing'],
            ['Re-encoding PNG-style images with Flate', 'Yes', 'Nothing'],
            ['Downsampling images', 'No', 'Pixels, permanently'],
            ['JPEG re-encoding', 'No', 'Detail around edges, permanently'],
            ['Flattening forms and annotations', 'No', 'Editability of the fields'],
            ['Rasterising pages to images', 'No', 'The entire text layer and all searchability'],
          ],
        },
        { t: 'warn', x: 'The last row is the trap. Some "compressors" convert every page to a JPEG and wrap the images back in a PDF. The file gets dramatically smaller and looks fine at 100 percent zoom, but the text is now a picture: unsearchable, unselectable, unusable for screen readers. Always press Ctrl+F on the result and search for a word you can see on screen.' },
        { t: 'h2', x: 'Text documents: lossless is usually enough' },
        { t: 'p', x: 'A PDF exported from Word, Google Docs or LaTeX is mostly vector text and a few images. There are no pixels to throw away, so the entire saving comes from structure. Realistic expectations:' },
        {
          t: 'ul',
          items: [
            'A clean 20-page report exported today: **5-15 percent**. It was already efficient.',
            'The same report after twelve rounds of edits and comments: **30-60 percent**, because incremental saves left old revisions inside the file.',
            'A document embedding a full CJK or large icon font: **can be dramatic**, since subsetting a 12 MB font down to the glyphs actually used is a single huge win.',
            'A document assembled by [merging](/tools/merge-pdf) ten sources: **20-40 percent**, because deduplication collapses the ten copies of the same logo into one.',
          ],
        },
        { t: 'h2', x: 'Scans: pick a DPI and accept the trade' },
        { t: 'p', x: 'A scanned page is a photograph. There is no lossless way to make a photograph meaningfully smaller. The question is how much resolution you can give up before it shows, and the honest answer depends on the destination.' },
        {
          t: 'table',
          caption: 'What each DPI target actually looks like.',
          head: ['DPI', 'Readable on screen', 'Readable printed', 'OCR accuracy', 'Verdict'],
          rows: [
            ['600', 'Yes', 'Yes, excellent', 'Excellent', 'Overkill unless archiving or scanning tiny print'],
            ['300', 'Yes', 'Yes', 'Excellent', 'The safe default when the file will be printed'],
            ['200', 'Yes', 'Good', 'Good', 'Best balance for text scans destined for email'],
            ['150', 'Yes', 'Acceptable at body-text sizes', 'Marginal', 'Fine for reading, risky if you still need to OCR'],
            ['96', 'Small text softens', 'No', 'Poor', 'Previews only'],
            ['72', 'Visibly blurry', 'No', 'Fails', 'Do not use for documents'],
          ],
        },
        { t: 'note', x: 'Do the OCR before you downsample, not after. Recognition accuracy falls off a cliff below about 200 DPI. Run [OCR](/tools/ocr-pdf) on the high-resolution scan, then compress — the text layer it produces is a few kilobytes and survives compression untouched. There is a full guide in [how to OCR a scanned PDF](/blog/ocr-scanned-documents/how-to-ocr-a-scanned-pdf).' },
        { t: 'h2', x: 'The colour mistake that costs the most' },
        { t: 'p', x: 'Most people scan black text on white paper in 24-bit colour because that is the scanner default. That stores three channels for a page that has one channel of information. Two better options:' },
        {
          t: 'ul',
          items: [
            '**Greyscale (8-bit)** — one third of the data, keeps the soft edges that make text look natural, and handles pencil marks, stamps and signatures well. This is the right default for scanned contracts.',
            '**Bitonal (1-bit)** — one twenty-fourth of the data. With CCITT Group 4 or JBIG2 encoding, a full page of text can be 20-60 KB. Perfect for clean printed text; terrible for anything with photographs, shading or a coloured letterhead.',
          ],
        },
        { t: 'h2', x: 'A safe procedure' },
        {
          t: 'steps',
          items: [
            { h: 'Keep the original', x: 'Copy the file before you touch it. Everything below is reversible only if you still have the source.' },
            { h: 'Run the lossless pass alone', x: 'In the [compressor](/tools/compress-pdf), compress structurally with no image changes. Note the new size. If it is small enough, stop.' },
            { h: 'Decide the destination', x: 'Screen only → 150 DPI. Will be printed → 300 DPI. Will be archived or re-OCR-ed → leave the images alone entirely.' },
            { h: 'Downsample once', x: 'Apply image compression to the original, not to an already-compressed copy. Compressing a JPEG twice stacks the artefacts.' },
            { h: 'Inspect at 400 percent', x: 'Zoom in on the smallest text and on any diagonal line or fine table rule. Artefacts appear there first, long before they show in body text.' },
            { h: 'Check the text layer survived', x: 'Ctrl+F for a visible word. If it is not found, the tool rasterised your pages — discard the result.' },
          ],
        },
        { t: 'cta', tool: 'compress-pdf', x: 'Run a lossless pass first and see how far it gets you.' },
        { t: 'p', x: 'If lossless gets you nowhere and downsampling would hurt, the file is simply big. Split it, or send a link. See [reducing a PDF for email](/blog/compress-pdf/reduce-pdf-file-size-for-email) for the practical limits.' },
      ],
      faqs: [
        { q: 'Is there such a thing as truly lossless PDF compression?', a: 'Yes. Font subsetting, packing objects into object streams, compressing the cross-reference table and deleting unreferenced objects are all bit-exact lossless. They typically save 10-30 percent. Anything advertising 90 percent savings on a text PDF is not lossless.' },
        { q: 'What DPI should I compress a PDF to?', a: '150 DPI for on-screen reading, 200 DPI for scanned text you may still print, 300 DPI for anything going to a printer properly. Below 150 the small text starts to soften; below 100 it becomes visibly blurry.' },
        { q: 'Will compressing a PDF break the OCR text?', a: 'No. The OCR text layer is stored as characters, not pixels, and takes a few kilobytes. Image compression never touches it. Just make sure you run OCR before downsampling, because recognition accuracy drops sharply below 200 DPI.' },
        { q: 'Why does my compressed PDF look blurry when I zoom in?', a: 'The images were downsampled below what your zoom level needs. A 150 DPI page looks perfect at 100 percent and soft at 300 percent. If you need to zoom, keep 300 DPI — or go back to the original file.' },
        { q: 'Does compressing a PDF twice make it smaller?', a: 'A second lossless pass gains nothing. A second lossy pass makes it smaller but stacks JPEG artefacts, and the damage compounds visibly. Always compress the original once at the setting you actually need.' },
      ],
      relatedTools: ['compress-pdf', 'ocr-pdf', 'pdf-to-jpg'],
      relatedPosts: ['how-to-compress-a-pdf', 'why-is-my-pdf-so-large', 'how-to-ocr-a-scanned-pdf'],
    },
    {
      slug: 'why-is-my-pdf-so-large',
      cluster: 'compress-pdf',
      title: 'Why is my PDF file so large? 8 reasons',
      metaTitle: 'Why Is My PDF So Large? 8 Causes and Fixes',
      metaDescription:
        'Eight things that make a PDF huge: scanned pages, unsubsetted fonts, duplicated images, incremental saves, uncropped photos, form fields and colour profiles.',
      published: '2026-04-08',
      updated: '2026-08-25',
      readMinutes: 8,
      intent: 'troubleshooting',
      primaryKeyword: 'why is my pdf so large',
      secondaryKeywords: ['pdf file size too big', 'what makes a pdf large', 'pdf huge file size', 'pdf bigger than original'],
      entities: ['PDF', 'Adobe InDesign', 'Microsoft Word', 'Adobe Acrobat', 'XMP', 'ICC profile', 'JPEG', 'CMYK'],
      answer:
        'A PDF is usually large for one of eight reasons: it is a scan stored as images, images are embedded at full resolution, fonts are embedded whole instead of subset, resources are duplicated per page, saves were incremental, images are cropped only visually, forms and attachments are attached, or colour profiles and transparency are heavy.',
      body: [
        { t: 'p', x: 'A four-page memo should be about 100 KB. If yours is 40 MB, something specific is wrong, and it is almost always one of the eight causes below. Work down the list — the first three account for the large majority of oversized files.' },
        { t: 'h2', x: '1. It is a scan, not a document' },
        { t: 'p', x: 'The single most common cause. If your PDF came from a scanner, a copier or a phone camera, every page is a photograph. A 600 DPI colour scan of one A4 page is 4960 × 7016 pixels — 35 megapixels, which is more than most cameras produce. Twenty pages of that is easily 100 MB.' },
        { t: 'p', x: '**Fix:** downsample to 150-200 DPI and switch colour scans of black text to greyscale. On the scanner itself, set 200 DPI greyscale as your default for documents. Reserve 300 DPI colour for photographs and artwork.' },
        { t: 'h2', x: '2. Images are embedded at their original resolution' },
        { t: 'p', x: 'You dropped a 6000-pixel-wide photo from your phone into a Word document and scaled it to two inches. On screen it looks like a small picture; inside the file it is still 6000 pixels wide, which works out to 3000 DPI. You are storing a hundred times more image data than the page can ever show.' },
        { t: 'p', x: '**Fix:** resize images to their display size before placing them. A 2-inch-wide image at 300 DPI needs 600 pixels. In Word, Picture Format → Compress Pictures → 220 ppi does this for the whole document at once.' },
        { t: 'h2', x: '3. Fonts are embedded in full instead of subset' },
        { t: 'p', x: 'PDF embeds fonts so the file renders identically everywhere. Well-behaved generators embed only the glyphs used — a subset. Badly-behaved ones embed the entire font file. A Latin font is 100-500 KB, but a CJK font covering Chinese, Japanese and Korean can be 5-25 MB. Embed three of those in full and you have a 60 MB file with nothing but text in it.' },
        { t: 'p', x: '**Fix:** run a structural compression pass, which subsets fonts as part of the rewrite. In Acrobat you can confirm the state under File → Properties → Fonts: subset fonts are labelled "Embedded Subset".' },
        { t: 'h2', x: '4. The same resource is stored many times' },
        { t: 'p', x: 'A letterhead logo placed on all 80 pages should be one object referenced 80 times. Some generators, and almost every "merge these files" workflow that does not deduplicate, store 80 separate copies. The same happens with background images, watermarks and repeated table graphics.' },
        { t: 'p', x: '**Fix:** deduplication is part of a proper structural compression pass. It is also why a merged document is often much larger than the sum of its parts until you compress it. See [merging PDF files](/blog/merge-pdf/how-to-merge-pdf-files).' },
        { t: 'h2', x: '5. Every save was an incremental update' },
        { t: 'p', x: 'PDF allows a writer to append changes to the end of the file rather than rewriting it. This is fast and it preserves digital signatures, so annotation tools use it constantly. The cost is that every previous version stays in the file. A document annotated across thirty sessions can carry twenty-nine dead copies of itself.' },
        { t: 'p', x: '**Fix:** a full rewrite — sometimes called "Save As" rather than "Save", or "linearise" — collapses the history into a single current version.' },
        { t: 'warn', x: 'Old revisions are a privacy problem too. If someone redacted a paragraph and saved incrementally, the original text may still sit in an earlier revision. [Remove metadata and flatten](/blog/pdf-privacy/remove-metadata-from-pdf) before sharing anything sensitive.' },
        { t: 'h2', x: '6. Images are cropped visually, not actually' },
        { t: 'p', x: 'Cropping in InDesign, PowerPoint or Word usually sets a visible frame over the image rather than deleting the hidden pixels. Crop a 20-megapixel photo down to a thin banner and the file still carries all 20 megapixels. The same applies to images placed partly off the edge of the page.' },
        { t: 'p', x: '**Fix:** in Word and PowerPoint, Compress Pictures has a "Delete cropped areas of pictures" checkbox. Tick it. In InDesign, use Package or export with image downsampling enabled.' },
        { t: 'h2', x: '7. Forms, annotations, attachments and scripts' },
        {
          t: 'ul',
          items: [
            '**Form fields** carry appearance streams — a stored rendering for each visual state of each field. A 200-field form can add several megabytes.',
            '**Embedded file attachments.** PDF can carry arbitrary files inside it. A spreadsheet attached to a report is invisible in the page view and fully counted in the file size.',
            '**Annotation appearance streams** from highlighting and commenting tools.',
            '**JavaScript** for form validation, plus the fonts those form fields reference.',
          ],
        },
        { t: 'p', x: '**Fix:** if the form is filled and finished, [flatten it](/tools/flatten-pdf). Flattening bakes the field values into the page and removes the interactive layer, which usually cuts a completed form substantially and also stops anyone editing the answers.' },
        { t: 'h2', x: '8. Colour profiles, transparency and vector overload' },
        { t: 'p', x: 'Print-ready files carry weight you do not need on screen: embedded ICC colour profiles for CMYK output, transparency groups flattened for older viewers, and vector artwork with tens of thousands of paths. A detailed map or CAD drawing exported as vectors can be 30 MB with no images at all.' },
        { t: 'p', x: '**Fix:** export for screen rather than for press, which drops the CMYK profiles. For a monstrous vector illustration, converting that one page to a 300 DPI image is often a 95 percent saving with no visible difference on screen.' },
        { t: 'h2', x: 'Diagnosing your own file' },
        {
          t: 'steps',
          items: [
            { h: 'Try to select text', x: 'Open the PDF and drag across a paragraph. If nothing highlights, it is a scan — cause 1, and you can stop reading here.' },
            { h: 'Divide size by page count', x: 'Under 100 KB per page is a normal text document. 100 KB - 1 MB usually means images. Over 1 MB per page is a scan or a full-resolution photo problem.' },
            { h: 'Check the fonts', x: 'File → Properties → Fonts in any full PDF viewer. Anything not marked "Embedded Subset" is cause 3.' },
            { h: 'Look for a rogue page', x: 'Split the file and compare the parts. One 25 MB page among forty 80 KB pages points straight at a single oversized image or vector drawing.' },
            { h: 'Run a lossless compression pass', x: 'Whatever the [compressor](/tools/compress-pdf) removes without touching images was structural waste — causes 3, 4 and 5.' },
          ],
        },
        {
          t: 'table',
          caption: 'Quick diagnosis by symptom.',
          head: ['Symptom', 'Likely cause', 'Fix'],
          rows: [
            ['Text cannot be selected', 'Scanned pages (1)', 'Downsample to 150-200 DPI, use greyscale'],
            ['Small file grew after editing', 'Incremental saves (5)', 'Save As, or run a structural rewrite'],
            ['Text-only file is 40 MB', 'Unsubsetted fonts (3)', 'Structural compression with font subsetting'],
            ['Merged file bigger than its parts', 'Duplicated resources (4)', 'Deduplicating compression pass'],
            ['One page is enormous', 'Full-resolution or uncropped image (2, 6)', 'Resize the image, delete cropped areas'],
            ['Filled form is huge', 'Field appearance streams (7)', 'Flatten the form'],
          ],
        },
        { t: 'cta', tool: 'compress-pdf', x: 'Start with a lossless pass — it tells you how much of your problem is structural.' },
      ],
      faqs: [
        { q: 'Why is my PDF bigger than the Word document it came from?', a: 'Word stores images compressed and fonts by reference. A PDF embeds the fonts and often stores images re-encoded at full resolution so the file renders identically everywhere. Use Word Compress Pictures at 220 ppi before exporting to close most of the gap.' },
        { q: 'Why did my PDF get bigger after I added a comment?', a: 'Annotation tools save incrementally, appending the change to the end of the file instead of rewriting it. Each session adds another layer. Doing a Save As, or running a structural compression pass, collapses them back into one version.' },
        { q: 'How big should a normal PDF be?', a: 'Roughly 20-100 KB per page for text with a few images. 100 KB - 1 MB per page for image-heavy documents. Over 1 MB per page almost always means scanned pages or photos embedded at their original camera resolution.' },
        { q: 'Does deleting pages reduce PDF file size?', a: 'Only if the tool rewrites the file. Some editors mark pages as removed but leave the objects in place. Delete the pages, then run a compression pass so the orphaned objects are actually dropped.' },
        { q: 'Can a PDF be large with no images at all?', a: 'Yes. Fully embedded CJK fonts, complex vector artwork such as maps or CAD exports, hundreds of form fields with appearance streams, and embedded file attachments can all produce a very large PDF with nothing but text and lines on the page.' },
      ],
      relatedTools: ['compress-pdf', 'flatten-pdf', 'split-pdf'],
      relatedPosts: ['how-to-compress-a-pdf', 'compress-pdf-without-losing-quality', 'reduce-pdf-file-size-for-email'],
    },
  ],
}
