import type { Cluster } from '../types'

export const convertToPdf: Cluster = {
  slug: 'convert-to-pdf',
  name: 'Converting files to PDF',
  title: 'Converting Word, Excel, HTML and images to PDF',
  metaTitle: 'Convert Word, Excel, HTML and Images to PDF',
  metaDescription:
    'Turn documents, spreadsheets, web pages and photos into PDFs that look right. Font embedding, print areas, page-break CSS and the DPI that matters in print.',
  intro:
    'Converting into PDF is the easy direction: the format was designed to freeze a layout so it renders identically everywhere. The failures are all avoidable and all boring — a font that was not embedded, a spreadsheet that spills onto 40 pages, a table cut in half by a page break, a photo at 72 DPI that prints like a mosaic. These guides cover the settings that prevent each one, in Word, Excel, browsers and image tools.',
  answer:
    'Every major application exports PDF directly: Word uses File → Save As → PDF, Excel uses Export → Create PDF/XPS after setting a print area, browsers use Ctrl+P with "Save as PDF" as the destination, and images can be combined into a single PDF. The settings that matter are font embedding, scale-to-fit and DPI.',
  primaryKeyword: 'convert to pdf',
  entities: ['Microsoft Word', 'Microsoft Excel', 'Google Docs', 'LibreOffice', 'Google Chrome', 'PDF/A', 'macOS Preview', 'HEIC'],
  icon: '⇧',
  tools: ['word-to-pdf', 'excel-to-pdf', 'html-to-pdf', 'jpg-to-pdf'],
  posts: [
    {
      slug: 'word-to-pdf',
      cluster: 'convert-to-pdf',
      title: 'How to convert Word to PDF and keep the fonts',
      metaTitle: 'Convert Word to PDF and Keep the Fonts',
      metaDescription:
        'Export a Word document to PDF with fonts embedded, links intact and headings preserved. The Save As options that matter, plus Google Docs and LibreOffice.',
      published: '2026-02-06',
      updated: '2026-07-25',
      readMinutes: 6,
      intent: 'howto',
      primaryKeyword: 'convert word to pdf',
      secondaryKeywords: ['word to pdf free', 'save docx as pdf', 'embed fonts in pdf', 'word to pdf keep formatting', 'docx to pdf'],
      entities: ['Microsoft Word', 'Google Docs', 'LibreOffice Writer', 'PDF/A', 'DOCX', 'macOS Preview', 'OpenType'],
      answer:
        'In Word, use File → Save As and pick PDF, or File → Export → Create PDF/XPS. Word embeds every font it can automatically. On macOS choose "Best for electronic distribution and accessibility" rather than printing to PDF, because the print route drops hyperlinks and accessibility tags.',
      body: [
        { t: 'p', x: 'Word to PDF is a two-click job that goes wrong in exactly three ways: a substituted font, a lost hyperlink, or a file four times bigger than it needed to be. All three come from picking the wrong export route.' },
        { t: 'h2', x: 'Word on Windows' },
        {
          t: 'steps',
          items: [
            { h: 'Use Save As, not Print', x: '**File → Save As**, then set "Save as type" to **PDF (*.pdf)**. This uses Microsoft own PDF writer, which embeds fonts, keeps hyperlinks clickable and writes structure tags.' },
            { h: 'Open Options before saving', x: 'Click the **Options…** button next to the Optimize choice. This is the dialog most people never open and it controls everything below.' },
            { h: 'Decide on bookmarks', x: 'Tick **Create bookmarks using: Headings** for any document over about ten pages. It builds a clickable outline in the PDF from your Word heading styles, for free.' },
            { h: 'Keep the accessibility tags', x: 'Leave **Document structure tags for accessibility** ticked. It costs a few kilobytes and makes the PDF readable by screen readers and reflowable on phones.' },
            { h: 'Choose PDF/A only if you need it', x: '**ISO 19005-1 compliant (PDF/A)** forces every font to be fully embedded and forbids external dependencies. Right for legal and archival submissions, but it produces a bigger file and disallows transparency effects.' },
            { h: 'Pick Standard, not Minimum size', x: 'Back in the Save As dialog, "Minimum size" downsamples every image to about 96 DPI. Fine for a web handout, wrong for anything that will be printed.' },
          ],
        },
        { t: 'note', x: 'File → Export → Create PDF/XPS opens the same dialog by a different route. There is no difference in the output.' },
        { t: 'h2', x: 'Word on macOS' },
        { t: 'p', x: 'Mac Word gives you two very different paths and only labels the difference obliquely:' },
        {
          t: 'ul',
          items: [
            '**File → Save As → File Format: PDF → "Best for electronic distribution and accessibility"** uses Microsoft own converter. Hyperlinks stay clickable, headings become bookmarks, accessibility tags are written. **Use this one.**',
            '**"Best for printing"** routes through the macOS print pipeline. The pages look right, but hyperlinks stop working, tags are gone and bookmarks are gone.',
            '**File → Print → PDF → Save as PDF** is the same print pipeline with the same losses. Convenient, but not for a document you are sending to someone.',
          ],
        },
        { t: 'h2', x: 'Why fonts get substituted' },
        { t: 'p', x: 'PDF embeds fonts so the file renders identically on a machine that has never heard of your typeface. Word does this automatically, with one exception you cannot argue with: some commercial fonts carry an embedding permission flag in their OS/2 table set to "Restricted License". Word obeys it and substitutes a similar font instead. There is no setting that overrides this, and no honest tool that ignores it.' },
        {
          t: 'table',
          caption: 'Font embedding by export route.',
          head: ['Route', 'Fonts embedded', 'Hyperlinks', 'Bookmarks', 'Accessibility tags'],
          rows: [
            ['Word Windows → Save As PDF', 'Yes, subset', 'Yes', 'Optional', 'Optional'],
            ['Word Mac → "electronic distribution"', 'Yes, subset', 'Yes', 'Yes', 'Yes'],
            ['Word Mac → "Best for printing"', 'Yes', 'No', 'No', 'No'],
            ['File → Print → Save as PDF', 'Yes', 'No', 'No', 'No'],
            ['Google Docs → Download PDF', 'Yes', 'Yes', 'Yes', 'Partial'],
            ['LibreOffice → Export as PDF', 'Yes', 'Yes', 'Yes', 'Yes'],
            ['Word → Save As → PDF/A', 'Yes, full embedding', 'Yes', 'Optional', 'Required'],
          ],
        },
        { t: 'p', x: 'To confirm afterwards, open the PDF in a full viewer and check **File → Properties → Fonts**. Every entry should say "Embedded" or "Embedded Subset". Anything without that label will be substituted on a machine that lacks the font.' },
        { t: 'h2', x: 'Google Docs' },
        { t: 'p', x: '**File → Download → PDF Document (.pdf)**. It embeds fonts, keeps links clickable and turns your heading styles into bookmarks. The catch is upstream: if you uploaded a .docx using a font Google does not have, Docs already substituted it when it opened the file, so the PDF faithfully records the wrong typeface. Check the document on screen before exporting.' },
        { t: 'h2', x: 'LibreOffice Writer' },
        { t: 'p', x: '**File → Export As → Export as PDF** opens the most detailed export dialog of any free office suite. The General tab controls JPEG quality and image downsampling; Digital Signatures lets you sign at export time; the PDF/A-2b checkbox is on the General tab. LibreOffice embeds fonts by default and honours the same licence restrictions Word does.' },
        { t: 'cta', tool: 'word-to-pdf', x: 'No Word licence? Convert a .docx to PDF in your browser — nothing is uploaded.' },
        { t: 'h2', x: 'Keeping the file small' },
        { t: 'p', x: 'A Word document with a few phone photos in it routinely exports as a 30 MB PDF, because Word stores the images at their original camera resolution. Before exporting, click any image, then **Picture Format → Compress Pictures → Apply to all pictures**, choose **Print (220 ppi)**, and tick **Delete cropped areas of pictures**. That one step frequently removes 80 percent of the eventual file size. There is more in [why your PDF is so large](/blog/compress-pdf/why-is-my-pdf-so-large), and you can always run the [compressor](/tools/compress-pdf) afterwards.' },
        { t: 'warn', x: 'Converting to PDF does not protect your content — it just makes editing inconvenient. It also does not remove the document history. The author name, company and editing time are copied straight from the Word properties into the PDF metadata. [Strip the metadata](/blog/pdf-privacy/remove-metadata-from-pdf) before sending anything outside your organisation.' },
        { t: 'p', x: 'If the finished PDF needs a signature, do that last: [sign the PDF](/blog/sign-pdf/how-to-sign-a-pdf) after every other change, because any later edit invalidates it.' },
      ],
      faqs: [
        { q: 'How do I convert Word to PDF for free?', a: 'Word itself does it: File → Save As, then choose PDF as the file type. Google Docs does it with File → Download → PDF Document. LibreOffice does it with File → Export as PDF. All three are free at the point of use and all three embed fonts.' },
        { q: 'Why do my fonts change when I save a Word file as PDF?', a: 'Either the font carries a restricted embedding licence, which Word must obey and substitutes around, or you exported through the macOS print pipeline. Use Save As with "Best for electronic distribution", and check File → Properties → Fonts in the result.' },
        { q: 'How do I keep hyperlinks working in the PDF?', a: 'Use Save As → PDF rather than Print → Save as PDF. The print pipeline flattens the page and loses link annotations. On a Mac specifically, pick "Best for electronic distribution and accessibility", not "Best for printing".' },
        { q: 'What is PDF/A and should I use it?', a: 'PDF/A is the archival standard: every font fully embedded, no external references, no encryption. Use it for legal filings, thesis submissions and long-term archives. Skip it otherwise, because it produces larger files and forbids some transparency effects.' },
        { q: 'Why is my exported PDF so much bigger than the Word file?', a: 'Word compresses images internally and references fonts; the PDF embeds fonts and often stores images at full resolution. Run Picture Format → Compress Pictures at 220 ppi with "Delete cropped areas" ticked before exporting, then compress the PDF if needed.' },
      ],
      relatedTools: ['word-to-pdf', 'compress-pdf', 'sign-pdf'],
      relatedPosts: ['excel-to-pdf', 'html-to-pdf', 'why-is-my-pdf-so-large'],
    },
    {
      slug: 'excel-to-pdf',
      cluster: 'convert-to-pdf',
      title: 'How to convert an Excel spreadsheet to PDF that actually fits',
      metaTitle: 'Excel to PDF: Make the Spreadsheet Actually Fit',
      metaDescription:
        'Stop Excel exporting 40 pages of stray columns. Set a print area, fit to one page wide, repeat header rows, control page breaks and export a readable PDF.',
      published: '2026-03-05',
      updated: '2026-08-08',
      readMinutes: 7,
      intent: 'howto',
      primaryKeyword: 'convert excel to pdf',
      secondaryKeywords: ['excel to pdf fit to page', 'spreadsheet to pdf', 'excel print area pdf', 'excel to pdf one page', 'xlsx to pdf'],
      entities: ['Microsoft Excel', 'Page Layout', 'Print Titles', 'Page Break Preview', 'Google Sheets', 'LibreOffice Calc', 'A4'],
      answer:
        'Set a print area, then use Page Layout → Scale to Fit with Width set to 1 page and Height left on Automatic. Add repeating header rows through Print Titles, switch to landscape for wide tables, and export with File → Export → Create PDF/XPS. Never set both Width and Height to 1 page.',
      body: [
        { t: 'p', x: 'Excel exports to PDF badly by default because a spreadsheet has no page size. It is an infinite grid, and Excel has to guess where to cut it. Six settings turn that guess into a decision you control, and they all live on the Page Layout tab.' },
        { t: 'h2', x: 'The six settings that matter' },
        {
          t: 'steps',
          items: [
            { h: 'Set the print area', x: 'Select the cells you actually want, then **Page Layout → Print Area → Set Print Area**. Without this, Excel exports every cell that has ever been touched — including the stray space in BZ4000 that produces 38 blank pages.' },
            { h: 'Fit to width, not to page', x: 'In **Page Layout → Scale to Fit**, set **Width: 1 page** and leave **Height: Automatic**. This is the single most important setting. It stops columns spilling onto their own sheets while letting the rows flow naturally over as many pages as they need.' },
            { h: 'Go landscape for wide tables', x: '**Page Layout → Orientation → Landscape**. A4 landscape is 297 mm wide against 210 portrait — 41 percent more width for nothing.' },
            { h: 'Repeat the header row', x: '**Page Layout → Print Titles → Sheet tab → Rows to repeat at top**, then click the row selector for row 1 (it fills in as `$1:$1`). Now every page carries the column headings instead of just the first.' },
            { h: 'Check Page Break Preview', x: '**View → Page Break Preview** shows blue lines where the pages will split. Drag them to move a break. Solid blue is a manual break you set; dashed blue is Excel automatic choice.' },
            { h: 'Export', x: '**File → Export → Create PDF/XPS**, then click **Options** to choose Active sheet(s), Entire workbook or Selection, and to set a page range.' },
          ],
        },
        { t: 'warn', x: 'Do not set both Width and Height to 1 page unless the data really is small. Excel will shrink the whole sheet until it fits, and a 200-row table forced onto one page ends up at about 4 point type — technically one page, unreadable in practice. Width 1 / Height Automatic is almost always what you meant.' },
        { t: 'h2', x: 'Every relevant setting, and where it lives' },
        {
          t: 'table',
          caption: 'Excel print settings that change the PDF.',
          head: ['Problem', 'Setting', 'Where'],
          rows: [
            ['Dozens of near-blank pages', 'Print Area', 'Page Layout → Print Area → Set Print Area'],
            ['Columns spill to extra sheets', 'Width: 1 page', 'Page Layout → Scale to Fit'],
            ['Table is too wide', 'Landscape', 'Page Layout → Orientation'],
            ['Headers only on page 1', 'Rows to repeat at top', 'Page Layout → Print Titles → Sheet'],
            ['Page splits mid-section', 'Manual page break', 'Page Layout → Breaks → Insert Page Break'],
            ['Content hugs the left edge', 'Center on page: Horizontally', 'Page Setup dialog → Margins'],
            ['No grid on the printout', 'Gridlines → Print', 'Page Layout → Sheet Options'],
            ['Want row and column labels', 'Headings → Print', 'Page Layout → Sheet Options'],
            ['Pages come out in a strange order', 'Page order: Down, then over', 'Page Setup dialog → Sheet'],
            ['Only one sheet exported', 'Publish what: Entire workbook', 'Export → Options'],
          ],
        },
        { t: 'tip', x: 'The little arrow at the bottom-right corner of the Page Setup group on the Page Layout tab opens the full Page Setup dialog. Centring, page order, first page number and print quality live there and nowhere else on the ribbon.' },
        { t: 'h2', x: 'Things that catch people out' },
        {
          t: 'ul',
          items: [
            '**Hidden rows and columns do not print.** That is usually what you want, but check that you did not hide something you needed. Filtered-out rows are hidden rows.',
            '**Grouped and collapsed outlines print collapsed.** Expand before exporting if the detail matters.',
            '**Comments and notes are invisible by default.** Page Setup → Sheet → Comments and Notes → "As displayed on sheet" or "At end of sheet".',
            '**Error values print as they appear.** Set Page Setup → Sheet → Cell errors as: `<blank>` to hide a column of #N/A from a client.',
            '**Charts export at screen resolution** unless they are on their own chart sheet. A chart embedded in a sheet can look soft in the PDF; move it to a dedicated chart sheet for a crisp result.',
            '**Conditional formatting colours print.** Check the cost in ink, or set Page Setup → Sheet → Black and white.',
          ],
        },
        { t: 'h2', x: 'Google Sheets and LibreOffice Calc' },
        { t: 'p', x: 'In **Google Sheets**, File → Download → PDF Document opens a print preview with the same controls under different names: Scale offers "Fit to width", Headers & footers has "Repeat frozen rows", and the Export dropdown chooses Current sheet, Workbook or Selected cells. Freeze row 1 with View → Freeze → 1 row first, so the repeat option becomes available.' },
        { t: 'p', x: 'In **LibreOffice Calc**, Format → Print Ranges → Define sets the print area, and Format → Page Style → Sheet has "Fit print range to width/height" plus "Rows to repeat".' },
        { t: 'cta', tool: 'excel-to-pdf', x: 'Convert an .xlsx to PDF in your browser, with fit-to-width handled for you.' },
        { t: 'h2', x: 'After the export' },
        { t: 'p', x: 'Always open the PDF and read it before sending. Two checks catch nearly everything: does page 2 have headers, and does any column end in `#####` (the column was too narrow and Excel could not display the number). Widen the column and export again.' },
        { t: 'p', x: 'If you exported each sheet separately, [merge them](/blog/merge-pdf/how-to-merge-pdf-files) into one document. If a monthly report needs page numbers, [add them to the PDF](/blog/watermark-page-numbers/add-page-numbers-to-pdf) rather than fighting Excel footers, which do not know how many pages the whole compiled document has. If the workbook is full of charts and screenshots, [compress the result](/tools/compress-pdf) before emailing it.' },
      ],
      faqs: [
        { q: 'How do I make an Excel spreadsheet fit on one page in PDF?', a: 'Page Layout → Scale to Fit, set Width to 1 page and leave Height on Automatic. Setting both to 1 page shrinks the text until everything fits, which for anything over about 40 rows produces type too small to read.' },
        { q: 'Why does my Excel PDF have so many blank pages?', a: 'Excel exports everything up to the last cell ever used, including cells you cleared but did not delete. Select your data, then Page Layout → Print Area → Set Print Area. To fix it permanently, delete the unused rows and columns entirely and save.' },
        { q: 'How do I repeat the header row on every page of the PDF?', a: 'Page Layout → Print Titles, open the Sheet tab, click in "Rows to repeat at top" and select row 1 so it reads $1:$1. Excel then prints those rows at the top of every page. Freezing panes does not do this.' },
        { q: 'Can I export the whole workbook to one PDF?', a: 'Yes. File → Export → Create PDF/XPS, click Options, and choose "Entire workbook". Each sheet keeps its own page setup, so set the print area and scaling on every sheet before you export, not just the active one.' },
        { q: 'Why are my numbers showing as hashes in the PDF?', a: 'The column is too narrow for the formatted number, so Excel displays ##### instead. It prints exactly as displayed. Widen the column, or reduce the decimal places, then export again.' },
      ],
      relatedTools: ['excel-to-pdf', 'merge-pdf', 'page-numbers'],
      relatedPosts: ['word-to-pdf', 'html-to-pdf', 'how-to-merge-pdf-files'],
    },
    {
      slug: 'html-to-pdf',
      cluster: 'convert-to-pdf',
      title: 'How to convert HTML to PDF',
      metaTitle: 'How to Convert HTML to PDF (Browser + Code)',
      metaDescription:
        'Convert HTML to PDF with the browser print dialog or headless Chrome. The @page and break-inside CSS that controls pagination, plus margins and backgrounds.',
      published: '2026-04-02',
      updated: '2026-08-30',
      readMinutes: 7,
      intent: 'howto',
      primaryKeyword: 'convert html to pdf',
      secondaryKeywords: ['html to pdf free', 'webpage to pdf', 'headless chrome pdf', 'css page break pdf', 'print to pdf css'],
      entities: ['Google Chrome', 'Puppeteer', 'WeasyPrint', 'CSS Paged Media', 'A4', 'Chromium', 'DevTools'],
      answer:
        'For a one-off, press Ctrl+P and set the destination to "Save as PDF" — the browser renders real text and clickable links. For repeatable output, control pagination with @page and break-inside CSS, and drive headless Chrome or Puppeteer so every run produces an identical file.',
      body: [
        { t: 'p', x: 'Your browser already contains an excellent HTML-to-PDF engine. The question is only how much control you need over the result.' },
        { t: 'h2', x: 'The one-off: print to PDF' },
        {
          t: 'steps',
          items: [
            { h: 'Load the page and scroll to the bottom', x: 'Lazy-loaded images below the fold never downloaded. Scroll all the way down first or they will be blank in the PDF.' },
            { h: 'Open the print dialog', x: 'Ctrl+P on Windows and Linux, Cmd+P on macOS.' },
            { h: 'Set the destination', x: 'Choose **Save as PDF** in the Destination dropdown, not a physical printer.' },
            { h: 'Open More settings', x: 'Set **Paper size** (A4 or Letter), **Margins** (Default, or None for a full-bleed capture), and **Scale**. Scale at 80 percent fits noticeably more per page and stays readable.' },
            { h: 'Decide about backgrounds', x: 'Tick **Background graphics** to keep coloured panels, table stripes and CSS background images. Leave it off to save ink if you will also print on paper.' },
            { h: 'Turn off headers and footers', x: 'Otherwise the browser stamps the page title, URL, date and page number onto every sheet.' },
          ],
        },
        { t: 'p', x: 'The result is a real text PDF: selectable, searchable and with working links. That matters — an image-based capture of the same page looks identical and is useless for search. If the page is full of ads and navigation, clean it first with the [web page printer](/print) and see [printing a web page without ads](/blog/print-web-pages/print-web-page-without-ads).' },
        { t: 'cta', tool: 'html-to-pdf', x: 'Convert an HTML file or a URL to PDF in your browser.' },
        { t: 'h2', x: 'Controlling the pagination with CSS' },
        { t: 'p', x: 'If you own the HTML, a handful of CSS rules fix the classic problems: a heading stranded at the bottom of a page, a table row split down the middle, an invoice total on a page by itself.' },
        { t: 'code', x: '@page {\n  size: A4;              /* or: A4 landscape, Letter, 210mm 297mm */\n  margin: 20mm 15mm;\n}\n\n@media print {\n  /* Never split these across a page boundary */\n  table, figure, blockquote, .invoice-total { break-inside: avoid; }\n  tr, li { break-inside: avoid; }\n\n  /* Keep a heading with the text that follows it */\n  h1, h2, h3 { break-after: avoid; }\n\n  /* Start each chapter on a fresh page */\n  .chapter { break-before: page; }\n\n  /* No orphaned single lines */\n  p { orphans: 3; widows: 3; }\n\n  /* Repeat table headers on every page */\n  thead { display: table-header-group; }\n\n  /* Print the destination of every link */\n  a[href^="http"]::after { content: " (" attr(href) ")"; font-size: 90%; }\n\n  nav, aside, .no-print { display: none; }\n}' },
        { t: 'p', x: 'Two of those rules do most of the work. `break-inside: avoid` on tables, figures and totals stops the single most common complaint, a block cut in half by a page boundary. `thead { display: table-header-group }` makes a long table repeat its column headings on every page, which is the paper equivalent of a frozen row. Everything else is a refinement you add once those two are in place.' },
        { t: 'note', x: '`break-inside`, `break-before` and `break-after` are the current CSS Fragmentation properties. The older `page-break-inside` family still works everywhere and is what most existing stylesheets use. Chrome and Firefox support both; keeping the legacy pair alongside the modern one costs nothing.' },
        { t: 'warn', x: '`position: fixed` and `position: sticky` elements are unreliable in print — a sticky header can appear on page one only, or on every page, or overlap the content. Set them to `position: static` inside your print media query.' },
        { t: 'h2', x: 'Headless Chrome for developers' },
        { t: 'p', x: 'For automated invoices, reports or receipts, drive the same rendering engine from the command line so every run is identical.' },
        { t: 'code', x: '# Chrome / Chromium, no browser window\nchrome --headless=new --disable-gpu \\\n       --print-to-pdf=invoice.pdf \\\n       --no-pdf-header-footer \\\n       https://example.com/invoice/1042\n\n# Puppeteer, with backgrounds and explicit margins\nconst browser = await puppeteer.launch();\nconst page = await browser.newPage();\nawait page.goto(url, { waitUntil: "networkidle0" });\nawait page.pdf({\n  path: "invoice.pdf",\n  format: "A4",\n  printBackground: true,\n  margin: { top: "20mm", bottom: "20mm", left: "15mm", right: "15mm" }\n});\nawait browser.close();' },
        { t: 'p', x: 'Two options matter more than the rest. `--no-pdf-header-footer` removes the URL and date stamp Chrome otherwise prints on every sheet, and `waitUntil: "networkidle0"` holds the capture until the page has stopped fetching, which is what prevents half-rendered charts. Always set the page format explicitly as well: Chrome defaults to US Letter regardless of your locale.' },
        {
          t: 'table',
          caption: 'HTML to PDF approaches compared.',
          head: ['Approach', 'Fidelity', 'Automatable', 'Notes'],
          rows: [
            ['Browser Ctrl+P', 'Exactly what Chrome renders', 'No', 'Free, instant, keeps links and text'],
            ['Browser tool in-page', 'Very high', 'No', 'No upload, good for local .html files'],
            ['Headless Chrome / Puppeteer', 'Identical to Chrome', 'Yes', 'Needs a Chromium binary, ~150 MB'],
            ['Playwright', 'Identical to Chromium', 'Yes', 'Cross-browser, PDF output is Chromium only'],
            ['WeasyPrint (Python)', 'Good, no JavaScript', 'Yes', 'Excellent Paged Media support, lightweight'],
            ['wkhtmltopdf', 'Dated engine', 'Yes', 'Archived project, old WebKit, avoid for new work'],
          ],
        },
        { t: 'tip', x: 'Debug a print stylesheet without printing anything. In Chrome DevTools press Ctrl+Shift+P, type "Show Rendering", and set **Emulate CSS media type** to `print`. The live page now renders with your print rules so you can inspect and edit them normally.' },
        { t: 'h2', x: 'Things that reliably break' },
        {
          t: 'ul',
          items: [
            '**Web fonts that have not finished loading.** In an automated run, wait for `document.fonts.ready` before generating the PDF or you get fallback fonts.',
            '**Lazy-loaded images.** Set `loading="eager"` in the print path, or scroll the page programmatically before capture.',
            '**Charts drawn in canvas.** They render as bitmaps at screen resolution and look soft. Render SVG for print, or draw the canvas at 2x and scale it down in CSS.',
            '**Viewport units.** `100vh` means the screen height, which has no meaning on paper. Use `mm` or `cm` inside the print media query.',
            '**Elements with `overflow: hidden` and a fixed height.** Only the visible portion prints; the rest is silently cut.',
          ],
        },
        { t: 'p', x: 'Once the PDF exists, [compress it](/tools/compress-pdf) if it is heading into an email, or [merge](/tools/merge-pdf) several generated pages into one document.' },
      ],
      faqs: [
        { q: 'How do I convert an HTML file to PDF for free?', a: 'Open the .html file in your browser with Ctrl+O, press Ctrl+P, and set the destination to "Save as PDF". The browser renders it exactly as it displays it, with selectable text and clickable links, at no cost and with no upload.' },
        { q: 'How do I stop a table breaking across pages in a PDF?', a: 'Add `break-inside: avoid` (and the legacy `page-break-inside: avoid`) to the table and to its rows inside a print media query. Add `thead { display: table-header-group }` so the header row repeats at the top of each page.' },
        { q: 'Why does my PDF look different from the web page?', a: 'The browser applies your print stylesheet, drops fixed positioning, and paginates a continuous layout. Emulate it in Chrome DevTools: Ctrl+Shift+P, "Show Rendering", set Emulate CSS media type to print, and fix what you see.' },
        { q: 'How do I set the page size and margins in CSS?', a: 'Use the @page rule: `@page { size: A4; margin: 20mm 15mm; }`. Add `landscape` after the size keyword for landscape. Browsers honour this in the print dialog, though the user can still override the margins manually.' },
        { q: 'What is the best HTML to PDF library?', a: 'For fidelity, Puppeteer or Playwright driving headless Chromium, because it is the same engine users see. For a lightweight server with no browser binary, WeasyPrint has the best CSS Paged Media support. Avoid wkhtmltopdf for new projects — it is archived and uses an old WebKit.' },
      ],
      relatedTools: ['html-to-pdf', 'compress-pdf', 'merge-pdf'],
      relatedPosts: ['word-to-pdf', 'images-to-pdf', 'print-web-page-without-ads'],
    },
    {
      slug: 'images-to-pdf',
      cluster: 'convert-to-pdf',
      title: 'How to combine photos and scans into one PDF',
      metaTitle: 'Combine Photos and Scans Into One PDF',
      metaDescription:
        'Turn JPG, PNG and HEIC photos into one PDF: page size, orientation, ordering, the DPI you need for printing, and the right settings for receipts and scans.',
      published: '2026-05-07',
      updated: '2026-08-27',
      readMinutes: 7,
      intent: 'howto',
      primaryKeyword: 'combine images into one pdf',
      secondaryKeywords: ['jpg to pdf', 'photos to pdf', 'scan to pdf', 'multiple images to one pdf', 'heic to pdf'],
      entities: ['JPEG', 'PNG', 'HEIC', 'macOS Preview', 'Microsoft Print to PDF', 'A4', 'iOS', 'DPI'],
      answer:
        'Drop your JPG or PNG files into an image-to-PDF tool, put them in the right order, and pick a page size. Choose A4 or Letter with each image fitted to the page for documents, and 300 DPI if the result will be printed. HEIC files from an iPhone must be converted to JPEG first in most browsers.',
      body: [
        { t: 'p', x: 'Photographing receipts, scanning a signed contract page by page, assembling a portfolio — they all end the same way: a folder of images that somebody wants as one file. Four decisions determine whether the result is usable.' },
        { t: 'h2', x: 'Decision 1: page size' },
        {
          t: 'table',
          caption: 'Page size by purpose.',
          head: ['Purpose', 'Page size', 'Fit mode'],
          rows: [
            ['Scanned documents, contracts', 'A4 or US Letter', 'Fit image to page, keep aspect ratio'],
            ['Receipts and small slips', 'A4, several per page', 'Fit, or tile 2-4 per sheet to save paper'],
            ['Photo album or portfolio', 'Match the image aspect ratio', 'Page size follows the image'],
            ['Mixed sizes from different sources', 'A4 for everything', 'Fit, so pages stay consistent'],
            ['Presentation handout', 'A4 landscape', 'Fit to page'],
          ],
        },
        { t: 'p', x: 'A4 is 210 × 297 mm; US Letter is 8.5 × 11 inches (216 × 279 mm). They are close but not identical, so a Letter-sized PDF printed on A4 gets a slightly different margin. Pick the one your recipient uses. For documents, one image per page with the aspect ratio preserved is almost always right — stretching a photo to fill A4 distorts it.' },
        { t: 'h2', x: 'Decision 2: DPI' },
        { t: 'p', x: 'DPI in this context means: how many of your image pixels land in one printed inch. It is arithmetic, not a setting you can wish for.' },
        {
          t: 'table',
          caption: 'Pixels needed to fill a page at each quality level.',
          head: ['Target', 'DPI', 'Pixels for a full A4 page', 'Typical result'],
          rows: [
            ['Professional print', '300', '2480 × 3508', 'Sharp at any reading distance'],
            ['Office printing', '200', '1654 × 2339', 'Good for text and diagrams'],
            ['Screen reading, email', '150', '1240 × 1754', 'Crisp on screen, acceptable on paper'],
            ['Web preview only', '72', '595 × 842', 'Visibly soft when printed'],
          ],
        },
        { t: 'p', x: 'A modern phone photo is typically 4032 × 3024 pixels, which is more than enough for a 300 DPI A4 page. A screenshot from a laptop is often 1440 × 900, which fills an A4 page at only about 110 DPI — fine on screen, soft on paper. You cannot add detail that was never captured, so scan or photograph at the resolution you need from the start.' },
        { t: 'h2', x: 'Decision 3: order' },
        { t: 'p', x: 'This is where most people lose ten minutes. Files named `page1.jpg` through `page10.jpg` sort as 1, 10, 2, 3 in almost every file browser, because the sort is alphabetical. Rename with zero padding — `page01`, `page02` … `page10` — and everything falls into place automatically. Phone photos named IMG_0001 onwards are already padded and sort correctly by capture time.' },
        { t: 'h2', x: 'Decision 4: file format' },
        {
          t: 'ul',
          items: [
            '**JPEG** — the right choice for photographs and camera scans. Already compressed, so the PDF stays small.',
            '**PNG** — right for screenshots, diagrams and anything with sharp text or flat colour. Lossless, so it produces a larger PDF; a full-page PNG screenshot can be several megabytes.',
            '**HEIC** — the iPhone default. **Chrome and Firefox cannot decode HEIC**, so a browser tool usually cannot read it directly. Two fixes: on the iPhone, Settings → Camera → Formats → **Most Compatible** makes the camera shoot JPEG from then on; or, for photos you already have, sharing them out of Photos to a Mac or Windows machine converts them to JPEG in transit.',
            '**TIFF** — common from office scanners and often multi-page. Convert to JPEG or PNG first; browser support is effectively nil.',
            '**WebP and AVIF** — decode fine in modern browsers, so they work if your tool supports them.',
          ],
        },
        { t: 'h2', x: 'Doing it' },
        {
          t: 'steps',
          items: [
            { h: 'Gather and rename', x: 'Put every image in one folder and zero-pad the names so they sort in reading order.' },
            { h: 'Open the converter', x: 'Go to the [JPG to PDF tool](/tools/jpg-to-pdf) and drop the whole folder in at once. Everything is processed in your browser, so a scanned passport or bank statement is never uploaded.' },
            { h: 'Check and fix the order', x: 'Drag any thumbnail that landed in the wrong place before generating the file.' },
            { h: 'Set page size and orientation', x: 'A4 or Letter for documents. Choose auto-orientation so a landscape photo gets a landscape page instead of being shrunk to fit a portrait one.' },
            { h: 'Generate and check', x: 'Open the PDF and page through it. Look for upside-down pages, which come from phone photos whose EXIF rotation was ignored.' },
            { h: 'Compress if it is going by email', x: 'Twenty phone photos make a 60 MB PDF. Run it through the [compressor](/tools/compress-pdf) at 150 DPI first — see [reducing a PDF for email](/blog/compress-pdf/reduce-pdf-file-size-for-email).' },
          ],
        },
        { t: 'cta', tool: 'jpg-to-pdf', x: 'Combine JPG and PNG files into a single PDF, in the right order.' },
        { t: 'h2', x: 'Built-in alternatives' },
        {
          t: 'ul',
          items: [
            '**macOS** — select the images in Finder, right-click → Quick Actions → **Create PDF**. Selection order determines page order, so click them in sequence. Preview also lets you drag pages around afterwards in the sidebar.',
            '**Windows** — select the images, right-click → **Print**, choose **Microsoft Print to PDF** as the printer and **Full page photo** as the layout, then Print. Tick "Fit picture to frame" off if you do not want cropping.',
            '**iPhone** — in Photos, select the images → Share → **Print**, then pinch outwards on the print preview. It turns into a PDF you can share or save to Files. It is undiscoverable and it works.',
            '**Android** — Google Drive → + → Scan uses the camera, auto-crops, deskews and saves straight to a multi-page PDF.',
          ],
        },
        { t: 'h2', x: 'Photographing documents well' },
        {
          t: 'ul',
          items: [
            'Shoot **straight down**, not at an angle. Perspective distortion is hard to fix and wrecks any later OCR.',
            'Use **even, indirect light**. Direct light creates a hotspot; a window on one side creates a gradient across the page.',
            'Put the page on a **dark surface** so the edge-detection in scanning apps can find it.',
            'Fill the frame with the page, and **do not use digital zoom** — move the phone closer instead.',
            'For anything you will need to search later, run [OCR](/tools/ocr-pdf) on the finished PDF. Details in [how to OCR a scanned PDF](/blog/ocr-scanned-documents/how-to-ocr-a-scanned-pdf).',
          ],
        },
        { t: 'warn', x: 'A photo carries EXIF metadata: GPS coordinates, the device model, the exact capture time. Those fields can travel into the PDF. Before sending photographed documents to anyone, [remove the metadata](/blog/pdf-privacy/remove-metadata-from-pdf).' },
      ],
      faqs: [
        { q: 'How do I combine multiple JPG files into one PDF?', a: 'Drop them all into an image-to-PDF tool, drag them into the right order, choose A4 or Letter as the page size, and generate. On macOS you can also select the files in Finder and use Quick Actions → Create PDF; on Windows, right-click → Print → Microsoft Print to PDF.' },
        { q: 'Why can I not upload HEIC photos?', a: 'Chrome and Firefox cannot decode HEIC, so browser-based tools cannot read the files. Set your iPhone to Settings → Camera → Formats → Most Compatible so it shoots JPEG, or copy the existing photos to a computer, which converts them to JPEG during the transfer.' },
        { q: 'What resolution do I need for a PDF I will print?', a: '300 DPI, which means about 2480 × 3508 pixels for a full A4 page. A phone photo at 4032 × 3024 exceeds that comfortably. A 1440-pixel-wide screenshot only reaches about 110 DPI on A4 and will look soft on paper.' },
        { q: 'Why are my PDF pages in the wrong order?', a: 'Alphabetical sorting puts page10 before page2. Rename the files with zero padding — page01, page02 and so on — and they will sort correctly everywhere. Most tools also let you drag the thumbnails into order before generating.' },
        { q: 'How do I make a scanned PDF searchable?', a: 'Combine the images into a PDF first, then run OCR on the result. OCR reads the characters in each image and writes an invisible text layer over them, so Ctrl+F and copy-paste start working while the pages still look identical.' },
      ],
      relatedTools: ['jpg-to-pdf', 'compress-pdf', 'ocr-pdf'],
      relatedPosts: ['html-to-pdf', 'word-to-pdf', 'how-to-ocr-a-scanned-pdf'],
    },
  ],
}
