import type { Cluster } from '../types'

export const ebooksPdf: Cluster = {
  slug: 'ebooks',
  name: 'Ebooks and PDF',
  title: 'Ebook formats, and how to turn one into a PDF',
  metaTitle: 'Ebook to PDF: EPUB, MOBI and AZW3 Explained',
  metaDescription:
    'Convert EPUB and MOBI files to PDF, understand what EPUB, AZW3 and plain text actually are, and learn why copy-protected ebooks never convert.',
  intro:
    'An ebook and a PDF answer the same question in opposite ways. EPUB, MOBI and AZW3 store the words plus a set of style rules and let the reading app decide where the lines break, so the book has no pages until something draws it. A PDF stores the finished page. Converting between them is therefore a decision, not a copy: you are choosing a page size, a margin and a text size on behalf of every future reader. These guides cover that decision, the differences between the formats, and the one situation where no converter can help you at all.',
  answer:
    'EPUB and MOBI are reflowable: the text rearranges to fit whatever screen it lands on, so the file contains no pages. A PDF contains fixed pages. Converting an ebook to PDF means picking the page size, margins and font size once, gaining a printable layout and losing the reader control over text size.',
  primaryKeyword: 'convert ebook to pdf',
  entities: ['EPUB', 'MOBI', 'AZW3', 'Amazon Kindle', 'Calibre', 'Apple Books', 'Kobo', 'Project Gutenberg', 'W3C', 'Adobe Digital Editions'],
  icon: '📖',
  tools: ['epub-to-pdf', 'mobi-to-pdf', 'ebook-converter', 'pdf-reader'],
  posts: [
    {
      slug: 'convert-epub-to-pdf',
      cluster: 'ebooks',
      title: 'How to convert an EPUB to PDF, and what you give up',
      metaTitle: 'How to Convert EPUB to PDF (Free)',
      metaDescription:
        'Turn an EPUB into a PDF you can print or annotate. Pick the page size, margins and text size first, because an EPUB has no pages until you choose them.',
      published: '2026-02-06',
      updated: '2026-08-19',
      readMinutes: 7,
      intent: 'howto',
      primaryKeyword: 'convert epub to pdf',
      secondaryKeywords: ['epub to pdf converter', 'change epub to pdf free', 'print an epub', 'epub to pdf page size', 'turn an ebook into a pdf'],
      entities: ['EPUB', 'XHTML', 'ZIP', 'Apple Books', 'Kobo', 'Calibre', 'W3C', 'A4 paper'],
      answer:
        'Upload the EPUB to a converter, choose a page size such as A4 or 6 by 9 inches, set the margins and the base font size, then download the PDF. An EPUB holds no pages of its own, so the converter builds them. You gain a printable fixed layout and lose reader control over text size.',
      body: [
        { t: 'p', x: 'An EPUB is a ZIP archive with a small web site inside it: one XHTML file per chapter, a stylesheet, the images, and an index file that lists the chapters in reading order. Take a copy, rename it from book.epub to book.zip, and your file manager will open it like any other archive. Nowhere in that bundle is there a page. Pages appear only when a reading app draws the text at a size somebody chose, which is why the same novel is 380 screens on a phone and 210 on a tablet.' },
        { t: 'p', x: 'Converting to PDF is the moment that choice gets made once and frozen. That is the whole job, and it is worth thirty seconds of thought before you press the button.' },
        { t: 'h2', x: 'What changes when a book stops reflowing' },
        {
          t: 'table',
          caption: 'The same book, as an EPUB and as a PDF made from it.',
          head: ['Behaviour', 'EPUB', 'PDF made from it'],
          rows: [
            ['Text size', 'The reader sets it, lines re-break to fit', 'Fixed at conversion time, you zoom instead'],
            ['Page numbers', 'None exist in the file, each app invents its own', 'Real and stable, safe to quote in an essay'],
            ['Printing', 'The app decides the layout, results vary wildly', 'What you see is what comes out of the printer'],
            ['Size of a 300-page novel', 'Usually 300 KB to 2 MB', 'Usually 1 MB to 5 MB'],
            ['Night mode', 'Colours swap, the text stays crisp', 'The viewer inverts the whole page, photographs included'],
            ['Footnotes', 'Tap for a pop-up, tap again to dismiss', 'A link that jumps to the foot of the chapter or the end of the book'],
            ['On a 6-inch e-reader', 'Native and comfortable', 'Readable but cramped, and you will be panning'],
          ],
        },
        { t: 'h2', x: 'Choose the page size before anything else' },
        { t: 'p', x: 'Every other setting follows from this one. Decide whether the PDF is going onto paper or onto a screen, then pick accordingly.' },
        {
          t: 'table',
          caption: 'Page sizes for an EPUB conversion, assuming 20 mm margins and 11 pt body text.',
          head: ['Page size', 'Dimensions', 'Roughly words per page', 'Choose it when'],
          rows: [
            ['A4', '210 × 297 mm', 'About 500', 'Printing at home or at work outside North America'],
            ['US Letter', '216 × 279 mm', 'About 480', 'Printing at home or at work in North America'],
            ['6 × 9 inch trade', '152 × 229 mm', 'About 300', 'You want it to read like a paperback'],
            ['A5', '148 × 210 mm', 'About 280', 'Reading on a tablet held in one hand'],
            ['B5', '176 × 250 mm', 'About 380', 'A compromise between printing and reading on screen'],
          ],
        },
        { t: 'note', x: 'A4 holds a lot of words per page, which is efficient for paper and tiring to read on screen. If you convert a novel to A4 and then read it on a laptop, the line length is roughly 95 characters, well past the 55 to 75 that most people read comfortably. For screen reading, A5 or 6 × 9 inches is the better answer.' },
        { t: 'h2', x: 'Converting an EPUB, step by step' },
        {
          t: 'steps',
          items: [
            { h: 'Check the book is not copy-protected', x: 'If the shop that sold it applied copy protection, no converter can read it, ours included. [What DRM is and what to do about it](/blog/ebooks/ebook-drm-explained) lists the signs, the clearest being a file that only opens after you sign in.' },
            { h: 'Open the converter', x: 'Go to [EPUB to PDF](/tools/epub-to-pdf) and drop the file in. This one runs on our server: the file is uploaded over a secure connection, converted, and deleted the moment it finishes. Files up to 100 MB, two minutes per job.' },
            { h: 'Set the page size', x: 'A4 or US Letter if it is going to a printer. A5 or 6 × 9 inches if it is going to a screen. This is the decision that shapes everything else.' },
            { h: 'Set the margins and the base text size', x: 'Start at 20 mm all round and 11 pt. If the PDF is destined for a ring binder or a staple in the corner, raise the inside margin to 25 mm so the first few characters of each line do not vanish into the fold.' },
            { h: 'Convert, then check three specific places', x: 'The cover, the first page of chapter two, and the table of contents. Those three catch nearly every problem: a cover stretched to fill a page it was never sized for, a chapter heading stranded alone at the foot of a page, and a contents list whose entries no longer jump anywhere.' },
            { h: 'Add the page numbers the EPUB never had', x: 'The book has real pages now, so give them numbers with [page numbers](/tools/page-numbers). Without them, a dropped printout is a jigsaw.' },
          ],
        },
        { t: 'cta', tool: 'epub-to-pdf', x: 'Convert an EPUB into a fixed-page PDF at the page size you choose.' },
        { t: 'note', x: 'Server conversions are metered because they use our machines rather than your browser. Free accounts get 5 a month, Pro and Lifetime get 300, an API key gets 5,000. The numbers are on the [pricing page](/pricing).' },
        { t: 'h2', x: 'What does not survive the trip' },
        {
          t: 'ul',
          items: [
            '**Reader control over text size.** This is the real loss. In an EPUB, someone who needs 24 pt text turns it up and the book re-breaks around them. In a PDF they must zoom, which means scrolling sideways at the end of every single line.',
            '**Pop-up footnotes** become jump links. You land at the note, then have to find your way back. In a printed copy you simply lose them.',
            '**Embedded fonts** are used when the converter can read them and quietly substituted when it cannot. A book set in a licensed serif may come out in a generic one. The words are identical, the texture is not.',
            '**Dark-mode and screen-width styling.** EPUB stylesheets can react to the device. A PDF page cannot react to anything.',
            '**Audio and video.** EPUB 3 allows both. A PDF page has no way to hold them, so they are dropped, not converted.',
            '**Reading position sync** across your phone, tablet and e-reader. That lives in the reading app, not in the file.',
          ],
        },
        { t: 'warn', x: 'If the person who will read this needs large text, do not convert. Keep the EPUB for them and send the PDF to the printer instead. A PDF is the least accessible way to hand someone a book, because enlarging the text is the one thing the format cannot do.' },
        { t: 'h2', x: 'Fixed-layout EPUB converts almost perfectly' },
        { t: 'p', x: 'Cookbooks, comics, photography books and children\'s picture books are often published as fixed-layout EPUB, where each page is already a designed page with a stated width and height. Those convert page for page with very little to decide, because the page size question is already answered inside the file.' },
        { t: 'p', x: 'You can tell which kind you have in two seconds: change the font size in your reading app. If the text re-breaks, it is reflowable. If nothing moves and the whole page just scales, it is fixed-layout. If you would rather look inside, rename a copy to .zip, open the .opf file in a text editor and look for this line.' },
        { t: 'code', x: '<!-- Fixed-layout: every page is already a page -->\n<meta property="rendition:layout">pre-paginated</meta>\n\n<!-- Reflowable books say this, or say nothing at all -->\n<meta property="rendition:layout">reflowable</meta>' },
        { t: 'h2', x: 'The PDF came out bigger than you expected' },
        { t: 'p', x: 'A 900 KB EPUB can become a 12 MB PDF. Two things cause it. First, an illustrated EPUB stores each image once and reuses it, while the PDF writer may place a fresh copy on every page it appears on. Second, every embedded font is written into the PDF in full unless the converter subsets it down to the characters actually used. Run the result through [compression](/tools/compress-pdf) and both usually collapse. [How to compress a PDF](/blog/compress/how-to-compress-a-pdf) explains which setting to reach for.' },
        { t: 'cta', tool: 'compress-pdf', x: 'Shrink the converted book before you email it or send it to print.' },
        { t: 'h2', x: 'Keep the EPUB' },
        { t: 'p', x: 'The conversion goes one way in practice. Turning a PDF back into a decent EPUB means guessing where chapters start and where headers and page numbers should be thrown away, and the result is never as clean as the file you began with. Keep the EPUB as your master copy and treat the PDF as an output you can always make again.' },
        { t: 'p', x: 'When you just want to read the result, open it in the [PDF reader](/tools/pdf-reader). That tool runs entirely inside your browser tab: nothing is uploaded, the file never leaves your computer, and closing the tab is the end of it. If all you need is the text, with no layout at all, [PDF to text](/tools/pdf-to-text) will give you the words in a plain file.' },
      ],
      faqs: [
        { q: 'How do I convert an EPUB to PDF for free?', a: 'Upload the EPUB to a converter, choose a page size and margins, and download the result. Our EPUB to PDF tool runs on our server, so the file is uploaded over a secure connection and deleted the moment the job finishes. Free accounts get 5 server conversions a month.' },
        { q: 'Why does my EPUB have no page numbers?', a: 'Because an EPUB contains no pages. It stores the text and a set of style rules, and the reading app breaks it into screens at whatever size you chose. Change the font size and the page count changes. Converting to PDF is what creates fixed, quotable pages.' },
        { q: 'What page size should I use when converting an EPUB?', a: 'A4 or US Letter if you are going to print it. A5 or 6 by 9 inches if you are going to read it on a screen, because A4 at 11 pt gives lines of about 95 characters, which is uncomfortably long to read.' },
        { q: 'Does converting an EPUB to PDF lose quality?', a: 'The text stays sharp because it is still text, not a picture of text. What you lose is behaviour: reader-controlled font size, reflow, pop-up footnotes, and any audio or video the EPUB carried. Embedded fonts may also be substituted.' },
        { q: 'Can I convert an EPUB I borrowed from the library?', a: 'Usually not. Library ebooks are normally issued with copy protection, which encrypts the contents and ties the key to your account. No converter can read them. A DRM-free EPUB converts normally.' },
      ],
      relatedTools: ['epub-to-pdf', 'ebook-converter', 'compress-pdf'],
      relatedPosts: ['ebook-formats-explained', 'ebook-drm-explained', 'how-to-compress-a-pdf'],
    },
    {
      slug: 'convert-mobi-to-pdf',
      cluster: 'ebooks',
      title: 'How to convert a MOBI file to PDF',
      metaTitle: 'How to Convert MOBI to PDF',
      metaDescription:
        'MOBI is the retired Kindle format. Convert one to a fixed-page PDF, pick a sensible page size, and find out why the pictures come out softer than the text.',
      published: '2026-03-17',
      updated: '2026-08-05',
      readMinutes: 6,
      intent: 'howto',
      primaryKeyword: 'convert mobi to pdf',
      secondaryKeywords: ['mobi to pdf converter', 'open a mobi file', 'kindle mobi to pdf', 'prc file to pdf', 'mobi to epub'],
      entities: ['MOBI', 'Mobipocket', 'Amazon Kindle', 'AZW3', 'Calibre', 'Project Gutenberg', 'Palm Database', 'Send to Kindle'],
      answer:
        'Upload the MOBI to a converter, pick a page size and margins, and download the PDF. MOBI is the retired Kindle format: compressed HTML inside a Palm database container, with no pages of its own, so the converter has to build them. Files bought with copy protection will not convert at all.',
      body: [
        { t: 'p', x: 'MOBI began as Mobipocket, a French ebook format from 2000. Amazon bought the company in 2005 and made it the Kindle format for the next decade. Inside, a MOBI is a Palm database file: a list of numbered records holding your book as compressed HTML, plus small indexes for the table of contents and the images. It has no pages, almost no stylesheet support, and no concept of a sheet of paper.' },
        { t: 'p', x: 'That last point is the whole reason the conversion has settings. Nothing in the file says how wide a page should be, so you say it.' },
        { t: 'h2', x: 'Where MOBI files come from now' },
        { t: 'p', x: 'Amazon retired the format in stages. Kindle Direct Publishing stopped accepting MOBI uploads from authors in 2021, and Send to Kindle stopped accepting .mobi files from readers in late 2022. Nobody makes new ones. So if you are holding one, it came from a short list of places.' },
        {
          t: 'ul',
          items: [
            '**A backup of an old Kindle library**, taken while the format was still supported.',
            '**A book bundle bought years ago**, from the era when a download page offered EPUB, MOBI and PDF side by side.',
            '**A public domain archive.** Project Gutenberg published MOBI downloads for years before retiring them, and thousands of those files are still sitting in folders.',
            '**A conversion you made yourself** in Calibre, to get a book onto a Kindle that would not read EPUB.',
            '**A .prc file**, which is the same format wearing an older extension. Treat it identically.',
          ],
        },
        { t: 'note', x: 'A .azw file looks like a MOBI and often is one, with Amazon copy protection wrapped around it. A .azw3 file is the newer, better format that replaced MOBI in 2011. If your file ends in .azw, .azw3 or .kfx, read [ebook formats explained](/blog/ebooks/ebook-formats-explained) before you try anything.' },
        { t: 'h2', x: 'MOBI is a weaker source than EPUB' },
        {
          t: 'table',
          caption: 'The same title converted from a MOBI and from an EPUB, and where the two results differ.',
          head: ['What you end up looking at', 'From MOBI', 'From EPUB'],
          rows: [
            ['Body text', 'Clean, it was HTML all along', 'Clean'],
            ['Images', 'Often visibly soft, they were shrunk when the MOBI was built', 'As sharp as the original files'],
            ['Tables', 'Frequently collapse into runs of loose text', 'Usually survive intact'],
            ['Fonts', 'Substituted, MOBI barely supports embedding them', 'Used when the converter can read them'],
            ['Chapter breaks', 'Usually correct, they are marked in the file', 'Correct'],
            ['Table of contents links', 'Usually present and working', 'Present and working'],
            ['Footnotes', 'Collected at the end of the book', 'End of the chapter or the end of the book'],
          ],
        },
        { t: 'tip', x: 'If the same book sits in your folder as both a .mobi and an .epub, convert the EPUB. It is the better source in every row of that table, and it takes exactly the same amount of your time.' },
        { t: 'h2', x: 'Converting a MOBI, step by step' },
        {
          t: 'steps',
          items: [
            { h: 'Check the size before anything else', x: 'A genuine MOBI holding a novel is normally 200 KB to 3 MB. If yours is a few kilobytes, it is not a book, it is a download token, and converting it will produce nothing useful.' },
            { h: 'Open the converter', x: 'Go to [MOBI to PDF](/tools/mobi-to-pdf) and drop the file in. This tool runs on our server: the file is uploaded over a secure connection, converted, and deleted the moment it finishes. Up to 100 MB per file, two minutes per job. Free accounts get 5 server conversions a month, Pro and Lifetime 300, an API key 5,000.' },
            { h: 'Pick a page size', x: 'A4 or US Letter for printing. A5 or 6 × 9 inches for reading on a screen, where a full A4 line is uncomfortably long.' },
            { h: 'Set margins and base text size', x: '20 mm and 11 pt is a sound default. Push the inside margin to 25 mm if the printout is going into a binder.' },
            { h: 'Convert, then look at the pictures first', x: 'The text will be fine. The images are where a MOBI conversion disappoints, so check the first illustration before you check anything else.' },
            { h: 'Number the pages', x: 'The book has real pages now. Add numbers with [page numbers](/tools/page-numbers) so a dropped stack can be put back in order.' },
          ],
        },
        { t: 'cta', tool: 'mobi-to-pdf', x: 'Turn an old Kindle MOBI file into a PDF you can print, annotate and keep.' },
        { t: 'h2', x: 'Why the pictures come out soft' },
        { t: 'p', x: 'The early Kindle had a six-inch screen at 600 × 800 pixels showing four shades of grey, and MOBI was built to suit it. Illustrations were shrunk hard before they were packed in, and plenty were converted to greyscale on the way. A converter can only work with what is in the file. If a diagram is 450 pixels wide, it is still 450 pixels wide in the PDF, and stretching it across an A4 page only makes the blur larger.' },
        { t: 'p', x: 'There is no fix on this side of the conversion. If the pictures matter, and this is a technical book, an atlas or anything with diagrams, look for an EPUB or the publisher\'s own PDF instead of improving the MOBI. Sharpening filters make blur look like blur with edges.' },
        { t: 'h2', x: 'Sometimes EPUB is the destination, not PDF' },
        { t: 'p', x: 'If the reason you are converting is that a modern reading app will not open your old MOBI, PDF is the wrong target. Convert MOBI to EPUB with the [ebook converter](/tools/ebook-converter) and stop there. You get a file that reflows, that current e-readers and phone apps open natively, and that keeps the reader in control of the text size.' },
        { t: 'p', x: 'Go to PDF when you want paper, a stable page number to cite, or a file you can mark up. Going MOBI to EPUB to PDF as two separate steps is rarely worth it: each conversion is another chance to lose a table or a heading level.' },
        { t: 'h2', x: 'When the file simply will not open' },
        {
          t: 'ul',
          items: [
            '**It is protected.** A file bought from a store and never opened outside its own app is almost certainly encrypted. See [why some ebooks cannot be converted](/blog/ebooks/ebook-drm-explained).',
            '**The extension is a lie.** Some downloads arrive named .mobi but are actually ZIP archives or PDFs. Open it in a text editor and look at the first few characters: a real MOBI shows readable structure markers, a ZIP starts with PK, a PDF starts with %PDF.',
            '**The download was cut short.** Compare the size on disk with the size the download page advertised. A truncated file often opens far enough to look real and then fails halfway through the conversion.',
            '**It is a .azw file.** That is a MOBI with Amazon protection around it, and it behaves like a locked file, not a broken one.',
          ],
        },
        { t: 'p', x: 'Once you have the PDF, open it in the [PDF reader](/tools/pdf-reader) to check it. That tool works entirely inside your browser tab, so nothing is uploaded and the file never leaves your computer. If the book is one you will study rather than simply read, [annotating a PDF for study](/blog/students/annotate-pdf-for-study) covers what to do next.' },
      ],
      faqs: [
        { q: 'How do I open a MOBI file?', a: 'Old Kindles and Calibre open MOBI files directly. Most current apps do not, because Amazon retired the format: Send to Kindle stopped accepting .mobi files in late 2022. Converting to EPUB or PDF is usually simpler than hunting for a reader.' },
        { q: 'What is the difference between MOBI and AZW3?', a: 'MOBI dates from 2000 and has almost no styling support. AZW3, also called KF8, replaced it in 2011 and understands real stylesheets, embedded fonts and proper tables. AZW3 is the better source for any conversion.' },
        { q: 'Why are the images blurry after converting a MOBI to PDF?', a: 'They were already small. MOBI files were built for a 600 by 800 pixel greyscale screen, so illustrations were shrunk before being packed in. A converter cannot add detail that is not in the file.' },
        { q: 'Can I convert a MOBI I bought from the Kindle store?', a: 'Only if it is DRM-free. Most store purchases carry copy protection, which encrypts the contents so no converter can read them. Our tools cannot and will not remove it.' },
        { q: 'Is a .prc file the same as a MOBI?', a: 'Yes, in almost every case. The .prc extension is the older Palm naming for the same container format. Feed it to a MOBI converter and it will be treated identically.' },
      ],
      relatedTools: ['mobi-to-pdf', 'ebook-converter', 'epub-to-pdf'],
      relatedPosts: ['convert-epub-to-pdf', 'ebook-formats-explained', 'ebook-drm-explained'],
    },
    {
      slug: 'ebook-formats-explained',
      cluster: 'ebooks',
      title: 'Ebook formats explained: EPUB, MOBI, AZW3, PDF and plain text',
      metaTitle: 'Ebook Formats Explained: EPUB, MOBI, PDF',
      metaDescription:
        'What EPUB, MOBI, AZW3, PDF and plain text really are, which apps and readers open which, and which format to keep if you want the book readable in 20 years.',
      published: '2026-01-22',
      updated: '2026-09-02',
      readMinutes: 8,
      intent: 'informational',
      primaryKeyword: 'ebook formats explained',
      secondaryKeywords: ['epub vs pdf', 'epub vs mobi', 'what is azw3', 'best ebook format', 'which ebook format to keep'],
      entities: ['EPUB', 'MOBI', 'AZW3', 'Amazon Kindle', 'Kobo', 'Apple Books', 'W3C', 'ISO 32000', 'Project Gutenberg', 'Calibre'],
      answer:
        'EPUB is the open standard and the best format to keep. MOBI is the retired Kindle format and AZW3 is its replacement, both tied to Amazon. PDF is a set of fixed pages rather than a reflowing book. Plain text is the most durable and the least capable. Keep EPUB and make the others from it.',
      body: [
        { t: 'p', x: 'Every ebook format answers one question: how do you store a book so a machine can draw it? There are only two answers. Reflowable formats store the words plus a set of style rules and let the reading app decide where lines break. Fixed formats store the finished page. Everything that follows, which apps open what, what can be printed, what can be quoted, comes out of that single split.' },
        { t: 'h2', x: 'The five formats, side by side' },
        {
          t: 'table',
          caption: 'What each format actually is, and what opens it.',
          head: ['Format', 'What it really is', 'Layout', 'Opens in', 'Keep it when'],
          rows: [
            ['EPUB (.epub)', 'A ZIP archive of XHTML chapters, a stylesheet, images and an index listing the reading order', 'Reflowable, unless the publisher chose fixed', 'Apple Books, Kobo, Google Play Books, Calibre, nearly every e-reader, and Kindle via Send to Kindle', 'You want one master copy that everything can read'],
            ['MOBI (.mobi, .prc)', 'Compressed HTML inside a Palm database container, designed in 2000', 'Reflowable, with almost no styling', 'Old Kindles and Calibre. Send to Kindle stopped accepting it in 2022', 'You have nothing better. Convert it and move on'],
            ['AZW3 (.azw3, KF8)', 'Amazon\'s 2011 replacement for MOBI, with real stylesheet support', 'Reflowable', 'Kindle devices and apps, Calibre', 'You read on a Kindle and the file is DRM-free'],
            ['PDF (.pdf)', 'A set of numbered fixed pages plus an index saying where each one sits', 'Fixed, always', 'Every computer, phone and browser of the last twenty years', 'The layout carries meaning: sheet music, textbooks, forms, anything printed'],
            ['Plain text (.txt)', 'The words, and nothing else at all', 'None, the app does whatever it likes', 'Everything, including a text editor from 1985', 'You want the words to survive no matter what happens'],
          ],
        },
        { t: 'note', x: 'Three more you will meet. **.azw** is usually a MOBI with Amazon copy protection wrapped around it. **.kfx** is the current Kindle format and is not publicly documented. **.acsm** is not a book at all: it is a small XML file, normally under 5 KB, that a reading app exchanges for the real download.' },
        { t: 'h2', x: 'Reflowable and fixed, in one paragraph' },
        { t: 'p', x: 'Open a reflowable book on a phone at 14 pt and it is 480 screens long. Turn the text up to 20 pt and it is 700. Nothing in the file changed; the app simply re-broke the lines. That is why a reflowable ebook cannot have real page numbers, and why quoting one properly means naming a chapter and a paragraph rather than a page. A PDF is the exact opposite: page 214 is page 214 on a phone, on a projector and on paper, forever.' },
        { t: 'h2', x: 'Getting a book onto the device you actually own' },
        {
          t: 'ul',
          items: [
            '**Kindle.** EPUB now works. Send to Kindle accepts EPUB, PDF, DOCX and TXT, and converts EPUB into Amazon\'s own format on arrival. MOBI has not been accepted since 2022.',
            '**Kobo.** EPUB natively and comfortably. PDF opens but is awkward on a small screen.',
            '**Apple Books.** EPUB and PDF, both first class. Not MOBI or AZW3.',
            '**Any phone.** A reading app handles EPUB; PDFs open in the built-in viewer with no app at all.',
            '**A printer.** PDF only. Every other format has to become a PDF first, whether you do it deliberately or the app does it for you badly.',
          ],
        },
        { t: 'h2', x: 'Which format to keep for twenty years' },
        { t: 'p', x: 'Keep EPUB. The specification is open and maintained by the W3C, and the container is an ordinary ZIP archive holding ordinary XHTML files. That is the part that matters: if every reading app on earth disappeared tomorrow, you could still rename a copy to .zip, unzip it, and open the chapters in a browser. Try it on any EPUB you own right now and you will see the chapter files.' },
        { t: 'p', x: 'AZW3 and KFX fail that test. They are proprietary, one is undocumented, and both are tied to a single company\'s hardware and account system. MOBI fails it for a different reason: it is already retired, and the tools that read it are shrinking every year.' },
        { t: 'p', x: 'PDF is durable in its own way. The format is an ISO standard (ISO 32000), and PDF/A is a restricted version designed specifically for archives, which embeds every font it uses so the page renders identically in fifty years. It is the right archive format when the layout is part of the meaning. It is the wrong one for a novel.' },
        { t: 'p', x: 'Plain text has no formatting, no images, no italics and no structure, and that is precisely why it will still open. It is the format of last resort and a genuinely good backup for anything irreplaceable.' },
        {
          t: 'ul',
          items: [
            'Keep the **EPUB** as your master copy, DRM-free.',
            'Keep a **PDF** as well when the layout carries information: a cookbook, a manual with diagrams, anything you will print.',
            'Keep a **.txt** extract of anything genuinely irreplaceable. It costs a few kilobytes.',
            'Store them as ordinary files with readable names, in a folder you back up, not only inside a reading app\'s private library.',
            'Name them so they sort usefully: author, then year, then title.',
          ],
        },
        { t: 'h2', x: 'Converting between them, and which directions work' },
        {
          t: 'table',
          caption: 'How each conversion actually goes.',
          head: ['Conversion', 'How it goes'],
          rows: [
            ['EPUB to PDF', 'Good. Choosing the page size is the whole job'],
            ['MOBI to PDF', 'Fine for text, soft for pictures, unreliable for tables'],
            ['MOBI or AZW3 to EPUB', 'Good, and it rescues an old file into a format with a future'],
            ['EPUB to plain text', 'Perfect for the words, and everything else is gone'],
            ['PDF to EPUB', 'The hard direction. A PDF has pages, not chapters, so the structure has to be guessed'],
            ['Anything with DRM', 'Does not happen, in any direction'],
          ],
        },
        { t: 'p', x: 'The [ebook converter](/tools/ebook-converter) handles the reflowable formats in both directions. It runs on our server: the file is uploaded over a secure connection, converted, and deleted the moment it finishes. Files up to 100 MB, two minutes per job. Free accounts get 5 server conversions a month, Pro and Lifetime 300, an API key 5,000, which are listed on the [pricing page](/pricing).' },
        { t: 'cta', tool: 'ebook-converter', x: 'Convert between EPUB, MOBI, AZW3, PDF and plain text.' },
        { t: 'h2', x: 'The one direction to avoid' },
        { t: 'p', x: 'PDF to EPUB is the conversion people are most often disappointed by, and the reason is structural rather than a matter of tool quality. A PDF does not know it has chapters. It knows it has pages, and on each page a set of instructions to place text at particular coordinates. A converter has to infer, from font sizes and positions, which lines are headings, which are body text, and which are running headers and page numbers to throw away. On a clean, born-digital report it does a decent job. On a two-column academic paper or a scanned book it produces a mess.' },
        { t: 'p', x: 'If all you want from a PDF is the words, do not convert it to EPUB. Use [PDF to text](/tools/pdf-to-text), which makes no promises about structure and therefore breaks none. [Converting a PDF to plain text](/blog/from-pdf/pdf-to-text) explains what you can expect to get back.' },
        { t: 'h2', x: 'Where to start' },
        { t: 'p', x: 'Look at what you have. If it is EPUB, you are already holding the best copy, and you can make a PDF whenever you need paper. If it is MOBI or AZW3, convert it to EPUB now and keep both. If it is PDF and that is the only copy, read it in the [PDF reader](/tools/pdf-reader), which runs entirely in your browser tab with nothing uploaded, and accept that this book is a set of pages rather than a reflowing text.' },
      ],
      faqs: [
        { q: 'What is the best ebook format to keep long term?', a: 'EPUB, without protection. It is an open standard maintained by the W3C, and the file is a ZIP archive of XHTML pages, so you can open the chapters in a browser even with no reading app at all. Keep a PDF as well if the layout matters.' },
        { q: 'What is the difference between EPUB and PDF?', a: 'EPUB is reflowable: it stores the words and style rules, and the app decides where lines break, so there are no fixed pages. PDF stores finished pages that look identical everywhere. EPUB is better for reading, PDF for printing and quoting.' },
        { q: 'Can a Kindle read EPUB files?', a: 'Yes. Send to Kindle accepts EPUB, PDF, DOCX and TXT, and converts EPUB to Amazon format when it arrives. It stopped accepting MOBI files in late 2022, which is the opposite of the situation most guides describe.' },
        { q: 'What is an AZW3 file?', a: 'AZW3, also called KF8, is the format Amazon introduced in 2011 to replace MOBI. It supports real stylesheets, embedded fonts and proper tables. It only opens on Kindle devices and apps, or in Calibre, and it converts only when it is DRM-free.' },
        { q: 'Why can I not turn my PDF into a good EPUB?', a: 'A PDF has no chapters, only pages with text placed at coordinates. The converter has to guess which lines are headings and which are page furniture to discard. It works on clean, born-digital documents and fails on two-column layouts and scans.' },
      ],
      relatedTools: ['ebook-converter', 'epub-to-pdf', 'pdf-reader'],
      relatedPosts: ['convert-epub-to-pdf', 'convert-mobi-to-pdf', 'ebook-drm-explained', 'pdf-to-text'],
    },
    {
      slug: 'ebook-drm-explained',
      cluster: 'ebooks',
      title: 'Why some ebooks cannot be converted at all',
      metaTitle: 'Why Some Ebooks Cannot Be Converted (DRM)',
      metaDescription:
        'Copy protection added by the shop that sold a book makes the file unreadable to any converter. What DRM is, how to spot it, and the routes that do work.',
      published: '2026-04-14',
      updated: '2026-08-28',
      readMinutes: 7,
      intent: 'informational',
      primaryKeyword: 'ebook drm explained',
      secondaryKeywords: ['why will my ebook not convert', 'what is an acsm file', 'drm free ebooks', 'library ebook will not convert', 'epub is encrypted'],
      entities: ['DRM', 'EPUB', 'Adobe Digital Editions', 'Amazon Kindle', 'Project Gutenberg', 'Standard Ebooks', 'Readium LCP', 'ISO 32000'],
      answer:
        'Some ebooks are encrypted by the shop that sold or lent them, so the text inside is unreadable to anything except an authorised reading app. That is DRM. Our converters cannot and will not remove it. DRM-free files convert normally, so the practical answer is to obtain a copy that was never locked.',
      body: [
        { t: 'p', x: 'A converter has to read a book before it can write a PDF. DRM stops it reading. The container still looks completely normal, and your file manager will show you an EPUB of a plausible size with a cover thumbnail, but the chapters inside are encrypted and the key sits with the shop that sold you the book, tied to your account and the devices you registered.' },
        { t: 'h2', x: 'What DRM actually is' },
        { t: 'p', x: 'DRM stands for digital rights management. In practice it is encryption plus a licence. When you buy or borrow a protected book, the shop encrypts the contents and issues your reading app a licence that unlocks them on the devices you have authorised. The app decrypts the text in memory as it draws each screen. At no point does a plain, readable book exist on your disk.' },
        { t: 'p', x: 'The important thing to understand is that DRM is a condition of the sale, not a property of the format. The same EPUB specification carries protected and unprotected books. Two files can be identical in structure and one converts in eight seconds while the other cannot be read at all, because a shop added a layer that the format itself never required.' },
        { t: 'h2', x: 'How to tell whether your file is protected' },
        {
          t: 'table',
          caption: 'Signs of copy protection, and what each one is telling you.',
          head: ['What you see', 'What it means'],
          rows: [
            ['The converter reports that the file is encrypted, or that it is not a valid EPUB', 'Protected, or genuinely corrupt. The next rows will tell you which'],
            ['The file is a few kilobytes and ends in .acsm', 'Not a book. It is a download ticket that a reading app redeems'],
            ['The extension is .azw or .kfx', 'A Kindle file, and normally protected'],
            ['Renaming a copy to .zip reveals a file called encryption.xml', 'Protected. That file lists exactly which parts are encrypted'],
            ['The book only opens after you sign in to an account', 'Protected. The sign-in is the licence check'],
            ['It opens in any reading app, on any device, with no account', 'DRM-free. It will convert normally'],
          ],
        },
        { t: 'note', x: 'The .acsm case catches more people than all the others combined. It is a small XML file, usually under 5 KB, that Adobe Digital Editions or a library app exchanges for the real download. If a converter tells you your 3 KB book contains no text, check the extension: you uploaded the ticket, not the book.' },
        { t: 'h2', x: 'What our tools do, and what they will not do' },
        { t: 'p', x: 'Our [EPUB to PDF](/tools/epub-to-pdf), [MOBI to PDF](/tools/mobi-to-pdf) and [ebook converter](/tools/ebook-converter) tools read a file, lay it out and write a PDF. Each runs on our server, so the file is uploaded over a secure connection, converted, and deleted the moment the job finishes. Free accounts get 5 server conversions a month, Pro and Lifetime 300, an API key 5,000.' },
        { t: 'p', x: 'None of them contains anything that removes copy protection, and we will not add it. Circumventing DRM is restricted by law in most countries, including under the United States Digital Millennium Copyright Act and the equivalent European rules, and those restrictions generally apply even to a book you paid for and even when the copy is only for you. Upload a protected file and the job fails and the file is deleted, exactly as any other failed job would be.' },
        { t: 'warn', x: 'Anywhere online offering to unlock your ebooks is asking you to hand over a purchased file and, in many cases, an account identifier that identifies you personally. We do not link to those and cannot help you find them. The rest of this page is about the routes that work instead.' },
        { t: 'h2', x: 'A password on a PDF is a different thing entirely' },
        { t: 'p', x: 'PDFs carry their own two locks, and neither is shop DRM. An **open password** is required before the file will display at all. A **permissions password** lets anyone view the file but flags it as no-printing or no-copying, and well-behaved software honours the flag. If you know the open password you can supply it and the file opens like any other. That is a completely separate mechanism from a library ebook wrapped in a licence. [Password-protecting a PDF](/blog/privacy/password-protect-pdf) covers what each of the two locks does and does not achieve.' },
        { t: 'h2', x: 'Routes that actually work' },
        {
          t: 'ul',
          items: [
            '**Buy DRM-free in the first place.** Technical and academic publishers routinely sell books this way, very often as one purchase that includes EPUB and PDF together. Standard Ebooks and Project Gutenberg publish public domain titles with no protection at all, carefully typeset and free.',
            '**Ask the publisher for their own PDF.** If you bought a locked copy from a shop but the publisher sells an unlocked one directly, that is usually one support email away, and some will swap it for you on proof of purchase.',
            '**Borrow in a format your device already reads.** Library apps often lend the same title in more than one format. Borrowing the EPUB rather than the Kindle edition frequently means it opens straight in your reader with nothing to convert.',
            '**Check what you already have.** Anyone who has bought book bundles usually has a DRM-free EPUB sitting in the same download folder as the locked copy, from a different shop, forgotten.',
            '**Use the printing the licence already allows.** Some authorised reading apps offer a print option for a page range. If it is greyed out, the licence does not permit it, and that is the honest answer rather than a problem to route around.',
          ],
        },
        { t: 'h2', x: 'Watermarked is not the same as locked' },
        { t: 'p', x: 'A growing number of shops use what is often called social DRM instead of encryption. There is no lock. Your name, email address or order number is simply written into the file, sometimes visibly on the copyright page and sometimes only in the hidden metadata fields. These are ordinary EPUBs. They open anywhere and convert normally.' },
        { t: 'p', x: 'The part worth knowing: the mark travels into the PDF you make. If you convert a watermarked book and print copies for a reading group, your email address goes with them. [Removing metadata](/blog/privacy/remove-metadata-from-pdf) strips the invisible half, and [edit metadata](/tools/edit-metadata) lets you see what is there in the first place. A line printed on the copyright page is part of the page and stays there unless you [delete that page](/tools/delete-pages).' },
        { t: 'h2', x: 'It is definitely not protected and it still fails' },
        {
          t: 'ul',
          items: [
            '**The extension does not match the file.** Open it in a text editor and look at the first characters. A ZIP, which includes every EPUB, starts with PK. A PDF starts with %PDF. If a file named .epub starts with %PDF, it is a PDF.',
            '**The download was truncated.** Compare the size on disk against the size the download page advertised. A partial file often looks fine until the conversion reaches the missing part.',
            '**It is over 100 MB.** That is the per-file ceiling. Illustrated cookbooks and comics reach it easily.',
            '**It is enormous rather than large.** Jobs are capped at two minutes. A fixed-layout comic with 400 full-page images can exceed that even under the size limit.',
            '**The EPUB itself is malformed.** Files produced by long-dead publishing tools sometimes break rules that reading apps forgive and converters do not.',
          ],
        },
        { t: 'p', x: 'If the file is clean and unprotected, the conversion is undramatic: pick a page size and download a PDF. Start with [converting an EPUB to PDF](/blog/ebooks/convert-epub-to-pdf), or read [ebook formats explained](/blog/ebooks/ebook-formats-explained) first if you are not sure what you are holding. And if you are wondering what happens to a file you do upload, [are online PDF tools safe](/blog/privacy/are-online-pdf-tools-safe) answers it directly.' },
      ],
      faqs: [
        { q: 'Can you remove the DRM from my ebook?', a: 'No. Our converters contain nothing capable of it and we will not add it. Circumventing copy protection is restricted by law in most countries, including for a book you paid for. A protected file simply fails and is deleted like any other failed job.' },
        { q: 'Why will my library ebook not convert?', a: 'Library ebooks are normally lent with copy protection, which encrypts the contents and ties the key to your account and the loan period. A converter cannot read the text at all. Borrowing a DRM-free edition, where the library offers one, avoids the problem.' },
        { q: 'What is an .acsm file?', a: 'It is not a book. It is a small XML download ticket, usually under 5 KB, that Adobe Digital Editions or a library app exchanges for the actual file. Uploading one to a converter converts the ticket and produces nothing useful.' },
        { q: 'Is it legal to convert an ebook I bought?', a: 'Changing the format of an unprotected file you own, for your own reading, is a different act from breaking protection, and the rules vary by country. What is consistent everywhere is that sharing the resulting file is copyright infringement whatever format it is in.' },
        { q: 'How do I know whether a shop sells DRM-free books?', a: 'The product page normally says so plainly, since shops that sell unlocked files treat it as a selling point. Technical publishers, many independent presses, Standard Ebooks and Project Gutenberg are reliable sources of unprotected files.' },
      ],
      relatedTools: ['epub-to-pdf', 'ebook-converter', 'pdf-reader'],
      relatedPosts: ['ebook-formats-explained', 'convert-epub-to-pdf', 'are-online-pdf-tools-safe'],
    },
  ],
}
