import type { Cluster } from '../types'

export const mergePdf: Cluster = {
  slug: 'merge-pdf',
  name: 'Merging PDF files',
  title: 'How to merge PDF files without installing anything',
  metaTitle: 'How to Merge PDF Files Free (2026 Guide)',
  metaDescription:
    'Combine PDFs into one file for free. Drag to set the page order, mix in JPG and PNG images, keep bookmarks, and merge without Adobe Acrobat on Windows or Mac.',
  intro:
    'Merging looks like the simplest thing you can do to a PDF, and it is the operation people get wrong most often: pages land in the wrong order, bookmarks vanish, a scanned receipt turns up sideways, and the output is somehow four times the size of the inputs. These guides cover ordering files properly, combining photos with documents, what a merge preserves and what it quietly destroys, and how to do all of it without a subscription.',
  answer:
    'Add every PDF to a merge tool, drag the files into the order you want, then merge and download one combined file. Pages keep their internal order within each file, so the file list decides everything. A browser-based merge runs locally, so nothing is uploaded to a server.',
  primaryKeyword: 'how to merge pdf files',
  entities: ['Adobe Acrobat', 'macOS Preview', 'Microsoft Windows 11', 'Google Drive', 'PDF bookmarks', 'JPEG', 'HEIC', 'qpdf'],
  icon: '⧉',
  tools: ['merge-pdf', 'organize-pdf', 'jpg-to-pdf', 'compress-pdf'],
  posts: [
    {
      slug: 'how-to-merge-pdf-files',
      cluster: 'merge-pdf',
      title: 'How to merge PDF files for free',
      metaTitle: 'How to Merge PDF Files for Free',
      metaDescription:
        'Merge two or more PDFs into one file in your browser. Drag to set the page order, keep bookmarks and links intact, and check the result before downloading.',
      published: '2026-01-28',
      updated: '2026-08-26',
      readMinutes: 6,
      intent: 'howto',
      primaryKeyword: 'how to merge pdf files',
      secondaryKeywords: ['combine pdf files free', 'merge pdf online', 'join pdfs into one', 'merge pdf without upload', 'combine two pdfs'],
      entities: ['Adobe Acrobat', 'macOS Preview', 'PDF bookmarks', 'ISO 32000', 'US Letter', 'A4', 'Microsoft Windows'],
      answer:
        'Open a browser merge tool, add every PDF you want to combine, drag the files into the order you need, then click Merge and download the single output file. Order is decided by the file list, top to bottom, and pages inside each file keep their own order.',
      body: [
        { t: 'p', x: 'Merging is a structural operation, not a rendering one. A well-built merge tool copies each page object from the source files into a new document and rebuilds the page tree. Nothing is re-drawn, re-compressed or re-typeset, so the text stays crisp and the file size is roughly the sum of the inputs.' },
        { t: 'h2', x: 'The five-step version' },
        {
          t: 'steps',
          items: [
            { h: 'Open the merge tool', x: 'Go to [merge PDF](/tools/merge-pdf). The files are processed in your browser, so nothing leaves your computer and there is no size cap imposed by an upload.' },
            { h: 'Add every file at once', x: 'Drag the whole selection in together rather than one at a time. In Finder or File Explorer, click the first file, then Shift-click the last to select a run.' },
            { h: 'Set the order', x: 'Drag the file cards into position. The first card becomes page 1. Check the page count shown on each card against what you expected, which catches the wrong-version-of-the-file mistake before it becomes a 60-page problem.' },
            { h: 'Merge', x: 'The combined document is built locally. A 12-file, 200-page merge finishes in a couple of seconds on a normal laptop.' },
            { h: 'Check page 1 and the last page', x: 'Open the result in a [PDF reader](/tools/pdf-reader) and confirm the first and last pages are what you expect. Those two checks catch almost every ordering error.' },
          ],
        },
        { t: 'cta', tool: 'merge-pdf', x: 'Combine any number of PDFs into one document, entirely in your browser.' },
        { t: 'h2', x: 'Getting the order right the first time' },
        { t: 'p', x: 'Most merge mistakes are ordering mistakes, and they happen because operating systems sort filenames as text, not as numbers. `chapter10.pdf` sorts before `chapter2.pdf` because the character "1" comes before "2".' },
        { t: 'p', x: 'Zero-pad the numbers and the problem disappears permanently: `01-cover.pdf`, `02-summary.pdf`, `10-appendix.pdf`. Once the filenames sort correctly, dragging the whole batch in gives you the right order with no manual reordering at all.' },
        { t: 'tip', x: 'For a scanned double-sided batch, scan all the odd pages, then all the even pages, and use a merge tool that supports alternate-page interleaving. Without it you get every front page followed by every back page, which is the single most common scanning complaint.' },
        { t: 'h2', x: 'What survives a merge, and what does not' },
        {
          t: 'table',
          caption: 'PDF features and how they behave when files are combined.',
          head: ['Feature', 'After merging', 'What to do about it'],
          rows: [
            ['Text and fonts', 'Preserved exactly', 'Nothing. Fonts are copied, subsets get merged.'],
            ['Internal links within one source file', 'Usually preserved', 'Check any table of contents links.'],
            ['Bookmarks / outline', 'Depends on the tool', 'Better tools nest each file under a parent bookmark; simple ones drop them.'],
            ['Form fields', 'Preserved, but duplicate names collide', 'Rename fields first, or flatten the forms before merging.'],
            ['Digital signatures', 'Invalidated', 'Merge first, then sign the combined document.'],
            ['Page size and orientation', 'Preserved per page', 'A merged file can legitimately mix A4 and Letter pages.'],
            ['Document metadata', 'Taken from the first file, or blank', 'Set the title and author afterwards.'],
            ['Attachments and embedded files', 'Often dropped', 'Extract them separately before merging.'],
            ['Encryption / password', 'Cannot be merged while locked', 'Remove the password first.'],
          ],
        },
        { t: 'warn', x: 'A merge invalidates every existing digital signature in the source files, because signing covers the byte range of the document it was applied to and merging rewrites that. Always merge before you [sign](/tools/sign-pdf), never after.' },
        { t: 'h2', x: 'Mixed page sizes' },
        { t: 'p', x: 'PDF stores a page size per page, so a merged document can contain A4 (210 × 297 mm), US Letter (216 × 279 mm) and a stray landscape spreadsheet page without any conflict. On screen this is invisible. On paper it is obvious: pages alternate between slightly taller and slightly wider, and a printer set to A4 will scale the Letter pages by about 96 percent.' },
        { t: 'p', x: 'If the document will be printed, normalise the page size before merging: re-export the odd file from its source application at the size you want, or print each file to PDF with a fixed paper size selected. If the document will only be read on screen, leave it alone.' },
        { t: 'h2', x: 'Why the merged file is bigger than expected' },
        { t: 'p', x: 'The output is normally close to the sum of the inputs, plus a little. Three things inflate it further:' },
        {
          t: 'ul',
          items: [
            '**Duplicated fonts.** Each source file carries its own embedded font subsets. Ten reports built from the same template can end up with ten copies of the same typeface, adding several megabytes.',
            '**Scanned pages.** A 300 DPI colour scan is roughly 1 to 3 MB per page before compression. Twenty scanned pages will dominate a merge regardless of what else is in it.',
            '**Images stored at full camera resolution.** A 12-megapixel photo placed on a page is still 12 megapixels inside the PDF, even though it displays at postcard size.',
          ],
        },
        { t: 'p', x: 'Compression fixes all three: it de-duplicates identical objects, downsamples images to a sensible DPI, and re-encodes scans. A 60 MB merged batch of scans usually lands between 5 and 12 MB with no visible change on screen. See [reducing PDF file size for email](/blog/compress-pdf/reduce-pdf-file-size-for-email).' },
        { t: 'cta', tool: 'compress-pdf', x: 'Merged file too big to send? Compress it before you attach it.' },
        { t: 'h2', x: 'When merging fails' },
        {
          t: 'table',
          head: ['Symptom', 'Cause', 'Fix'],
          rows: [
            ['Tool refuses one of the files', 'The PDF is password-protected', 'Open it, enter the password, and re-save an unprotected copy'],
            ['"Invalid PDF" or a blank page', 'The file is truncated or malformed', 'Run it through [repair](/tools/repair-pdf) first'],
            ['Pages appear rotated', 'The source page carries a rotation flag', 'Fix it after merging with [rotate](/tools/rotate-pdf)'],
            ['Text looks different in one section', 'A font was not embedded in that source file', 'Re-export that file with fonts embedded'],
            ['Merge is very slow', 'A file contains hundreds of high-resolution images', 'Compress that file first, then merge'],
          ],
        },
        { t: 'h2', x: 'After the merge' },
        { t: 'p', x: 'A combined document usually needs two finishing touches. First, [page numbers](/tools/page-numbers), because the original per-file numbering no longer makes sense across a 90-page compilation. Second, a set of bookmarks so a reader can jump between the original documents. If the merged file is going outside your organisation, also check what the [metadata](/tools/edit-metadata) says: it inherits the author name from whichever file was first in the list.' },
      ],
      faqs: [
        { q: 'How do I merge PDF files without uploading them anywhere?', a: 'Use a merge tool that runs in the browser using WebAssembly rather than a server. The files are read by JavaScript on your own machine, combined locally, and offered back as a download. Nothing is transmitted, which also means there is no upload size limit.' },
        { q: 'Can I merge PDFs on Windows without extra software?', a: 'No. Windows 10 and 11 have no built-in PDF merge. Microsoft Print to PDF is a virtual printer that can only handle one document at a time, and Edge can view PDFs but not combine them. You need either a browser tool or an installed application.' },
        { q: 'Does merging reduce the quality of a PDF?', a: 'No. A proper merge copies page objects without re-rendering anything, so text, vectors and images are byte-identical to the originals. Quality only changes if you also compress the result.' },
        { q: 'How many PDFs can I merge at once?', a: 'A browser tool is limited by available memory rather than a fixed count. Fifty text documents merge without trouble; fifty large scanned files may need to be done in two passes on a machine with less RAM.' },
        { q: 'Will merging keep the bookmarks from each file?', a: 'It depends on the tool. Better implementations create a parent bookmark per source file and nest the original outline underneath. Simpler ones drop the outline entirely, in which case you can add bookmarks to the merged document afterwards.' },
      ],
      relatedTools: ['merge-pdf', 'compress-pdf', 'organize-pdf'],
      relatedPosts: ['merge-pdf-without-acrobat', 'reorder-pdf-pages', 'combine-images-and-pdfs'],
    },
    {
      slug: 'merge-pdf-without-acrobat',
      cluster: 'merge-pdf',
      title: 'How to combine PDFs without Adobe Acrobat',
      metaTitle: 'Combine PDFs Without Adobe Acrobat',
      metaDescription:
        'Merge PDFs without paying for Acrobat. macOS Preview step by step, why Windows 11 cannot do it, what Google Drive really offers, and free browser tools.',
      published: '2026-02-25',
      updated: '2026-07-31',
      readMinutes: 7,
      intent: 'comparison',
      primaryKeyword: 'combine pdf without acrobat',
      secondaryKeywords: ['merge pdf mac preview', 'merge pdf windows 11 free', 'google drive merge pdf', 'free alternative to acrobat', 'combine pdf files offline'],
      entities: ['Adobe Acrobat', 'macOS Preview', 'Microsoft Windows 11', 'Google Drive', 'Microsoft Edge', 'PDFtk', 'Ghostscript', 'qpdf'],
      answer:
        'macOS can merge PDFs for free in Preview: open one file, show Thumbnails, drag the second PDF into the sidebar, then use File, Export as PDF. Windows 11 has no built-in merge and Google Drive cannot combine files either, so on those platforms use a free browser-based merge tool.',
      body: [
        { t: 'p', x: 'Acrobat Pro is the reference implementation and it costs roughly the price of a streaming subscription every month, billed annually. If merging is the only thing you need, you are paying for a page editor, a form designer, a redaction engine and a PDF printer you will not use. Here is what each free route actually does.' },
        { t: 'h2', x: 'macOS: Preview does merge, with one trap' },
        { t: 'p', x: 'Preview is a real PDF editor pretending to be a viewer. It has merged PDFs since Mac OS X 10.6 and there is nothing to install.' },
        {
          t: 'steps',
          items: [
            { h: 'Open the first PDF in Preview', x: 'Double-click it, or right-click and choose Open With → Preview if another app has claimed the file type.' },
            { h: 'Show the thumbnail sidebar', x: 'Press **⌥⌘2**, or use **View → Thumbnails**. Nothing else works without it.' },
            { h: 'Drag the second PDF into the sidebar', x: 'Drag from Finder and drop it **between two thumbnails**, so a horizontal insertion line appears. Do not drop it on top of a thumbnail.' },
            { h: 'Reorder if needed', x: 'Drag thumbnails up and down. Select several with ⌘-click or Shift-click and move them as a group.' },
            { h: 'Export, do not just save', x: 'Use **File → Export as PDF**. Saving in place can leave the second document embedded as an annotation rather than flattened into the page tree.' },
          ],
        },
        { t: 'warn', x: 'The trap is step 3. Dropping a PDF **onto** a page thumbnail attaches it as an annotation instead of inserting its pages. The file looks merged in Preview and arrives as a single page with a paperclip icon for everyone else. If your merged file is suspiciously small, this is what happened.' },
        { t: 'h2', x: 'Windows: there is no built-in way, and that surprises people' },
        { t: 'p', x: 'Windows 11 ships a PDF viewer inside Edge and a virtual printer called Microsoft Print to PDF. Neither can combine two files.' },
        {
          t: 'table',
          caption: 'What Windows tools can and cannot do with PDFs.',
          head: ['Tool', 'View', 'Print to PDF', 'Merge two PDFs'],
          rows: [
            ['Microsoft Edge', 'Yes, with annotation', 'Yes, one document', 'No'],
            ['Microsoft Print to PDF', 'No', 'Yes, one document at a time', 'No'],
            ['File Explorer', 'Preview pane only', 'No', 'No'],
            ['Microsoft Word', 'Opens and converts, reflowing the layout', 'Yes', 'Only by inserting each PDF as an object, which rasterises it'],
            ['Photos / Paint', 'No', 'No', 'No'],
          ],
        },
        { t: 'p', x: 'The Word route deserves a specific warning. **Insert → Object → Text from File** will place a PDF in a Word document, but Word converts each page to a picture and often only imports the first page. The output is a document of images: unsearchable, large, and unprintable at any real quality. It is not a merge.' },
        { t: 'h2', x: 'Google Drive cannot merge PDFs either' },
        { t: 'p', x: 'This one costs people the most time, because it feels like it should work. Drive stores PDFs, previews them, and can OCR one into a Google Doc. It has no combine function. Opening two PDFs as Docs and pasting one into the other destroys the layout entirely, since the conversion turns a fixed-layout document into a reflowing one. Third-party Workspace add-ons exist, but they upload your files to that vendor, which is usually the opposite of what someone choosing Drive for privacy reasons wanted.' },
        { t: 'h2', x: 'Browser tools: the answer on Windows, and fine everywhere' },
        { t: 'p', x: 'A merge tool built on WebAssembly does the work inside the page, on your own machine. The distinction matters: an "online PDF merger" usually means your document is uploaded to someone else\'s server, processed there, and deleted on a promise. A browser-based tool never sends the bytes anywhere.' },
        {
          t: 'ol',
          items: [
            'Open [merge PDF](/tools/merge-pdf) and drop the files in.',
            'Drag them into order and merge.',
            'Download the result. No account, no watermark, no page limit.',
          ],
        },
        { t: 'cta', tool: 'merge-pdf', x: 'Merge PDFs on Windows, Mac, Linux or ChromeOS, with no upload and no install.' },
        { t: 'h2', x: 'Command line, if you already live there' },
        { t: 'p', x: 'Three tools do this well and all are free. **qpdf** is the most correct: it preserves structure and is actively maintained. **pdftk** is the classic and still fine for simple jobs. **Ghostscript** re-writes the file, which can shrink it but also re-encodes images.' },
        { t: 'code', x: '# qpdf — cleanest structural merge\nqpdf --empty --pages a.pdf b.pdf c.pdf -- merged.pdf\n\n# qpdf — merge only pages 1-3 of a.pdf with all of b.pdf\nqpdf --empty --pages a.pdf 1-3 b.pdf -- merged.pdf\n\n# pdftk — the classic\npdftk a.pdf b.pdf cat output merged.pdf\n\n# Ghostscript — re-writes and often compresses\ngs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite \\\n   -sOutputFile=merged.pdf a.pdf b.pdf' },
        { t: 'note', x: 'On macOS there is also a hidden Automator action at `/System/Library/Automator/Combine PDF Pages.action`, and a Python script Apple ships with Preview\'s print pipeline. Both work, and both are more effort than dragging thumbnails.' },
        { t: 'h2', x: 'Choosing between them' },
        {
          t: 'table',
          head: ['Situation', 'Best option'],
          rows: [
            ['Mac, two or three files, one-off', 'Preview'],
            ['Windows, any number of files', 'Browser merge tool'],
            ['Confidential documents', 'Browser tool that runs locally, or qpdf offline'],
            ['Same merge every week', 'qpdf or pdftk in a script'],
            ['Hundreds of files', 'Command line, driven by a loop'],
            ['You need bookmarks nested per source file', 'qpdf, or a tool that advertises outline preservation'],
            ['You already pay for Acrobat', 'Acrobat: Tools → Combine Files'],
          ],
        },
        { t: 'h2', x: 'What you give up by not buying Acrobat' },
        { t: 'p', x: 'Honestly, not much for merging. Where Acrobat still earns its price is true redaction that removes the underlying text rather than covering it, PDF/A validation and conversion, accessibility tagging for screen readers, and Bates numbering for legal discovery. Combining files is not on that list. Neither is [reordering pages](/blog/merge-pdf/reorder-pdf-pages), [splitting](/blog/split-pdf/split-pdf-into-pages) or compression, all of which have solid free equivalents.' },
      ],
      faqs: [
        { q: 'Can Windows 11 merge PDF files without software?', a: 'No. There is no built-in merge in Windows 10 or 11. Microsoft Print to PDF handles one document at a time and Edge can only view and annotate. A browser-based merge tool is the closest thing to a built-in option.' },
        { q: 'How do I merge PDFs on a Mac for free?', a: 'Open the first PDF in Preview, press Option+Command+2 to show thumbnails, drag the second PDF into the sidebar between two page thumbnails, then choose File then Export as PDF. Do not drop the file on top of a thumbnail or it becomes an attachment.' },
        { q: 'Can Google Drive combine two PDFs?', a: 'No. Drive can store, preview and OCR PDFs but has no merge function. Converting them to Google Docs and pasting one into the other destroys the fixed layout, so it is not a workaround.' },
        { q: 'Is a free PDF merger safe for confidential documents?', a: 'Only if it processes files in your browser rather than uploading them. Check whether the tool describes local or client-side processing. If a file has to be uploaded to be merged, treat the document as having left your control.' },
        { q: 'Does Adobe Acrobat Reader merge PDFs?', a: 'The free Reader does not. Merging is a paid Acrobat feature, and Adobe also offers a limited web version that requires signing in and caps free use.' },
      ],
      relatedTools: ['merge-pdf', 'organize-pdf', 'split-pdf'],
      relatedPosts: ['how-to-merge-pdf-files', 'combine-images-and-pdfs', 'split-pdf-into-pages'],
    },
    {
      slug: 'combine-images-and-pdfs',
      cluster: 'merge-pdf',
      title: 'How to combine images and PDFs into one document',
      metaTitle: 'Combine Images and PDFs Into One File',
      metaDescription:
        'Turn JPG, PNG and HEIC photos into PDF pages and merge them with your PDFs. Fix rotation, pick a page size, and keep a receipt batch small enough to email.',
      published: '2026-03-18',
      updated: '2026-08-14',
      readMinutes: 6,
      intent: 'howto',
      primaryKeyword: 'combine images and pdf',
      secondaryKeywords: ['merge jpg and pdf', 'photos to pdf', 'heic to pdf', 'combine receipts into one pdf', 'scan multiple pages to one pdf'],
      entities: ['JPEG', 'PNG', 'HEIC', 'Apple Photos', 'EXIF', 'A4', 'US Letter', 'Adobe Acrobat'],
      answer:
        'Convert the images to PDF pages first, then merge them with your existing PDFs. A JPG, PNG or HEIC becomes a one-page PDF sized to the image, and once every input is a PDF you can drag all of them into a single ordered document and download one file.',
      body: [
        { t: 'p', x: 'PDF pages hold images perfectly well, but a merge tool works on PDFs, not on a mixed pile of formats. The reliable pattern is two steps: normalise everything to PDF, then combine. Doing it in that order also gives you a chance to fix orientation and page size before anything is locked into a page tree.' },
        { t: 'h2', x: 'Step 1: turn the images into PDF pages' },
        {
          t: 'steps',
          items: [
            { h: 'Gather the images in one folder', x: 'Rename them so they sort in the order you want: `01.jpg`, `02.jpg`, and so on. Zero-padding matters, because `10.jpg` sorts before `2.jpg` otherwise.' },
            { h: 'Open the converter', x: 'Go to [JPG to PDF](/tools/jpg-to-pdf) and drop the whole folder selection in at once.' },
            { h: 'Pick a page size', x: 'Choose **Fit to image** to make each page exactly the size of the photo, or **A4 / Letter** to place each image on a standard sheet. Fit to image is right for screenshots; a standard sheet is right for anything that will be printed.' },
            { h: 'Set the orientation handling', x: 'Auto-rotate uses the EXIF orientation tag so photos taken sideways come out upright. Turn it off only if a specific image is being rotated incorrectly.' },
            { h: 'Convert', x: 'You get either one PDF per image or a single multi-page PDF, depending on the option chosen. For merging, one multi-page PDF is fewer things to drag.' },
          ],
        },
        { t: 'cta', tool: 'jpg-to-pdf', x: 'Convert JPG, PNG, HEIC and WebP images into PDF pages in your browser.' },
        { t: 'h2', x: 'HEIC: why iPhone photos need a moment' },
        { t: 'p', x: 'Since iOS 11, iPhones save photos as HEIC by default, a container using HEVC compression that stores a similar-quality image in roughly half the bytes of JPEG. PDF has no native support for it, so a HEIC has to be decoded and re-encoded before it can become a page. Any converter that accepts HEIC is doing that for you.' },
        { t: 'p', x: 'If you would rather avoid the issue entirely, change the camera setting: **Settings → Camera → Formats → Most Compatible** makes the iPhone shoot JPEG instead. And if you AirDrop photos to a Mac, macOS converts on the fly, which is why the same photo is sometimes HEIC and sometimes JPEG depending on how it arrived.' },
        { t: 'h2', x: 'Step 2: merge everything' },
        { t: 'p', x: 'With every input now a PDF, open [merge PDF](/tools/merge-pdf), drop them all in, drag the cards into order and merge. A typical expense claim ends up as: cover letter PDF, then the receipts PDF built from photos, then the bank statement extract. One file, one attachment, one thing for the person on the other end to open.' },
        { t: 'h2', x: 'Getting the resolution right' },
        { t: 'p', x: 'This is where image-to-PDF goes wrong. An image has pixels; a PDF page has physical dimensions. The relationship between them is DPI, and choosing badly gives you either a blurry printout or a 90 MB file.' },
        {
          t: 'table',
          caption: 'Pixels needed to fill a full page at common resolutions.',
          head: ['Page', 'At 150 DPI (screen, draft print)', 'At 300 DPI (proper print)', 'At 600 DPI (archival scan)'],
          rows: [
            ['US Letter, 8.5 × 11 in', '1275 × 1650 px', '2550 × 3300 px', '5100 × 6600 px'],
            ['A4, 210 × 297 mm', '1240 × 1754 px', '2480 × 3508 px', '4960 × 7016 px'],
            ['A5, 148 × 210 mm', '874 × 1240 px', '1748 × 2480 px', '3496 × 4960 px'],
            ['Typical iPhone photo', '4032 × 3024 px — more than enough for any of these', '', ''],
          ],
        },
        { t: 'p', x: 'A modern phone photo is around 12 megapixels, which is well above what a printed page can resolve. Placing it at full resolution wastes several megabytes per page for detail nobody will ever see. Downsampling to 300 DPI for print, or 150 DPI for a document that will only be read on screen, typically cuts the file by 70 to 90 percent.' },
        { t: 'h2', x: 'The receipt problem, worked through' },
        { t: 'p', x: 'Twelve phone photos of receipts at about 3.5 MB each gives roughly 42 MB of source images. Converted straight to PDF pages at full resolution, the document lands near 40 MB, which will bounce off a 25 MB Gmail attachment limit. Three fixes, in order of how much you should reach for them:' },
        {
          t: 'ol',
          items: [
            'Downsample to 150 DPI during conversion. Receipts are text on white; 150 DPI is legible and roughly quarters the size.',
            'Convert to greyscale. A receipt has no meaningful colour and greyscale cuts another third.',
            'Run the merged file through [compression](/tools/compress-pdf), which typically brings 40 MB down to 3 to 6 MB.',
          ],
        },
        { t: 'tip', x: 'Photograph receipts against a dark surface in even light and crop tightly before converting. A tight crop with high contrast both shrinks the file and dramatically improves OCR accuracy later.' },
        { t: 'h2', x: 'Making the result searchable' },
        { t: 'p', x: 'A PDF made from photos contains no text, only pictures of text. Ctrl+F finds nothing, and neither will your accounting software or your operating system search index. Running [OCR](/tools/ocr-pdf) adds an invisible text layer under the image: the page looks identical, but the amounts, dates and vendor names become searchable and copyable. For a receipts archive this is the difference between a folder you use and a folder you forget.' },
        { t: 'cta', tool: 'ocr-pdf', x: 'Add a searchable text layer to a PDF built from photos or scans.' },
        {
          t: 'table',
          caption: 'Common jobs and the order to do them in.',
          head: ['Job', 'Sequence'],
          rows: [
            ['Expense claim from phone photos', 'Crop → JPG to PDF at 150 DPI greyscale → merge → OCR → compress'],
            ['Signed contract, scan mixed with the original', 'Scan signature pages → images to PDF → merge with the original → do not compress'],
            ['Portfolio of design work', 'PNG to PDF, fit to image, full resolution → merge → do not compress'],
            ['Passport and ID for an application', 'Photos to PDF at Letter or A4 → merge → check nothing is cropped at the edges'],
            ['A book or manual you photographed', 'Images to PDF → merge → OCR → add [page numbers](/tools/page-numbers)'],
          ],
        },
        { t: 'h2', x: 'A note on quality loss' },
        { t: 'p', x: 'Placing a JPEG into a PDF is lossless: the original JPEG bytes are embedded as-is, so the page is exactly as good as the file you started with. Quality is only lost if you downsample during conversion or compress afterwards, both of which are choices you control. PNG behaves differently, since PDF re-encodes it, but the result is still visually identical for screenshots and diagrams.' },
      ],
      faqs: [
        { q: 'How do I combine photos and a PDF into one file?', a: 'Convert the photos into PDF pages first with an image-to-PDF tool, then merge the resulting PDF with your existing one. Merge tools only accept PDFs, so the conversion step is what makes the combination possible.' },
        { q: 'Can I merge HEIC photos from my iPhone into a PDF?', a: 'Yes, if the converter decodes HEIC. It is re-encoded during conversion because PDF has no native HEIC support. Alternatively set Settings, Camera, Formats to Most Compatible so the phone shoots JPEG instead.' },
        { q: 'What resolution should I use for images in a PDF?', a: 'Use 150 DPI for documents that will only be read on screen and 300 DPI for anything that will be printed. For US Letter that means 1275 by 1650 pixels and 2550 by 3300 pixels respectively. Higher adds size without adding visible detail.' },
        { q: 'Why is my photo sideways in the PDF?', a: 'The camera stored the image upright but recorded the rotation in an EXIF orientation tag, and the converter ignored it. Enable auto-rotate during conversion, or rotate the finished page in a PDF page editor, which writes the rotation into the page itself.' },
        { q: 'How do I scan several pages into a single PDF?', a: 'Most scanner software has a multi-page or batch mode that outputs one PDF. If yours produces one file per page, convert or collect them and merge the results, which also lets you drop the blank reverse sides.' },
      ],
      relatedTools: ['jpg-to-pdf', 'merge-pdf', 'ocr-pdf'],
      relatedPosts: ['how-to-merge-pdf-files', 'reorder-pdf-pages', 'how-to-ocr-a-scanned-pdf'],
    },
    {
      slug: 'reorder-pdf-pages',
      cluster: 'merge-pdf',
      title: 'How to reorder, rotate and delete PDF pages',
      metaTitle: 'Reorder, Rotate and Delete PDF Pages',
      metaDescription:
        'Fix a PDF whose pages are out of order, sideways or unwanted. Drag thumbnails to reorder, rotate in 90 degree steps, remove pages and save the result.',
      published: '2026-04-14',
      updated: '2026-08-21',
      readMinutes: 5,
      intent: 'howto',
      primaryKeyword: 'reorder pdf pages',
      secondaryKeywords: ['rearrange pdf pages', 'rotate pdf and save', 'organize pdf pages', 'move pages in a pdf', 'pdf page order wrong'],
      entities: ['macOS Preview', 'Adobe Acrobat', 'qpdf', 'Microsoft Windows', 'Google Chrome', 'EXIF'],
      answer:
        'Open the PDF in a page organiser, drag the page thumbnails into the order you want, use the rotate buttons for any sideways page, select unwanted pages and delete them, then download. Rotation is stored as a page property, so a rotated page stays rotated in every viewer and on paper.',
      body: [
        { t: 'p', x: 'Three operations, one interface. Reordering, rotating and deleting all edit the same thing: the page tree that tells a PDF reader which pages exist and in what sequence. That is why every decent tool puts them on one screen full of thumbnails rather than in three separate menus.' },
        { t: 'h2', x: 'The workflow' },
        {
          t: 'steps',
          items: [
            { h: 'Open the file in a page organiser', x: 'Go to [organize PDF](/tools/organize-pdf) and drop the file in. Every page appears as a thumbnail with its page number.' },
            { h: 'Fix the order first', x: 'Drag a thumbnail to a new position. Select a run with Shift-click, or scattered pages with Ctrl-click (⌘-click on macOS), then move them as a block.' },
            { h: 'Rotate anything sideways', x: 'Hover a page and use the rotate buttons. Rotation goes in 90 degree steps only, because that is all the PDF format stores. Select several pages to rotate them together.' },
            { h: 'Delete what you do not need', x: 'Select the pages and press Delete, or type a range such as `2,5,11-13` if the tool accepts one.' },
            { h: 'Download and verify', x: 'Open the result and check the page count. If you deleted four pages from a 40-page file, the output must be 36 pages.' },
          ],
        },
        { t: 'cta', tool: 'organize-pdf', x: 'Reorder, rotate and delete pages on one screen, without uploading the file.' },
        { t: 'h2', x: 'Why your rotation did not stick' },
        { t: 'p', x: 'PDF stores rotation as a **`/Rotate`** entry on each page, and it accepts exactly four values: 0, 90, 180 and 270. Many PDF readers offer a View → Rotate command that turns the page on screen without touching that entry. Close the file and the rotation is gone, because nothing was written. To make it permanent you need a tool that edits the page object and saves a new file, which is what a page organiser or [rotate PDF](/tools/rotate-pdf) does.' },
        { t: 'note', x: 'This is also why a page can look upright in one app and sideways in another. If the rotation lives only in a viewer\'s display state, every other viewer starts from the stored value. Write it into the file and the ambiguity disappears.' },
        { t: 'h2', x: 'The double-sided scan problem' },
        { t: 'p', x: 'A single-sided document feeder gives you a very specific mess. You scan all the fronts, flip the stack, scan all the backs, and end up with pages 1, 3, 5, 7 followed by 8, 6, 4, 2. Reversed, because flipping the stack reverses the order of the reverse sides.' },
        {
          t: 'ol',
          items: [
            'Reverse the second batch so the even pages run 2, 4, 6, 8.',
            'Interleave the two batches, taking one page from each in turn. Some merge tools call this **alternate and mix**.',
            'Delete the blank backs, which is usually most of them.',
            'Rotate any page the feeder pulled in sideways.',
          ],
        },
        { t: 'tip', x: 'Blank scanned pages are rarely truly blank: dust and paper texture leave speckles, so a "delete blank pages" filter that looks for pure white will miss them. Sorting by page byte size is a better heuristic, since a genuinely empty scan is a fraction of the size of one with text on it.' },
        {
          t: 'table',
          caption: 'Page editing, tool by tool.',
          head: ['Task', 'Browser organiser', 'macOS Preview', 'Adobe Acrobat', 'qpdf'],
          rows: [
            ['Reorder pages', 'Drag thumbnails', 'Drag in the sidebar (⌥⌘2)', 'Organize Pages', 'Rewrite the page list'],
            ['Rotate and save', 'Rotate buttons', '⌘L / ⌘R, then Export as PDF', 'Organize Pages → Rotate', '--rotate=+90:2-5'],
            ['Delete pages', 'Select and Delete', 'Select thumbnail, press Delete', 'Organize Pages → Delete', '--pages . 1-4,7-z --'],
            ['Extract to a new file', 'Extract pages tool', 'Drag thumbnails to the desktop', 'Organize Pages → Extract', '--pages in.pdf 3-9 --'],
            ['Cost', 'Free', 'Free with macOS', 'Subscription', 'Free, command line'],
          ],
        },
        { t: 'h2', x: 'What breaks when you move pages around' },
        {
          t: 'ul',
          items: [
            '**Bookmarks point at page objects, not page numbers.** Reordering usually keeps them working; deleting a bookmarked page leaves a dead entry that jumps nowhere.',
            '**Printed page numbers do not update.** The number drawn on the page is part of the page content. After reordering, either accept the mismatch or strip and re-apply them with [page numbers](/tools/page-numbers).',
            '**Cross-references inside the text go stale.** "See page 14" is just text.',
            '**Digital signatures are invalidated.** Any structural edit breaks a signature. Reorganise first, sign last.',
            '**Form field tab order** follows the original page sequence in some documents and needs to be reset.',
          ],
        },
        { t: 'h2', x: 'Deleting is not redacting' },
        { t: 'p', x: 'Removing a page removes it from the page tree. Depending on how the file is written, the underlying objects can survive in the file as orphaned data, particularly if the editor saves an incremental update rather than rewriting the whole document. For confidential material, use a tool that fully rewrites the file, then [flatten](/tools/flatten-pdf) it and [strip the metadata](/tools/remove-metadata). More on that in [deleting pages from a PDF](/blog/split-pdf/delete-pages-from-pdf).' },
        { t: 'cta', tool: 'rotate-pdf', x: 'Just need to turn a few pages the right way up and save it properly?' },
        { t: 'h2', x: 'A sensible order of operations' },
        { t: 'p', x: 'When a document needs several fixes, do them in this order: merge everything first, then reorder, then rotate, then delete, then add page numbers, then OCR if it is scanned, and compress last. Compression goes last because every earlier step rewrites the file and would undo it. Signing, if needed, goes after compression, because signing must be the final change.' },
      ],
      faqs: [
        { q: 'How do I permanently rotate a page in a PDF?', a: 'Use a tool that edits the page and saves a new file rather than a viewer that only rotates the display. The rotation is stored as a /Rotate value of 0, 90, 180 or 270 on the page itself, which is what makes it persist across viewers and when printing.' },
        { q: 'How do I rearrange PDF pages on a Mac?', a: 'Open the PDF in Preview, press Option+Command+2 to show thumbnails, then drag pages into the order you want. Use File then Export as PDF to save a clean copy rather than saving in place.' },
        { q: 'Can I reorder PDF pages without Adobe Acrobat?', a: 'Yes. macOS Preview does it for free, and browser-based page organisers work on Windows, Linux and ChromeOS with no installation. Acrobat is not required for any page-level operation.' },
        { q: 'My scanned document has every second page upside down. How do I fix it?', a: 'The feeder scanned the reverse sides while the paper was inverted. Select just the even-numbered pages in a page organiser and rotate that selection 180 degrees in one action, rather than fixing them one at a time.' },
        { q: 'Does reordering pages change the file size?', a: 'Barely. Reordering rewrites the page tree, which is a small part of the file, while the page content stays as it was. Deleting pages does reduce the size, roughly in proportion to what those pages contained.' },
      ],
      relatedTools: ['organize-pdf', 'rotate-pdf', 'delete-pages'],
      relatedPosts: ['how-to-merge-pdf-files', 'delete-pages-from-pdf', 'extract-pages-from-pdf'],
    },
  ],
}
