import type { Cluster } from '../types'

export const ocrScans: Cluster = {
  slug: 'ocr-scanned-documents',
  name: 'OCR and scanned documents',
  title: 'OCR and scanned documents: turning pictures of words back into words',
  metaTitle: 'OCR a Scanned PDF and Make It Searchable',
  metaDescription:
    'Make any scan searchable. How OCR works, how to add a text layer to a scanned PDF, how to pull text out of a photo, and how to get more out of bad scans.',
  intro:
    'A scanned page is a photograph. Your computer sees a grid of grey pixels where you see a sentence, which is why Ctrl+F finds nothing and copy-paste returns an empty clipboard. Optical character recognition reads those pixels and works out which letters they represent, then writes the result back into the file as an invisible text layer sitting exactly on top of the image. These guides cover running OCR on a PDF, pulling text out of photos and screenshots, testing whether a file is searchable, and rescuing bad scans.',
  answer:
    'OCR converts the pixels of a scanned page into machine-readable characters and stores them as an invisible text layer aligned with the image. The page still looks identical, but it becomes searchable, selectable and copyable. Accuracy runs above 98 percent on clean 300 DPI print and far lower on handwriting.',
  primaryKeyword: 'ocr scanned pdf',
  entities: ['Tesseract', 'OCRmyPDF', 'Adobe Acrobat', 'ABBYY FineReader', 'Google Lens', 'Live Text', 'Poppler', 'Unicode'],
  icon: '🔍',
  tools: ['ocr-pdf', 'pdf-to-text', 'pdf-to-word', 'compress-pdf'],
  posts: [
    {
      slug: 'how-to-ocr-a-scanned-pdf',
      cluster: 'ocr-scanned-documents',
      title: 'How to OCR a scanned PDF so you can search it',
      metaTitle: 'How to OCR a Scanned PDF So You Can Search It',
      metaDescription:
        'Add a searchable text layer to a scanned PDF with OCR. How the invisible layer works, which language packs to pick, and what accuracy you should expect.',
      published: '2026-01-08',
      updated: '2026-08-25',
      readMinutes: 7,
      intent: 'howto',
      primaryKeyword: 'how to ocr a scanned pdf',
      secondaryKeywords: ['make scanned pdf searchable', 'ocr pdf free', 'add text layer to pdf', 'scanned pdf to text', 'tesseract ocr pdf'],
      entities: ['Tesseract', 'OCRmyPDF', 'Adobe Acrobat', 'ABBYY FineReader', 'Google Drive', 'LSTM', 'Poppler', 'Unicode'],
      answer:
        'Run the PDF through an OCR tool, choose the language of the document, and export. The tool reads each page image, recognises the characters, and writes them back as an invisible text layer positioned over the picture. The page looks unchanged but becomes searchable, selectable and copyable.',
      body: [
        { t: 'p', x: 'You scan a twelve-page contract, open it, press Ctrl+F to find the termination clause, and get nothing. The document is not broken — it simply does not contain any text. It contains twelve photographs of text, and the difference is total as far as software is concerned.' },
        { t: 'h2', x: 'What OCR actually adds' },
        { t: 'p', x: 'Optical character recognition looks at the pixels, segments them into blocks, lines, words and characters, and classifies each shape against a trained model. The output is a stream of Unicode characters, each with a bounding box saying where on the page it came from.' },
        { t: 'p', x: 'A good OCR tool then does something clever with that: it writes the recognised text back into the PDF in **invisible rendering mode**, positioned exactly over the matching pixels in the scan. Visually nothing changes, because the text is drawn with no ink. But Ctrl+F now finds words, selecting a paragraph highlights it in the right place, and copy-paste works. This is why the result is called a searchable PDF rather than a converted one — the original image is still there, untouched.' },
        { t: 'note', x: 'This is also why OCR is non-destructive. If the recognition gets a word wrong, the picture of the page is still correct; only the hidden text is wrong. You can always re-run OCR with better settings without losing anything.' },
        { t: 'h2', x: 'Run it in your browser' },
        {
          t: 'steps',
          items: [
            { h: 'Open the file', x: 'Drop the scanned PDF onto the [OCR tool](/tools/ocr-pdf). Recognition runs locally in your browser, which matters because scans are usually the most sensitive documents anyone owns.' },
            { h: 'Choose the language', x: 'Pick the language the document is written in. This is the single biggest lever on accuracy — the recogniser uses the language model to resolve ambiguous shapes. Select two languages only if the document genuinely mixes them.' },
            { h: 'Let it download the language pack', x: 'Each language is a separate trained data file of roughly 2 to 15 MB, fetched once and then cached. The first run on a new language is slower for this reason.' },
            { h: 'Wait for the pages', x: 'Budget a few seconds per page on a modern laptop. PDFs are capped at the first 30 pages in the browser, so split anything longer with [Split PDF](/tools/split-pdf) and run the parts one at a time.' },
            { h: 'Check a page before you trust it', x: 'Open the result and search for a word you know appears on page one. If it is not found, the language, resolution or orientation is wrong — see [how to get better OCR results](/blog/ocr-scanned-documents/improve-ocr-accuracy).' },
            { h: 'Download', x: 'Export the searchable PDF. Keep the original scan as well until you have confirmed the new file is good.' },
          ],
        },
        { t: 'cta', tool: 'ocr-pdf', x: 'Make a scanned PDF searchable in your browser. No upload, no account, over 100 languages.' },
        { t: 'h2', x: 'Language packs' },
        { t: 'p', x: 'The open-source engine behind most free OCR is **Tesseract**, originally built at HP, developed by Google for over a decade, and now community-maintained. Since version 4 it uses an LSTM neural network rather than the old character-classifier approach, which roughly halved the error rate on ordinary print. It ships trained data for more than 100 languages.' },
        {
          t: 'table',
          caption: 'Common Tesseract language codes.',
          head: ['Language', 'Code', 'Notes'],
          rows: [
            ['English', 'eng', 'The default. Best-trained model.'],
            ['German', 'deu', 'Handles compound words well.'],
            ['French', 'fra', 'Watch accented capitals on low-resolution scans.'],
            ['Spanish / Portuguese', 'spa / por', 'Very reliable on clean print.'],
            ['Russian', 'rus', 'Cyrillic. Do not combine with Latin scripts unnecessarily.'],
            ['Arabic', 'ara', 'Right-to-left and cursive; expect lower accuracy.'],
            ['Bengali / Hindi', 'ben / hin', 'Indic scripts need higher resolution, 400 DPI is safer.'],
            ['Chinese, Japanese, Korean', 'chi_sim, chi_tra, jpn, kor', 'Large models. Vertical text needs the vertical variants.'],
          ],
        },
        { t: 'warn', x: 'Adding extra languages does not make recognition safer, it makes it worse. Every additional language widens the set of candidate characters, so a Latin document processed as eng+rus will start producing Cyrillic lookalikes. Select only the languages actually present.' },
        { t: 'h2', x: 'What accuracy to expect' },
        {
          t: 'table',
          caption: 'Realistic character accuracy by source quality.',
          head: ['Source', 'Typical accuracy', 'What that feels like'],
          rows: [
            ['Digital print scanned at 300 DPI, clean', '98 - 99.5%', 'A handful of errors in a long document'],
            ['Office scan at 200 DPI', '95 - 98%', 'Search mostly works, proper nouns suffer'],
            ['Photocopy of a photocopy', '85 - 95%', 'Usable for searching, not for quoting'],
            ['Phone photo, uneven light', '80 - 95%', 'Depends almost entirely on the lighting'],
            ['Fax, dot matrix, small type', '70 - 90%', 'Expect to correct it by hand'],
            ['Neat handwriting', '50 - 80%', 'Specialist handwriting models only'],
            ['Cursive handwriting', 'Near zero with Tesseract', 'Not what the engine is built for'],
          ],
        },
        { t: 'p', x: 'Note that 98 percent character accuracy still means roughly one error every two lines. That is fine for finding a document in an archive and not fine for a legal quotation, so proofread anything you intend to rely on.' },
        { t: 'h2', x: 'On the command line' },
        { t: 'p', x: 'For bulk work, OCRmyPDF wraps Tesseract and handles the PDF plumbing, including deskewing and rotation.' },
        { t: 'code', x: '# Add a searchable layer, straighten crooked pages, fix upside-down scans\nocrmypdf --language eng --deskew --rotate-pages --optimize 1 scan.pdf searchable.pdf\n\n# A German and English document, skipping pages that already have text\nocrmypdf -l deu+eng --skip-text report.pdf out.pdf\n\n# Check the result: this should print real words, not nothing\npdftotext searchable.pdf - | head -40' },
        { t: 'h2', x: 'File size and what to do about it' },
        { t: 'p', x: 'OCR adds only the text layer, which is tiny — usually a few kilobytes per page. Files still grow when a tool re-encodes the page images on the way out, sometimes doubling the size. If that happens, run the result through the [compressor](/tools/compress-pdf), which re-encodes the scan images without touching the text layer you just created.' },
        { t: 'h2', x: 'What to do with the text once you have it' },
        { t: 'p', x: 'A searchable PDF is the usual goal, but the recognised text can also be exported on its own. Use [PDF to text](/tools/pdf-to-text) for a plain file you can grep or feed to another program, or [PDF to Word](/tools/pdf-to-word) when you need to edit the document rather than read it. If you are not sure whether a given file needs OCR at all, [test whether it is searchable first](/blog/ocr-scanned-documents/make-pdf-searchable).' },
      ],
      faqs: [
        { q: 'Does OCR change how my scanned PDF looks?', a: 'No. The recognised text is written in an invisible rendering mode positioned over the original image, so the page appears exactly as before. Only searching, selecting and copying behave differently.' },
        { q: 'How accurate is OCR?', a: 'Around 98 to 99.5 percent character accuracy on clean 300 DPI print, dropping to 85 to 95 percent on photocopies and phone photos. Even 98 percent means about one error every two lines, so proofread anything you plan to quote.' },
        { q: 'Can OCR read handwriting?', a: 'Tesseract is built for printed type and performs poorly on handwriting, especially cursive. Neat block capitals sometimes work. For handwritten archives you need a dedicated handwriting recognition service rather than a general OCR engine.' },
        { q: 'Which language should I select for OCR?', a: 'Only the language actually in the document. Adding extra languages widens the candidate character set and lowers accuracy. Select two only when the pages genuinely mix scripts, such as a bilingual contract.' },
        { q: 'Is browser-based OCR safe for confidential documents?', a: 'Browser OCR runs the recognition engine locally as WebAssembly, so the file never leaves your machine. That is a meaningful difference from server-based services, where the scan is uploaded and processed remotely.' },
      ],
      relatedTools: ['ocr-pdf', 'pdf-to-text'],
      relatedPosts: ['make-pdf-searchable', 'improve-ocr-accuracy', 'extract-text-from-image'],
    },
    {
      slug: 'extract-text-from-image',
      cluster: 'ocr-scanned-documents',
      title: 'How to extract text from an image or photo',
      metaTitle: 'How to Extract Text From an Image or Photo',
      metaDescription:
        'Copy text out of a photo or screenshot on any device. Live Text on Mac and iPhone, Snipping Tool on Windows, Google Lens, and what to do with a whole folder.',
      published: '2026-02-11',
      updated: '2026-07-31',
      readMinutes: 6,
      intent: 'howto',
      primaryKeyword: 'extract text from image',
      secondaryKeywords: ['copy text from a photo', 'image to text converter', 'get text out of a screenshot', 'ocr an image free', 'copy text from picture'],
      entities: ['Google Lens', 'Live Text', 'Snipping Tool', 'Microsoft PowerToys', 'Google Drive', 'Microsoft OneNote', 'Tesseract', 'Windows 11'],
      answer:
        'On a Mac or iPhone, select the text directly in the image using Live Text. On Windows 11, open the screenshot in Snipping Tool and use Text actions. Anywhere else, right-click the image in Chrome and choose Search with Google Lens, then copy the text it detects.',
      body: [
        { t: 'p', x: 'This used to require software. Now every major operating system reads text out of images for free, usually without you installing anything, and the results on a decent photo are close to perfect. The trick is knowing where each platform hid it.' },
        { t: 'h2', x: 'The fastest method on each platform' },
        {
          t: 'table',
          caption: 'Built-in text recognition, as of 2026.',
          head: ['Platform', 'How', 'Notes'],
          rows: [
            ['macOS', 'Open the image, hover the text, select it like normal text', 'Live Text. Works in Photos, Preview, Quick Look and Safari.'],
            ['iPhone / iPad', 'Long-press text in a photo, or tap the Live Text icon in Camera', 'Also translates and dials phone numbers it recognises.'],
            ['Windows 11', 'Open in Snipping Tool → **Text actions** → Copy all text', 'Also offers Quick redact for emails and phone numbers.'],
            ['Windows 10 or 11', 'PowerToys Text Extractor, Win+Shift+T, then drag a box', 'Grabs text from anything on screen, including video.'],
            ['Any browser', 'Right-click the image → **Search with Google Lens** → Text', 'Cloud-based. The image is sent to Google.'],
            ['Android', 'Google Photos → Lens, or the Google app camera', 'Copy to computer sends the text to a signed-in desktop Chrome.'],
            ['Anywhere', 'Upload to Google Drive, right-click → Open with Google Docs', 'Runs OCR and gives you an editable document.'],
          ],
        },
        { t: 'h2', x: 'Photographing a page so it actually reads' },
        { t: 'p', x: 'Most failures are capture failures, not recognition failures. Two minutes of care at the photo stage saves ten minutes of correcting text afterwards.' },
        {
          t: 'steps',
          items: [
            { h: 'Get even light', x: 'Near a window, no flash, no direct sun. Uneven light produces a bright half and a dark half, and the dark half thresholds to solid black.' },
            { h: 'Keep your shadow off the page', x: 'Stand so your body and the phone are not between the light and the paper. This is the single most common cause of a failed capture.' },
            { h: 'Hold the phone parallel to the page', x: 'Shoot straight down. A tilted photo gives you keystoned text where lines converge, and recognisers handle that badly.' },
            { h: 'Fill the frame', x: 'Get close enough that the text fills most of the image. A capital letter should be at least 25 to 30 pixels tall in the final photo.' },
            { h: 'Tap to focus, then check', x: 'Focus on the text, not the page edge. Zoom into the photo afterwards and confirm the letters are crisp before you walk away.' },
            { h: 'Use a document scanner mode if you have one', x: 'The Notes app on iOS and Google Drive on Android both have a scan mode that detects the page edges, corrects perspective and flattens the lighting automatically.' },
          ],
        },
        { t: 'tip', x: 'If you are capturing several pages, shoot them all first and process them together. It is far faster, and consistent lighting across the set means one adjustment fixes every page.' },
        { t: 'h2', x: 'Screenshots' },
        { t: 'p', x: 'Screenshots are the easiest case by a wide margin: the text is perfectly sharp, evenly lit and rendered at whole-pixel positions. Accuracy is normally at or near 100 percent, and even small interface labels come through.' },
        { t: 'p', x: 'The exceptions are text over busy photographic backgrounds, very low-contrast grey-on-grey interfaces, and text at 200 percent zoom that has been resampled by a screen recording. For a screenshot on a high-resolution display, capture at the native resolution rather than a downscaled copy.' },
        { t: 'h2', x: 'When you have a folder full of images' },
        { t: 'p', x: 'Point-and-click methods stop making sense at about ten files. At that point, combine the images into one PDF and run OCR over the whole thing in a single pass.' },
        {
          t: 'ol',
          items: [
            'Sort the files so the names put them in reading order — most tools use filename order, not the order you selected them.',
            'Combine them with the [images to PDF tool](/tools/jpg-to-pdf), which puts one image on each page.',
            'Run the result through [OCR](/tools/ocr-pdf) once, choosing the correct language.',
            'Export plain text with [PDF to text](/tools/pdf-to-text) if you want the words rather than the document.',
          ],
        },
        { t: 'cta', tool: 'ocr-pdf', x: 'Got more than a handful of images? Combine them into one PDF and OCR the lot in a single pass.' },
        { t: 'h2', x: 'Privacy: on-device or in the cloud?' },
        { t: 'p', x: 'This distinction is worth knowing before you photograph a payslip. Live Text on Apple devices and PowerToys Text Extractor on Windows run entirely on the device. Google Lens and Google Drive OCR send the image to a server. Browser-based OCR tools that use WebAssembly also run locally, with only the language model downloaded.' },
        { t: 'warn', x: 'Photos carry EXIF metadata, which routinely includes the exact GPS coordinates where the picture was taken and the device that took it. If you are sharing a photographed document rather than just reading it, strip that first — the same reasoning as [removing metadata from a PDF](/blog/pdf-privacy/remove-metadata-from-pdf).' },
        { t: 'h2', x: 'What comes out, and what does not' },
        { t: 'p', x: 'Recognition returns characters, not layout. Columns are usually merged into a single stream, tables lose their cell structure and arrive as loose runs of numbers, and hyphenated line breaks stay hyphenated. Expect to clean up. If the layout matters more than the words, keep the image and add a searchable text layer instead of extracting plain text — see [how to OCR a scanned PDF](/blog/ocr-scanned-documents/how-to-ocr-a-scanned-pdf).' },
      ],
      faqs: [
        { q: 'How do I copy text from a photo on an iPhone?', a: 'Open the photo, press and hold on the text, and drag the selection handles as you would in any document. This is Live Text, built into iOS since version 15, and it runs entirely on the device.' },
        { q: 'How do I extract text from a screenshot on Windows?', a: 'Open the screenshot in Snipping Tool and choose Text actions, then Copy all text. Alternatively install Microsoft PowerToys and press Win+Shift+T to drag a box around any text on screen.' },
        { q: 'Is there a free image-to-text converter?', a: 'Yes, and you probably already have one. Live Text on macOS and iOS, Text actions in the Windows 11 Snipping Tool, and Google Lens in Chrome are all free. Browser OCR tools handle batches without uploading anything.' },
        { q: 'Why is the extracted text full of mistakes?', a: 'Almost always a capture problem: uneven lighting, a tilted phone, or text too small in the frame. Reshoot with the phone parallel to the page in even daylight, filling the frame with the text.' },
        { q: 'Can I extract text from many images at once?', a: 'Combine them into a single PDF first, one image per page, then run OCR over the whole document in one pass. That is much faster than opening ten images individually and keeps everything in order.' },
      ],
      relatedTools: ['ocr-pdf', 'jpg-to-pdf'],
      relatedPosts: ['how-to-ocr-a-scanned-pdf', 'improve-ocr-accuracy', 'images-to-pdf'],
    },
    {
      slug: 'make-pdf-searchable',
      cluster: 'ocr-scanned-documents',
      title: 'How to tell if a PDF is searchable, and make it so',
      metaTitle: 'Is Your PDF Searchable? How to Test and Fix It',
      metaDescription:
        'Three quick tests that tell you whether a PDF contains real text or just pictures of text, what causes each failure, and how to fix an image-only document.',
      published: '2026-03-05',
      updated: '2026-08-08',
      readMinutes: 5,
      intent: 'troubleshooting',
      primaryKeyword: 'how to tell if a pdf is searchable',
      secondaryKeywords: ['pdf search not working', 'image only pdf', 'cannot select text in pdf', 'pdf copy paste gibberish', 'make pdf searchable'],
      entities: ['Adobe Acrobat', 'Poppler', 'Tesseract', 'Unicode', 'PDF', 'Google Chrome', 'Preview (macOS)'],
      answer:
        'Press Ctrl+F and search for a word you can see on the page. If it is not found, try to select the text with your mouse. If the cursor only draws a rectangle instead of highlighting words, the PDF is image-only and needs OCR to become searchable.',
      body: [
        { t: 'p', x: 'A PDF that will not search is one of the most common document complaints, and it has three quite different causes. Two minutes of testing tells you which one you have, and the fix follows directly from that.' },
        { t: 'h2', x: 'Test 1: the Ctrl+F test' },
        { t: 'p', x: 'Open the file in any viewer, press **Ctrl+F** (**Cmd+F** on a Mac), and type a common word you can plainly see on the current page. Something short and unambiguous: a name, a date, "the".' },
        { t: 'p', x: 'No results means there is no matching text layer. But do not stop here — the search box may simply be searching a page you are not looking at, and some viewers restrict search scope in odd ways. Run the second test to confirm.' },
        { t: 'h2', x: 'Test 2: the select-text test' },
        { t: 'p', x: 'Click at the start of a line and drag across it. This is the decisive test.' },
        {
          t: 'ul',
          items: [
            'Words **highlight** as you drag, following the shape of the line: there is a real text layer. Your search problem is something else.',
            'A **blue rectangle** is drawn over the page and no words highlight: the page is an image. This is an image-only PDF and needs OCR.',
            'Text highlights but **pastes as gibberish**: there is a text layer, but the font encoding is broken. Different problem, covered below.',
          ],
        },
        { t: 'h2', x: 'Test 3: the file size test' },
        { t: 'p', x: 'A useful sanity check before you even open the file. Divide the file size by the page count.' },
        {
          t: 'table',
          caption: 'Rough size per page, and what it implies.',
          head: ['Size per page', 'Almost certainly', 'Searchable?'],
          rows: [
            ['10 - 80 KB', 'Text and vector graphics, born digital', 'Yes'],
            ['80 - 300 KB', 'Text plus a few photos', 'Yes'],
            ['300 KB - 1 MB', 'Colour scan, JPEG compressed', 'Only if OCR was applied'],
            ['1 - 5 MB', 'High-resolution or lossless scan', 'Usually not'],
            ['Under 10 KB', 'Bilevel fax-style scan, or a nearly blank page', 'Usually not'],
          ],
        },
        { t: 'p', x: 'On the command line, Poppler settles it in one line: `pdftotext file.pdf -` prints the extracted text to your terminal. Empty output, or output consisting only of form feeds, means there is nothing to extract.' },
        { t: 'h2', x: 'Fixing an image-only PDF' },
        { t: 'p', x: 'This is the common case and the fix is straightforward: run OCR, which adds an invisible text layer over the existing images without changing how the page looks.' },
        { t: 'cta', tool: 'ocr-pdf', x: 'Add a searchable text layer to a scanned PDF in your browser, in over 100 languages.' },
        { t: 'p', x: 'The step-by-step version, along with language selection and the accuracy you should expect, is in [how to OCR a scanned PDF](/blog/ocr-scanned-documents/how-to-ocr-a-scanned-pdf). If the scan is poor, spend five minutes on [improving the input](/blog/ocr-scanned-documents/improve-ocr-accuracy) before running recognition — it makes far more difference than any setting.' },
        { t: 'h2', x: 'The awkward middle case: hybrid PDFs' },
        { t: 'p', x: 'Documents assembled from several sources are frequently part searchable and part not. A born-digital report with three scanned appendices behaves normally for forty pages and then goes silent. So does a contract where a signed page was scanned and reinserted.' },
        { t: 'p', x: 'The symptom is distinctive: search works, but misses things you know are there. Test the specific page you care about rather than page one. Most OCR tools have a skip-text option that processes only the image pages and leaves the existing text layers untouched, which is exactly what you want here — re-OCRing a page that already has good text usually makes it worse.' },
        { t: 'h2', x: 'Text that selects but pastes as nonsense' },
        { t: 'p', x: 'You highlight "Invoice total" and paste it, and get something like `,QYRLFH WRWDO`. The page has a text layer, but the PDF is missing the mapping that says which Unicode character each glyph represents.' },
        {
          t: 'ul',
          items: [
            '**A subset font with no ToUnicode map.** The generator embedded only the glyphs it used and did not include the translation table. Very common with older LaTeX output and some report generators.',
            '**Ligatures.** "fi" and "fl" are single glyphs in many fonts, so words like "define" lose characters on copy even when everything else is fine.',
            '**A symbol or custom font.** Icon fonts and some corporate typefaces map letters to arbitrary code points by design.',
          ],
        },
        { t: 'p', x: 'There is no clean repair for this from outside the file. The practical workaround is to convert the pages to images and OCR them, which recognises the visible shapes and ignores the broken encoding entirely. It is a heavy fix, but it is reliable.' },
        { t: 'h2', x: 'When search still fails on a text PDF' },
        {
          t: 'table',
          head: ['Symptom', 'Likely cause', 'Fix'],
          rows: [
            ['Search finds nothing anywhere', 'No text layer at all', 'Run OCR'],
            ['Search works on some pages only', 'Hybrid document', 'OCR with a skip-text option'],
            ['Text selects but copies as gibberish', 'Missing ToUnicode map', 'Rasterise those pages and OCR them'],
            ['Search misses accented or non-Latin words', 'Wrong OCR language, or encoding loss', 'Re-run OCR with the correct language'],
            ['Search misses hyphenated words', 'Line-break hyphens are in the text layer', 'Search for the shorter fragment instead'],
            ['Viewer search is slow or incomplete', 'Very large file or no index', 'Extract with [PDF to text](/tools/pdf-to-text) and search that'],
          ],
        },
        { t: 'note', x: 'A searchable PDF is not an editable one. OCR gives you findable words sitting invisibly over a picture; the picture is still what you see. To actually edit the content you need to [convert it to Word](/tools/pdf-to-word), which rebuilds the layout as real paragraphs and accepts that some formatting will shift.' },
      ],
      faqs: [
        { q: 'How can I tell if a PDF is searchable?', a: 'Try to select a line of text with your mouse. If individual words highlight, there is a real text layer. If the drag only draws a rectangle over the page, the document is image-only and needs OCR.' },
        { q: 'Why does Ctrl+F find nothing in my PDF?', a: 'The most common reason is that the pages are scanned images with no text layer. It can also happen on hybrid documents where only some pages were scanned, or when the fonts lack a Unicode mapping.' },
        { q: 'Why does copied text from a PDF come out as gibberish?', a: 'The embedded font has no ToUnicode map, so the viewer knows which glyph to draw but not which character it represents. Rasterising those pages and running OCR over them recovers the text reliably.' },
        { q: 'Can a PDF be partly searchable?', a: 'Yes, and it is common. Documents assembled from a digital report plus scanned appendices search normally on some pages and not at all on others. Use an OCR tool with a skip-text option so existing text layers are left alone.' },
        { q: 'Does making a PDF searchable make it editable?', a: 'No. OCR adds an invisible text layer over the scanned image; what you see is still the picture. To edit the content, convert the document to Word or another editable format and expect some layout to shift.' },
      ],
      relatedTools: ['ocr-pdf', 'pdf-to-word'],
      relatedPosts: ['how-to-ocr-a-scanned-pdf', 'improve-ocr-accuracy', 'pdf-to-text'],
    },
    {
      slug: 'improve-ocr-accuracy',
      cluster: 'ocr-scanned-documents',
      title: 'How to get better OCR results from bad scans',
      metaTitle: 'How to Get Better OCR Results From Bad Scans',
      metaDescription:
        'Fix the input and OCR fixes itself. Scan at 300 DPI, deskew, raise contrast, split columns, pick one language, and know where handwriting recognition stops.',
      published: '2026-04-09',
      updated: '2026-08-16',
      readMinutes: 7,
      intent: 'howto',
      primaryKeyword: 'improve ocr accuracy',
      secondaryKeywords: ['ocr not working well', 'best dpi for ocr', 'deskew scanned document', 'ocr multi column document', 'ocr handwriting accuracy'],
      entities: ['Tesseract', 'OCRmyPDF', 'Otsu', 'ScanTailor', 'Adobe Acrobat', 'ABBYY FineReader', 'Poppler', 'LSTM'],
      answer:
        'Scan at 300 DPI, straighten the page to within half a degree, raise the contrast until the paper is white and the ink black, process one column at a time, and select only the language actually present. Input quality dominates every engine setting you can change afterwards.',
      body: [
        { t: 'p', x: 'OCR settings get most of the attention and deserve almost none of it. The difference between a 300 DPI straight scan and a 150 DPI crooked photocopy is the difference between 99 percent and 80 percent accuracy, and no engine option closes that gap. Fix the picture and the recognition looks after itself. The steps for the recognition pass itself are in [how to OCR a scanned PDF](/blog/ocr-scanned-documents/how-to-ocr-a-scanned-pdf).' },
        { t: 'h2', x: 'Resolution: 300 DPI, and why' },
        { t: 'p', x: 'Recognition engines want a capital letter to be roughly 30 pixels tall. For 10 or 12 point body type, that lands almost exactly at 300 DPI. Below that, characters start sharing pixels with their neighbours and the classifier confuses rn with m, cl with d, and 8 with B.' },
        {
          t: 'table',
          caption: 'Scan resolution and OCR outcomes.',
          head: ['Resolution', 'Result', 'Use it for'],
          rows: [
            ['150 DPI', 'Noticeably worse. Small type fails.', 'Nothing you care about'],
            ['200 DPI', 'Acceptable for large clean type', 'Bulk scanning where speed matters most'],
            ['300 DPI', 'The sweet spot for 10-12 pt text', 'Almost everything'],
            ['400 DPI', 'Better for small type and Indic or CJK scripts', 'Footnotes, dictionaries, dense type'],
            ['600 DPI', 'Marginal gain, four times the file size', 'Very small print, degraded originals'],
            ['1200 DPI', 'No benefit, often slower and worse', 'Not for OCR'],
          ],
        },
        { t: 'warn', x: 'Never upscale a low-resolution scan to hit 300 DPI. Interpolation smears the character edges, which is precisely the information the recogniser needs. A 150 DPI scan enlarged to 300 performs worse than the 150 DPI original. Rescan instead — see [what resolution you need](/blog/pdf-images/best-image-format-for-print).' },
        { t: 'h2', x: 'Straighten the page' },
        { t: 'p', x: 'Line detection assumes text runs horizontally. A skew of two or three degrees, which is what you get from a page dropped casually into a feeder, causes lines to be merged or split and drags accuracy down sharply. Aim for under half a degree.' },
        { t: 'p', x: 'Most OCR pipelines can do this for you: OCRmyPDF has `--deskew`, Acrobat straightens during its recognition pass, and dedicated tools like ScanTailor handle whole books. Also correct page orientation — a scan rotated 90 or 180 degrees produces complete nonsense, which `--rotate-pages` detects and fixes.' },
        { t: 'h2', x: 'Contrast and binarisation' },
        { t: 'p', x: 'Engines convert the page to pure black and white before recognising anything, using a threshold. The default global method works well on evenly lit scans and fails on anything with a gradient, which is why phone photos produce a page that is half readable and half solid black.' },
        {
          t: 'steps',
          items: [
            { h: 'Convert to greyscale', x: 'Colour adds nothing for text recognition and can confuse the threshold. Greyscale first.' },
            { h: 'Set the white point', x: 'Use Levels in any image editor and drag the white input slider left until the paper is genuinely white, not light grey. This removes paper texture and scanner noise in one move.' },
            { h: 'Set the black point', x: 'Drag the black slider right until the ink is solid. Stop as soon as thin strokes start breaking up — over-thresholding erodes letters and is worse than a slightly grey page.' },
            { h: 'Fix uneven lighting first if present', x: 'A gradient across the page needs adaptive thresholding, not a global one. ScanTailor and the `--clean` option in OCRmyPDF both handle this.' },
            { h: 'Remove speckle', x: 'Photocopy dust and JPEG noise get classified as punctuation. A light despeckle pass removes stray marks smaller than a full stop.' },
            { h: 'Crop to the text area', x: 'Cut off dark scan borders, the shadow in a book gutter and any visible desk. Every non-text region is somewhere for the layout analyser to go wrong.' },
          ],
        },
        { t: 'h2', x: 'Tell the engine what the page looks like' },
        { t: 'p', x: 'Layout analysis runs before recognition, and it is where multi-column documents fall apart: a newspaper processed as a single block interleaves lines from adjacent columns into unreadable text. Tesseract exposes this as the page segmentation mode.' },
        {
          t: 'table',
          caption: 'Tesseract page segmentation modes worth knowing.',
          head: ['Mode', 'Meaning', 'Use for'],
          rows: [
            ['--psm 1', 'Automatic with orientation detection', 'Mixed batches of unknown scans'],
            ['--psm 3', 'Fully automatic, no orientation detection', 'The default. Ordinary documents.'],
            ['--psm 4', 'A single column of variable-size text', 'Receipts, invoices, price lists'],
            ['--psm 6', 'One uniform block of text', 'A cropped column, a paragraph, a table cell'],
            ['--psm 7', 'A single line of text', 'Labels, headings, meter readings'],
            ['--psm 11', 'Sparse text, find as much as possible', 'Diagrams, screenshots, scattered labels'],
          ],
        },
        { t: 'p', x: 'For a stubborn multi-column page, the most reliable approach is not a setting at all: crop each column into its own image and recognise them separately with `--psm 6`, then join the results. It is manual and it always works.' },
        { t: 'code', x: '# Straighten, clean and recognise, keeping any existing text layers\nocrmypdf -l eng --deskew --rotate-pages --clean --skip-text messy.pdf clean.pdf\n\n# One cropped column, treated as a single block of text\ntesseract column-1.png out --psm 6 -l eng\n\n# Check the confidence the engine had, word by word\ntesseract page.png - --psm 3 -l eng tsv | head -30' },
        { t: 'h2', x: 'Language selection' },
        { t: 'p', x: 'Pick exactly the languages present, and no more. Each additional language expands the candidate character set, so a plain English page processed as eng+rus+ara will start returning characters that were never on the paper. If a document is genuinely bilingual, two languages is right; three is almost always a mistake.' },
        { t: 'p', x: 'Non-Latin scripts have their own requirements. Arabic and Persian are cursive and connected, so accuracy is structurally lower. Indic scripts such as Bengali, Devanagari and Tamil have complex conjunct forms and benefit from 400 DPI. Chinese and Japanese have large character sets and need the vertical model when the text runs vertically.' },
        { t: 'h2', x: 'Where handwriting stops' },
        { t: 'p', x: 'Tesseract is trained on printed type. Neat block capitals sometimes come through at 60 to 80 percent, which is enough to search for a name and not enough to read. Ordinary cursive returns essentially nothing usable, and no amount of preprocessing changes that, because the engine has no model for connected script.' },
        { t: 'p', x: 'Handwritten text recognition is a separate field with separate models. If you have a handwritten archive, use a service built for it rather than tuning a print engine. For forms that mix printed labels with handwritten answers, expect the labels to recognise cleanly and the answers not to — which is still useful, because it lets you find the right form quickly.' },
        { t: 'h2', x: 'A checklist before you run OCR' },
        {
          t: 'ol',
          items: [
            'Scan or photograph at 300 DPI, 400 for small or non-Latin type.',
            'Check the orientation is upright, not rotated 90 or 180 degrees.',
            'Deskew to under half a degree.',
            'Convert to greyscale and set the black and white points.',
            'Crop out borders, gutters and anything that is not the page.',
            'Despeckle lightly.',
            'Select only the languages actually in the document.',
            'Choose a segmentation mode that matches the layout, or split columns manually.',
            'Recognise one page, read the output, then run the rest.',
          ],
        },
        { t: 'cta', tool: 'ocr-pdf', x: 'Once the input is clean, run OCR in your browser and get a searchable file back.' },
        { t: 'tip', x: 'Always test on one representative page before processing two hundred. Thirty seconds of checking catches a wrong language or an upside-down batch before it costs you an hour, and lets you confirm the file is genuinely [searchable afterwards](/blog/ocr-scanned-documents/make-pdf-searchable).' },
      ],
      faqs: [
        { q: 'What DPI is best for OCR?', a: '300 DPI for ordinary 10 to 12 point text, which puts a capital letter at roughly 30 pixels tall. Go to 400 DPI for very small type or for Indic and CJK scripts. Above 600 DPI there is no benefit and processing slows down.' },
        { q: 'Why is my OCR output full of random characters?', a: 'Usually too many languages selected, a rotated or skewed page, or over-thresholding that broke the letter strokes. Check orientation first, then reduce to a single language, then ease off the contrast.' },
        { q: 'How do I OCR a document with two columns?', a: 'Try page segmentation mode 1 or 3 first. If lines from adjacent columns interleave, crop each column into its own image and recognise them separately with mode 6, then join the results in order.' },
        { q: 'Can I improve OCR by upscaling a low-resolution scan?', a: 'No. Interpolation smears character edges, which is exactly the detail the recogniser depends on. An upscaled 150 DPI scan performs worse than the original. Rescan at 300 DPI instead.' },
        { q: 'Will OCR ever read my handwriting?', a: 'General OCR engines are trained on printed type. Neat block capitals may reach 60 to 80 percent; cursive returns almost nothing. Handwritten archives need a dedicated handwriting recognition service rather than a print-oriented engine.' },
      ],
      relatedTools: ['ocr-pdf', 'pdf-to-text'],
      relatedPosts: ['how-to-ocr-a-scanned-pdf', 'make-pdf-searchable', 'best-image-format-for-print'],
    },
  ],
}
