import type { Cluster } from '../types'

export const pdfPrivacy: Cluster = {
  slug: 'privacy',
  name: 'PDF privacy and security',
  title: 'PDF privacy: metadata, passwords and redaction that works',
  metaTitle: 'PDF Privacy: Metadata, Passwords, Redaction',
  metaDescription:
    'What a PDF leaks about you, what a password really protects, and how to redact so the text is genuinely gone. Practical methods with the limits spelled out.',
  intro:
    'Every PDF carries more than the words on the page: the author name from the account that made it, the application that produced it, edit timestamps, and sometimes GPS coordinates inside embedded photos. On top of that sit two widely misunderstood controls, password protection, which does less than people assume, and redaction, which most people do wrong. These guides cover what leaks, what protects, and how to check that it worked.',
  answer:
    'Before sharing a PDF, strip the document metadata, redact any sensitive content properly by removing it rather than covering it, and use encryption only when you genuinely need to control who can open the file. Always verify redaction by trying to select and copy the text afterwards.',
  primaryKeyword: 'pdf privacy',
  entities: ['PDF', 'Adobe Acrobat', 'XMP', 'EXIF', 'AES-256', 'GDPR', 'HIPAA', 'ExifTool', 'ISO 32000'],
  icon: '🔒',
  tools: ['remove-metadata', 'edit-metadata', 'flatten-pdf', 'pdf-to-jpg'],
  posts: [
    {
      slug: 'remove-metadata-from-pdf',
      cluster: 'privacy',
      title: 'How to remove hidden metadata from a PDF before sharing',
      metaTitle: 'Remove Hidden Metadata From a PDF',
      metaDescription:
        'A PDF stores your name, your software, edit timestamps and sometimes GPS data from embedded photos. How to see all of it and strip it before you share.',
      published: '2026-01-20',
      updated: '2026-08-11',
      readMinutes: 6,
      intent: 'howto',
      primaryKeyword: 'how to remove metadata from a pdf',
      secondaryKeywords: ['pdf metadata removal', 'remove author name from pdf', 'strip pdf metadata', 'hidden data in pdf', 'pdf document properties'],
      entities: ['PDF', 'Adobe Acrobat', 'XMP', 'EXIF', 'ExifTool', 'Microsoft Word', 'macOS Preview', 'Quartz PDFContext'],
      answer:
        'To remove metadata from a PDF, open it in a metadata tool and clear the Title, Author, Subject, Keywords, Creator and Producer fields along with the XMP block, then save. Embedded image EXIF and GPS data survive that step, so rasterise or re-encode the images if photos are involved.',
      body: [
        { t: 'p', x: 'Open any PDF you did not make yourself and press **Ctrl+D** (Cmd+D on macOS) in a reader. The document properties panel usually names a person, a company, an application and two timestamps. None of that is on the page. All of it travels with the file.' },
        { t: 'p', x: 'That is fine for an internal report and a problem for an anonymous submission, a whistleblower document, a CV sent to a company where you already work, or a tender response that should not reveal which of your clients the template came from.' },
        { t: 'h2', x: 'What a PDF actually stores about you' },
        {
          t: 'table',
          caption: 'Metadata fields in a typical PDF and what each reveals.',
          head: ['Field', 'Typical value', 'What it gives away'],
          rows: [
            ['Author', 'Nasir Uddin', 'The account name on the machine that exported the file'],
            ['Title', 'Invoice template v4 FINAL FINAL', 'Internal naming, version history, sometimes a client name'],
            ['Creator', 'Microsoft Word for Microsoft 365', 'The application that authored the content'],
            ['Producer', 'macOS Version 14.5 Quartz PDFContext', 'The operating system and version that wrote the PDF'],
            ['CreationDate / ModDate', 'D:20260114T093412+06\'00\'', 'When you worked on it, and your time zone offset'],
            ['Keywords / Subject', 'Q3, internal, do not circulate', 'Whatever the original author typed, often left in place'],
            ['XMP packet', 'A separate XML metadata stream', 'A duplicate of the above, plus editing history in some apps'],
            ['Embedded image EXIF', 'Camera model, GPS 23.8103, 90.4125', 'Where and when a photo in the document was taken'],
          ],
        },
        { t: 'warn', x: 'The last row is the one people miss. Clearing the document properties does not touch data inside the images embedded in the pages. If you dropped a phone photo into a Word document and exported to PDF, the photo may still carry the GPS coordinates of the place you took it.' },
        { t: 'h2', x: 'Remove it in your browser' },
        {
          t: 'steps',
          items: [
            { h: 'Open the metadata tool', x: 'Go to [Remove metadata](/tools/remove-metadata) and drop the PDF in. The file is parsed in the browser tab, which matters here more than anywhere else on the site, you do not want to upload the very file whose provenance you are trying to hide.' },
            { h: 'Read what is there first', x: 'Look at every field before you clear anything. Sometimes the interesting leak is a Title field naming a client you are not supposed to mention.' },
            { h: 'Clear the document information fields', x: 'Author, Title, Subject, Keywords, Creator and Producer. Empty is safer than a plausible fake, unless you specifically need a cover story.' },
            { h: 'Clear the XMP block as well', x: 'XMP is a second copy of the metadata stored as XML. A tool that clears only the document info dictionary leaves the XMP behind, and readers will still show the old author.' },
            { h: 'Decide about the dates', x: 'Creation and modification dates are not always removable without breaking readers. Where the tool allows it, blanking or normalising them removes the time zone hint.' },
            { h: 'Handle embedded photos', x: 'If the document contains camera photos and the location matters, convert the pages to images and rebuild the PDF, or replace the photos with re-exported copies that were stripped first.' },
            { h: 'Save and verify', x: 'Reopen the saved file and press Ctrl+D again. If a field is still populated, the tool wrote a new copy but left the old object in the file, try again with a tool that rewrites the document rather than appending to it.' },
          ],
        },
        { t: 'cta', tool: 'remove-metadata', x: 'Strip author, creator, timestamps and the XMP block from a PDF in your browser.' },
        { t: 'h2', x: 'How to check what is left' },
        { t: 'p', x: 'Do not trust a tool that says "done" without showing you the result. Three ways to audit, from easiest to most thorough:' },
        {
          t: 'ul',
          items: [
            '**Any PDF reader.** File → Properties, or Ctrl+D. Shows the document info dictionary, which is what most recipients would ever see.',
            '**macOS Preview.** Tools → Show Inspector, then the ⓘ tab. Fast and already installed on every Mac.',
            '**ExifTool on the command line.** The thorough option: it reports the document info, the XMP packet and the EXIF inside embedded images, which no consumer viewer does.',
          ],
        },
        { t: 'code', x: '# See everything, including data inside embedded images\nexiftool -a -G1 -s report.pdf\n\n# Strip document-level metadata in place (keeps a backup)\nexiftool -all= report.pdf' },
        { t: 'note', x: 'PDF files are append-only by design: an edit often writes a new version of an object and leaves the old one further up the file, reachable through the cross-reference table. That is why a "removed" author name sometimes reappears in a hex dump. A tool that fully rewrites the document, or a round trip through a rasterising step, removes those remnants.' },
        { t: 'h2', x: 'Other hidden content worth checking' },
        { t: 'p', x: 'Metadata is only one of several things carried invisibly in a PDF:' },
        {
          t: 'table',
          head: ['Hidden item', 'How it gets there', 'What to do'],
          rows: [
            ['Comment and annotation authors', 'Review comments carry the reviewer name', 'Delete the annotations or [flatten the file](/tools/flatten-pdf)'],
            ['Form field values', 'A filled form keeps values in the field objects', 'Flatten the form so values become page content'],
            ['Hidden layers', 'Design files exported with optional content groups', 'Flatten, or re-export from the source without the layers'],
            ['File attachments', 'Spreadsheets embedded inside the PDF', 'Check the attachments panel in a reader and remove them'],
            ['Bookmarks and named destinations', 'Carry old chapter and file names', 'Remove the outline if the names are revealing'],
            ['Cropped-away content', 'Cropping changes the visible box, not the content', 'Rasterise the pages if the cropped area is sensitive'],
          ],
        },
        { t: 'warn', x: 'Cropping is the sibling of the black-box mistake. Setting a crop box hides part of a page from view but leaves the content in the file, so anyone can restore it by resetting the crop. If the cropped-off area is sensitive, treat it as a redaction job and follow [the proper method](/blog/privacy/redact-pdf-properly).' },
        { t: 'h2', x: 'When to strip and when to set' },
        { t: 'p', x: 'Blanking every field is right for anonymous or externally shared documents. For a published report, deliberately setting the metadata is better: a real Title improves how the file appears in search results and in a browser tab, and a sensible Author is professional rather than leaky. Use [edit metadata](/tools/edit-metadata) to write clean values instead of empty ones.' },
        { t: 'tip', x: 'Build it into the routine. Anything leaving your organisation gets the same three steps: strip metadata, confirm redactions, then check the file opens correctly. It takes under a minute and it is the cheapest privacy control available. If you also [compress the file](/blog/compress/how-to-compress-a-pdf) for email, do that before the metadata pass, since compression tools often write their own Producer string.' },
      ],
      faqs: [
        { q: 'How do I see the metadata in a PDF?', a: 'Press Ctrl+D (Cmd+D on macOS) in most PDF readers to open document properties, or use Tools then Show Inspector in macOS Preview. For a complete view including data inside embedded images, run ExifTool on the file from a terminal.' },
        { q: 'Does removing metadata change how the PDF looks?', a: 'No. Metadata is stored separately from the page content, so clearing it leaves every page pixel-identical. Only the document properties panel changes, along with what search tools can index about the file.' },
        { q: 'Can GPS data really be inside a PDF?', a: 'Yes, when the PDF contains photos taken on a phone. The EXIF block inside the embedded image can carry coordinates, camera model and capture time, and clearing the document properties does not touch it. Rasterising the pages removes it.' },
        { q: 'Why does the old author name come back after I remove it?', a: 'PDF edits are often appended rather than rewritten, so the previous version of the object can survive in the file. Use a tool that fully rewrites the document, or convert the pages to images and rebuild, then re-check the properties.' },
        { q: 'Should I always blank the metadata?', a: 'Not always. For anonymous or externally shared documents, yes. For a published report, set clean values instead: an accurate Title helps search engines and browser tabs, while a deliberate Author looks professional rather than accidental.' },
      ],
      relatedTools: ['remove-metadata', 'edit-metadata'],
      relatedPosts: ['redact-pdf-properly', 'are-online-pdf-tools-safe', 'password-protect-pdf'],
    },
    {
      slug: 'password-protect-pdf',
      cluster: 'privacy',
      title: 'How to password protect a PDF, and what it actually protects',
      metaTitle: 'Password Protect a PDF: What It Really Does',
      metaDescription:
        'User password versus owner password, AES-256 versus legacy schemes, and why print and copy restrictions are advisory. Plus the tools that genuinely encrypt.',
      published: '2026-02-24',
      updated: '2026-07-27',
      readMinutes: 7,
      intent: 'informational',
      primaryKeyword: 'how to password protect a pdf',
      secondaryKeywords: ['pdf user password vs owner password', 'encrypt pdf aes 256', 'pdf permissions password', 'secure a pdf with a password', 'pdf password limits'],
      entities: ['PDF', 'Adobe Acrobat', 'AES-256', 'RC4', 'LibreOffice', 'macOS Preview', 'Microsoft Word', 'ISO 32000-2', 'qpdf'],
      answer:
        'A PDF supports two passwords: a user password that is required to open the file and genuinely encrypts it, and an owner password that only sets permissions such as printing. Only the user password protects the content. Permissions are advisory and any determined tool can ignore them.',
      body: [
        { t: 'p', x: 'PDF encryption is one of the most misunderstood features in everyday document handling, because a single dialog offers two things that sound similar and behave completely differently.' },
        { t: 'h2', x: 'Two passwords, two different jobs' },
        {
          t: 'table',
          caption: 'The two PDF passwords compared.',
          head: ['', 'User password (open password)', 'Owner password (permissions password)'],
          rows: [
            ['Prompted when', 'Opening the file', 'Editing, printing or extracting, in some readers'],
            ['Encrypts content?', 'Yes, the page data is genuinely encrypted', 'The file is encrypted with an empty user password'],
            ['Without the password you can', 'See nothing but the file name', 'Read everything'],
            ['Enforcement', 'Cryptographic', 'Advisory, the reader chooses to obey'],
            ['Removable without the password?', 'No, not practically, with a strong password', 'Yes, with common command-line tools'],
            ['Use it for', 'Genuinely restricting who can read a document', 'Signalling intent, nothing more'],
          ],
        },
        { t: 'warn', x: 'If you set only an owner password, the file is technically encrypted but with an empty user password, so anyone can open it. Standard tools such as qpdf will strip the restrictions in one command without knowing your password. Do not use a permissions password as a security control.' },
        { t: 'h2', x: 'Which encryption strength' },
        {
          t: 'table',
          head: ['Scheme', 'Introduced with', 'Verdict in 2026'],
          rows: [
            ['RC4 40-bit', 'Acrobat 3, PDF 1.1', 'Broken. Recoverable by brute force in minutes.'],
            ['RC4 128-bit', 'Acrobat 5, PDF 1.4', 'Deprecated. Do not choose it for anything new.'],
            ['AES-128', 'Acrobat 7, PDF 1.6', 'Acceptable, still widely compatible.'],
            ['AES-256', 'Acrobat X, PDF 2.0 / ISO 32000-2', 'The correct choice. Strength now depends on your password, not the cipher.'],
          ],
        },
        { t: 'p', x: 'With AES-256 the algorithm is not the weak point, your password is. A six-character password on AES-256 is a six-character password. Use a passphrase of four or more unrelated words, or a generated string of at least 16 characters from a password manager.' },
        { t: 'h2', x: 'What this site cannot do, honestly' },
        { t: 'note', x: 'PrintxPDF is a browser-based toolkit that rearranges and rewrites the structure of PDF files. It does not add AES encryption, and no page here will claim otherwise. If you need a genuinely encrypted PDF, use one of the desktop options below, they are free, already installed on most machines, and they produce real encryption.' },
        {
          t: 'steps',
          items: [
            { h: 'macOS Preview', x: 'Open the PDF, choose **File → Export as PDF**, expand **Permissions**, tick "Require password to open document", and set the password. Preview writes AES-256 on current macOS versions.' },
            { h: 'LibreOffice', x: 'Open the document, choose **File → Export as → Export as PDF**, open the **Security** tab, click "Set Passwords", and enter an open password. Free, cross-platform, and it produces AES-256.' },
            { h: 'Microsoft Word', x: 'Choose **File → Save As**, pick PDF, click **Options**, and tick "Encrypt the document with a password". Works from the document you already have open.' },
            { h: 'Adobe Acrobat Pro', x: '**All tools → Protect a PDF → Encrypt with password**. Choose "Require a password to open the document" and set compatibility to Acrobat X or later for AES-256.' },
            { h: 'qpdf on the command line', x: 'For scripted or bulk work: `qpdf --encrypt user owner 256 -- in.pdf out.pdf`. Free, open source, and the most controllable option.' },
          ],
        },
        { t: 'h2', x: 'What a password does not protect against' },
        {
          t: 'ul',
          items: [
            '**A recipient who reshares it.** Once someone opens the file, they can save an unprotected copy, screenshot it, or forward the password. Encryption controls the first opening, not what happens afterwards.',
            '**Sensitive content already visible in the document.** Encryption hides the file from outsiders; it does nothing about the third-party names on page 9 that should have been [redacted](/blog/privacy/redact-pdf-properly).',
            '**Metadata leakage in the file name.** `Q3-layoffs-final.pdf` in an email subject line tells the story before anyone types a password.',
            '**Print and copy restrictions.** These are permission flags a conforming reader agrees to honour. Non-conforming tools ignore them entirely.',
            '**A weak password.** Recovery tools try millions of candidates a second against a PDF. A dictionary word with a number on the end will not hold.',
          ],
        },
        { t: 'warn', x: 'Never email a protected file and its password in the same message, or in a reply to the same thread. Anyone who reaches the mailbox has both. Send the password by a different channel, a phone call, a text message, or a message in a separate application.' },
        { t: 'h2', x: 'When encryption is the right tool' },
        { t: 'p', x: 'Encryption fits a narrow but real set of cases: a document going to one identified recipient, a file on removable media, an archive on shared storage where the storage administrators should not be able to read it, or a regulatory requirement that names encryption at rest. In each of those, the threat is a party who should never see the content at all.' },
        { t: 'p', x: 'It fits badly where the concern is downstream behaviour by a legitimate recipient. For that, combine a [CONFIDENTIAL watermark](/blog/watermark/add-watermark-to-pdf) naming the recipient with an explicit written restriction. The watermark will not stop anyone either, but it survives forwarding, and it makes a leak traceable in a way that a password never does.' },
        { t: 'h2', x: 'Removing a password you own' },
        { t: 'p', x: 'If you know the password and want an unprotected working copy, open the file, enter the password, and export or print to a new PDF. In macOS Preview, File → Export as PDF with permissions left empty produces a clean copy. In Acrobat, use Protect → Remove Security. On the command line, `qpdf --decrypt --password=yourpassword in.pdf out.pdf` does it in one step.' },
        { t: 'tip', x: 'Encrypted PDFs cannot be processed by browser-based tools, including the ones here, because the page content is unreadable until it is decrypted. If you need to [merge](/blog/merge/how-to-merge-pdf-files), split or compress an encrypted file, decrypt it first with the password you hold, do the work, then re-encrypt the result.' },
        { t: 'cta', tool: 'remove-metadata', x: 'Whatever you do about passwords, strip the metadata before the file leaves your machine.' },
      ],
      faqs: [
        { q: 'What is the difference between a user password and an owner password?', a: 'A user password is required to open the document and genuinely encrypts the content. An owner password only sets permissions such as printing or copying, leaves the file openable by anyone, and can be stripped by common tools without knowing it.' },
        { q: 'Can PrintxPDF add a password to my PDF?', a: 'No. The tools here run in your browser and rewrite the structure of a PDF; they do not perform AES encryption. Use macOS Preview, LibreOffice, Microsoft Word, Adobe Acrobat or qpdf, all of which produce genuinely encrypted files.' },
        { q: 'Is AES-256 PDF encryption secure?', a: 'The cipher is sound, so the security of the file comes down to the password. A generated string of at least 16 characters, or a passphrase of four or more unrelated words, is what makes AES-256 meaningful in practice.' },
        { q: 'Can someone remove the print restriction from my PDF?', a: 'Yes, easily, if you only set an owner password. Permission flags are advisory and depend on the reader choosing to honour them. Only a user password, which encrypts the content, actually restricts access.' },
        { q: 'Why will online PDF tools not open my protected file?', a: 'The page content is encrypted, so a tool cannot read it without the password. Decrypt the file locally with the password you hold, run the operation, and re-encrypt the result afterwards.' },
      ],
      relatedTools: ['remove-metadata', 'merge-pdf'],
      relatedPosts: ['remove-metadata-from-pdf', 'redact-pdf-properly', 'are-online-pdf-tools-safe'],
    },
    {
      slug: 'redact-pdf-properly',
      cluster: 'privacy',
      title: 'How to redact a PDF so the text is really gone',
      metaTitle: 'How to Redact a PDF (So Text Is Really Gone)',
      metaDescription:
        'A black rectangle does not redact anything: the text stays in the file and copies straight out. The method that really removes it, and how to verify it.',
      published: '2026-03-17',
      updated: '2026-08-25',
      readMinutes: 8,
      intent: 'howto',
      primaryKeyword: 'how to redact a pdf',
      secondaryKeywords: ['redact pdf properly', 'black box pdf not redacted', 'permanently remove text from pdf', 'verify pdf redaction', 'redaction failure pdf'],
      entities: ['PDF', 'Adobe Acrobat', 'pdftotext', 'GDPR', 'content stream', 'OCR', 'ExifTool', 'macOS Preview'],
      answer:
        'To redact a PDF, the sensitive content must be deleted from the file, not covered. Cover the areas with solid black, then rasterise every page to an image and rebuild the PDF, which destroys the text layer. Verify by selecting all text and pasting it into a text editor.',
      body: [
        { t: 'warn', x: 'Drawing a black rectangle over text does not remove the text. The characters stay in the page content stream underneath the box. Anyone can select the area, press copy, and paste the hidden words into a text editor. Every reported redaction failure, in court filings, government reports and corporate disclosures, is this mistake.' },
        { t: 'p', x: 'This is not an obscure edge case. A PDF page is a list of drawing instructions executed in order. "Put the word Hendricks at x=180, y=420" is one instruction. "Fill a black rectangle over that area" is a later instruction. The second one paints over the first on screen. It does not erase it from the list.' },
        { t: 'h2', x: 'Things that look like redaction and are not' },
        {
          t: 'table',
          caption: 'Fake redaction methods and how each one fails.',
          head: ['What people do', 'Does it remove the text?', 'How it is recovered'],
          rows: [
            ['Draw a black rectangle in a viewer or markup tool', 'No', 'Select over the box, copy, paste'],
            ['Use the highlighter set to black', 'No', 'Same, highlights are transparent annotations'],
            ['Change the text colour to white', 'No', 'Select all and paste; it is still there'],
            ['Add a black box in the source document, then export', 'No', 'The export still writes the characters underneath'],
            ['Crop the page to hide a margin', 'No', 'Reset the crop box and the content returns'],
            ['Blur or pixelate a scanned name', 'Partly, and unreliably', 'Short pixelated text can be reconstructed by matching candidates'],
            ['Delete the text and box over the gap', 'Yes for the text, but check', 'Undo history and appended objects can survive in the file'],
            ['Cover, then rasterise the page to an image', 'Yes', 'There is no text layer left to recover'],
          ],
        },
        { t: 'p', x: 'Note the blur row. Pixelation of a short, known-format string, a name, a licence number, a postcode, is reversible in principle: an attacker pixelates candidate strings the same way and looks for a match. Never blur. Use solid, opaque black.' },
        { t: 'h2', x: 'The reliable browser method' },
        { t: 'p', x: 'The idea is simple: make the sensitive area invisible, then destroy the entire text layer by turning every page into a picture of itself. Once a page is an image, there is nothing to select, extract or search, including the words that were under the box.' },
        {
          t: 'steps',
          items: [
            { h: 'Work on a copy', x: 'Duplicate the file first, for example `report-REDACTED-WORKING.pdf`, and keep the original in a separate folder. Never redact your only copy.' },
            { h: 'Cover every sensitive area with solid black', x: 'Use any editor or annotation tool to draw filled, fully opaque rectangles. Overlap generously: extend past the ends of the words and cover descenders. A sliver of a letter left visible is enough to narrow a name.' },
            { h: 'Check every page, not just the obvious ones', x: 'Names recur in headers, footers, contents pages, bookmarks and appendices. Search the whole document for each term before you move on.' },
            { h: 'Rasterise the pages', x: 'Convert the marked-up file to images with [PDF to JPG](/tools/pdf-to-jpg) at 200 to 300 DPI. Below 200 DPI the printed result looks soft; above 300 the file grows fast with little visible gain.' },
            { h: 'Rebuild the PDF from the images', x: 'Use [JPG to PDF](/tools/jpg-to-pdf) to reassemble the pages in order. The new file has no text objects at all, so the covered words are genuinely gone.' },
            { h: 'Strip the metadata', x: 'Run the new file through [remove metadata](/tools/remove-metadata). Titles and keywords frequently contain the same names you just redacted.' },
            { h: 'Verify before it leaves your machine', x: 'Do the checks in the next section, every single time. A redaction you have not verified is not a redaction.' },
          ],
        },
        { t: 'cta', tool: 'pdf-to-jpg', x: 'Rasterise pages to images, the step that actually destroys the hidden text layer.' },
        { t: 'h2', x: 'Verifying that it worked' },
        { t: 'p', x: 'Four checks, one minute, on the final file you are about to send. Run all four.' },
        {
          t: 'ol',
          items: [
            '**Select all and paste.** Open the redacted file, press Ctrl+A then Ctrl+C, and paste into a plain text editor. On a correctly rasterised file, nothing is selectable and nothing pastes. If you get a wall of text, the text layer survived, stop and start again.',
            '**Search for a redacted term.** Press Ctrl+F and type one of the names you removed. Zero results is the expected answer. A hit means the word is still in the file even though you cannot see it.',
            '**Extract the text on the command line.** Run `pdftotext redacted.pdf -` and read the output, or pipe it to grep for the removed terms. This bypasses the viewer entirely and is the check that catches everything.',
            '**Check the file size.** A rasterised document is usually larger than the text original. A file identical in size to the original means the rasterising step never ran.',
          ],
        },
        { t: 'code', x: '# The definitive check: extract raw text and search it\npdftotext redacted.pdf - | grep -i -e "hendricks" -e "07700 900" -e "@example.com"\n\n# Expect no output. Any line here is a leak.' },
        { t: 'warn', x: 'Do not skip verification because the tool said "redaction applied". Tools that claim to redact sometimes only draw. The only evidence that matters is that the text cannot be extracted from the finished file.' },
        { t: 'h2', x: 'The desktop alternative' },
        { t: 'p', x: 'Adobe Acrobat Pro has a true redaction feature and it is the right tool for volume work. It is a two-stage operation and people get caught by stage two: **Redact → Mark for Redaction** only marks the areas, and the content is not removed until you press **Apply**. A file saved between those two steps still contains everything. After applying, run **Sanitize Document** as well, which removes metadata, hidden layers, attachments and scripts in one pass.' },
        { t: 'h2', x: 'What redaction still does not cover' },
        {
          t: 'ul',
          items: [
            '**Metadata.** Title, Author and Keywords are separate from the page content and survive rasterising in some pipelines. Always run a [metadata pass](/blog/privacy/remove-metadata-from-pdf) afterwards.',
            '**Inference.** Redacting a name but leaving a job title, a date and a department can identify a person as surely as the name did. Redact the identifying combination, not just the obvious field.',
            '**Consistency across a set.** If the same person is redacted on page 4 and left visible on page 30, the redaction on page 4 achieved nothing. Search the whole set for every term.',
            '**Attachments and embedded files.** A spreadsheet attached inside the PDF is not part of any page and is not rasterised. Check the attachments panel and remove them.',
          ],
        },
        { t: 'note', x: 'Delete the intermediate marked-up file when you are done: it holds both the boxes and the text. If you later run OCR to restore searchability, the engine reads only what is visible, so black areas produce nothing.' },
        { t: 'p', x: 'Covering is not removing, and the only proof of removal is failing to extract the text. A [watermark or stamp](/blog/watermark/watermark-vs-stamp) solves a different problem entirely.' },
      ],
      faqs: [
        { q: 'Why is a black box not a real redaction?', a: 'The rectangle is drawn on top of the page, while the text remains in the content stream underneath. Selecting over the box and copying, or running a text extraction tool, returns the hidden words in full. Nothing has been removed.' },
        { q: 'How do I permanently remove text from a PDF for free?', a: 'Cover the sensitive areas with solid opaque black, convert every page to an image at 200 to 300 DPI, and rebuild the PDF from those images. This destroys the text layer entirely, so there is nothing left to extract.' },
        { q: 'How do I check that a PDF redaction worked?', a: 'Open the finished file, press Ctrl+A then Ctrl+C, and paste into a text editor: nothing should paste. Then search for a redacted term with Ctrl+F, and run pdftotext on the file and grep the output. All three must come back empty.' },
        { q: 'Is blurring or pixelating a name enough?', a: 'No. Pixelation of short, predictable strings such as names or reference numbers can be reversed by pixelating candidate strings and matching the result. Always use solid, fully opaque black, then remove the underlying content.' },
        { q: 'Does redaction remove the metadata too?', a: 'Not necessarily. Title, Author, Subject and Keywords live outside the page content and can survive the process. Run a metadata removal pass on the final file and check the document properties before sharing it.' },
      ],
      relatedTools: ['pdf-to-jpg', 'jpg-to-pdf'],
      relatedPosts: ['remove-metadata-from-pdf', 'watermark-vs-stamp', 'are-online-pdf-tools-safe'],
    },
    {
      slug: 'are-online-pdf-tools-safe',
      cluster: 'privacy',
      title: 'Are online PDF tools safe? What happens to your file',
      metaTitle: 'Are Online PDF Tools Safe? What Happens',
      metaDescription:
        'Some PDF sites upload your file to a server, others process it in your browser. How to tell the difference in thirty seconds, and what GDPR and HIPAA require.',
      published: '2026-04-14',
      updated: '2026-08-30',
      readMinutes: 7,
      intent: 'informational',
      primaryKeyword: 'are online pdf tools safe',
      secondaryKeywords: ['online pdf converter privacy', 'do pdf sites store my files', 'browser based pdf tool', 'pdf tool gdpr', 'secure pdf tool for confidential documents'],
      entities: ['GDPR', 'HIPAA', 'WebAssembly', 'pdf.js', 'Chrome DevTools', 'TLS', 'Mozilla', 'data processing agreement'],
      answer:
        'It depends entirely on whether the tool uploads your file or processes it in your browser. Upload-based sites send the document to a server that could store or read it. Browser-based tools never transmit the file at all. You can tell which is which in thirty seconds using the network tab.',
      body: [
        { t: 'p', x: 'Two websites can offer the identical [merge PDF](/tools/merge-pdf) button and do something completely different underneath. One sends your document across the internet to a machine you know nothing about. The other never moves it off your laptop. The page usually does not say which, so you have to check.' },
        { t: 'h2', x: 'The two architectures' },
        {
          t: 'table',
          caption: 'Upload-based and browser-based PDF tools compared.',
          head: ['', 'Upload-based (server-side)', 'Browser-based (client-side)'],
          rows: [
            ['Where the file goes', 'To the provider servers', 'Nowhere, it stays in the browser tab'],
            ['Who could read it', 'The provider, their hosting company, anyone who breaches either', 'Only you'],
            ['Works offline', 'No', 'Yes, once the page has loaded'],
            ['Typical retention', '1 hour to 24 hours, by policy', 'None, there is nothing to retain'],
            ['Limits on file size', 'Server-side, often generous', 'Your device memory, usually a few hundred MB'],
            ['Heavy jobs (OCR, big scans)', 'Faster on server hardware', 'Slower, but private'],
            ['GDPR position', 'The provider is a data processor; you need an agreement', 'No processor, because no transfer'],
            ['What to verify', 'The privacy policy, retention, and the contract', 'That it really does not upload, check it yourself'],
          ],
        },
        { t: 'h2', x: 'Check it yourself in thirty seconds' },
        { t: 'p', x: 'You do not have to take anyone at their word, including this site. The browser will tell you whether your file left the machine.' },
        {
          t: 'steps',
          items: [
            { h: 'Open the developer tools', x: 'Press **F12**, or Ctrl+Shift+I (Cmd+Option+I on macOS), and switch to the **Network** tab.' },
            { h: 'Clear the log and start recording', x: 'Click the clear icon so you are only looking at what happens next.' },
            { h: 'Load your file into the tool', x: 'Use a test PDF of a few megabytes, not your confidential one. Size matters here: a large file makes an upload obvious.' },
            { h: 'Watch the request list', x: 'Sort by **Size**. A POST or PUT request whose size is close to your file size means the document was uploaded. A tool that stays local shows no such request at all.' },
            { h: 'Run the operation and look again', x: 'Some sites process locally but upload on export. Do the whole job, merge, compress, download, and watch throughout.' },
            { h: 'The offline test', x: 'The simplest proof of all: load the page, disconnect from the network, then use the tool. If it still works, the processing is genuinely happening on your device.' },
          ],
        },
        { t: 'note', x: 'Browser-based processing is normal engineering now, not a marketing claim. Mozilla pdf.js renders every PDF in Firefox, and WebAssembly builds of established PDF libraries run in a tab at usable speed. That is why a modern browser tool can merge, split, rotate or number pages without a server at all.' },
        { t: 'h2', x: 'Reading a privacy policy for what matters' },
        { t: 'p', x: 'If a tool does upload, four questions decide whether you should use it for this particular document:' },
        {
          t: 'ol',
          items: [
            '**How long is the file kept?** Look for a specific number: "deleted after one hour" is a commitment; "we do not keep files longer than necessary" is not.',
            '**Who can access it while it is there?** Some providers state that files are encrypted at rest and inaccessible to staff. Many say nothing, which usually means staff can read them.',
            '**Is the content used for anything else?** Training data, analytics, quality sampling. This clause is often buried in a section about "improving our services".',
            '**Where are the servers?** For personal data under GDPR, a transfer outside the EEA needs a legal basis such as standard contractual clauses.',
          ],
        },
        { t: 'warn', x: 'A deletion promise is a policy, not a technical guarantee. You cannot verify it, you cannot audit it, and backups may outlive it. For a document that would cause real harm if exposed, do not rely on retention terms, do not upload it in the first place.' },
        { t: 'h2', x: 'GDPR, HIPAA and workplace rules' },
        { t: 'p', x: 'The rules do not care whether a tool is free. They care about where personal data goes.' },
        {
          t: 'ul',
          items: [
            '**GDPR.** Uploading a document containing personal data makes the tool provider your processor. Article 28 requires a written data processing agreement. Free consumer sites do not offer one, so uploading customer or employee documents to them is a compliance problem regardless of how careful the provider is.',
            '**HIPAA.** Any document with protected health information requires a business associate agreement with the service. Almost no free PDF site will sign one. A browser-based tool sidesteps the question entirely, because no disclosure to a third party occurs.',
            '**Legal privilege.** Sending a privileged document through a third-party service can complicate a privilege claim. Firms handle this with local tooling for a reason.',
            '**Your own IT policy.** Many organisations block file-upload converters at the network level. If a tool works on a locked-down corporate laptop, that is often because it never uploads anything.',
          ],
        },
        { t: 'h2', x: 'A practical rule' },
        {
          t: 'table',
          head: ['Document', 'Upload-based tool', 'Browser-based tool'],
          rows: [
            ['A public report or a blog post PDF', 'Fine', 'Fine'],
            ['Your own CV', 'Acceptable', 'Better'],
            ['A contract with a client named in it', 'No', 'Yes'],
            ['Payslips, bank statements, tax filings', 'No', 'Yes'],
            ['Medical records or anything with PHI', 'No, without a signed agreement', 'Yes'],
            ['A 900MB scanned archive needing OCR', 'Practical, with a vetted provider', 'May exceed browser memory'],
          ],
        },
        { t: 'h2', x: 'Things that do not answer the question' },
        {
          t: 'ul',
          items: [
            '**The padlock in the address bar.** TLS protects the file in transit. It says nothing about what the server does with it afterwards.',
            '**"Files are deleted after 1 hour".** Reassuring, unverifiable, and irrelevant if the file was readable during that hour.',
            '**A long privacy policy.** Length is not commitment. Search it for the words "retain", "delete", "third party" and "train" and read only those paragraphs.',
            '**"No registration required".** Anonymity for you, not for the file.',
          ],
        },
        { t: 'tip', x: 'The strongest signal is behavioural, not written: does the tool still work with the network disconnected? Nothing can fake that. Everything on this site is built to pass that test, which is also why [encrypted PDFs](/blog/privacy/password-protect-pdf) and very large scans have to be handled elsewhere, there is no server here to hand the hard work to.' },
        { t: 'cta', tool: 'merge-pdf', x: 'Merge PDFs entirely in your browser, try it with the network switched off.' },
        { t: 'p', x: 'Whichever kind of tool you use, the file itself still carries its own history. Strip the [document metadata](/blog/privacy/remove-metadata-from-pdf) before sharing, and confirm any [redactions are real](/blog/privacy/redact-pdf-properly) rather than drawn on.' },
      ],
      faqs: [
        { q: 'Are online PDF converters safe to use?', a: 'Only if they do not upload your file, or if you have a contract with the provider. Upload-based converters send the document to a server that could store or read it. Browser-based tools process the file locally and transmit nothing.' },
        { q: 'How can I tell if a PDF tool uploads my file?', a: 'Open developer tools with F12, go to the Network tab, clear it, then load your file. A POST or PUT request roughly the size of your document means it was uploaded. The definitive test is disconnecting from the network: a local tool keeps working.' },
        { q: 'Can I use a free online PDF tool for confidential work documents?', a: 'Not an upload-based one. Under GDPR the provider becomes your data processor and you need a written agreement, and for health data HIPAA requires a business associate agreement. Browser-based tools avoid the issue because nothing is disclosed.' },
        { q: 'Does HTTPS mean my uploaded PDF is private?', a: 'No. HTTPS encrypts the file while it travels to the server. Once it arrives, the provider can read it, store it and process it. The padlock tells you nothing about retention or access.' },
        { q: 'Why do browser-based tools struggle with very large files?', a: 'They are limited by your device memory rather than server hardware, so files of several hundred megabytes and heavy jobs such as OCR on large scans can be slow or fail. That is the trade-off you accept in exchange for the file never leaving your machine.' },
      ],
      relatedTools: ['merge-pdf', 'remove-metadata'],
      relatedPosts: ['remove-metadata-from-pdf', 'redact-pdf-properly', 'password-protect-pdf'],
    },
  ],
}
