import type { Cluster } from '../types'

export const pdfImages: Cluster = {
  slug: 'pdf-images',
  name: 'PDFs and images',
  title: 'PDFs and images: convert, extract and print at the right resolution',
  metaTitle: 'PDF to Image: Convert, Extract and Print Right',
  metaDescription:
    'Turn PDF pages into JPG or PNG, pull the original embedded images out of a PDF, and choose the resolution and format that still looks sharp on real paper.',
  intro:
    'A PDF page is not a picture. It is a set of drawing instructions: place this font here, stroke this curve, paint this photo into that rectangle. That means there are two completely different ways to get an image out of a PDF, and they produce different results. You can render the page at a resolution you choose, or you can extract the original photo that was embedded when the file was made. These guides cover both, plus the resolution and format numbers that decide whether the result prints cleanly.',
  answer:
    'To turn a PDF page into an image, render it at a chosen resolution: 144 DPI for screens, 300 DPI for printing. To recover a photo that was placed in the PDF, extract the embedded image instead, which returns the original pixels without re-rendering or quality loss.',
  primaryKeyword: 'convert pdf to image',
  entities: ['JPEG', 'PNG', 'WebP', 'Adobe Acrobat', 'Poppler', 'ImageMagick', 'Adobe Photoshop', 'CMYK'],
  icon: '🖼',
  tools: ['pdf-to-jpg', 'jpg-to-pdf', 'compress-pdf', 'pdf-reader'],
  posts: [
    {
      slug: 'pdf-to-jpg',
      cluster: 'pdf-images',
      title: 'How to convert PDF pages to JPG or PNG images',
      metaTitle: 'How to Convert PDF Pages to JPG or PNG Images',
      metaDescription:
        'Convert PDF pages to JPG or PNG images in your browser. Pick the right DPI, choose between JPG and PNG, and export a single page or the whole document.',
      published: '2026-01-22',
      updated: '2026-08-14',
      readMinutes: 6,
      intent: 'howto',
      primaryKeyword: 'convert pdf to jpg',
      secondaryKeywords: ['pdf to png', 'export pdf page as image', 'save pdf page as jpg', 'pdf to image converter', 'pdf to jpg 300 dpi'],
      entities: ['JPEG', 'PNG', 'WebP', 'Adobe Acrobat', 'Preview (macOS)', 'Poppler', 'ImageMagick', 'A4', 'US Letter'],
      answer:
        'Open the PDF in a converter, choose a resolution, and export. Use 144 DPI for screens and email, 300 DPI for printing. Choose PNG for pages that are mostly text, tables or diagrams, and JPG for pages dominated by photographs, where it is roughly three times smaller.',
      body: [
        { t: 'p', x: 'Converting a PDF page to an image is called **rendering**. The converter reads the drawing instructions in the page, paints them onto a blank canvas of whatever size you asked for, and hands you the pixels. Nothing about the PDF changes, and you can render the same page a hundred times at a hundred different sizes.' },
        { t: 'p', x: 'That makes the resolution your most important decision. Get it wrong low and the text turns to mush; get it wrong high and you have a 40 MB PNG that will not attach to an email. Here is how to pick.' },
        { t: 'h2', x: 'Step 1: Pick the resolution' },
        { t: 'p', x: 'Inside a PDF, one unit equals 1/72 of an inch. That is why a converter that offers a **scale** of 1×, 2× or 3× is really offering you 72, 144 and 216 DPI. Tools that ask for DPI directly are doing the same arithmetic for you.' },
        {
          t: 'table',
          caption: 'Render scale, the resolution it produces, and the resulting pixel size of a full page.',
          head: ['Scale', 'DPI', 'US Letter page', 'A4 page', 'Good for'],
          rows: [
            ['1×', '72', '612 × 792 px', '595 × 842 px', 'Thumbnails, contact sheets, quick previews'],
            ['2×', '144', '1224 × 1584 px', '1191 × 1684 px', 'Screens, slides, web pages, email attachments'],
            ['3×', '216', '1836 × 2376 px', '1786 × 2526 px', 'Zooming in on small type, detailed diagrams'],
            ['4.17×', '300', '2550 × 3300 px', '2480 × 3508 px', 'Printing the page at its real size'],
            ['8.33×', '600', '5100 × 6600 px', '4960 × 7016 px', 'OCR of very small type, archival capture'],
          ],
        },
        { t: 'p', x: 'The default in most converters is 144 DPI, and for most jobs that is right. Only step up to 300 if the image is going on paper. See [what resolution you need for printing](/blog/pdf-images/best-image-format-for-print) for the full reasoning behind the 300 DPI number.' },
        { t: 'h2', x: 'Step 2: Convert the file' },
        {
          t: 'steps',
          items: [
            { h: 'Open the converter', x: 'Go to the [PDF to JPG tool](/tools/pdf-to-jpg) and drop your file onto the page. The file is processed in your browser, so nothing is uploaded to a server.' },
            { h: 'Choose the format', x: 'Pick **PNG** for text, tables, screenshots, line art and logos. Pick **JPG** for pages that are mostly photographs.' },
            { h: 'Set the resolution', x: 'Choose 144 DPI for anything that will be viewed on a screen, or 300 DPI if the result is going to a printer. Watch the estimated file size as you change it.' },
            { h: 'Pick the pages', x: 'Export every page, or type a range such as `1`, `4-6` or `2,7,9` to get only the pages you need. Each page becomes a separate image file.' },
            { h: 'Download', x: 'A single page downloads as one image. Several pages download as a ZIP, with files named after the page number so the order survives.' },
          ],
        },
        { t: 'cta', tool: 'pdf-to-jpg', x: 'Convert a PDF to JPG or PNG in your browser. No upload, no account, no watermark.' },
        { t: 'h2', x: 'JPG or PNG? The short version' },
        { t: 'p', x: 'PNG is lossless: every pixel comes back exactly as it was rendered, so the black edge of a letter stays a hard black edge. JPG throws away detail in 8 × 8 pixel blocks to save space, which is invisible on a photograph and very visible around text, where it produces a faint grey halo known as ringing.' },
        {
          t: 'table',
          caption: 'The same A4 page of text and charts, exported at 144 DPI.',
          head: ['Format', 'File size', 'Text edges', 'Transparency'],
          rows: [
            ['PNG', '380 KB', 'Perfectly crisp', 'Supported'],
            ['JPG, quality 90', '160 KB', 'Faint halo around black text', 'Not supported'],
            ['JPG, quality 60', '55 KB', 'Visible blocking around letters', 'Not supported'],
            ['WebP, quality 90', '95 KB', 'Crisp', 'Supported'],
          ],
        },
        { t: 'p', x: 'For a page that is one large photograph, those numbers invert: the PNG balloons to several megabytes while the JPG stays small and looks identical. [PNG versus JPG for PDF pages](/blog/pdf-images/pdf-to-png-transparent) walks through the edge cases.' },
        { t: 'h2', x: 'Rendering a page is not the same as extracting a photo' },
        { t: 'p', x: 'If your goal is to recover a photograph that somebody placed into the PDF, rendering the page is the wrong tool. Rendering gives you a picture of the whole page at the size you chose, including the surrounding text and margins, and the photo inside it has been resampled. Extraction pulls the original file back out untouched. See [extracting the original images from a PDF](/blog/pdf-images/extract-images-from-pdf).' },
        { t: 'h2', x: 'Other ways to do it' },
        {
          t: 'table',
          head: ['Method', 'Resolution control', 'Notes'],
          rows: [
            ['Browser tool', 'Yes, exact DPI', 'Nothing leaves your computer. Handles batches.'],
            ['Adobe Acrobat Pro', 'Yes, File → Export To → Image', 'Offers a colour-space and anti-aliasing setting. Paid.'],
            ['Preview on macOS', 'Yes, File → Export, set Resolution', 'One page at a time unless you select thumbnails first.'],
            ['pdftoppm (Poppler)', 'Yes, -r flag', 'Fastest option for hundreds of files. Command line.'],
            ['Screenshot', 'No, always your screen resolution', 'Avoid. You get 96 DPI at best, plus whatever the viewer was zoomed to.'],
          ],
        },
        { t: 'code', x: '# Poppler: pages 3 to 5 as 300 DPI JPEGs named page-03.jpg and so on\npdftoppm -jpeg -r 300 -f 3 -l 5 report.pdf page\n\n# ImageMagick: every page as a 150 DPI PNG\nmagick -density 150 report.pdf page-%02d.png' },
        { t: 'warn', x: 'Do not screenshot a PDF page when you need a usable image. A screenshot captures your display, so you inherit the viewer zoom level, any scroll bars, and roughly 96 DPI. Printing that gives you soft, fuzzy text that no amount of sharpening recovers.' },
        { t: 'h2', x: 'Keeping the file size under control' },
        { t: 'p', x: 'A 300 DPI PNG of a Letter page is 2550 × 3300 pixels — about 8.4 million pixels, which commonly lands between 1 MB and 4 MB. Three practical ways to shrink it: drop to 144 DPI if the image is only going on screen; switch to JPG at quality 85 if the page has photos; or crop the page to just the region you need before exporting.' },
        { t: 'tip', x: 'Going the other way is just as easy. If you have a folder of photos or scans and you want one document, [combine them into a single PDF](/tools/jpg-to-pdf) instead of emailing twelve attachments.' },
        { t: 'h2', x: 'After the conversion' },
        { t: 'p', x: 'Images are bigger than text, so a PDF rebuilt from page images grows fast. If you convert a document to images and then back to a PDF, expect the result to be several times larger than the original and no longer searchable — you will need to [OCR it](/blog/ocr-scanned-documents/how-to-ocr-a-scanned-pdf) to get the text back. When size becomes a problem, compress the file before you send it anywhere.' },
      ],
      faqs: [
        { q: 'What DPI should I use to convert a PDF to JPG?', a: 'Use 144 DPI for anything viewed on a screen and 300 DPI for anything printed. 72 DPI is only useful for thumbnails, and going above 300 mostly produces very large files without visible improvement, except for OCR of tiny type.' },
        { q: 'Does converting a PDF to JPG reduce the quality?', a: 'Rendering itself is lossless, but the JPG encoder is not. At quality 90 the loss is invisible on photographs and slightly visible around text. Choose PNG if the page is mostly text and you want a pixel-exact result.' },
        { q: 'How do I convert only one page of a PDF to an image?', a: 'Enter that page number in the page range box before exporting. Most converters accept single numbers, ranges such as 4-6, and comma-separated lists such as 2,7,9.' },
        { q: 'Can I convert a PDF to images without uploading it?', a: 'Yes. Browser-based converters render the file with JavaScript on your own machine, so the PDF never leaves your computer. That matters for contracts, medical records and anything else confidential.' },
        { q: 'Why is my exported image blurry?', a: 'Almost always because the export resolution was too low for the final use, or because the page contained a low-resolution photo to begin with. Rendering at 600 DPI cannot add detail that was never in the source image.' },
      ],
      relatedTools: ['pdf-to-jpg', 'jpg-to-pdf'],
      relatedPosts: ['pdf-to-png-transparent', 'extract-images-from-pdf', 'best-image-format-for-print'],
    },
    {
      slug: 'extract-images-from-pdf',
      cluster: 'pdf-images',
      title: 'How to extract the original images from a PDF',
      metaTitle: 'Extract the Original Images From a PDF',
      metaDescription:
        'Pull the original embedded photos out of a PDF instead of screenshotting the page. How extraction differs from rendering, and what each one does to quality.',
      published: '2026-02-18',
      updated: '2026-07-29',
      readMinutes: 6,
      intent: 'howto',
      primaryKeyword: 'extract images from pdf',
      secondaryKeywords: ['pull images out of pdf', 'save pictures from a pdf', 'pdf image extractor', 'get original photo from pdf', 'pdfimages command'],
      entities: ['Poppler', 'Adobe Acrobat', 'JPEG', 'PNG', 'JPEG 2000', 'Microsoft Word', 'Adobe InDesign', 'EXIF'],
      answer:
        'Extraction pulls the embedded image object out of the PDF byte for byte, so a photo saved as a JPEG inside the file comes back as the same JPEG at its original pixel size. Rendering instead repaints the whole page at a resolution you choose, which resamples the photo and adds the surrounding text and margins.',
      body: [
        { t: 'p', x: 'People ask for the same thing in two very different ways. "Get me the picture from page 4" can mean *give me a snapshot of page 4*, or it can mean *give me the actual photograph that the designer placed on page 4*. The first is rendering. The second is extraction. Only extraction returns the original pixels.' },
        { t: 'h2', x: 'Rendering versus extracting' },
        {
          t: 'table',
          caption: 'The same photograph, taken out of the same PDF two ways.',
          head: ['', 'Render the page', 'Extract the image'],
          rows: [
            ['What you get', 'A picture of the whole page', 'Just the photo, cropped exactly as it was embedded'],
            ['Pixel dimensions', 'Whatever DPI you chose', 'The original dimensions, whatever they are'],
            ['Quality', 'Resampled once more', 'Byte-for-byte identical to what was embedded'],
            ['Background and text', 'Included', 'Excluded'],
            ['Works on vector charts', 'Yes', 'No, there is no image object to extract'],
            ['Typical use', 'Previews, slides, printing a page', 'Recovering a photo, reusing a logo, archiving a scan'],
          ],
        },
        { t: 'h2', x: 'What is actually stored inside a PDF' },
        { t: 'p', x: 'Every picture in a PDF is an object with a compression filter attached, and that filter tells you what you can get back:' },
        {
          t: 'ul',
          items: [
            '**DCTDecode** — the object holds JPEG data verbatim. Extraction is a straight copy: the JPEG that comes out is the JPEG that went in, with zero additional loss.',
            '**FlateDecode** — raw pixels compressed losslessly. These come out best as PNG, and they are exactly as sharp as the day they were placed.',
            '**JPXDecode** — JPEG 2000, common in scanned archives and some Mac-created PDFs. Fewer editors open it, so converting to PNG or TIFF on the way out is usually sensible.',
            '**CCITTFaxDecode** and **JBIG2Decode** — one-bit black-and-white scans, the classic output of a fax machine or a document scanner in text mode. Tiny files, no greys.',
            '**Inline images** — small graphics written directly into the page content stream rather than stored as separate objects. Some extractors skip these entirely.',
          ],
        },
        { t: 'h2', x: 'Extract images in your browser' },
        {
          t: 'steps',
          items: [
            { h: 'Open the file', x: 'Drop the PDF onto the [PDF to JPG tool](/tools/pdf-to-jpg) and switch it to image extraction rather than page rendering.' },
            { h: 'Let it scan the objects', x: 'The tool walks every page and lists the image objects it finds, with the pixel size and format of each. A page can hold one image or fifty.' },
            { h: 'Check the dimensions before you take anything', x: 'A logo listed as 180 × 60 px is a small logo, no matter how big it looks on the page. That number tells you immediately whether the image is worth extracting.' },
            { h: 'Select what you want', x: 'Tick individual images, or take everything on a page. Decorative rules, gradient strips and repeated header logos are usually noise you can skip.' },
            { h: 'Download', x: 'Single images download directly; a selection downloads as a ZIP, named by page and object so you can tell them apart.' },
          ],
        },
        { t: 'cta', tool: 'pdf-to-jpg', x: 'Extract embedded images or render whole pages, both in the browser and both free.' },
        { t: 'h2', x: 'The command-line way' },
        { t: 'p', x: 'Poppler ships `pdfimages`, which is the reference implementation for this job and is worth knowing if you handle PDFs in bulk. Start by listing what is in the file before extracting anything.' },
        { t: 'code', x: '# List every image: page, dimensions, colour space, filter, DPI as placed\npdfimages -list brochure.pdf\n\n# Extract everything in its native format (JPEG stays JPEG, rest becomes PNG/TIFF)\npdfimages -all brochure.pdf out/img\n\n# Only pages 2 to 4\npdfimages -all -f 2 -l 4 brochure.pdf out/img' },
        { t: 'p', x: 'The `-list` output includes an x-ppi and y-ppi column, which tells you the effective resolution of each image *as it appears on the page*. An image listed at 72 ppi has been stretched and will print softly no matter what you do to it afterwards.' },
        { t: 'h2', x: 'Why an extracted image is sometimes disappointing' },
        { t: 'p', x: 'Extraction returns the original bytes, but "original" means whatever was stored at the moment the PDF was created, not whatever the photographer shot. Four things commonly happen before that point:' },
        {
          t: 'ul',
          items: [
            '**The authoring app downsampled it.** Microsoft Word compresses inserted pictures by default, and Acrobat presets such as "Reduce File Size" resample images down to around 150 ppi. That decision is baked in and cannot be undone.',
            '**The image is scaled up on the page.** A 600 × 400 photo stretched across a full A4 width is being displayed at roughly 70 ppi. It looks fine on screen and falls apart on paper.',
            '**It was split into tiles.** Some export pipelines slice one photograph into horizontal strips. You get six images that must be reassembled in order.',
            '**The transparency lives in a separate object.** A cut-out image is stored as the picture plus an **SMask**, a greyscale alpha channel. Extract only the picture and you get a rectangle with the background back.',
          ],
        },
        { t: 'warn', x: 'If an extracted photo comes back as a colour negative or with wildly wrong colours, it was stored in CMYK or with a Decode array applied. Open it in an editor and convert to RGB, or render that page instead, which applies the colour conversion for you.' },
        { t: 'h2', x: 'When extraction cannot help' },
        { t: 'p', x: 'Charts, logos and diagrams built in Illustrator or exported from a spreadsheet are usually **vector art**: paths and fills, not pixels. There is no image object to extract, so `pdfimages` finds nothing on a page that visibly contains a chart. Render that page at 300 or 600 DPI instead, or crop it afterwards. Conversely, a scanned document is the opposite case: the entire page is one giant image, so extracting it gives you the full sheet including the margins.' },
        { t: 'h2', x: 'Before you reuse anything' },
        { t: 'note', x: 'Extracted images frequently carry their original EXIF block, including camera model, timestamps and sometimes GPS coordinates. That is useful when you are recovering your own archive and a problem when you are republishing someone else’s file. Strip it first — see [removing metadata from a PDF](/blog/pdf-privacy/remove-metadata-from-pdf) for the same idea applied to the document itself.' },
        { t: 'p', x: 'Being able to pull an image out of a document does not grant you a licence to use it. Stock photos, press images and figures from journals are routinely embedded in PDFs under terms that cover that one publication only.' },
        { t: 'p', x: 'Once you have the images you want, you can [rebuild them into a clean PDF](/tools/jpg-to-pdf), or read up on [the resolution you need for printing](/blog/pdf-images/best-image-format-for-print) before committing them to paper.' },
      ],
      faqs: [
        { q: 'What is the difference between extracting and converting a PDF to images?', a: 'Converting renders each page into a new picture at a resolution you choose. Extracting copies out the image objects that were already inside the file, at their original pixel dimensions and with no additional compression.' },
        { q: 'Why did extraction find no images in my PDF?', a: 'The page is probably vector art or live text rather than a photograph. Charts, logos and typeset text are drawn as paths and glyphs, so there is no image object to pull out. Render the page instead.' },
        { q: 'Can I get a higher-resolution image than the one in the PDF?', a: 'No. The embedded image is the highest resolution that exists in the file. Rendering the page at 600 DPI enlarges the same pixels; it does not recover detail that was discarded when the PDF was made.' },
        { q: 'Why does one photo come out as several image files?', a: 'Some export pipelines tile large images into strips, and cut-out images store their transparency as a separate mask object. Reassemble the strips in order, and recombine the mask as an alpha channel in an editor.' },
        { q: 'Is extracting images from a PDF legal?', a: 'Technically it is just reading the file, but copyright still applies to what you find. Images embedded in reports, journals and brochures are usually licensed for that publication only, so check before republishing.' },
      ],
      relatedTools: ['pdf-to-jpg', 'compress-pdf'],
      relatedPosts: ['pdf-to-jpg', 'best-image-format-for-print', 'remove-metadata-from-pdf'],
    },
    {
      slug: 'pdf-to-png-transparent',
      cluster: 'pdf-images',
      title: 'PNG vs JPG for PDF pages: which should you pick?',
      metaTitle: 'PNG vs JPG for PDF Pages: Which to Pick',
      metaDescription:
        'PNG or JPG for a PDF page? Compare transparency, text sharpness and file size, and see which format suits screenshots, scans, photographs and diagrams best.',
      published: '2026-03-27',
      updated: '2026-08-19',
      readMinutes: 5,
      intent: 'comparison',
      primaryKeyword: 'png vs jpg for pdf pages',
      secondaryKeywords: ['pdf to png transparent background', 'should i use png or jpg', 'png or jpeg for text', 'transparent pdf export'],
      entities: ['PNG', 'JPEG', 'WebP', 'TIFF', 'Adobe Photoshop', 'GIMP', 'sRGB', 'DEFLATE'],
      answer:
        'Choose PNG when the page contains text, tables, line art or screenshots, or when you need a transparent background: it is lossless and keeps letter edges perfectly sharp. Choose JPG when the page is dominated by photographs, where it produces a file roughly three times smaller with no visible difference.',
      body: [
        { t: 'p', x: 'The two formats were designed for different pictures. JPEG was built in 1992 for photographs, where smooth gradients hide the detail it discards. PNG arrived in 1996 for the opposite kind of image: flat colour, hard edges, screenshots, logos and diagrams. A PDF page can be either of those things, which is why there is no single right answer.' },
        { t: 'h2', x: 'The comparison in one table' },
        {
          t: 'table',
          caption: 'PNG and JPG compared for PDF page exports.',
          head: ['', 'PNG', 'JPG'],
          rows: [
            ['Compression', 'Lossless (DEFLATE)', 'Lossy (discrete cosine transform)'],
            ['Text and line edges', 'Pixel-exact, no artefacts', 'Grey halo and blocking, worse at low quality'],
            ['Photographs', 'Faithful but very large', 'Excellent, tiny for the quality'],
            ['Transparency', 'Yes, full 8-bit alpha channel', 'None, transparent areas become white or black'],
            ['Typical A4 text page at 144 DPI', 'About 380 KB', 'About 160 KB at quality 90'],
            ['Typical A4 photo page at 144 DPI', 'About 3.2 MB', 'About 420 KB at quality 90'],
            ['Re-saving repeatedly', 'No degradation ever', 'Degrades a little each save'],
            ['Colour depth', 'Up to 16 bits per channel', '8 bits per channel'],
            ['Universal support', 'Yes', 'Yes'],
          ],
        },
        { t: 'h2', x: 'Text sharpness is the deciding factor' },
        { t: 'p', x: 'JPEG works on 8 × 8 pixel blocks and throws away the high-frequency information inside each one. High frequency is exactly what a letterform is: a hard black-to-white transition in the space of one or two pixels. The encoder cannot represent that cheaply, so it approximates, and the approximation shows up as a faint grey shimmer around every character. On a photograph of a beach, the same behaviour is completely invisible.' },
        { t: 'p', x: 'This gets worse as the resolution drops. A 300 DPI JPG of a page of body text looks fine because each letter is 30 or 40 pixels tall. The same page at 72 DPI, where a letter is 8 pixels tall, is a mess in JPG and still perfectly legible in PNG.' },
        { t: 'tip', x: 'A simple rule that almost always works: if you would call the page a **document**, use PNG. If you would call it a **photo**, use JPG. Mixed pages follow whichever dominates the area.' },
        { t: 'h2', x: 'Transparency' },
        { t: 'p', x: 'JPEG has no alpha channel at all, so a transparent background gets composited onto something opaque — usually white, occasionally black — during export. PNG stores a full 8-bit alpha channel, meaning each pixel can be anywhere from fully opaque to fully clear, with soft anti-aliased edges in between.' },
        { t: 'p', x: 'This matters for the specific job people search for: getting a PDF page out with a transparent background, so a logo or a stamp can sit on top of something else. Two things to know before you try it.' },
        {
          t: 'ul',
          items: [
            'Most PDF pages **have a real white background**. The page paints a white rectangle before it draws anything else, so a transparent render still comes out white. Only PDFs that were authored without a background rectangle — logos, single-object exports, some Illustrator files — render transparent.',
            'Renderers **default to compositing onto white** because that is what a printed page looks like. You need a converter that exposes a transparent-background option to get the alpha channel through.',
          ],
        },
        {
          t: 'steps',
          items: [
            { h: 'Render as PNG', x: 'Open the file in the [PDF to JPG tool](/tools/pdf-to-jpg), choose PNG, and turn on the transparent background option if the page has no painted background of its own.' },
            { h: 'Check the corners', x: 'Open the result in any image viewer that shows a checkerboard for transparency. Solid white corners mean the PDF painted a background, and no export setting will change that.' },
            { h: 'Remove the white if you have to', x: 'In GIMP use **Colors → Color to Alpha** with white as the target. In Photoshop, use the Channels panel or **Select → Color Range**. Both leave a slight fringe on anti-aliased text.' },
            { h: 'Save as PNG-24', x: 'PNG-8 only supports one fully transparent index colour, which produces hard jagged edges. PNG-24 with alpha keeps the soft edges intact.' },
          ],
        },
        { t: 'h2', x: 'Screenshots and scans' },
        { t: 'p', x: 'Screenshots are the strongest case for PNG. A user interface is flat colour, thin one-pixel borders and small text — everything JPEG handles badly. A PNG screenshot is often *smaller* than the JPG, because large areas of identical colour compress extremely well under DEFLATE.' },
        { t: 'p', x: 'Scans go the other way. A scanned page is photographic in nature: paper texture, scanner noise and slight tonal variation everywhere. PNG has to store all of that noise faithfully, so a 300 DPI PNG scan can hit 8 MB per page while a quality-85 JPG of the same scan is 400 KB and looks the same. Scanned archives use JPEG for exactly this reason. If your scans are going into a document, [compressing the PDF](/blog/compress-pdf/how-to-compress-a-pdf) usually just means re-encoding those images.' },
        { t: 'h2', x: 'What about WebP?' },
        { t: 'p', x: 'WebP does both jobs: lossless mode for graphics, lossy mode for photos, and an alpha channel in both. It typically lands 25 to 35 percent smaller than the equivalent PNG or JPG. Every current browser supports it. The catch is everything that is not a browser — older printing workflows, some office suites and a few document management systems still reject it — so use WebP when the destination is the web and PNG or JPG when the destination is anything else.' },
        { t: 'h2', x: 'Quick decision guide' },
        {
          t: 'table',
          head: ['Your page is…', 'Export as'],
          rows: [
            ['Body text, a table or a contract', 'PNG'],
            ['A screenshot of an app or a website', 'PNG'],
            ['A logo or a signature that needs a clear background', 'PNG with alpha'],
            ['A chart, a diagram or line art', 'PNG'],
            ['A photograph, or a page that is mostly one photo', 'JPG, quality 85 to 90'],
            ['A scanned page of a book or a form', 'JPG, quality 85'],
            ['Anything going straight onto a web page', 'WebP, PNG or JPG as a fallback'],
            ['Anything going to a print shop', 'PNG or TIFF at 300 DPI'],
          ],
        },
        { t: 'cta', tool: 'pdf-to-jpg', x: 'Export any PDF page as PNG or JPG, at the resolution you choose, entirely in your browser.' },
        { t: 'note', x: 'Whichever you pick, remember that an exported page image is no longer searchable text — it is pixels. If you need the words back, run the image through [OCR](/blog/ocr-scanned-documents/how-to-ocr-a-scanned-pdf) or keep the original PDF alongside the image.' },
      ],
      faqs: [
        { q: 'Is PNG or JPG better for a PDF page?', a: 'PNG for pages of text, tables, diagrams or screenshots, because it keeps edges pixel-exact. JPG for pages that are mostly photographs, because it is around three times smaller with no visible difference on continuous-tone images.' },
        { q: 'Can I export a PDF page with a transparent background?', a: 'Only if the page does not paint its own background. Most documents draw a white rectangle first, so the export is white regardless of the setting. Logos and single-object PDFs usually do render with transparency.' },
        { q: 'Why does my JPG text look fuzzy?', a: 'JPEG discards high-frequency detail in 8 × 8 blocks, and the hard edges of letters are exactly that detail. The result is a grey halo around characters. Export as PNG, or raise both the quality setting and the resolution.' },
        { q: 'Does PNG lose quality when I save it again?', a: 'No. PNG compression is lossless, so you can open and re-save a PNG any number of times and the pixels stay identical. JPG loses a little detail on every save, which compounds over several rounds.' },
        { q: 'Should I use WebP instead?', a: 'Use WebP when the image is going onto a web page — it is typically 25 to 35 percent smaller than PNG or JPG with an alpha channel in both modes. Stick with PNG or JPG for print shops, office documents and older software.' },
      ],
      relatedTools: ['pdf-to-jpg', 'jpg-to-pdf'],
      relatedPosts: ['pdf-to-jpg', 'best-image-format-for-print', 'extract-images-from-pdf'],
    },
    {
      slug: 'best-image-format-for-print',
      cluster: 'pdf-images',
      title: 'What resolution and format do you need for printing?',
      metaTitle: 'Print Resolution and Format: The 300 DPI Rule',
      metaDescription:
        'How many pixels you need to print sharply: the 300 DPI rule, exact pixel sizes for every paper size, CMYK versus RGB, and why upscaling does not really help.',
      published: '2026-04-30',
      updated: '2026-08-26',
      readMinutes: 8,
      intent: 'informational',
      primaryKeyword: 'what resolution do i need for printing',
      secondaryKeywords: ['300 dpi print size', 'pixel dimensions for a4 print', 'cmyk vs rgb printing', 'best image format for print', 'can you upscale a photo for print'],
      entities: ['DPI', 'PPI', 'CMYK', 'sRGB', 'Adobe RGB', 'TIFF', 'Adobe Photoshop', 'A4', 'Pantone'],
      answer:
        'For anything held in the hand, supply 300 pixels per inch of final print size: 2480 × 3508 px for A4, 2550 × 3300 px for US Letter, 1200 × 1800 px for a 4 × 6 photo. Posters viewed from a metre away are fine at 150 DPI. Upscaling invents pixels and does not add real detail.',
      body: [
        { t: 'p', x: 'The number that matters is not the file size or the megapixel count. It is **pixels divided by inches**: how many pixels land in each inch of the finished print. Everything else follows from that one ratio.' },
        { t: 'h2', x: 'Where 300 DPI comes from' },
        { t: 'p', x: 'It is not a marketing number. Commercial offset printing screens images at around 150 lines per inch, and the long-standing rule in prepress is to supply image data at twice the line screen. 150 × 2 = 300. Below that you start to see the halftone structure; above it the press simply cannot resolve the extra detail, so the file gets bigger for nothing.' },
        { t: 'p', x: 'Home inkjets advertise much larger numbers, like 4800 × 1200 dpi, but those describe ink droplets, not image pixels. It takes many droplets to reproduce one pixel of continuous tone. Feeding an inkjet a 1200 PPI image gains you nothing over 300.' },
        { t: 'h2', x: 'Pixel dimensions by paper size' },
        {
          t: 'table',
          caption: 'Minimum pixel dimensions for common print sizes.',
          head: ['Print size', 'At 150 DPI (draft)', 'At 300 DPI (final)', 'Megapixels at 300'],
          rows: [
            ['4 × 6 in photo', '600 × 900', '1200 × 1800', '2.2 MP'],
            ['5 × 7 in photo', '750 × 1050', '1500 × 2100', '3.2 MP'],
            ['8 × 10 in photo', '1200 × 1500', '2400 × 3000', '7.2 MP'],
            ['A5 (148 × 210 mm)', '874 × 1240', '1748 × 2480', '4.3 MP'],
            ['A4 (210 × 297 mm)', '1240 × 1754', '2480 × 3508', '8.7 MP'],
            ['US Letter (8.5 × 11 in)', '1275 × 1650', '2550 × 3300', '8.4 MP'],
            ['A3 (297 × 420 mm)', '1754 × 2480', '3508 × 4961', '17.4 MP'],
            ['13 × 19 in poster', '1950 × 2850', '3900 × 5700', '22.2 MP'],
          ],
        },
        { t: 'p', x: 'To check any image yourself, divide its pixel width by the width you want to print in inches. A 3000-pixel-wide photo printed 10 inches wide is 300 DPI. The same photo printed 20 inches wide is 150 DPI. Nothing about the file changed; only the size you asked for did.' },
        { t: 'h2', x: 'Viewing distance changes the answer' },
        { t: 'p', x: 'The 300 DPI rule assumes normal reading distance, roughly 30 cm. Human vision resolves about one arcminute, so the further away something is viewed, the coarser it can be without anyone noticing. This is why billboards printed at 15 DPI look perfectly sharp from the road.' },
        {
          t: 'table',
          head: ['Piece', 'Typical viewing distance', 'Practical resolution'],
          rows: [
            ['Business card, book, brochure', '30 cm', '300 DPI'],
            ['Wall poster, exhibition print', '1 to 2 m', '150 DPI'],
            ['Trade-show banner', '2 to 4 m', '100 DPI'],
            ['Building wrap, billboard', '10 m or more', '15 to 30 DPI'],
          ],
        },
        { t: 'h2', x: 'CMYK and RGB' },
        { t: 'p', x: 'Screens emit light and mix red, green and blue. Presses lay ink on paper that reflects it. The two gamuts overlap but are not the same shape, so some colours you see on screen — saturated oranges, vivid cyans, electric blues — cannot be reproduced with process inks. They are converted to the nearest printable colour, which usually reads as duller.' },
        {
          t: 'ul',
          items: [
            '**Home and office printing:** send RGB. Your printer driver handles the conversion and is tuned for its own inks. Converting to CMYK yourself first usually makes things worse.',
            '**Commercial offset printing:** ask the printer what they want. Many modern workflows now prefer RGB with an embedded profile and do the conversion themselves; others want files already in their specific CMYK profile.',
            '**sRGB is the safe default** for anything shared or uploaded. Adobe RGB holds more saturated colours but is misread as dull by software that ignores profiles.',
            '**Rich black:** pure K-only black prints as a slightly washed dark grey on large areas. Print shops typically use a rich black around 60C 40M 40Y 100K for solid backgrounds, while keeping small body text 100K only so it stays sharp.',
          ],
        },
        { t: 'note', x: 'Black text should always be one ink. Text set in a four-colour black shows coloured fringes if the press is even slightly out of registration. This is one of the most common reasons a printed proof looks blurry when the file looked perfect.' },
        { t: 'h2', x: 'Which format to send' },
        {
          t: 'table',
          head: ['Format', 'Use it for', 'Watch out for'],
          rows: [
            ['PDF', 'Complete documents, anything with text', 'Embed all fonts. PDF/X-1a or PDF/X-4 for commercial work.'],
            ['TIFF', 'High-quality photos, scans for reproduction', 'Very large files. Use LZW compression.'],
            ['PNG', 'Logos, screenshots, graphics with transparency', 'RGB only; no CMYK support at all.'],
            ['JPG', 'Photographs, when size matters', 'Export at quality 90 or above. Never re-save repeatedly.'],
            ['SVG / AI / EPS', 'Logos, line art, anything scaled large', 'Vector: resolution-independent, so DPI does not apply.'],
          ],
        },
        { t: 'p', x: 'For a document rather than a single image, PDF beats all of them. It carries text as text, so type prints at the printer’s full resolution rather than at whatever DPI you rasterised to. That is why [saving a web page as a PDF](/blog/save-webpage-as-pdf/save-webpage-as-pdf-chrome) prints far more crisply than screenshotting it.' },
        { t: 'h2', x: 'The upscaling myth' },
        { t: 'p', x: 'Enlarging an image in Photoshop or any other editor does not recover detail. Traditional interpolation — bicubic, Lanczos — examines neighbouring pixels and guesses the values in between. The result has more pixels and exactly the same amount of real information, spread thinner. A 600 × 400 photo resampled to 3000 × 2000 is a soft 600 × 400 photo with a bigger file size.' },
        { t: 'p', x: 'Modern AI upscalers are better at this and can produce a convincing 2× enlargement. But they **invent** plausible detail from a trained model rather than recovering what was there — fine for a decorative background, a serious problem for a product photo or a document scan.' },
        { t: 'warn', x: 'Never upscale text or a scanned document to hit a DPI target. Rescan it at the correct resolution instead. Upscaled type looks visibly soft on paper and [wrecks OCR accuracy](/blog/ocr-scanned-documents/improve-ocr-accuracy), because the character shapes have been smeared by interpolation.' },
        { t: 'h2', x: 'A pre-print checklist' },
        {
          t: 'ol',
          items: [
            'Divide pixel width by intended print width in inches. Aim for 300, accept 200, worry below 150.',
            'Check the real viewing distance before insisting on 300 for a large piece.',
            'Add 3 mm of bleed on every edge if any colour runs to the edge of the paper.',
            'Keep important content at least 5 mm inside the trim line.',
            'Set body text to black ink only, not a four-colour mix.',
            'Embed every font, or convert type to outlines.',
            'Print one page at actual size on your own printer before ordering five hundred.',
          ],
        },
        { t: 'cta', tool: 'pdf-to-jpg', x: 'Need a page as a print-ready image? Render it at 300 DPI rather than screenshotting the screen.' },
        { t: 'p', x: 'If your finished file is now enormous, that is normal for print resolution — but do not compress it before the printer sees it. [Compression](/tools/compress-pdf) is for email and archives, not for the press.' },
      ],
      faqs: [
        { q: 'How many pixels do I need to print an A4 page?', a: 'A4 at 300 DPI is 2480 × 3508 pixels, about 8.7 megapixels. At 150 DPI, acceptable for drafts and internal copies, it is 1240 × 1754 pixels. Below roughly 150 DPI the softness becomes obvious at reading distance.' },
        { q: 'Is 300 DPI always necessary?', a: 'No. 300 DPI assumes the piece is held at reading distance. A poster viewed from a metre away looks sharp at 150 DPI, a trade-show banner at 100, and a billboard at 15 to 30. Match the resolution to the viewing distance.' },
        { q: 'Should I convert my images to CMYK before printing?', a: 'For home and office printers, no — send RGB and let the driver convert. For commercial offset printing, ask the printer: many now prefer RGB with an embedded profile, while others require a specific CMYK profile.' },
        { q: 'Can I make a low-resolution image printable by upscaling it?', a: 'Not really. Interpolation adds pixels without adding information, and AI upscalers invent plausible detail rather than recovering the original. Both are acceptable for decorative images and unsuitable for documents, product photos or evidence.' },
        { q: 'What is the difference between DPI and PPI?', a: 'PPI describes pixels in a digital image; DPI describes ink dots a printer lays down. They are used interchangeably in everyday practice, but a 4800 dpi inkjet still only needs a 300 PPI image, because many dots make up one pixel.' },
      ],
      relatedTools: ['pdf-to-jpg', 'jpg-to-pdf'],
      relatedPosts: ['pdf-to-jpg', 'pdf-to-png-transparent', 'print-web-page-to-pdf-vs-printer'],
    },
  ],
}
