import type { Cluster } from '../types'

export const printWebPages: Cluster = {
  slug: 'print-web-pages',
  name: 'Printing web pages',
  title: 'How to print any web page without ads, menus or wasted paper',
  metaTitle: 'How to Print a Web Page Without Ads (2026 Guide)',
  metaDescription:
    'Print any web page without ads, sidebars or navigation. Reader mode, print preview, browser print settings and a free printer-friendly tool that runs in your browser.',
  intro:
    'A web page is built for scrolling, not for paper. Hitting Ctrl+P usually gives you the article plus three ad slots, a cookie banner, a newsletter box and a comment wall spread over nine sheets. These guides cover every reliable way to strip that clutter first: Chrome and Safari reader modes, browser print settings, print preview tricks, and a free browser-based cleaner that lets you delete anything left over before you print.',
  answer:
    'To print a web page without ads, open it in a printer-friendly tool or your browser Reader mode first, then print. This removes navigation, ads and sidebars and typically cuts a nine-page printout to two or three pages while keeping the article text and images intact.',
  primaryKeyword: 'how to print a web page without ads',
  entities: ['Google Chrome', 'Safari Reader', 'Firefox Reader View', 'Microsoft Edge', 'Ctrl+P', 'print preview', 'CSS print stylesheet', 'Readability'],
  icon: '⎙',
  tools: ['pdf-reader', 'html-to-pdf', 'jpg-to-pdf'],
  posts: [
    {
      slug: 'print-web-page-without-ads',
      cluster: 'print-web-pages',
      title: 'How to print a web page without ads',
      metaTitle: 'How to Print a Web Page Without Ads — 5 Free Methods',
      metaDescription:
        'Five ways to print a web page without ads, banners or sidebars: printer-friendly tools, Chrome reader mode, print preview, browser extensions and CSS tricks.',
      published: '2026-01-14',
      updated: '2026-08-28',
      readMinutes: 6,
      intent: 'howto',
      primaryKeyword: 'how to print a web page without ads',
      secondaryKeywords: ['print webpage without ads', 'printer friendly version of website', 'remove ads before printing', 'print article only', 'print without sidebar'],
      entities: ['Google Chrome', 'Safari', 'Firefox', 'Microsoft Edge', 'Adobe Acrobat', 'Readability', 'Ctrl+P', 'Cmd+P'],
      answer:
        'Paste the page URL into a printer-friendly tool, or turn on your browser Reader mode, then press Ctrl+P. Both strip ads, menus and sidebars before the page reaches your printer, usually reducing a long article from eight or nine sheets to two or three.',
      body: [
        { t: 'p', x: 'You found a recipe, a receipt or a long article and you want it on paper. You press **Ctrl+P** (or **Cmd+P** on a Mac) and the preview shows nine pages: a giant header image, a navigation bar, two ad slots, a "related stories" grid and, somewhere in the middle, the 600 words you actually wanted.' },
        { t: 'p', x: 'The problem is that web pages are laid out for a scrolling screen. Unless the publisher wrote a dedicated print stylesheet, and most did not, your printer receives the whole layout. Here are five ways to fix that, from fastest to most technical.' },
        { t: 'h2', x: 'Method 1: Use a printer-friendly tool (fastest)' },
        { t: 'p', x: 'A printer-friendly tool fetches the page, runs a content-extraction algorithm over it, and shows you just the article. You then delete anything else you do not want and print the result.' },
        {
          t: 'steps',
          items: [
            { h: 'Copy the page address', x: 'Click the address bar and copy the full URL, starting with https://.' },
            { h: 'Open the cleaner', x: 'Go to the [web page printer](/print) and paste the URL into the box.' },
            { h: 'Delete what is left', x: 'Delete mode is on by default. Hover any paragraph, image or table and click to remove it. Click and drag to sweep several blocks at once. Ctrl+Z undoes anything.' },
            { h: 'Set the text and image size', x: 'Open the Style menu to choose a text size, shrink images to half-page, or remove images entirely to save ink.' },
            { h: 'Print or save', x: 'Press Print for a crisp, text-based printout, or Download PDF to keep a copy.' },
          ],
        },
        { t: 'cta', tool: 'pdf-reader', x: 'Prefer to work with a file you already have? Open it in the free browser PDF reader.' },
        { t: 'h2', x: 'Method 2: Turn on Reader mode first' },
        { t: 'p', x: 'Every major browser except Chrome ships a reader mode that strips a page down to text and images. Turn it on, then print from inside it.' },
        {
          t: 'table',
          caption: 'Reader mode by browser, as of 2026.',
          head: ['Browser', 'How to open Reader', 'Notes'],
          rows: [
            ['Safari (macOS/iOS)', 'Click the ☰ icon at the left of the address bar, or press ⌃⌘R', 'Best of the built-in readers. Lets you pick a font and background before printing.'],
            ['Firefox', 'Click the page icon in the address bar, or press F9', 'Reader View has a built-in print button.'],
            ['Microsoft Edge', 'Click "Immersive Reader" in the address bar, or press F9', 'Also offers Read Aloud and picture dictionary.'],
            ['Google Chrome', 'No stable reader mode', 'Use a printer-friendly tool or an extension instead.'],
          ],
        },
        { t: 'warn', x: 'Reader mode fails on pages that are not articles: dashboards, order confirmations, forum threads, search results and anything behind a heavy JavaScript app. For those, use Method 1 or Method 3.' },
        { t: 'h2', x: 'Method 3: Fix it in the print dialog' },
        { t: 'p', x: 'The print dialog itself has settings that remove a surprising amount of junk. Press Ctrl+P and look for **More settings**.' },
        {
          t: 'ul',
          items: [
            '**Background graphics** — leave this off. It is off by default and keeps you from printing solid colour blocks and hero images.',
            '**Headers and footers** — turn off to remove the page title, URL, date and page number your browser adds.',
            '**Scale** — drop to 80 or 90 percent to fit more text per sheet without making it unreadable.',
            '**Pages** — do not print the whole document. Look at the preview, find the two pages that hold your content, and enter a range like `2-3`.',
            '**Print using system dialog** — on Chrome this opens your operating system dialog, which exposes two-sided printing and draft quality.',
          ],
        },
        { t: 'tip', x: 'Selecting the text you want before pressing Ctrl+P, then choosing **Selection only** in the print dialog, is the single fastest trick in this article. It works in Chrome, Firefox and Edge.' },
        { t: 'h2', x: 'Method 4: A browser extension or bookmarklet' },
        { t: 'p', x: 'If you print pages often, a one-click button beats copying URLs. A bookmarklet is a bookmark whose address is a small piece of JavaScript; click it on any page and it opens that page in the cleaner. There is a ready-made one on the [extensions page](/extensions/chrome) that you can drag to your bookmarks bar. No install, no permissions, works in every browser.' },
        { t: 'h2', x: 'Method 5: Hide elements yourself with DevTools' },
        { t: 'p', x: 'For a page that resists everything else, you can delete elements by hand. Right-click the ad or sidebar, choose **Inspect**, then press Delete on the highlighted node in the Elements panel. Repeat for each unwanted block, then print. Changes disappear on reload, so nothing is permanent.' },
        { t: 'code', x: "// Or paste this in the DevTools Console to hide common clutter:\ndocument.querySelectorAll('nav, aside, footer, iframe, [class*=\"ad\"], [class*=\"promo\"]')\n  .forEach(el => el.remove());" },
        { t: 'h2', x: 'Which method should you use?' },
        {
          t: 'table',
          head: ['If you want to…', 'Use'],
          rows: [
            ['Print one article quickly, with control over what stays', 'A printer-friendly tool (Method 1)'],
            ['Print several articles from the same site', 'Reader mode (Method 2)'],
            ['Print two pages out of a twelve-page document', 'Print dialog page range (Method 3)'],
            ['Print pages every day', 'Extension or bookmarklet (Method 4)'],
            ['Print a dashboard, invoice or web app screen', 'DevTools (Method 5) or a full-page screenshot'],
          ],
        },
        { t: 'p', x: 'Once the page is clean, you might also want to [save it as a PDF instead of printing](/blog/save-webpage-as-pdf/save-webpage-as-pdf-chrome), or [cut the ink cost](/blog/save-paper-ink/save-ink-when-printing) further.' },
      ],
      faqs: [
        { q: 'How do I print only the article and not the whole web page?', a: 'Select the article text with your mouse, press Ctrl+P, and choose "Selection only" in the print dialog. If the site does not support that, paste the URL into a printer-friendly tool, which extracts the article automatically.' },
        { q: 'Why does my printout have big blank areas?', a: 'Blank areas usually come from images or ad slots that failed to load, or from CSS floats that leave gaps on paper. Removing images in the print settings, or using a printer-friendly view, closes those gaps.' },
        { q: 'Can I print a web page without images?', a: 'Yes. In a printer-friendly tool, set images to "None" in the Style menu. In your browser, turning off "Background graphics" removes decorative images but not inline article photos, so a cleaner is more thorough.' },
        { q: 'Is there a printer-friendly version of every website?', a: 'No. Some publishers ship a dedicated print stylesheet, but most do not, which is why the same article can print as three tidy pages on one site and nine messy ones on another. A cleaner gives every site the same treatment.' },
        { q: 'Does printing a web page cost anything?', a: 'The browser method is free. Browser-based cleaning tools like this one are also free and run entirely on your computer, so there is no upload, no account and no per-page charge.' },
      ],
      relatedTools: ['pdf-reader', 'html-to-pdf'],
      relatedPosts: ['print-selected-text-only', 'save-webpage-as-pdf-chrome', 'print-recipe-without-ads'],
    },
    {
      slug: 'print-selected-text-only',
      cluster: 'print-web-pages',
      title: 'How to print only the part of a page you selected',
      metaTitle: 'Print Only Selected Text From a Web Page',
      metaDescription:
        'Print just the text you highlighted instead of the whole page. Selection-only printing in Chrome, Firefox, Edge and Safari, plus what to do when it fails.',
      published: '2026-02-03',
      updated: '2026-07-19',
      readMinutes: 4,
      intent: 'howto',
      primaryKeyword: 'print selected text only',
      secondaryKeywords: ['print selection chrome', 'print only highlighted text', 'print part of a web page', 'print selection safari'],
      entities: ['Google Chrome', 'Mozilla Firefox', 'Microsoft Edge', 'Safari', 'Ctrl+P', 'print dialog'],
      answer:
        'Highlight the text you want, press Ctrl+P (Cmd+P on Mac), and choose "Selection only" under the pages option in the print dialog. Chrome, Firefox and Edge all support this. Safari uses "Print Selected Text" from the File menu after you select.',
      body: [
        { t: 'p', x: 'Printing a selection is the fastest way to get one paragraph, one table or one recipe onto paper without touching anything else on the page. Every desktop browser supports it, but each one hides the setting somewhere different.' },
        { t: 'h2', x: 'Chrome, Edge and other Chromium browsers' },
        {
          t: 'steps',
          items: [
            { h: 'Select the content', x: 'Click and drag across the text you want. Include the heading if you want it on the printout.' },
            { h: 'Open the print dialog', x: 'Press Ctrl+P on Windows or Cmd+P on macOS. Do not right-click and choose Print, which prints the whole page in some builds.' },
            { h: 'Find the Pages dropdown', x: 'Under **Pages**, open the dropdown that says "All" and choose **Selection only**.' },
            { h: 'Check the preview', x: 'The preview should now show just your selection. If it still shows everything, your selection was lost when the dialog opened — close it, reselect, and try again.' },
            { h: 'Print', x: 'Choose your printer, or "Save as PDF" as the destination, and confirm.' },
          ],
        },
        { t: 'h2', x: 'Firefox' },
        { t: 'p', x: 'Firefox puts the same option under **Print** → **More settings** → **Print** → **Selection**. Firefox also remembers the choice for the next print job in the same session, which is handy if you are printing several selections in a row.' },
        { t: 'h2', x: 'Safari on macOS' },
        { t: 'p', x: 'Safari does not offer a selection radio button in the print sheet. Instead, select the text, then use **File → Print Selected Text**. If that menu item is greyed out, click once inside the page body first so Safari knows which frame the selection belongs to.' },
        { t: 'h2', x: 'When selection printing does not work' },
        { t: 'p', x: 'A few situations break it:' },
        {
          t: 'ul',
          items: [
            'The content sits inside an **iframe**, such as an embedded document viewer or a comment widget. Browsers treat that as a separate page. Open the iframe in its own tab first (right-click → "This Frame" → "Open Frame in New Tab" in Firefox).',
            'The page uses **CSS that disables selection** (`user-select: none`). Reader mode or a printer-friendly view sidesteps it.',
            'The selection spans a **table that gets clipped**. Printers cut wide tables at the page edge. Switch to landscape orientation, or reduce the scale to 70 percent.',
            'The site is a **single-page app** that re-renders when the dialog opens, wiping the selection.',
          ],
        },
        { t: 'tip', x: 'For any of the above, paste the URL into the [web page printer](/print), delete everything except the block you want, and print that. It takes about ten seconds and works regardless of how the site is built.' },
        { t: 'cta', tool: 'html-to-pdf', x: 'Already have the content in an HTML file? Convert it straight to PDF.' },
        { t: 'h2', x: 'Printing a selection to PDF' },
        { t: 'p', x: 'The same trick works for PDFs: choose **Save as PDF** as your printer destination instead of a physical printer. You get a one-page PDF containing only the selection, which is ideal for filing receipts or quoting a source in a report. See [saving a web page as a PDF](/blog/save-webpage-as-pdf/save-webpage-as-pdf-chrome) for the full walkthrough.' },
      ],
      faqs: [
        { q: 'Why is "Selection only" missing from my print dialog?', a: 'The option only appears when the browser detects an active text selection at the moment the dialog opens. If you selected text and then clicked elsewhere, the selection was cleared. Reselect and press Ctrl+P without clicking anything in between.' },
        { q: 'Can I print a selection on a phone?', a: 'Mobile browsers do not offer selection printing. Instead, copy the text, paste it into a notes app or into a printer-friendly tool paste box, and print from there.' },
        { q: 'Does printing a selection keep the formatting?', a: 'Mostly. Headings, bold text, links and lists survive. Complex multi-column layouts and floated images often reflow, which is usually an improvement on paper.' },
        { q: 'How do I print two separate paragraphs from different parts of a page?', a: 'Hold Ctrl (Cmd on Mac) while dragging to build a multi-part selection in Firefox. Chrome does not support discontinuous selections, so paste the URL into a cleaner and delete the paragraphs you do not want instead.' },
      ],
      relatedTools: ['html-to-pdf', 'pdf-reader'],
      relatedPosts: ['print-web-page-without-ads', 'fix-web-page-printing-problems', 'save-webpage-as-pdf-chrome'],
    },
    {
      slug: 'fix-web-page-printing-problems',
      cluster: 'print-web-pages',
      title: 'Web page printing problems and how to fix them',
      metaTitle: 'Web Page Won’t Print Correctly? 12 Fixes',
      metaDescription:
        'Cut-off text, blank pages, missing images, tiny fonts and wasted sheets. Twelve common web page printing problems with a fix for each, in every major browser.',
      published: '2026-03-11',
      updated: '2026-08-05',
      readMinutes: 7,
      intent: 'troubleshooting',
      primaryKeyword: 'web page not printing correctly',
      secondaryKeywords: ['printout cut off on right side', 'web page prints blank pages', 'images not printing from website', 'print preview looks wrong'],
      entities: ['Google Chrome', 'Safari', 'Firefox', 'print preview', 'CSS print stylesheet', 'landscape orientation', 'page scaling'],
      answer:
        'Most web page printing problems come from three causes: the page is wider than the paper, background graphics are disabled, or the site has no print stylesheet. Fix them by switching to landscape, lowering the scale to 80 percent, enabling background graphics, or printing through a printer-friendly view.',
      body: [
        { t: 'p', x: 'Print preview is the diagnostic tool here. Almost every problem below is visible before you waste a sheet, so always look at the preview first.' },
        { t: 'h2', x: 'Text is cut off on the right side' },
        { t: 'p', x: 'The page layout is wider than your paper. Three fixes, in order of preference: switch **Layout** to Landscape; reduce **Scale** to 80 or 70 percent; or use a printer-friendly view, which reflows the text to the paper width instead of cropping it. Wide data tables almost always need landscape.' },
        { t: 'h2', x: 'Pages print blank, or mostly blank' },
        { t: 'p', x: 'Usually the content is inside a scrolling container or an iframe that the browser does not paginate. It can also happen when a site hides its content behind a `@media print { display: none }` rule, which some publishers use to push you towards a paid print service. A cleaner extracts the text from the page source, so it prints regardless.' },
        { t: 'h2', x: 'Images are missing from the printout' },
        { t: 'p', x: 'Two separate causes:' },
        {
          t: 'ul',
          items: [
            '**Background graphics are off.** If the image is a CSS background rather than an `<img>` tag, it will not print until you tick "Background graphics" in More settings. This also brings back colour blocks, so expect more ink.',
            '**Lazy loading.** Images below the fold never loaded because you never scrolled there. Scroll the whole page to the bottom before printing so every image is fetched.',
          ],
        },
        { t: 'h2', x: 'Everything prints in a tiny font' },
        { t: 'p', x: 'The site set a small print font size, or your scale is stuck below 100 percent from a previous job. Reset Scale to Default, then use a printer-friendly view where you can set text to Large or XL explicitly.' },
        { t: 'h2', x: 'Nine pages for a 600-word article' },
        { t: 'p', x: 'This is the classic complaint and it is what printer-friendly tools exist for. See [how to print a web page without ads](/blog/print-web-pages/print-web-page-without-ads) for the full method. In the browser alone, the quickest partial fix is to look at the preview, identify the two or three pages holding your content, and print only that range.' },
        { t: 'h2', x: 'Links print as unreadable blue underlined text' },
        { t: 'p', x: 'On paper, a link is just decoration unless the URL is visible. In a printer-friendly view you can choose to strip link styling entirely, or to print each URL in brackets after the link text so a reader can type it in. The second option is useful for reference material and academic printouts.' },
        { t: 'h2', x: 'Headers and footers add junk to every page' },
        { t: 'p', x: 'Your browser, not the site, adds the page title, URL, date and page numbers. Turn off **Headers and footers** in More settings. Note that this also removes page numbers, so for a long document you may prefer to keep them, or [add proper page numbers to a PDF](/blog/watermark-page-numbers/add-page-numbers-to-pdf) instead.' },
        { t: 'h2', x: 'The print dialog opens then immediately closes' },
        { t: 'p', x: 'A script on the page is calling `window.print()` and then navigating. Save the page first (Ctrl+S, "Web page, HTML only"), open the saved file, and print from there. Or paste the URL into a cleaner, which never runs the page scripts.' },
        { t: 'h2', x: 'A table splits awkwardly across pages' },
        { t: 'p', x: 'Rows break mid-cell because the browser has nowhere better to split. Landscape orientation plus a scale reduction usually fits the table on one page. If it is genuinely long, converting to a PDF and then [splitting by page range](/blog/split-pdf/split-pdf-into-pages) gives you cleaner control.' },
        { t: 'h2', x: 'Colours look wrong or too dark' },
        { t: 'p', x: 'Screens are backlit, paper is not, so mid-grey text on a white screen becomes muddy on paper. Print in black and white (greyscale) for text documents, which is also faster and cheaper. See [saving ink](/blog/save-paper-ink/save-ink-when-printing).' },
        { t: 'h2', x: 'A quick checklist' },
        {
          t: 'ol',
          items: [
            'Open print preview before anything else.',
            'Scroll the whole page first so lazy images load.',
            'Turn off headers and footers.',
            'Try landscape for anything with a table.',
            'Set scale to 80 percent as a first attempt at fitting more per page.',
            'If the preview is still a mess, stop and use a printer-friendly view.',
          ],
        },
        { t: 'cta', tool: 'pdf-reader', x: 'Got a PDF that prints badly? Open it in the reader and check the page size first.' },
      ],
      faqs: [
        { q: 'Why does my web page print differently than it looks on screen?', a: 'Browsers apply a separate print stylesheet, so colours, columns and sizes can all change. Print preview shows the real result. Sites that never tested their print stylesheet produce the worst mismatches.' },
        { q: 'How do I stop a web page from printing extra blank pages at the end?', a: 'A trailing element such as a tall footer or an empty container pushes an extra page. Set the print range to exclude the last page, or delete the footer in a printer-friendly view before printing.' },
        { q: 'Why is my printout missing the last few lines of text?', a: 'The content sits inside a fixed-height scrolling box, so only the visible portion prints. Extract the text with a printer-friendly tool, which ignores the container height.' },
        { q: 'Can I make a web page print in black and white only?', a: 'Yes. Choose greyscale or "Black and white" in your printer settings, not the browser. On some printers this is under "Color" in the system print dialog.' },
      ],
      relatedTools: ['pdf-reader', 'html-to-pdf'],
      relatedPosts: ['print-web-page-without-ads', 'print-selected-text-only', 'save-ink-when-printing'],
    },
    {
      slug: 'print-web-page-to-pdf-vs-printer',
      cluster: 'print-web-pages',
      title: 'Print to paper or save as PDF? How to decide',
      metaTitle: 'Print to Paper vs Save as PDF: Which to Choose',
      metaDescription:
        'When to print a web page on paper and when to save it as a PDF instead. Cost, searchability, archiving, legal records and sharing compared side by side.',
      published: '2026-04-22',
      updated: '2026-06-30',
      readMinutes: 5,
      intent: 'comparison',
      primaryKeyword: 'print to pdf vs print to paper',
      secondaryKeywords: ['should i save as pdf or print', 'pdf vs paper archiving', 'save webpage for records', 'digital vs paper records'],
      entities: ['PDF', 'PDF/A', 'Adobe Acrobat', 'Google Drive', 'Microsoft Print to PDF', 'archiving'],
      answer:
        'Save as PDF when you need to search, share, archive or keep a dated record. Print on paper when you need to annotate by hand, read away from a screen, or produce something for a physical file. A PDF costs nothing, is searchable, and can always be printed later.',
      body: [
        { t: 'p', x: 'Both options come from the same print dialog, so the decision is really about what happens to the document afterwards.' },
        {
          t: 'table',
          caption: 'Paper and PDF compared for common tasks.',
          head: ['Need', 'Paper', 'PDF'],
          rows: [
            ['Cost per copy', 'Ink plus paper, roughly 3-8 cents a page', 'Free'],
            ['Search the text later', 'No', 'Yes, if the text layer is intact'],
            ['Prove when you saved it', 'Only by hand-dating it', 'File metadata carries a creation date'],
            ['Annotate by hand', 'Excellent', 'Needs a tablet or a PDF annotator'],
            ['Share with someone remote', 'Scan or post it', 'Attach and send'],
            ['Survive twenty years', 'Fades, but needs no software', 'Very good, use PDF/A for archives'],
            ['Read without a device', 'Yes', 'No'],
            ['Bulk storage', 'Filing cabinets', 'Megabytes'],
          ],
        },
        { t: 'h2', x: 'Save as PDF when…' },
        {
          t: 'ul',
          items: [
            'You are keeping a **receipt, order confirmation or booking**. You will want to search it later by order number.',
            'You are collecting **research or references**. A folder of PDFs is searchable; a stack of paper is not.',
            'You need a **record of what a page said on a given date** — a price, a policy, a listing. The file metadata carries the date.',
            'You are **sharing with someone else**. Email an attachment instead of scanning.',
            'You might need **several copies** later.',
          ],
        },
        { t: 'h2', x: 'Print on paper when…' },
        {
          t: 'ul',
          items: [
            'You need to **write on it**: a recipe you follow at the counter, a form to fill by hand, a checklist for a site visit.',
            'You are **reading something long**. Comprehension and recall are measurably better on paper for dense material.',
            'Someone requires a **physical copy**: a boarding pass, a proof of address, a document for an office that will not take email.',
            'You want to **step away from screens**.',
          ],
        },
        { t: 'h2', x: 'The best of both: clean once, output twice' },
        { t: 'p', x: 'The clutter problem is identical for both destinations. A nine-page printout is also a nine-page PDF with ads baked into it. Clean the page first, then decide the output:' },
        {
          t: 'steps',
          items: [
            { h: 'Clean the page', x: 'Paste the URL into the [web page printer](/print) and delete anything you do not need.' },
            { h: 'For paper', x: 'Press **Print**. Text stays crisp and selectable because your browser renders the real text.' },
            { h: 'For a file', x: 'Press **Download PDF**, or choose "Save as PDF" as the destination in the print dialog for a smaller, searchable file.' },
            { h: 'For a message or slide', x: 'Press **Screenshot** to get a PNG of the cleaned page.' },
          ],
        },
        { t: 'note', x: 'Printing to PDF through the browser print dialog keeps the text selectable and produces a small file. Exporting a rendered image of the page produces a picture of the text: it looks identical but cannot be searched. Prefer the print dialog when searchability matters, and use [OCR](/blog/ocr-scanned-documents/how-to-ocr-a-scanned-pdf) if you end up with an image-only file.' },
        { t: 'h2', x: 'A note on archiving' },
        { t: 'p', x: 'For documents you need to keep for years, PDF/A is the archival flavour: it embeds every font and forbids external dependencies, so the file renders the same in 2046 as it does today. Ordinary PDFs are usually fine, but if the document is legally or historically important, converting to PDF/A is cheap insurance. Either way, [strip the metadata](/blog/pdf-privacy/remove-metadata-from-pdf) before sharing anything you did not author.' },
        { t: 'cta', tool: 'compress-pdf', x: 'Archiving a lot of files? Compress them first so the folder stays manageable.' },
      ],
      faqs: [
        { q: 'Is a PDF of a web page legally valid as proof?', a: 'It depends on the jurisdiction and the purpose. A self-saved PDF shows what you saw, but it is easy to edit, so it carries less weight than a notarised capture or a third-party archiving service. For anything contentious, use a timestamped archiving service as well.' },
        { q: 'Does saving as PDF keep the links clickable?', a: 'Yes, when you print to PDF through the browser dialog. Links become clickable annotations in the PDF. Image-based exports lose them.' },
        { q: 'Which uses less storage, PDF or a screenshot?', a: 'A text-based PDF is far smaller, often ten to fifty times smaller than a full-page PNG screenshot of the same article, because it stores characters rather than pixels.' },
        { q: 'Can I print a PDF later exactly as it looks now?', a: 'Yes, that is the format’s purpose. As long as the fonts are embedded, the PDF prints identically on any printer and any operating system.' },
      ],
      relatedTools: ['compress-pdf', 'pdf-to-text'],
      relatedPosts: ['save-webpage-as-pdf-chrome', 'print-web-page-without-ads', 'reduce-pdf-file-size-for-email'],
    },
  ],
}
