import type { Cluster } from '../types'

export const printRecipes: Cluster = {
  slug: 'print-recipes',
  name: 'Printing recipes',
  title: 'How to print recipes without the life story, the ads or the ink bill',
  metaTitle: 'How to Print a Recipe Without the Ads',
  metaDescription:
    'Print any recipe as one clean page: skip the life story and the ads, drop the photos to save ink, and build a kitchen binder and meal plan that get used.',
  intro:
    'A recipe is roughly 300 words of ingredients and method. The page it lives on is usually 2,000 words of memoir, eleven photographs, a video player, three ad slots and a comment section, printing as seven or eight sheets. These guides cover getting the recipe alone onto one page, deciding which pictures are worth the ink, and turning a pile of printouts into a binder and a weekly meal plan that survive a working kitchen.',
  answer:
    'To print a recipe cleanly, use the site\'s own Print Recipe button if the recipe sits in a recipe card, since it opens a stripped-down version. If there is no button, paste the page address into a printer-friendly tool, delete the story and the photos, and print the result as one page.',
  primaryKeyword: 'how to print a recipe without ads',
  entities: ['WP Recipe Maker', 'Tasty Recipes', 'Schema.org Recipe', 'Google Chrome', 'Safari Reader', 'Pinterest', 'Avery', 'Ctrl+P'],
  icon: '🍳',
  tools: ['html-to-pdf', 'merge-pdf', 'compress-pdf', 'pdf-reader'],
  posts: [
    {
      slug: 'print-recipe-without-ads',
      cluster: 'print-recipes',
      title: 'How to print a recipe without the life story and ads',
      metaTitle: 'Print a Recipe Without the Ads or Story',
      metaDescription:
        'Get the ingredients and method onto one clean page. Recipe card print buttons, jump-to-recipe links, reader mode and a cleaner that works on any food blog.',
      published: '2026-01-31',
      updated: '2026-08-21',
      readMinutes: 6,
      intent: 'howto',
      primaryKeyword: 'how to print a recipe without ads',
      secondaryKeywords: ['print recipe only', 'print recipe without story', 'printable recipe from blog', 'food blog print button', 'recipe card print'],
      entities: ['WP Recipe Maker', 'Tasty Recipes', 'Schema.org Recipe', 'Google Chrome', 'Safari Reader', 'Firefox Reader View', 'Ctrl+P', 'Pinterest'],
      answer:
        'Look for a Print Recipe button on the recipe card first, because it opens a stripped-down version with just the ingredients and method. If the site has no button, paste the page address into a printer-friendly tool, delete the story and photos, and print. Either way you get one page instead of eight.',
      body: [
        { t: 'p', x: 'You want 300 words: a list of ingredients and a numbered method. The page gives you a childhood memory about a grandmother, eleven photographs of the same bowl, an autoplaying video, three ad slots and 400 comments. Press **Ctrl+P** and the preview says nine pages.' },
        { t: 'h2', x: 'Why food blogs are like this' },
        { t: 'p', x: 'It is not vanity. A list of ingredients is not protected by copyright in most countries, so anyone can lift it. The surrounding narrative is protected, and it is what gives the page something original to rank on. Longer pages also carry more advertising, and advertising is what pays for a free recipe. Knowing this makes it easier to be efficient rather than annoyed: the story is the price of the recipe, and you only have to pay it on screen.' },
        { t: 'h2', x: 'Method 1: the site\'s own print button' },
        { t: 'p', x: 'Most food blogs run their recipes through a plugin — **WP Recipe Maker**, **Tasty Recipes**, **Create by Mediavine** and similar — which puts the recipe in a bordered card with its own small toolbar. That toolbar almost always has a **Print** or **Print Recipe** link, and it is the single best option when it exists.' },
        {
          t: 'steps',
          items: [
            { h: 'Find the recipe card', x: 'Scroll to the bordered box holding the ingredients, or click **Jump to Recipe** at the top of the page, which the same plugins add automatically.' },
            { h: 'Click Print or Print Recipe', x: 'It opens a new tab or window containing only the card: title, times, servings, ingredients, method.' },
            { h: 'Set the options in that window', x: 'These print views usually offer their own checkboxes — include images, include notes, adjust servings. Untick images to halve the ink.' },
            { h: 'Scale the servings before printing', x: 'Many cards let you change 4 servings to 6 and rewrite every quantity. Do it here rather than doing arithmetic at the counter.' },
            { h: 'Press Ctrl+P in that window', x: 'Check the preview says one page. If it says two, turn off images or drop the scale to 90 percent.' },
          ],
        },
        { t: 'note', x: 'If a page has a **Jump to Recipe** link at the top, it almost certainly has a print button further down. The two arrive together in the same plugin. Look inside the bordered card for a small printer icon.' },
        { t: 'h2', x: 'Method 2: a printer-friendly tool for everything else' },
        { t: 'p', x: 'Plenty of sites have no card and no button: personal blogs, newspaper food sections, forum posts, old pages from 2009 that hold the only good version of a dish. For those, clean the page yourself.' },
        {
          t: 'steps',
          items: [
            { h: 'Copy the page address', x: 'Click the address bar and copy the whole URL.' },
            { h: 'Open the cleaner', x: 'Go to the [web page printer](/print) and paste the address in. It extracts the article and drops the navigation, sidebars and ad slots.' },
            { h: 'Delete the story', x: 'Delete mode is on by default. Click the memoir paragraphs, the video embed and the "you might also like" grid to remove them. Click and drag to sweep several blocks at once, and Ctrl+Z to undo.' },
            { h: 'Deal with the pictures', x: 'Open the Style menu and set images to small, or remove them entirely. Keep one photo of the finished dish if the shape or the colour matters.' },
            { h: 'Print or save', x: 'Press Print for paper, or Download PDF to keep it for a [recipe binder](/blog/print-recipes/make-a-recipe-binder).' },
          ],
        },
        { t: 'cta', tool: 'html-to-pdf', x: 'Turn a recipe page into a clean, one-page PDF you can file or print later.' },
        { t: 'h2', x: 'Method 3: select the recipe and print the selection' },
        { t: 'p', x: 'The fastest trick of all when it works. Drag to select from the word "Ingredients" through the last step of the method, press Ctrl+P, and choose **Selection only** under Pages. Chrome, Firefox and Edge all support it; on Safari use **File → Print Selected Text**. Full detail in [printing only what you selected](/blog/print-web-pages/print-selected-text-only).' },
        { t: 'p', x: 'It fails when the recipe card is inside an iframe, or when the site blocks text selection. In both cases fall back to Method 2.' },
        { t: 'h2', x: 'Which method to use' },
        {
          t: 'table',
          caption: 'Choosing a method by what the page offers.',
          head: ['The page has…', 'Use', 'Typical result'],
          rows: [
            ['A recipe card with a Print button', 'The site button', '1 page, correctly formatted, servings adjustable'],
            ['A Jump to Recipe link but no visible button', 'Look inside the card again, then the site button', '1 page'],
            ['No card, plain blog post', 'Paste the URL into a cleaner', '1-2 pages after deleting the story'],
            ['A paywall or login', 'Reader mode, or select and print the selection', '1-2 pages'],
            ['A recipe inside a video description', 'Copy the text into the cleaner paste box', '1 page'],
            ['A photo of a handwritten card', '[OCR it](/blog/ocr-scanned-documents/how-to-ocr-a-scanned-pdf) first, then print the text', '1 page, searchable'],
          ],
        },
        { t: 'h2', x: 'Make the printout usable in a kitchen' },
        {
          t: 'ul',
          items: [
            '**Bump the text size.** You are reading this from three feet away with wet hands. 14 to 16 point is right; the browser default of 12 point is not.',
            '**Keep the times and the temperature at the top.** Oven temperature, prep time and total time are what you need before you start, not buried after step four.',
            '**Print single-sided.** Turning a greasy page over mid-recipe is how pages get lost. One recipe, one sheet, one side.',
            '**Add the source.** A short line with the site name means you can find the original when you want the notes or the comments.',
            '**Do not print the comments.** The one useful comment is worth copying into the margin by hand; the other 399 are not worth four sheets.',
          ],
        },
        { t: 'tip', x: 'If you cook from the same site often, keep the cleaner open in a pinned tab. Paste, delete, print, paste the next one — it removes the hunting-for-the-print-button step entirely.' },
        { t: 'h2', x: 'Save the paper as well as the ads' },
        { t: 'p', x: 'A cleaned recipe usually lands between two-thirds and a full page. If it spills onto a second page by three lines, drop the print scale to 90 percent rather than accepting a sheet with four lines on it. Combined with turning images off, the difference over a year of cooking is substantial — see [saving ink when printing](/blog/save-paper-ink/save-ink-when-printing) and [printing recipes without pictures](/blog/print-recipes/print-recipe-without-pictures).' },
      ],
      faqs: [
        { q: 'How do I print just the recipe and not the whole blog post?', a: 'Use the Print Recipe button inside the recipe card if the site has one, which opens a stripped version containing only the ingredients and method. If not, paste the page address into a printer-friendly tool and delete the story before printing.' },
        { q: 'Why do food blogs have such long stories before the recipe?', a: 'Ingredient lists are not protected by copyright, so the surrounding writing is what makes the page original and rankable, and longer pages carry more advertising, which pays for the free recipe. The story is the price, but only on screen.' },
        { q: 'How do I print a recipe from a site with no print button?', a: 'Select from the ingredients through the end of the method, press Ctrl+P and choose Selection only. If the site blocks selection, paste the URL into a browser-based cleaner, delete everything except the recipe, and print that.' },
        { q: 'Can I change the number of servings before printing?', a: 'Yes on sites using a recipe card plugin: the card usually has a servings control that rewrites every quantity. Change it before you open the print view, since the print window inherits whatever the card is showing.' },
        { q: 'How do I get a recipe onto exactly one page?', a: 'Turn images off, set the text to 14 point, and drop the print scale to 90 percent if it still spills. Those three adjustments fit almost any home recipe onto a single sheet without making it hard to read at arm\'s length.' },
      ],
      relatedTools: ['html-to-pdf', 'pdf-reader'],
      relatedPosts: ['print-recipe-without-pictures', 'print-web-page-without-ads', 'make-a-recipe-binder'],
    },
    {
      slug: 'print-recipe-without-pictures',
      cluster: 'print-recipes',
      title: 'How to print a recipe without the pictures',
      metaTitle: 'How to Print a Recipe Without Pictures',
      metaDescription:
        'Photos are what make a recipe print on four pages and drain a colour cartridge. How to drop them in every browser, and which single photo is worth keeping.',
      published: '2026-02-27',
      updated: '2026-07-22',
      readMinutes: 5,
      intent: 'howto',
      primaryKeyword: 'print recipe without pictures',
      secondaryKeywords: ['print web page without images', 'save ink printing recipes', 'text only recipe print', 'remove images before printing', 'draft mode printing'],
      entities: ['Google Chrome', 'Firefox Reader View', 'Safari Reader', 'Microsoft Edge', 'EconoMode', 'Ctrl+P', 'inkjet', 'laser printer'],
      answer:
        'To print a recipe without pictures, use a printer-friendly tool and set images to none, or open the site\'s own print view and untick "include images". Browsers have no images-off switch of their own, so turning off background graphics only removes decorative images, not the recipe photos.',
      body: [
        { t: 'p', x: 'Photographs are why a 300-word recipe becomes a four-page printout. A single full-width food photo can occupy half a sheet on its own, and a step-by-step sequence of eight process shots turns one page into four. On an inkjet, each of those pages is also the most expensive kind of page you can print.' },
        { t: 'h2', x: 'What images actually cost' },
        {
          t: 'table',
          caption: 'Approximate cost and page impact per printed page.',
          head: ['Page type', 'Rough inkjet cost', 'Sheets for one recipe'],
          rows: [
            ['Text only', '3-5 cents', '1'],
            ['Text plus one small photo', '6-9 cents', '1'],
            ['Text plus one full-width photo', '12-20 cents', '2'],
            ['Full step-by-step photo sequence', '15-25 cents per photo page', '4-6'],
            ['Same, on a colour laser', '8-12 cents', 'Same page count'],
          ],
        },
        { t: 'p', x: 'The figures vary widely by printer and cartridge, but the ratio holds everywhere: a colour photo page costs roughly three to five times a text page, and it is the page count that hurts most. Dropping the images is usually the difference between one sheet and four.' },
        { t: 'h2', x: 'Turning images off, by method' },
        {
          t: 'steps',
          items: [
            { h: 'In a printer-friendly tool', x: 'Open the [web page printer](/print), paste the recipe URL, then open the **Style** menu and set images to **None**. This is the only method that reliably removes every image, including the ones inside the recipe card.' },
            { h: 'In the site\'s own print view', x: 'Recipe card plugins usually offer an "include images" checkbox in their print window. Untick it before printing.' },
            { h: 'In Reader mode', x: 'Firefox Reader View and Safari Reader keep photos but drop everything decorative, so the page count falls even though the images remain. A partial fix.' },
            { h: 'In the browser print dialog', x: 'Open **More settings** and untick **Background graphics**. Be clear about what this does: it removes CSS background images and colour blocks only, not the inline photos in the article.' },
            { h: 'In the printer driver', x: 'Choose greyscale or black-and-white, and draft or **EconoMode** quality. The photos still print and still take up the space, but they cost far less ink.' },
          ],
        },
        { t: 'warn', x: 'There is no "do not print images" switch in Chrome, Edge or Safari. Guides that tell you to untick Background graphics for this are half right at best: it removes decorative backgrounds and leaves every photo in the recipe untouched. Use a cleaner or the site print view instead.' },
        { t: 'cta', tool: 'html-to-pdf', x: 'Produce a text-only PDF of a recipe page and print it as many times as you like.' },
        { t: 'h2', x: 'Keep exactly one photo' },
        { t: 'p', x: 'Stripping every image is not always right. One picture earns its place when the finished appearance is information rather than decoration:' },
        {
          t: 'ul',
          items: [
            '**Shaping and assembly.** Plaited bread, folded dumplings, a layered bake — you cannot tell from words whether you have done it correctly.',
            '**A doneness cue.** The colour of a caramel, the set of a custard, the crumb of a loaf when it is right.',
            '**A cutting or portioning diagram.** How a joint of meat divides, or how a tray bake is scored.',
            '**Unfamiliar ingredients.** A photo of the right kind of chilli or noodle saves a wrong purchase.',
          ],
        },
        { t: 'p', x: 'In a cleaner, that means setting images to small rather than none, then deleting the ones you do not need individually. A small reference photo occupies about a fifth of the page width and prints for a fraction of the cost of a full-width one.' },
        { t: 'h2', x: 'Greyscale rather than nothing' },
        { t: 'p', x: 'Where a photo shows shape or texture — the plait, the fold, the cut — greyscale carries the information at a fraction of the ink cost. Where a photo shows a colour cue, such as how brown a caramel should be, greyscale destroys the point of including it. Decide per photo, then set the printer to greyscale for the whole job if none of them need colour.' },
        {
          t: 'table',
          head: ['If the photo shows…', 'Print it as'],
          rows: [
            ['A shaping or folding step', 'Greyscale, small'],
            ['A colour or browning cue', 'Colour, small — or skip it and read the description'],
            ['The finished dish, for reference', 'Greyscale, small, one only'],
            ['The blogger\'s kitchen, hands, or table setting', 'Do not print it'],
            ['An ingredient flat-lay', 'Do not print it — the list is on the page'],
          ],
        },
        { t: 'tip', x: 'Print recipes in draft quality by default. Text stays perfectly readable at arm\'s length, pages come out faster, and cartridges last two to three times longer. On most drivers the setting is under Quality or Print Quality, and on many HP printers it is labelled EconoMode.' },
        { t: 'h2', x: 'The one-page target' },
        { t: 'p', x: 'Aim to have every recipe in your kitchen on one side of one sheet. Images off, text at 14 point, scale at 90 percent if needed. That way a recipe is one thing you can hold, prop up or wipe down, and the [binder you build from them](/blog/print-recipes/make-a-recipe-binder) has a consistent format. If you are also printing weekly, the same settings apply to a [meal plan and shopping list](/blog/print-recipes/meal-plan-printables).' },
      ],
      faqs: [
        { q: 'How do I print a web page without images?', a: 'Use a printer-friendly tool and set images to None in its style options. Browsers do not have an images-off switch, and unticking Background graphics in the print dialog only removes CSS backgrounds, not the photos inside the article.' },
        { q: 'Does turning off Background graphics remove recipe photos?', a: 'No. It removes CSS background images and colour blocks only. Inline photographs in the recipe still print at full size. To drop them you need a cleaner, the site\'s own print view, or a reader mode.' },
        { q: 'How much ink does a photo actually use?', a: 'A full-width colour photo page typically costs three to five times a text page on an inkjet, roughly 12 to 20 cents against 3 to 5. The bigger cost is usually paper: photos are what turn a one-page recipe into four sheets.' },
        { q: 'Should I keep any pictures at all?', a: 'Keep one when the picture is information rather than decoration: a shaping or folding step, a doneness cue such as caramel colour, a cutting diagram, or an unfamiliar ingredient. Print it small, and in greyscale unless the colour is the point.' },
        { q: 'What is the cheapest way to print recipes regularly?', a: 'Images off, draft or EconoMode quality, greyscale, 14 point text, single-sided, one recipe per sheet. That combination keeps recipes readable in a kitchen while using a fraction of the ink and a quarter of the paper.' },
      ],
      relatedTools: ['html-to-pdf', 'compress-pdf'],
      relatedPosts: ['print-recipe-without-ads', 'save-ink-when-printing', 'make-a-recipe-binder'],
    },
    {
      slug: 'make-a-recipe-binder',
      cluster: 'print-recipes',
      title: 'How to build a printed recipe binder that survives a kitchen',
      metaTitle: 'Build a Recipe Binder That Survives a Kitchen',
      metaDescription:
        'Nine rules for a printed recipe binder that lasts: one format, the right page size, sheet protectors, a real index, and what to laminate and what to leave.',
      published: '2026-03-24',
      updated: '2026-08-07',
      readMinutes: 7,
      intent: 'listicle',
      primaryKeyword: 'how to make a recipe binder',
      secondaryKeywords: ['printed recipe binder', 'recipe binder organisation', 'recipe card sizes', 'sheet protectors recipes', 'laminating recipes'],
      entities: ['Avery', 'A5', 'US Letter', 'Pinterest', 'polypropylene', 'D-ring binder', 'sheet protector', 'laminating pouch'],
      answer:
        'Build a recipe binder by printing every recipe to one consistent format on one side of a sheet, filing them in top-loading sheet protectors inside a two-inch D-ring binder, dividing by category, and keeping a printed index at the front that you update when you add a recipe.',
      body: [
        { t: 'p', x: 'A recipe binder fails for predictable reasons: every page a different size and font, no way to find anything, and grease-soaked sheets that come apart within a year. Nine decisions fix all three, and the first one matters more than the other eight combined.' },
        { t: 'h2', x: '1. One format, no exceptions' },
        { t: 'p', x: 'Every recipe goes in looking the same: same paper size, same font size, title at the top, times and temperature under the title, ingredients then method, source at the bottom. Consistency is what makes a binder scannable — you learn where to look and stop reading the layout each time.' },
        { t: 'p', x: 'The easiest way to enforce it is to clean each page through the same process before printing. Paste the URL into the [web page printer](/print), delete the story, set the text size, print. It takes a minute and the twentieth recipe looks like the first. Full method in [printing a recipe without the ads](/blog/print-recipes/print-recipe-without-ads).' },
        { t: 'h2', x: '2. Pick a page size and commit' },
        {
          t: 'table',
          caption: 'Recipe page formats and what each one suits.',
          head: ['Format', 'Size', 'Recipes per sheet', 'Best for'],
          rows: [
            ['US Letter / A4', '8.5 x 11 in / 210 x 297 mm', '1', 'The default. Largest text, easiest to read across a counter.'],
            ['Half letter / A5', '5.5 x 8.5 in / 148 x 210 mm', '2 per sheet, cut', 'A compact binder that fits in a drawer.'],
            ['4 x 6 in card', '4 x 6 in', '4 per sheet, cut', 'A traditional recipe box. Tight for anything with 12 ingredients.'],
            ['5 x 7 in card', '5 x 7 in', '2 per sheet, cut', 'A good compromise for a card box.'],
          ],
        },
        { t: 'p', x: 'Full-size sheets are the right answer for most people. You can read them from across the kitchen, they need no cutting, and standard sheet protectors and binders are cheap and universal. Choose cards only if you already own a card box you like.' },
        { t: 'h2', x: '3. Print one recipe per side' },
        { t: 'p', x: 'Never double-side. A recipe printed on the back of another means turning a page with sticky hands mid-method, and it makes the binder impossible to reorder later. One recipe, one sheet, one side. The blank reverse is also where you write what you changed.' },
        { t: 'h2', x: '4. Sheet protectors do the real work' },
        {
          t: 'ul',
          items: [
            'Use **top-loading, three-hole polypropylene** protectors. Top-loading means you never have to open the rings to swap a page.',
            'Choose **non-glare** rather than clear. Kitchen lighting is usually overhead, and glossy protectors mirror it straight into your eyes.',
            'Look for **archival, acid-free, PVC-free**. PVC sleeves yellow and can transfer plasticiser onto the print over a few years.',
            'A splash wipes straight off a protector, which is the whole point. The paper inside stays clean for a decade.',
            'Heavyweight protectors, sometimes sold as 3.5 mil or "heavy duty", cost slightly more and outlast the cheap ones by years.',
          ],
        },
        { t: 'h2', x: '5. Buy a bigger binder than you think' },
        { t: 'p', x: 'A two-inch **D-ring** binder holds roughly 150 to 175 sheets in protectors. D-rings, not round rings: pages sit flat and turn without catching, and a D-ring binder holds noticeably more than a round-ring one of the same nominal size. Buy the two-inch even if you are starting with thirty recipes, because a binder that is full is a binder you stop adding to.' },
        { t: 'h2', x: '6. Divide by how you decide, not how a cookbook does' },
        { t: 'p', x: 'Cookbook categories are for browsing. A kitchen binder is for deciding what to cook tonight, so divide it the way you actually choose:' },
        {
          t: 'ol',
          items: [
            'Weeknight, 30 minutes or less',
            'Weekend and slow cooking',
            'Baking and bread',
            'Sides, sauces and dressings',
            'Guests and celebrations',
            'Preserving, freezing and batch cooking',
            'Tried once, undecided — the holding pen',
          ],
        },
        { t: 'p', x: 'That last tab is the one that keeps the binder honest. A recipe waits there until you have cooked it twice; then it earns a real tab or goes in the bin.' },
        { t: 'h2', x: '7. Keep an index at the front' },
        { t: 'p', x: 'Tabs get you to a section. An index gets you to a recipe. Keep a simple two-column list — recipe name and section — printed and slipped into the front pocket, and reprint it whenever you have added five or six recipes. Handwrite the additions in between; it takes ten seconds and keeps the index true.' },
        { t: 'tip', x: 'Number your sections and write the section number in the corner of each printed page before it goes into a protector. A page that comes out of the binder can then be put back where it belongs without reading it.' },
        { t: 'h2', x: '8. Laminate only what you cook constantly' },
        {
          t: 'table',
          head: ['', 'Sheet protector', 'Laminating pouch'],
          rows: [
            ['Cost per page', 'A few cents', 'Higher, plus a machine'],
            ['Can be swapped or corrected', 'Yes, in seconds', 'No, it is permanent'],
            ['Can you write on it', 'Yes, on the paper inside', 'Only with a wipe-off marker'],
            ['Survives a splash', 'Yes', 'Yes, and survives immersion'],
            ['Best thickness', 'n/a', '5 mil for stiffness, 3 mil to stay flexible'],
            ['Use for', 'Everything', 'The ten recipes you cook every month'],
          ],
        },
        { t: 'p', x: 'Laminate the weekly staples and the reference sheets: roasting times, conversions, a bread ratio table. Everything else lives in a protector, where you can pull the page out and write on it.' },
        { t: 'h2', x: '9. Digitise the binder once' },
        { t: 'p', x: 'Keep the PDFs you printed from, in one folder, named consistently — `chicken-lemon-orzo.pdf` rather than `print_1.pdf`. Then [merge them into a single PDF](/blog/merge-pdf/how-to-merge-pdf-files) once or twice a year as a backup. If the binder gets ruined, you reprint it in an afternoon instead of hunting for forty pages again.' },
        { t: 'cta', tool: 'merge-pdf', x: 'Merge your recipe PDFs into one backup file, in your browser.' },
        { t: 'p', x: 'For hand-written family recipes, photograph them, [run OCR](/blog/ocr-scanned-documents/how-to-ocr-a-scanned-pdf) so the text is searchable, and print a clean typed version for the binder. Keep the original card somewhere dry; the point of the binder is that you stop handling it.' },
        { t: 'note', x: 'The binder only works if adding to it is easy. Clean, print, protector, tab, index line. If any step needs more than a minute, recipes stop going in and pile up in browser tabs instead.' },
      ],
      faqs: [
        { q: 'What size should recipe pages be for a binder?', a: 'Full-size Letter or A4 sheets are best for most kitchens: largest text, no cutting, and standard protectors and binders. Choose half-letter or A5 for a compact drawer binder, and 4x6 or 5x7 cards only if you already have a card box.' },
        { q: 'Are sheet protectors or laminating better for recipes?', a: 'Sheet protectors for almost everything, because pages can be swapped, corrected and written on. Laminate only the ten or so recipes you cook every month, plus reference sheets such as roasting times and conversions.' },
        { q: 'How big a binder do I need for a recipe collection?', a: 'A two-inch D-ring binder holds roughly 150 to 175 pages in protectors. Start with that size even for a small collection, since a binder that is already full is one you stop adding recipes to.' },
        { q: 'How should I organise a recipe binder?', a: 'Divide it by how you actually decide what to cook — weeknight, weekend, baking, sides, guests, batch cooking — rather than by cookbook categories. Add a "tried once" section as a holding pen, and keep a printed index at the front.' },
        { q: 'Should I print recipes double-sided to save paper?', a: 'No. Turning a page with sticky hands mid-method is how sheets get ruined, and double-sided pages cannot be reordered. Keep one recipe per side and use the blank reverse for notes on what you changed.' },
      ],
      relatedTools: ['merge-pdf', 'html-to-pdf'],
      relatedPosts: ['print-recipe-without-ads', 'meal-plan-printables', 'how-to-merge-pdf-files'],
    },
    {
      slug: 'meal-plan-printables',
      cluster: 'print-recipes',
      title: 'How to make a weekly meal plan and shopping list you can print',
      metaTitle: 'Make a Printable Weekly Meal Plan',
      metaDescription:
        'Build a one-page meal plan and shopping list you will use: a template that fits a fridge door, aisle-grouped lists, and recipes combined into one weekly PDF.',
      published: '2026-04-19',
      updated: '2026-08-16',
      readMinutes: 6,
      intent: 'howto',
      primaryKeyword: 'printable weekly meal plan',
      secondaryKeywords: ['meal plan template print', 'printable shopping list', 'weekly meal planner pdf', 'combine recipes into one pdf', 'meal prep printable'],
      entities: ['A4', 'US Letter', 'Google Sheets', 'Microsoft Excel', 'PDF', 'Ctrl+P', 'landscape orientation'],
      answer:
        'Build a one-page plan with seven day columns and rows for the meals you actually plan, put an aisle-grouped shopping list on the reverse, and merge the week\'s recipes into a single PDF behind it. Print one copy for the fridge and one for the shop.',
      body: [
        { t: 'p', x: 'A meal plan on a phone gets checked in the supermarket and forgotten in the kitchen. A meal plan on the fridge door gets read by everyone in the house, including the person who was going to ask what is for dinner. That is the whole case for printing it.' },
        { t: 'h2', x: 'What the page needs' },
        { t: 'p', x: 'One page, landscape, seven columns. Rows only for the meals you genuinely plan — most households plan dinners and nothing else, and a template with three meals a day just produces 14 empty boxes and a feeling of failure.' },
        {
          t: 'table',
          caption: 'A weekly plan layout that fits one landscape sheet.',
          head: ['Row', 'Purpose', 'Height'],
          rows: [
            ['Day headers', 'Mon to Sun, with the date', 'Narrow'],
            ['Dinner', 'The meal you actually plan', 'Tall — two lines of writing'],
            ['Lunch or leftovers', 'Often just an arrow from the night before', 'Short'],
            ['Prep ahead', 'Defrost, soak, marinate, take out of the freezer', 'Short'],
            ['Notes', 'Who is out, who is cooking, what needs using up', 'Short'],
          ],
        },
        { t: 'p', x: 'The "prep ahead" row is the one that earns its space. Almost every weeknight failure is something that needed defrosting that morning. Writing it in a row you look at over breakfast fixes it.' },
        { t: 'h2', x: 'Build the template once' },
        {
          t: 'steps',
          items: [
            { h: 'Make a table in a spreadsheet', x: 'Google Sheets or Excel is easier than a word processor for this. Seven columns across, five rows down, plus a title row with a space for the week beginning date.' },
            { h: 'Set the page to landscape and fit to one page', x: 'In Sheets: **File → Print → Landscape**, then set Scale to "Fit to width". In Excel: **Page Layout → Orientation → Landscape**, then **Fit Sheet on One Page**.' },
            { h: 'Make the boxes tall enough to write in', x: 'A dinner cell needs around 2 cm of height. If you cannot write a dish name and a note in it with a normal pen, the plan will not get used.' },
            { h: 'Export to PDF, not print directly', x: 'Save it as `meal-plan-template.pdf`. Now you have a fixed file you can print any week without touching the layout again.' },
            { h: 'Put the shopping list on the reverse', x: 'Make it page two of the same PDF and print double-sided. One sheet leaves the house, and it has both halves of the job on it.' },
            { h: 'Print two copies', x: 'One for the fridge door, one for a pocket. The fridge copy is the reference; the pocket copy gets crossed off and thrown away.' },
          ],
        },
        { t: 'cta', tool: 'html-to-pdf', x: 'Turn a plan or list built in the browser into a clean printable PDF.' },
        { t: 'h2', x: 'A shopping list grouped by aisle' },
        { t: 'p', x: 'A list in the order you thought of things sends you back and forth across the shop. A list grouped by area cuts the trip roughly in half. Use fixed headings so the same list works every week:' },
        {
          t: 'ul',
          items: [
            '**Fruit and vegetables** — usually the first aisle, and the one you buy most of.',
            '**Meat, fish and chilled** — including dairy and eggs.',
            '**Bakery**',
            '**Cupboard** — tins, dried goods, oils, spices, pasta and rice.',
            '**Frozen** — deliberately near the end so nothing thaws in the trolley.',
            '**Household and other** — everything that is not food.',
            '**Already have** — a short column to tick before leaving, which is what stops the fourth jar of cumin.',
          ],
        },
        { t: 'tip', x: 'Leave four blank lines under each heading. A list with no space to add anything gets abandoned the first time someone remembers they need bin bags.' },
        { t: 'h2', x: 'Combine the week\'s recipes into one PDF' },
        { t: 'p', x: 'The plan tells you what you are cooking. The recipes tell you how. Keeping them together as one file means one print job, one staple, and nothing to look up mid-week.' },
        {
          t: 'steps',
          items: [
            { h: 'Clean each recipe', x: 'Run each one through the [web page printer](/print), delete the story and the photos, and download it as a PDF. Method in [printing a recipe without the ads](/blog/print-recipes/print-recipe-without-ads).' },
            { h: 'Name the files by day', x: '`mon-chicken-orzo.pdf`, `tue-dal.pdf`, and so on. The names decide the order in the next step, so this is worth thirty seconds.' },
            { h: 'Merge them behind the plan', x: 'Open [Merge PDF](/tools/merge-pdf), add the plan first and then the recipes in order, and download the combined file.' },
            { h: 'Number the pages', x: 'Run the merged file through [Page numbers](/tools/page-numbers) so a dropped stack goes back together correctly.' },
            { h: 'Print the pack', x: 'Plan and shopping list double-sided, recipes single-sided so they can be pulled out and propped up.' },
          ],
        },
        { t: 'h2', x: 'Keep a season of plans, not just this week' },
        {
          t: 'table',
          head: ['Approach', 'What you keep', 'Why it helps'],
          rows: [
            ['One file per week', 'Plan, list and the recipes you used', 'A ready-made repeat when a week goes well'],
            ['A rotation of four weeks', 'Four complete packs', 'Removes the planning decision entirely for a month'],
            ['A seasonal folder', 'Twelve or so packs by month', 'Matches what is cheap and available'],
            ['One merged archive per year', 'Everything, in one PDF', 'Searchable, and easy to back up'],
          ],
        },
        { t: 'p', x: 'Weeks that worked are the most valuable thing you produce. Note on the fridge copy what got eaten and what did not, and keep the ones that scored well. After a couple of months you are picking a plan rather than writing one, which is where the time saving actually comes from.' },
        { t: 'note', x: 'Print the plan on Sunday morning, not Sunday night. Anything you find on Sunday night that needs defrosting is already a Monday problem.' },
        { t: 'p', x: 'If the plan and recipe pack grows past a dozen pages, [compress the PDF](/blog/compress-pdf/how-to-compress-a-pdf) before emailing it to whoever else is cooking, and file the printed version in the [recipe binder](/blog/print-recipes/make-a-recipe-binder) so it is easy to repeat.' },
      ],
      faqs: [
        { q: 'What should a printable weekly meal plan include?', a: 'Seven day columns and rows for the meals you actually plan, plus a prep-ahead row for anything that needs defrosting or soaking, and a notes row for who is out or cooking. Keep it to one landscape page so it fits a fridge door.' },
        { q: 'How do I combine several recipes into one PDF?', a: 'Save each cleaned recipe as its own PDF, name the files by day so they sort correctly, then merge them in order with a browser-based merge tool. Add page numbers afterwards so a dropped stack goes back together.' },
        { q: 'How should I organise a printed shopping list?', a: 'Group it by shop area — fruit and vegetables, chilled, bakery, cupboard, frozen, household — rather than by recipe. Put frozen last so nothing thaws, and leave four blank lines under each heading for additions.' },
        { q: 'Should I print one copy of the meal plan or two?', a: 'Two. The fridge copy stays as the reference all week, and the pocket copy goes to the shop and gets crossed off and thrown away. Printing both at once takes no longer than printing one.' },
        { q: 'How do I fit a weekly planner on one page?', a: 'Use landscape orientation and set your spreadsheet to fit to one page, then keep the rows to the meals you genuinely plan. Dinner cells need about 2 cm of height so there is room to write a dish name and a note.' },
      ],
      relatedTools: ['merge-pdf', 'page-numbers'],
      relatedPosts: ['make-a-recipe-binder', 'print-recipe-without-ads', 'how-to-merge-pdf-files'],
    },
  ],
}
