import type { Cluster } from '../types'

export const publishersWordpress: Cluster = {
  slug: 'publishers',
  name: 'For publishers and developers',
  title: 'Print buttons, print stylesheets and printer-friendly pages',
  metaTitle: 'Print Buttons and Print CSS for Publishers',
  metaDescription:
    'Add a print or PDF button to WordPress or any website, write a print stylesheet that works, and stop readers printing nine sheets to get one article.',
  intro:
    'Readers still print. Recipes go on the counter, itineraries go in a pocket, order confirmations go in a folder, and documentation goes next to the keyboard. Almost none of that is designed for: most sites ship no print stylesheet at all, so the nav bar takes the first sheet and the article arrives in fragments. These four guides cover the two halves of the fix, a button people can find, and a stylesheet that makes the button worth pressing.',
  answer:
    'Give readers a print button and a print stylesheet. The button is a plain HTML anchor or a button calling window.print(), placed near the article title. The stylesheet hides navigation, resets the layout to a single column, sets @page margins, controls page breaks and prints link URLs so the paper copy stands on its own.',
  primaryKeyword: 'how to add a print button to a website',
  entities: ['WordPress', 'WooCommerce', 'CSS', 'Gutenberg', 'Google Chrome DevTools', 'Squarespace', 'Shopify', 'Wix', 'Mozilla Developer Network'],
  icon: '⚙',
  tools: ['html-to-pdf', 'qr-code', 'pdf-to-text'],
  posts: [
    {
      slug: 'add-print-button-to-wordpress',
      cluster: 'publishers',
      title: 'How to add a print button to WordPress',
      metaTitle: 'How to Add a Print Button to WordPress',
      metaDescription:
        'Five ways to add a print or PDF button to WordPress: a plugin, a Custom HTML block, a shortcode, a theme filter and WooCommerce orders, with working code.',
      published: '2026-01-21',
      updated: '2026-08-18',
      readMinutes: 8,
      intent: 'howto',
      primaryKeyword: 'add print button to wordpress',
      secondaryKeywords: ['wordpress print button plugin', 'wordpress print shortcode', 'print button gutenberg block', 'woocommerce print order button', 'wordpress print friendly'],
      entities: ['WordPress', 'WooCommerce', 'Gutenberg', 'PHP', 'functions.php', 'Elementor', 'Yoast SEO', 'Site Editor'],
      answer:
        'The quickest route is a Custom HTML block containing a single anchor tag, which works on any theme with no plugin. For a button on every post, register a shortcode in a child theme or site-specific plugin and append it with the_content filter. WooCommerce order pages need window.print() instead, because they are login-gated.',
      body: [
        { t: 'p', x: 'There are five ways to put a print button on a WordPress site, and they differ mainly in how much of your future they cost. A Custom HTML block takes thirty seconds but has to be pasted into every post. A theme filter takes fifteen minutes and then never needs touching again. Pick by how many posts you have.' },
        {
          t: 'table',
          caption: 'The five routes compared.',
          head: ['Route', 'Effort', 'Applies to', 'Survives a theme update'],
          rows: [
            ['A plugin', 'Two minutes', 'Everything, with settings', 'Yes'],
            ['Custom HTML block', 'Thirty seconds', 'One post', 'Yes'],
            ['Synced pattern', 'Five minutes', 'Every post you insert it into', 'Yes'],
            ['Shortcode plus the_content filter', 'Fifteen minutes', 'Every post automatically', 'Yes, if it lives in a child theme or a plugin'],
            ['Editing the parent theme template', 'Ten minutes', 'Whatever the template covers', 'No. It is wiped on the next update'],
          ],
        },
        { t: 'h2', x: 'Route 1: install a plugin' },
        {
          t: 'steps',
          items: [
            { h: 'Open the plugin installer', x: 'In wp-admin go to **Plugins → Add New**.' },
            { h: 'Search and install', x: 'Search for a print or print-friendly plugin, click **Install Now**, then **Activate**. The [PrintxPDF WordPress plugin](/wordpress) adds Print, PDF and Email buttons and needs no API key on the free tier.' },
            { h: 'Choose placement', x: 'In the plugin settings pick top, bottom or both, and inline or floating. Bottom-of-article is the safest default: a floating button competes with cookie banners and chat widgets on mobile.' },
            { h: 'Limit it to the right post types', x: 'Turn the button off on the home page, archives and search results. It belongs on single posts, pages and any custom post type that people actually print.' },
            { h: 'Check the output', x: 'Open a post, click the button and read what comes out. If the plugin only calls the browser print dialog, you still need a print stylesheet, see [writing a print stylesheet](/blog/publishers/print-stylesheet-css).' },
          ],
        },
        { t: 'h2', x: 'Route 2: a Custom HTML block, no plugin' },
        { t: 'p', x: 'In the block editor, add a **Custom HTML** block wherever you want the button and paste this. It is a plain anchor, so it works in every theme, needs no JavaScript to be clickable, and cannot break your site.' },
        { t: 'code', x: '<!-- Printer-friendly link. Works with JavaScript disabled. -->\n<a class="pxp-print"\n   href="https://printxpdf.com/print?url="\n   onclick="this.href=\'https://printxpdf.com/print?url=\'+encodeURIComponent(location.href)"\n   target="_blank" rel="noopener">&#9113; Print / PDF</a>\n\n<style>\n.pxp-print{display:inline-flex;align-items:center;gap:.5rem;padding:10px 18px;\n  font:700 14px/1 system-ui,sans-serif;text-decoration:none;border:2px solid currentColor;\n  border-radius:6px;color:inherit}\n@media print{.pxp-print{display:none !important}}\n</style>' },
        { t: 'tip', x: 'Turn that block into a **synced pattern** (select the block → the three-dot menu → Create pattern, with "Synced" on). Insert the pattern into other posts and every copy updates when you edit the original. This is the old Reusable Blocks feature under its current name.' },
        { t: 'h2', x: 'Route 3: a shortcode you can drop anywhere' },
        { t: 'p', x: 'A shortcode gives you `[print_button]` in any editor, widget or page builder, and one place to change the markup later. Put this in a child theme’s `functions.php` or, better, in a small site-specific plugin so it survives a theme change too.' },
        { t: 'code', x: "<?php\n// wp-content/plugins/site-print-button/site-print-button.php\n\nfunction pxp_print_button( $atts ) {\n    $a = shortcode_atts( array( 'label' => 'Print / PDF' ), $atts, 'print_button' );\n\n    $target = 'https://printxpdf.com/print?url=' . rawurlencode( get_permalink() );\n\n    return sprintf(\n        '<a class=\"pxp-print\" href=\"%s\" target=\"_blank\" rel=\"noopener\">%s</a>',\n        esc_url( $target ),\n        esc_html( $a['label'] )\n    );\n}\nadd_shortcode( 'print_button', 'pxp_print_button' );" },
        { t: 'p', x: 'Use it as `[print_button]` or `[print_button label="Print this recipe"]`. Three details matter: `shortcode_atts` gives you a default label, `rawurlencode` keeps query strings and non-ASCII characters in the permalink intact, and `esc_url` plus `esc_html` are not optional, a shortcode that echoes unescaped attributes is a cross-site scripting hole.' },
        { t: 'h2', x: 'Route 4: put it on every post automatically' },
        { t: 'p', x: 'Rather than editing templates, append the shortcode with a filter. The three guards below matter: without them the button also appears in excerpts, RSS feeds, related-post widgets and anywhere else the theme runs the loop.' },
        { t: 'code', x: "add_filter( 'the_content', function ( $content ) {\n    if ( ! is_singular( array( 'post', 'page' ) ) ) {\n        return $content;   // not a single view\n    }\n    if ( ! in_the_loop() || ! is_main_query() ) {\n        return $content;   // a widget or a related-posts loop\n    }\n\n    return $content . do_shortcode( '[print_button]' );\n} );" },
        { t: 'warn', x: 'Never edit the parent theme’s `functions.php` or its `single.php`. The next theme update overwrites both and your button disappears with no error message. Use a child theme, or a two-file plugin in `wp-content/plugins/`, which also survives switching themes entirely.' },
        { t: 'h3', x: 'Block themes and the Site Editor' },
        { t: 'p', x: 'On a block theme, the template route lives in **Appearance → Editor → Templates → Single**. Add a **Shortcode** block or a **Custom HTML** block into the template near the post content, then save. It applies to every post using that template and it is stored in the database rather than in theme files, so it survives updates.' },
        { t: 'cta', tool: 'html-to-pdf', x: 'Testing what your theme actually produces on paper? Convert the page to PDF and read it.' },
        { t: 'h2', x: 'WooCommerce is a different problem' },
        { t: 'p', x: 'Order confirmations, invoices and packing slips are the pages customers most want to print, and they are the ones a URL-based cleaner cannot help with, because they sit behind a login and an order key. A tool fetching that URL gets the login screen.' },
        {
          t: 'ul',
          items: [
            'On order and account pages, use `window.print()` and a real print stylesheet. That prints what the logged-in browser can already see.',
            'Hook the button onto `woocommerce_order_details_after_order_table` for the thank-you and order-detail views.',
            'For the product page, `woocommerce_single_product_summary` at priority 35 puts it under the add-to-cart area.',
            'For proper invoices and packing slips, use a dedicated invoicing plugin. It generates a real PDF server-side with your tax details on it, which is what accountants and customs forms need.',
            'Hide the button, the cart widget, the menu and the upsell blocks in `@media print` or the invoice arrives with a "You may also like" carousel on it.',
          ],
        },
        { t: 'code', x: "add_action( 'woocommerce_order_details_after_order_table', function () {\n    printf(\n        '<button type=\"button\" class=\"pxp-print button\" onclick=\"window.print()\">%s</button>',\n        esc_html__( 'Print this order', 'my-theme' )\n    );\n} );" },
        { t: 'h2', x: 'Which one should you pick' },
        { t: 'p', x: 'If you have fewer than twenty posts, use the Custom HTML block and stop reading. If you publish regularly, spend the fifteen minutes on the shortcode and the filter: it is roughly thirty lines of code, it lives outside the theme, and it means every post you write from now on has the button without you thinking about it. If you would rather not touch PHP at all, a plugin is a perfectly respectable answer.' },
        { t: 'p', x: 'Whichever route you take, the button is only half the job. A button that opens a print dialog full of navigation and sidebars is worse than no button, because now the reader blames you rather than the browser. Pair it with [a print stylesheet](/blog/publishers/print-stylesheet-css), and run the [printer-friendly checklist](/blog/publishers/printer-friendly-website-design) once across your main templates. If you are not on WordPress, the same anchor works everywhere, see [adding a print button to any website](/blog/publishers/print-button-any-website) or generate one on the [button builder](/website-button).' },
        { t: 'cta', tool: 'qr-code', x: 'Printing something readers will act on? Put a QR code on the paper that leads back to the live page.' },
      ],
      faqs: [
        { q: 'What is the easiest way to add a print button in WordPress?', a: 'A Custom HTML block containing a single anchor tag. It takes thirty seconds, needs no plugin and no PHP, and works in every theme. The only drawback is that you have to paste it into each post, which a synced pattern solves.' },
        { q: 'How do I add a print button to every post at once?', a: 'Register a shortcode in a child theme or site-specific plugin, then append it with a the_content filter guarded by is_singular, in_the_loop and is_main_query. Those guards stop the button appearing in excerpts, feeds and related-post widgets.' },
        { q: 'Can I add a print button without a plugin?', a: 'Yes. A print button is one anchor tag or one button element calling window.print(). Neither needs a plugin. Plugins are worth it when you want placement settings, analytics or a cleaned-up output page without writing CSS.' },
        { q: 'Why does my WooCommerce order print with the whole shop menu on it?', a: 'Because the order page has no print stylesheet. Add a @media print block that hides the header, navigation, cart widget, footer and the print button itself, and reset the order table to full width.' },
        { q: 'Should the print button call window.print() or open a cleaner?', a: 'Call window.print() when you have written a good print stylesheet and the page is login-gated. Send the URL to a cleaner when the page is public and you have not written print CSS, because the cleaner does the layout work for you.' },
      ],
      relatedTools: ['html-to-pdf', 'qr-code'],
      relatedPosts: ['print-button-any-website', 'print-stylesheet-css', 'printer-friendly-website-design'],
    },
    {
      slug: 'print-stylesheet-css',
      cluster: 'publishers',
      title: 'How to write a print stylesheet that actually works',
      metaTitle: 'Write a Print Stylesheet That Actually Works',
      metaDescription:
        'A working @media print stylesheet: hiding chrome, @page margins, break-inside and break-after, printing link URLs with attr(href), and six bugs that break it.',
      published: '2026-02-11',
      updated: '2026-08-26',
      readMinutes: 10,
      intent: 'howto',
      primaryKeyword: 'print stylesheet css',
      secondaryKeywords: ['@media print css', 'page-break-inside avoid', 'css print link url attr href', '@page margin css', 'css print not working'],
      entities: ['CSS', 'Mozilla Developer Network', 'Google Chrome DevTools', 'WebKit', 'Firefox', 'Safari', 'CSS Paged Media', 'W3C'],
      answer:
        'Wrap print rules in @media print, hide navigation and widgets, reset the article container to a single block-level column, set margins with @page, and control pagination with break-inside: avoid on figures and break-after: avoid on headings. Ship the legacy page-break-* aliases alongside the modern properties, because engines still disagree.',
      body: [
        { t: 'p', x: 'Print CSS is the last unloved stylesheet on most sites, and unusually cheap to get right: about forty lines takes you from "the nav bar owns sheet one" to something a reader would keep. What follows is a stylesheet you can paste and trim, plus what will break it.' },
        { t: 'h2', x: 'Start from the preview, not from the CSS' },
        { t: 'p', x: 'Open your own article and press Ctrl+P before you write a single rule. That preview is the specification. Note every element that should not be there, every place the text is clipped, and every page that is blank. You will usually find the same six problems on every template, and you will fix them once.' },
        { t: 'note', x: 'In Chrome DevTools you can press Ctrl+Shift+P, run **Show Rendering**, and set **Emulate CSS media type** to `print`. That is fast for iterating on colours and hidden elements, but it does **not** paginate: page breaks, `@page` margins and orphan control only appear in the real print preview. Use both.' },
        { t: 'h2', x: 'Layer 1: hide what paper does not need' },
        { t: 'code', x: '@media print {\n  /* Interface that means nothing on paper */\n  nav, aside, footer, form, video, iframe, dialog,\n  .site-header, .sidebar, .comments, .newsletter,\n  .share-buttons, .cookie-banner, .related-posts,\n  [role="banner"], [role="navigation"], [role="complementary"],\n  [data-print="hide"] {\n    display: none !important;\n  }\n\n  /* Give the article the whole sheet */\n  html, body {\n    margin: 0;\n    padding: 0;\n    width: auto;\n    background: #fff;\n    color: #000;\n    font: 11pt/1.45 Georgia, "Times New Roman", serif;\n  }\n\n  main, article, .content, .entry-content {\n    display: block;      /* flex and grid fragment badly across pages */\n    float: none;\n    width: auto;\n    max-width: none;\n    margin: 0;\n    padding: 0;\n    overflow: visible;   /* a clipped wrapper prints one page and stops */\n    height: auto;\n  }\n}' },
        { t: 'p', x: 'Three of those lines do most of the work. `display: block` on the article container matters because flex and grid containers fragment unpredictably across pages, and a two-column card grid will happily slice a card in half at the page boundary. `overflow: visible` and `height: auto` matter because a wrapper with `height: 100vh` or `overflow: hidden` truncates your document to exactly one page, which is the single most common cause of "only the first page prints".' },
        { t: 'h2', x: 'Layer 2: the page box and the breaks' },
        { t: 'code', x: '@page {\n  margin: 18mm 16mm 20mm 16mm;   /* top right bottom left */\n}\n\n@media print {\n  /* Never split these */\n  figure, table, pre, blockquote, img, li, .card {\n    break-inside: avoid;\n    page-break-inside: avoid;      /* legacy alias, still honoured by some engines */\n  }\n\n  /* Never strand a heading at the foot of a page */\n  h1, h2, h3, h4 {\n    break-after: avoid;\n    page-break-after: avoid;\n  }\n\n  /* At least three lines of a paragraph on each side of a break */\n  p, li { orphans: 3; widows: 3; }\n\n  /* Repeat table headers on every page */\n  thead { display: table-header-group; }\n  tfoot { display: table-footer-group; }\n\n  /* Optional: a wide table gets its own landscape sheet (Chromium 110+) */\n  @page wide { size: A4 landscape; }\n  .table-wide { page: wide; }\n}' },
        { t: 'warn', x: 'Do not put `size: A4` on the bare `@page` rule of a site with an international audience. A reader on US Letter then gets an A4 page scaled or clipped onto Letter paper. Setting only the margin is portable; the paper size belongs to the person holding the printer.' },
        {
          t: 'table',
          caption: 'What is safe to rely on, as of 2026.',
          head: ['What you want', 'Modern property', 'Ship alongside it', 'Reality check'],
          rows: [
            ['Keep a figure whole', '`break-inside: avoid`', '`page-break-inside: avoid`', 'Solid in Chromium and Safari. Firefox is patchy on flex and grid children'],
            ['Start a section on a fresh sheet', '`break-before: page`', '`page-break-before: always`', 'Works everywhere. Never apply it to the first heading or you get a blank opening sheet'],
            ['Keep a heading with its text', '`break-after: avoid`', '`page-break-after: avoid`', 'Chromium honours it. Firefox often ignores it on headings'],
            ['No stranded single lines', '`orphans: 3; widows: 3`', 'nothing', 'Chromium and Safari only. Firefox has never implemented it'],
            ['Set the paper margins', '`@page { margin: 18mm }`', 'nothing', 'Widely supported, but the user can still override it in the print dialog'],
            ['Repeat table headers', '`thead { display: table-header-group }`', 'nothing', 'Reliable, and one of the highest-value rules on this list'],
            ['Force background colours', '`print-color-adjust: exact`', '`-webkit-print-color-adjust: exact`', 'A request, not a guarantee. Never let a background colour carry meaning'],
          ],
        },
        { t: 'h2', x: 'Layer 3: make the links mean something' },
        { t: 'p', x: 'On paper a hyperlink is decoration. Printing the destination after the link text turns a printout into a document a reader can act on, which matters most for documentation, references and anything academic.' },
        { t: 'code', x: '@media print {\n  a { color: #000; text-decoration: underline; }\n\n  /* Print the destination after external links */\n  a[href^="http"]::after {\n    content: " (" attr(href) ")";\n    font-size: 85%;\n    word-break: break-all;   /* long URLs must not overflow the sheet */\n  }\n\n  /* ...but not for these */\n  a[href^="#"]::after,\n  a[href^="mailto:"]::after,\n  a[href^="tel:"]::after,\n  a[href^="javascript:"]::after,\n  a.no-print-url::after,\n  nav a::after {\n    content: "";\n  }\n\n  /* Expand abbreviations too */\n  abbr[title]::after { content: " (" attr(title) ")"; }\n}' },
        { t: 'tip', x: 'Add `a.no-print-url` to any link whose visible text is already the URL, or you will print `https://example.com (https://example.com)` on every reference line. The `nav a::after` reset is belt and braces for themes that keep a breadcrumb visible on paper.' },
        { t: 'h2', x: 'Layer 4: colour, images and the dark-mode trap' },
        { t: 'p', x: 'The nastiest modern print bug is dark mode. If your colour tokens are redefined in a `prefers-color-scheme: dark` block and your print block does not redefine them, a reader whose operating system is set to dark gets a solid black A4 rectangle and an empty toner cartridge. Print styles must come after, and must reassert the colours.' },
        { t: 'code', x: '@media print {\n  /* Reassert light values regardless of the reader\'s colour scheme */\n  :root {\n    --bg: #fff;\n    --fg: #000;\n    --muted: #444;\n    --line: #999;\n  }\n\n  body { background: #fff !important; color: #000 !important; }\n\n  img, svg, canvas {\n    max-width: 100% !important;\n    height: auto !important;\n    break-inside: avoid;\n  }\n\n  /* Keep code blocks readable and unbroken */\n  pre, code {\n    font-family: ui-monospace, "SFMono-Regular", Menlo, monospace;\n    font-size: 9pt;\n    white-space: pre-wrap;\n    word-wrap: break-word;\n    border: 1px solid #ccc;\n  }\n\n  /* A fixed header repeats or clips on every sheet */\n  .site-header, .toolbar, [style*="position:fixed"] {\n    position: static !important;\n  }\n}' },
        { t: 'p', x: 'Lazy-loaded images are the other silent failure. Chromium now eagerly loads `loading="lazy"` images before printing, but a custom IntersectionObserver loader will still print blank boxes for anything the reader never scrolled past. If you rolled your own, force the images in before the dialog opens:' },
        { t: 'code', x: "// Load every deferred image before the print dialog paints\nwindow.addEventListener('beforeprint', () => {\n  document.querySelectorAll('img[data-src]').forEach((img) => {\n    if (!img.src) img.src = img.dataset.src;\n  });\n  document.querySelectorAll('img[loading=\"lazy\"]').forEach((img) => {\n    img.loading = 'eager';\n  });\n});\n\n// Same event, if you need to expand collapsed sections\nwindow.addEventListener('beforeprint', () => {\n  document.querySelectorAll('details').forEach((d) => (d.open = true));\n});" },
        { t: 'h2', x: 'The six bugs you will actually hit' },
        {
          t: 'table',
          head: ['Symptom', 'Cause', 'Fix'],
          rows: [
            ['Only the first page prints', '`height: 100vh` or `overflow: hidden` on a wrapper', 'Set both to `auto` and `visible` inside `@media print`'],
            ['The whole sheet is solid black', 'Dark-mode tokens applied and never overridden for print', 'Redeclare the colour custom properties inside the print block'],
            ['Images are missing', 'Lazy loading, or the image is a CSS background', 'Force-load on `beforeprint`; use `<img>` for content images, never `background-image`'],
            ['A card grid slices a card in half', 'Flex and grid fragmentation', 'Set the container to `display: block` for print'],
            ['The header appears on every sheet', '`position: fixed`', 'Set `position: static` in `@media print`'],
            ['A blank sheet at the end', 'A trailing `break-after: page`, or a tall hidden footer', 'Audit the last break rule; hide the footer entirely'],
          ],
        },
        { t: 'h2', x: 'A testing routine that catches the rest' },
        {
          t: 'steps',
          items: [
            { h: 'Test the real preview in three engines', x: 'Chrome, Firefox and Safari paginate differently. Firefox in particular ignores orphans, widows and some break-after rules, so a layout that is perfect in Chrome can strand headings in Firefox.' },
            { h: 'Test both paper sizes', x: 'Switch the print dialog between A4 and Letter. A4 is 20mm narrower and 17mm taller than Letter, which is enough to push a wide table over the edge.' },
            { h: 'Test in dark mode', x: 'Set the operating system to dark, reload and open the preview. This catches the black-page bug that never shows up on a developer machine set to light.' },
            { h: 'Test your longest and your widest page', x: 'The longest article finds your break bugs; the widest data table finds your overflow bugs. Everything else sits between them.' },
            { h: 'Save as PDF and read it', x: 'Print to PDF and actually read the file at 100 percent. Check that the text is selectable, that the URLs are expanded, and that nothing is clipped at the margin.' },
            { h: 'Check the headers you cannot control', x: 'The browser adds its own title, URL, date and page numbers. You cannot remove them from CSS; the reader turns them off. Design assuming they are on.' },
          ],
        },
        { t: 'cta', tool: 'html-to-pdf', x: 'Render a page to PDF to see exactly what your print stylesheet produces.' },
        { t: 'cta', tool: 'pdf-to-text', x: 'Extract the text from your printed PDF to confirm the text layer survived intact.' },
        { t: 'p', x: 'Now give readers a way to reach it: [a print button on any site](/blog/publishers/print-button-any-website), or on WordPress [the button routes](/blog/publishers/add-print-button-to-wordpress). For the wider audit, run through [making your website printer-friendly](/blog/publishers/printer-friendly-website-design). To see how a page behaves with no print CSS at all, paste it into the [web page printer](/print).' },
      ],
      faqs: [
        { q: 'Why is my print CSS not working?', a: 'Three usual causes: the rules sit outside a @media print block, a dark-mode block later in the cascade overrides them, or you tested with the DevTools media emulator, which does not paginate. Always confirm in the real Ctrl+P preview.' },
        { q: 'What is the difference between break-inside and page-break-inside?', a: 'break-inside is the modern CSS Fragmentation property; page-break-inside is the legacy alias. Browsers map the old names onto the new ones, but engine support still differs in edge cases, so shipping both costs one line and removes the guesswork.' },
        { q: 'How do I print the URL of a link in CSS?', a: 'Use a[href^="http"]::after { content: " (" attr(href) ")"; }. Add resets with content: "" for anchors, mailto, tel and any link whose visible text is already the URL, and set word-break: break-all so long URLs do not overflow.' },
        { q: 'Can I control the paper size from CSS?', a: 'Yes, with @page { size: A4 } or size: letter, but you usually should not. A reader on the other paper size gets scaled or clipped output. Set only the margins and let the print dialog decide the sheet.' },
        { q: 'Can I remove the browser header and footer with CSS?', a: 'No. The page title, URL, date and page numbers are added by the browser, outside the document, and only the reader can turn them off in the print dialog. Design your margins on the assumption that they are switched on.' },
      ],
      relatedTools: ['html-to-pdf', 'pdf-to-text'],
      relatedPosts: ['printer-friendly-website-design', 'add-print-button-to-wordpress', 'fix-web-page-printing-problems'],
    },
    {
      slug: 'printer-friendly-website-design',
      cluster: 'publishers',
      title: 'How to make your website printer-friendly',
      metaTitle: 'How to Make Your Website Printer-Friendly',
      metaDescription:
        'Ten things publishers get wrong when readers print, how to test in print preview, and a checklist covering nav, dark mode, links, tables, images and QR codes.',
      published: '2026-03-17',
      updated: '2026-07-24',
      readMinutes: 8,
      intent: 'listicle',
      primaryKeyword: 'printer friendly website',
      secondaryKeywords: ['printer friendly web design', 'website print preview test', 'print friendly page checklist', 'why does my website print badly', 'print css audit'],
      entities: ['CSS', 'Google Chrome', 'Safari', 'Firefox', 'A4', 'US Letter', 'QR code', 'WCAG'],
      answer:
        'Open your own pages in print preview and fix what you see: hide navigation and widgets, override dark-mode colours, expand link URLs, keep tables and figures whole, load lazy images, and print the page title, URL and date. Most sites fail because nobody has ever looked at the preview.',
      body: [
        { t: 'p', x: 'A two-minute experiment: open the ten sites you read most, press Ctrl+P on an article page, and count how many produce something you would keep. Usually one or two. Not because print CSS is hard, but because nobody on those teams ever opened the preview.' },
        { t: 'p', x: 'The whole discipline fits in one sentence: **the printed page should be the article, plus enough context to know where it came from, and nothing else.** Everything below is a way of failing that sentence.' },
        { t: 'h2', x: '1. The navigation eats the first sheet' },
        { t: 'p', x: 'A sticky header, a mega menu and a search box print at full size at the top of sheet one, and a long menu takes the whole sheet. Hide `nav`, `header`, `aside`, `footer` and anything with `role="navigation"` in `@media print`, and the article starts where it should.' },
        { t: 'h2', x: '2. Dark mode leaks onto paper' },
        { t: 'p', x: 'The expensive one. If your colour tokens live in a `prefers-color-scheme: dark` block and your print styles do not reset them, every reader on a dark OS prints a solid black rectangle. It costs them a visible slice of a cartridge and is invisible to you, because your machine is light. Test in dark mode.' },
        { t: 'h2', x: '3. Links become meaningless' },
        { t: 'p', x: 'Blue underlined text on paper is noise. Expand the destination with `content: " (" attr(href) ")"` on external links and reset it to empty for anchors and navigation. On reference-heavy content this one rule is the difference between a printout and a document.' },
        { t: 'h2', x: '4. Images are missing, or enormous' },
        {
          t: 'ul',
          items: [
            'A **CSS background image** does not print unless the reader ticks "Background graphics", which is off by default. Content images belong in an `<img>` tag.',
            '**Lazy-loaded images** below the fold never loaded, so they print blank. Force them in on a `beforeprint` listener.',
            'A **hero image** takes the top half of sheet one for no gain. Hide it, or cap it at about 60mm.',
            'Set `max-width: 100%` and `height: auto`, or a 2000px figure is clipped at the margin.',
          ],
        },
        { t: 'h2', x: '5. Tables are guillotined at the right edge' },
        { t: 'p', x: 'A table wider than the text column is cut off silently, with no scrollbar to hint anything is missing. Give wide tables a landscape page rule, reduce the print font size, or at minimum add `thead { display: table-header-group }` so page two still has column headers.' },
        { t: 'h2', x: '6. The article is inside a scroll container' },
        { t: 'p', x: 'Any wrapper with `overflow: hidden`, `height: 100vh` or a fixed height truncates the printed document to one page. It is the commonest cause of "the site only prints the first page", and the fix is two lines.' },
        { t: 'h2', x: '7. You paginate through the middle of things' },
        { t: 'p', x: 'Figures split from captions, headings stranded at the foot of a sheet, code broken across the fold, a single orphaned line. `break-inside: avoid` on figures, tables and code, `break-after: avoid` on headings, and `orphans: 3; widows: 3` cover almost all of it, [the full rules](/blog/publishers/print-stylesheet-css).' },
        { t: 'h2', x: '8. The paper has no identity' },
        { t: 'p', x: 'A printed article that does not say where it came from is worthless as a reference and as marketing. Add a print-only block with the site name, page title, publication date and canonical URL. Browsers add their own header and footer, but readers can switch those off.' },
        { t: 'h2', x: '9. You send readers to a worse "print version"' },
        { t: 'p', x: 'A separate `?print=1` page is now usually a downgrade: it goes stale, loses images, forks your analytics and gives search engines another URL to index. A print stylesheet on the canonical page does the same job. If you keep one, canonicalise it back to the article.' },
        { t: 'h2', x: '10. The pages people actually print get the least attention' },
        { t: 'p', x: 'Print traffic is wildly uneven. A tiny minority of pages account for almost all of it, and they rarely get design attention.' },
        {
          t: 'table',
          caption: 'Where to spend your print CSS budget.',
          head: ['Page type', 'How often it gets printed', 'What must survive'],
          rows: [
            ['Recipe', 'Constantly', 'Ingredients with quantities, method, oven temperature, yield, timings'],
            ['Order confirmation or receipt', 'Constantly', 'Order number, date, line items, totals, tax, seller address'],
            ['Ticket or booking', 'Constantly', 'The barcode or QR code, at a size a scanner can read'],
            ['Documentation and API reference', 'Often', 'Code blocks unwrapped, unbroken and monospaced'],
            ['Long-form article', 'Sometimes', 'Body text, captions, the URL and the date'],
            ['Terms or policy', 'Rarely, but it matters', 'Every clause, numbered, with the effective date'],
          ],
        },
        { t: 'warn', x: 'Size barcodes and QR codes properly. A QR code needs a quiet zone of four modules on every side and roughly 20mm square as a minimum for a short URL, 25mm on a tired office laser. Shrunk into a 12mm corner slot it is decoration, not a link.' },
        { t: 'cta', tool: 'qr-code', x: 'Generate a QR code at a size that still scans after a laser printer has had its way with it.' },
        { t: 'h2', x: 'The checklist' },
        {
          t: 'table',
          caption: 'Run this against your article template, your commerce templates and your longest page.',
          head: ['Check', 'How to test', 'Pass looks like'],
          rows: [
            ['Nav and widgets hidden', 'Ctrl+P on any article', 'The title is at the top of sheet one'],
            ['Dark mode neutralised', 'Set the OS to dark, reload, Ctrl+P', 'White paper, black text'],
            ['Single column', 'Look at the preview', 'No sidebar, no floated rails, full text width'],
            ['Link URLs expanded', 'Read a paragraph with links in it', 'The destination in brackets after the text'],
            ['Images present and sized', 'Scroll to the bottom first, then Ctrl+P', 'Every figure appears, none clipped'],
            ['Tables intact', 'Print your widest table', 'All columns visible, headers repeated on page two'],
            ['Page identity', 'Look at the first sheet', 'Site name, title, date and canonical URL'],
            ['A visible way in', 'Look at the live page', 'A print button near the title or at the end'],
          ],
        },
        { t: 'h2', x: 'Why it is worth the afternoon' },
        { t: 'p', x: 'A good print stylesheet is a good reading stylesheet with the interface removed, so the work overlaps with accessibility, reader modes and anything an assistant reads. It also fixes a quiet failure mode: readers who get nine sheets of clutter never file a bug. They just decide your site is annoying.' },
        { t: 'cta', tool: 'html-to-pdf', x: 'Render your template to PDF and check the result at full size before you ship.' },
        { t: 'p', x: 'Next: the code is in [writing a print stylesheet](/blog/publishers/print-stylesheet-css), the button in [adding a print button to any website](/blog/publishers/print-button-any-website), and on WordPress start with [the WordPress routes](/blog/publishers/add-print-button-to-wordpress). [Web page printing problems](/blog/print/fix-web-page-printing-problems) is the same list from the reader end.' },
      ],
      faqs: [
        { q: 'How do I test whether my website is printer-friendly?', a: 'Press Ctrl+P on your longest article, your widest table page and one commerce page, in Chrome, Firefox and Safari, with the operating system set to dark mode at least once. The preview is the whole test; almost every problem is visible in it.' },
        { q: 'Do I still need a separate printer-friendly page?', a: 'No. A print stylesheet on the canonical URL does the job without a second page to keep in sync, index and analyse. If you already have one, canonicalise it to the article so search engines do not treat it as duplicate content.' },
        { q: 'Why does my site print a solid black page?', a: 'Your dark-mode colour tokens are applied and never overridden for print. Redeclare the background and text colours inside the @media print block, which must come after the prefers-color-scheme block in the cascade.' },
        { q: 'Should the print button be at the top or the bottom of an article?', a: 'Near the title works best for recipes, tickets and receipts, where printing is the point. For long articles, put it at the end as well, since that is where a reader decides the piece is worth keeping.' },
        { q: 'How big does a QR code need to be on a printed page?', a: 'About 20mm square as a hard minimum for a short URL, 25mm to be comfortable, with a quiet zone of four modules of clear space on every side. Longer URLs need more modules and therefore more physical size.' },
      ],
      relatedTools: ['qr-code', 'html-to-pdf'],
      relatedPosts: ['print-stylesheet-css', 'add-print-button-to-wordpress', 'print-button-any-website'],
    },
    {
      slug: 'print-button-any-website',
      cluster: 'publishers',
      title: 'How to add a print or PDF button to any website',
      metaTitle: 'Add a Print or PDF Button to Any Website',
      metaDescription:
        'Copy-paste a print or PDF button into any site: a plain HTML anchor, a CSP-safe window.print() button, plus notes for Squarespace, Wix, Shopify and Webflow.',
      published: '2026-04-08',
      updated: '2026-08-11',
      readMinutes: 8,
      intent: 'howto',
      primaryKeyword: 'add print button to website',
      secondaryKeywords: ['html print button code', 'window.print() button', 'squarespace print button', 'shopify print button', 'print page button javascript'],
      entities: ['HTML', 'JavaScript', 'Squarespace', 'Wix', 'Shopify', 'Webflow', 'Ghost', 'Content Security Policy', 'Liquid'],
      answer:
        'Paste a single anchor tag that opens the current URL in a printer-friendly view, or a button element calling window.print(). Both are a few lines of plain HTML and work in any CMS or static site. Hide the button in @media print, and use the anchor form inside Wix, where embeds are iframes.',
      body: [
        { t: 'p', x: 'A print button is one HTML element. Every plugin, widget and paid service on this subject is packaging around that element. Below are the two versions worth using, when each applies, and where to paste them in the platforms that make it awkward.' },
        { t: 'h2', x: 'Decide what the button should do first' },
        {
          t: 'table',
          caption: 'Two behaviours, two different requirements.',
          head: ['Behaviour', 'What it needs from you', 'Best for'],
          rows: [
            ['`window.print()` on the current page', 'A print stylesheet you have written and tested', 'Login-gated pages: orders, accounts, dashboards, invoices'],
            ['Open the URL in a printer-friendly view', 'Nothing. The cleaner does the layout work', 'Public pages, especially when you have no print CSS yet'],
            ['Both, side by side', 'A stylesheet, plus one extra link', 'Publishers who want a paper option and a PDF option'],
          ],
        },
        { t: 'p', x: 'If you have not written print CSS, the second option is strictly better today and you can add the first later. If your page is behind a login, the second option cannot work at all: a cleaner fetching that URL gets the sign-in screen, not the order.' },
        { t: 'h2', x: 'Version 1: the plain anchor' },
        { t: 'p', x: 'No framework, no build step, no dependency. It degrades gracefully: with JavaScript disabled it still opens the cleaner, just without the current URL prefilled.' },
        { t: 'code', x: '<!-- Printer-friendly link. Paste anywhere HTML is allowed. -->\n<a class="pxp-print"\n   href="https://printxpdf.com/print?url="\n   onclick="this.href=\'https://printxpdf.com/print?url=\'+encodeURIComponent(location.href)"\n   target="_blank" rel="noopener">&#9113; Print / PDF</a>\n\n<style>\n.pxp-print{display:inline-flex;align-items:center;gap:.5rem;padding:10px 18px;\n  font:700 14px/1 system-ui,-apple-system,sans-serif;letter-spacing:.03em;\n  text-decoration:none;color:inherit;border:2px solid currentColor;border-radius:6px}\n.pxp-print:hover{background:currentColor;color:#fff}\n@media print{.pxp-print{display:none !important}}\n</style>' },
        { t: 'p', x: '`encodeURIComponent` is the part people leave out, and it is why buttons break on pages with query strings or accented characters in the path. The `@media print` rule at the bottom is the part everyone leaves out, and it is why printed pages have a "Print" button printed on them.' },
        { t: 'h2', x: 'Version 2: window.print(), CSP-safe' },
        { t: 'p', x: 'If your site sends a strict `Content-Security-Policy` header, an inline `onclick` will be blocked and the button will silently do nothing. Attach a listener instead. Use a real `<button type="button">`, not an anchor with a `javascript:` href: buttons are keyboard-operable and announced correctly by screen readers, and `type="button"` stops it submitting a surrounding form.' },
        { t: 'code', x: '<button type="button" class="pxp-print" data-print-page>\n  &#9113; Print this page\n</button>\n\n<script>\n  document.querySelectorAll(\'[data-print-page]\').forEach(function (btn) {\n    btn.addEventListener(\'click\', function () {\n      window.print();\n    });\n  });\n\n  // Optional: expand collapsed sections before the dialog paints\n  window.addEventListener(\'beforeprint\', function () {\n    document.querySelectorAll(\'details\').forEach(function (d) { d.open = true; });\n  });\n</script>' },
        { t: 'p', x: 'To open the cleaner from a button instead of an anchor, swap the click handler for `window.open(\'https://printxpdf.com/print?url=\' + encodeURIComponent(location.href), \'_blank\', \'noopener\')`.' },
        { t: 'tip', x: 'Do not ship an icon on its own. A printer glyph with no label is unrecognisable to a good number of readers under thirty, who have never used one. Label it "Print / PDF", and if you must go icon-only, add an `aria-label`.' },
        { t: 'h2', x: 'Where to paste it, platform by platform' },
        {
          t: 'table',
          head: ['Platform', 'Where it goes', 'Gotcha'],
          rows: [
            ['Static site (Hugo, Jekyll, Eleventy, Astro)', 'The post layout partial, next to the title or after the content', 'None. Put it in the layout once and every page has it'],
            ['Squarespace', 'A **Code Block** where you want the button', 'Site-wide code injection needs a Business plan or higher; a per-page Code Block does not'],
            ['Wix', 'Add → Embed Code → Embed HTML', 'The embed is an **iframe**, so `window.print()` prints only the empty embed. Use the anchor version'],
            ['Webflow', 'An **Embed** element in the Designer', 'Embeds render inline, not in an iframe, so both versions work'],
            ['Shopify', '`sections/main-article.liquid` or `main-page.liquid`', 'Use Liquid to build the URL: `{{ canonical_url | url_encode }}`'],
            ['Ghost', 'The post template, or a Code Injection block', 'Handlebars gives you the absolute URL: `{{url absolute="true"}}`'],
            ['Email templates', 'The anchor version only', 'No JavaScript runs in email. Hard-code the article URL into the href'],
            ['Notion, Substack, Medium', 'Not possible', 'No custom HTML. Link to the cleaner with the URL written out in full'],
          ],
        },
        { t: 'p', x: 'The Wix case is worth spelling out because it wastes a lot of afternoons. Wix HTML embeds run inside an iframe on a different origin. Calling `window.print()` there prints the iframe, which contains nothing but your button, and `parent.print()` is blocked by the same-origin policy. The anchor, which simply navigates a new tab, is unaffected.' },
        { t: 'h2', x: 'Putting it in place' },
        {
          t: 'steps',
          items: [
            { h: 'Pick the behaviour', x: 'Cleaner link for public pages with no print CSS. `window.print()` for login-gated pages, or for public pages where you have already written and tested a stylesheet.' },
            { h: 'Paste it into the template, not the page', x: 'One edit in a layout beats fifty edits in fifty posts. On a hosted CMS, use a synced pattern, a reusable block or a saved section so there is still one source of truth.' },
            { h: 'Place it where the decision happens', x: 'Near the title for recipes, tickets and receipts. At the end as well for long articles, which is where a reader decides the piece is worth keeping.' },
            { h: 'Hide it on paper', x: 'Add `@media print { .pxp-print { display: none !important } }`. Do this now, because you will not notice it until a reader mentions it.' },
            { h: 'Check the keyboard and the screen reader', x: 'Tab to it, press Enter, and confirm it announces as a link or a button with a real name. `type="button"` on buttons, `rel="noopener"` on anchors with `target="_blank"`.' },
            { h: 'Print the result and read it', x: 'Do not ship on the strength of the preview thumbnail. Print one page, or save it as a PDF and read it at full size.' },
          ],
        },
        { t: 'cta', tool: 'html-to-pdf', x: 'Check what your page really produces on paper before you put a button on it.' },
        { t: 'h2', x: 'Generate one instead of writing it' },
        { t: 'p', x: 'If you would rather pick a colour, size and label than edit CSS, the [button builder](/website-button) produces the same markup with inline styles, ready to paste into any CMS. On WordPress specifically, [the plugin, block and shortcode routes](/blog/publishers/add-print-button-to-wordpress) cover the options in more detail, and [the WordPress plugin page](/wordpress) has the one-click version.' },
        { t: 'cta', tool: 'qr-code', x: 'Add a QR code so the printed sheet still leads back to the live page.' },
        { t: 'p', x: 'A button without a stylesheet is only half a feature. When you have the button in place, spend an afternoon on [a print stylesheet](/blog/publishers/print-stylesheet-css) and run the [printer-friendly checklist](/blog/publishers/printer-friendly-website-design) over your main templates.' },
      ],
      faqs: [
        { q: 'What is the HTML code for a print button?', a: 'The minimum is <button type="button" onclick="window.print()">Print</button>. Use type="button" so it never submits a surrounding form, and add a @media print rule hiding the button, or it prints on the page itself.' },
        { q: 'Should I use a link or a button for printing?', a: 'A button element when it triggers window.print(), because it performs an action on the current page. An anchor when it navigates somewhere, such as opening the page in a printer-friendly view in a new tab. Do not use an anchor with a javascript: href.' },
        { q: 'Why does my print button not work on Wix?', a: 'Wix HTML embeds run inside an iframe, so window.print() prints the empty embed rather than the page, and parent.print() is blocked cross-origin. Use the anchor version, which opens the page URL in a new tab instead.' },
        { q: 'How do I pass the current page URL to a print tool?', a: 'Append it as an encoded query parameter: encodeURIComponent(location.href) in JavaScript, or the url_encode filter in Shopify Liquid. Encoding matters because raw query strings and accented characters break the link.' },
        { q: 'Does a print button need JavaScript?', a: 'Not if it is an anchor pointing at a printer-friendly view, which works with scripting disabled. It does if it calls window.print(). The anchor version is also the only one that works inside an email template.' },
      ],
      relatedTools: ['html-to-pdf', 'qr-code'],
      relatedPosts: ['add-print-button-to-wordpress', 'print-stylesheet-css', 'printer-friendly-website-design'],
    },
  ],
}
