import type { Cluster } from '../types'

export const qrCodes: Cluster = {
  slug: 'qr-codes',
  name: 'QR codes for print',
  title: 'QR codes for print: size, contrast and error correction that actually work',
  metaTitle: 'QR Codes for Print: Size, Contrast, Error Levels',
  metaDescription:
    'Make QR codes that scan off paper every time. Real millimetre sizes, the 10:1 distance rule, quiet zones, error correction levels and vector export settings.',
  intro:
    'A QR code that works on your screen can fail completely on paper. Ink spreads, laminate reflects, the code gets scaled down to fit a corner of the card, and the quiet zone disappears into a photo. These guides cover the numbers that decide whether a printed code scans: minimum module size, the 10:1 distance rule, error correction levels L through H, contrast, and why you should always export vector rather than a small PNG.',
  answer:
    'A printed QR code scans reliably when it is exported as vector, printed at least 2 cm wide, surrounded by a four-module quiet zone, and set in dark ink on a light background. Use the 10:1 rule: the code must be at least one tenth of the scanning distance.',
  primaryKeyword: 'qr code for print',
  entities: ['QR Code', 'Denso Wave', 'ISO/IEC 18004', 'Reed-Solomon', 'SVG', 'vCard', 'Google Lens', 'Adobe Illustrator'],
  icon: '▩',
  tools: ['qr-code', 'jpg-to-pdf', 'html-to-pdf', 'compress-pdf'],
  posts: [
    {
      slug: 'qr-code-for-print',
      cluster: 'qr-codes',
      title: 'How to make a QR code that actually scans off paper',
      metaTitle: 'How to Make a QR Code That Scans Off Paper',
      metaDescription:
        'Vector export, minimum size, quiet zone, contrast and error correction levels L, M, Q and H explained, plus how to test a QR code before you print 500 copies.',
      published: '2026-01-27',
      updated: '2026-08-18',
      readMinutes: 7,
      intent: 'howto',
      primaryKeyword: 'qr code for print',
      secondaryKeywords: ['qr code svg for printing', 'qr code error correction level', 'qr code quiet zone', 'printed qr code not scanning', 'high resolution qr code'],
      entities: ['QR Code', 'Denso Wave', 'ISO/IEC 18004', 'Reed-Solomon', 'SVG', 'PNG', 'CMYK', 'Google Lens', 'Adobe Illustrator'],
      answer:
        'Export the QR code as vector SVG, print it at least 2 cm (0.8 in) wide, keep a quiet zone of four blank modules on every side, and use dark ink on a light background. Choose error correction level M for most jobs, then scan a real test print before running the full batch.',
      body: [
        { t: 'p', x: 'A printed QR code almost never fails because of the code. It fails because someone exported a 200-pixel PNG and scaled it up, printed it pale grey over a photograph, squeezed it into a 12 mm corner, or cropped away the margin. All four are avoidable in two minutes.' },
        { t: 'p', x: 'The QR Code was designed by Denso Wave in 1994 and standardised as ISO/IEC 18004, a standard unusually specific about the physical conditions a symbol needs. The four rules below come straight out of it.' },
        { t: 'h2', x: 'Rule 1: Export vector, never a small raster' },
        { t: 'p', x: 'A QR code is a grid of black squares, which is a vector drawing rather than a photograph. An SVG or PDF stays perfectly sharp at 15 mm on a card and at 3 metres on a banner; a PNG is locked to the pixel grid it was made at.' },
        { t: 'p', x: 'If you must use raster, do the arithmetic. At 300 DPI one millimetre is 11.8 pixels, so a 25 mm code needs 295 pixels square as a minimum. Export at 1024 px or more and let the layout scale it **down**, never up.' },
        {
          t: 'table',
          caption: 'Which file format to hand to a printer.',
          head: ['Format', 'Good for', 'Watch out for'],
          rows: [
            ['SVG', 'Anything a designer or print shop handles', 'Nothing. Scales to any size with no loss of edge quality.'],
            ['Print-ready PDF', 'Sending straight to a printer', 'Check the driver is not scaling the page.'],
            ['PNG, 1024 px or larger', 'Documents, slides, email signatures', 'Never enlarge after export. Re-generate at the size you need.'],
            ['PNG, 256 px or smaller', 'Screens only', 'Prints as soft, blurred modules. The most common cause of a failed scan.'],
            ['JPG', 'Nothing at all', 'Compression smears the hard black-and-white edges a scanner reads.'],
          ],
        },
        { t: 'note', x: 'The [QR code generator](/tools/qr-code) exports SVG, PNG up to 2048 px and a print-ready PDF, all in your browser, so what you type never leaves your machine.' },
        { t: 'h2', x: 'Rule 2: 2 cm is the practical floor' },
        { t: 'p', x: 'The smallest square in a QR code is a **module**. A version 1 symbol is 21 modules across and every version up adds four, so a typical short URL at error correction M lands on version 3, or 29 modules across.' },
        { t: 'p', x: 'Consumer printing and phone cameras need each module to be roughly **0.5 mm** wide; 0.4 mm is where things get unreliable. Twenty-nine modules at 0.5 mm is 14.5 mm, so 15 mm is the theoretical floor. Round up to **20 mm (0.8 in)** for tolerance against cheap paper, ink spread and a shaky hand. For anything read from further away, see [what size a QR code should be](/blog/qr-codes/qr-code-size-for-print).' },
        { t: 'h2', x: 'Rule 3: The quiet zone is part of the code' },
        { t: 'p', x: 'The blank border is not whitespace, it is a required component. ISO/IEC 18004 specifies **four modules of clear margin on all four sides**, and scanners use it to find where the symbol starts and stops. On a 25 mm code with 0.7 mm modules that is a 2.8 mm blank frame.' },
        { t: 'warn', x: 'Do not crop the margin to make the code fit, do not butt it against a photograph, and never place it within 5 mm of a trim edge. Press trimming tolerance is 1 to 2 mm per cut and it will eat your quiet zone.' },
        { t: 'tip', x: 'The generator here defaults its quiet zone slider to 2 modules, fine on screen and marginal on paper. Drag it to **4** before downloading anything you will print.' },
        { t: 'h2', x: 'Rule 4: Dark on light, with real contrast' },
        {
          t: 'ul',
          items: [
            '**Never invert the code.** Light modules on a dark background break older scanners and point-of-sale hardware, even though phone cameras cope.',
            '**Print the dark modules as 100% K**, not rich black. A single ink plate cannot misregister, so module edges stay crisp.',
            '**Avoid red, orange and yellow modules.** Laser scanners read with a red beam and cannot tell red ink from white paper.',
            '**No gradients or photographs behind the code**, and keep a clear tonal gap. Charcoal on cream is fine; mid-grey on light grey is not.',
          ],
        },
        { t: 'h2', x: 'Error correction: L, M, Q and H' },
        { t: 'p', x: 'QR codes carry Reed-Solomon error correction, so a partly damaged symbol still decodes. You choose how much redundancy to spend: more correction means more modules for the same data, which at a fixed size makes the code harder to scan.' },
        {
          t: 'table',
          caption: 'The four error correction levels and when to use each.',
          head: ['Level', 'Data recoverable', 'Effect on the symbol', 'Use it for'],
          rows: [
            ['L (Low)', 'About 7%', 'Smallest, fewest modules', 'Long payloads such as a vCard, on clean flat paper'],
            ['M (Medium)', 'About 15%', 'The default, right most of the time', 'Flyers, cards, menus, posters, packaging'],
            ['Q (Quartile)', 'About 25%', 'Noticeably denser', 'A small centre logo, labels that get scuffed'],
            ['H (High)', 'About 30%', 'Densest for the same data', 'Outdoors, curved bottles, larger logo overlays'],
          ],
        },
        { t: 'p', x: 'The trap is treating H as free insurance. On a 20 mm code it can push module size below 0.4 mm, making the symbol harder to read than the L version would have been. On flat paper indoors, with no logo, M is correct.' },
        { t: 'warn', x: 'A logo in the middle must stay under about 20% of the code area at level H, and must never touch the three large corner squares. Those are the finder patterns and the decoder needs all three.' },
        { t: 'h2', x: 'Test before you print 500 copies' },
        {
          t: 'steps',
          items: [
            { h: 'Print one proof at final size', x: 'On the real stock, at 100% scale. Turn off "fit to page", which silently shrinks the code.' },
            { h: 'Scan with three phones', x: 'A current iPhone, a current Android, and one that is three or four years old. The old phone finds your mistakes.' },
            { h: 'Scan at the real distance and light', x: 'Hold the phone where a customer would. Dim rooms and glossy laminate under a spotlight behave unlike your desk.' },
            { h: 'Follow the link', x: 'Check it lands where you meant, works on mobile, and has no redirect that could expire.' },
            { h: 'Only then run the job', x: 'Keep the SVG and exact payload on file so a reprint is identical.' },
          ],
        },
        { t: 'cta', tool: 'qr-code', x: 'Generate an SVG, PNG or print-ready PDF QR code in your browser. Nothing is uploaded.' },
        { t: 'h2', x: 'Quick diagnosis when a printed code will not scan' },
        {
          t: 'ol',
          items: [
            'Measure it. Under 20 mm on a hand-held piece is the likeliest answer.',
            'Check the blank border. Under four modules of margin, or a photograph running beneath it, breaks detection.',
            'Check the source file. A JPG or a small PNG needs regenerating as SVG.',
            'Shorten the payload. A 900-character vCard makes a dense symbol; a short URL scans from twice the distance.',
          ],
        },
        { t: 'p', x: 'Once the artwork is right, [combine the proofs into one PDF](/blog/convert-to-pdf/images-to-pdf) before sending. For cards, the layout details are in [putting a QR code on a business card](/blog/qr-codes/qr-code-on-business-card).' },
      ],
      faqs: [
        { q: 'Why does my QR code work on screen but not when printed?', a: 'Almost always size or resolution. A code that fills your monitor is huge; the same file at 15 mm on paper has modules under 0.4 mm. Re-export as SVG, print at 20 mm or larger, and keep a four-module quiet zone.' },
        { q: 'What is the minimum size for a printed QR code?', a: 'Twenty millimetres, about 0.8 inches, for anything held in the hand. The absolute technical floor is roughly 15 mm for a short URL, but 20 mm gives you tolerance for paper, ink spread and older phone cameras.' },
        { q: 'Which error correction level should I use?', a: 'Level M, which recovers about 15% of the data, is right for most printed material. Move to Q or H only if you are placing a logo over the centre, printing on a curved surface, or expecting the code to get scuffed.' },
        { q: 'Can I print a QR code in colour?', a: 'Yes, as long as the modules stay clearly darker than the background. Keep the dark modules a deep, desaturated colour and the background near-white. Avoid red, orange or yellow modules, which red-beam laser scanners cannot see.' },
        { q: 'Should I use PNG or SVG for a QR code?', a: 'SVG for anything printed, because it stays sharp at every size. PNG is fine for screens and for documents where you cannot embed vector, but export at 1024 pixels or more and only ever scale it down.' },
      ],
      relatedTools: ['qr-code', 'compress-pdf'],
      relatedPosts: ['qr-code-size-for-print', 'qr-code-on-business-card', 'best-image-format-for-print'],
    },
    {
      slug: 'wifi-qr-code',
      cluster: 'qr-codes',
      title: 'How to make a WiFi QR code guests can scan',
      metaTitle: 'How to Make a WiFi QR Code Guests Can Scan',
      metaDescription:
        'Create a WiFi QR code that joins guests to your network automatically. The WIFI: format explained, iOS and Android support, printing tips and security advice.',
      published: '2026-02-16',
      updated: '2026-07-24',
      readMinutes: 6,
      intent: 'howto',
      primaryKeyword: 'wifi qr code',
      secondaryKeywords: ['wifi qr code generator', 'wifi qr code format', 'guest wifi qr code', 'scan to join wifi', 'print wifi password card'],
      entities: ['WPA2', 'WPA3', 'SSID', 'iOS', 'Android', 'Google Lens', 'Apple Camera', 'Wi-Fi Alliance'],
      answer:
        'A WiFi QR code encodes the plain text WIFI:T:WPA;S:NetworkName;P:Password;; and phones turn it into a one-tap join prompt. iPhones running iOS 11 or later and Android 10 or later read it with the built-in camera, so no app is needed on either side.',
      body: [
        { t: 'p', x: 'Reading a 22-character WPA2 password out loud to a guest is the worst part of hosting anyone. A WiFi QR code fixes it permanently: the guest points a camera at a card on the table, taps once, and is online. No app, no typing, no dictating capital letters.' },
        { t: 'h2', x: 'The format, exactly' },
        { t: 'p', x: 'There is nothing magic inside the code. It is plain text in a convention that Android and iOS both recognise, originally published by ZXing and now supported everywhere:' },
        { t: 'code', x: 'WIFI:T:WPA;S:Cafe Guest;P:flatwhite2026;;' },
        {
          t: 'table',
          caption: 'Every field in a WIFI: payload.',
          head: ['Field', 'Meaning', 'Values'],
          rows: [
            ['T', 'Security type', '`WPA` for WPA, WPA2 and WPA3; `WEP` for ancient routers; `nopass` for an open network'],
            ['S', 'Network name (SSID)', 'Exactly as broadcast, including capitals and spaces'],
            ['P', 'Password', 'Omit entirely when T is `nopass`'],
            ['H', 'Hidden network', '`H:true` only if the SSID is not broadcast. Leave it out otherwise.'],
            [';;', 'Terminator', 'Two semicolons close the payload. Some readers fail without them.'],
          ],
        },
        { t: 'note', x: 'There is no separate WPA3 keyword. Use `T:WPA` for WPA2 and WPA3 alike; phones negotiate the actual handshake with the router. A mixed WPA2/WPA3 network works from a single code.' },
        { t: 'h2', x: 'Escaping special characters' },
        { t: 'p', x: 'If your SSID or password contains a semicolon, comma, colon, double quote or backslash, each one must be escaped with a backslash or the parser will cut the payload short. This is the most common reason a hand-written WiFi code half-works.' },
        { t: 'code', x: '// Password is:  pa;ss,word"1\nWIFI:T:WPA;S:Guest Room;P:pa\\;ss\\,word\\"1;;' },
        { t: 'h2', x: 'Making one in under a minute' },
        {
          t: 'steps',
          items: [
            { h: 'Open the generator', x: 'Go to the [QR code generator](/tools/qr-code) and choose the **wifi** tab.' },
            { h: 'Type the network name exactly', x: 'Copy it from your router admin page or your phone rather than typing it from memory. `Guest_WiFi` and `Guest WiFi` are different networks.' },
            { h: 'Enter the password and security type', x: 'Pick WPA / WPA2 unless you are running an open network, in which case choose Open and leave the password blank.' },
            { h: 'Raise the quiet zone to 4', x: 'The slider defaults to 2, which is enough on screen. Four modules of blank margin is what printed codes need.' },
            { h: 'Check the payload preview', x: 'The raw `WIFI:` string is shown under the preview. Read it once and confirm the password is character-for-character correct.' },
            { h: 'Download SVG for printing', x: 'Use SVG if you are placing it in a design, or the print-ready PDF if you are sending it straight to a printer.' },
            { h: 'Test with two phones before laminating', x: 'One iPhone, one Android. Forget the network on your own phone first, or it will join from memory and tell you nothing.' },
          ],
        },
        { t: 'cta', tool: 'qr-code', x: 'Build a WiFi QR code in your browser. The password is never sent anywhere.' },
        { t: 'h2', x: 'Which phones can scan it' },
        {
          t: 'table',
          caption: 'Native WiFi QR support, as of 2026.',
          head: ['Device', 'How it works', 'Notes'],
          rows: [
            ['iPhone / iPad, iOS 11+', 'Open Camera, point at the code, tap the "Join Network" banner', 'No app needed. Works from the Control Centre code scanner too.'],
            ['Android 10+', 'Open Camera or Google Lens, point, tap the prompt', 'Android can also generate a code: Settings, Network, Wi-Fi, tap the network, Share.'],
            ['Older Android (8-9)', 'Usually needs Google Lens or a scanner app', 'Same code, just an extra tap to get to a scanner.'],
            ['Windows / macOS laptops', 'No native camera join', 'Print the network name and password as text alongside the code.'],
          ],
        },
        { t: 'tip', x: 'Always print the SSID and password as readable text under the code. Laptops, older phones and anyone with a cracked camera lens will need them, and it costs you one line of type.' },
        { t: 'h2', x: 'Printing it for a cafe, guest room or office' },
        { t: 'p', x: 'A WiFi code sits on a table tent, a wall card or a laminated door hanger, so it is read from roughly 30 to 60 cm. Applying the ten-to-one rule from [QR code sizing](/blog/qr-codes/qr-code-size-for-print), that means a symbol **30 to 60 mm** wide. A 40 mm code on an A6 table tent is a safe, tested default.' },
        {
          t: 'ul',
          items: [
            '**Matte laminate, not gloss.** Gloss under a ceiling spotlight throws a highlight straight across the modules and kills the scan.',
            '**Keep it off the fold.** On a table tent, the code must sit entirely on one flat panel.',
            '**Black on white.** Brand colours are fine for the frame and text; leave the modules alone.',
            '**Print at 300 DPI or place vector.** A screenshot of the code pasted into a document is the usual culprit behind a fuzzy card.',
            '**Reprint when the password changes.** Old cards in circulation are a support problem, so date the card in small type on the back.',
          ],
        },
        { t: 'h2', x: 'The security question nobody asks' },
        { t: 'warn', x: 'A WiFi QR code is not encrypted. Anyone with a phone can decode it and read your password as plain text, and a photograph of the card taken from across the room decodes just as well as the card in your hand. Treat a printed WiFi code as publishing the password on the wall, because that is exactly what it is.' },
        {
          t: 'ul',
          items: [
            '**Use the guest network**, never your main SSID. Almost every router made since 2018 offers one.',
            '**Turn on client isolation** (sometimes called AP isolation or guest isolation) so guests cannot see each other or your printers, NAS and cameras.',
            '**Never put the admin password on a card.** The guest network password and the router login must be different.',
            '**Rotate it.** For a rented flat or a shop, changing the guest password and reprinting once a quarter is cheap.',
            '**Do not post it publicly.** A code in a shop window, or in a photo on social media, is readable by anyone who walks or scrolls past.',
          ],
        },
        { t: 'p', x: 'Once the card design is finished, [save it as a PDF](/blog/print-web-pages/print-web-page-to-pdf-vs-printer) so you can reprint it identically, and keep the SVG next to it. If you are making several versions for different rooms, [merge them into one file](/tools/merge-pdf) so the print shop gets a single job.' },
      ],
      faqs: [
        { q: 'Do WiFi QR codes work on iPhone?', a: 'Yes. Every iPhone running iOS 11 or later reads them with the stock Camera app. Point the camera at the code and a "Join Network" banner appears at the top of the screen; tap it and the phone connects without you typing anything.' },
        { q: 'Does a WiFi QR code work with WPA3?', a: 'Yes. Use T:WPA in the payload for WPA, WPA2 and WPA3 alike. There is no separate WPA3 keyword in the format, and phones negotiate the correct handshake with the router themselves.' },
        { q: 'Can someone steal my WiFi password from the printed code?', a: 'Yes, trivially. The password is stored as plain text and any QR scanner will display it. Only ever encode a guest network password, enable client isolation on the router, and never print the code where the public can photograph it.' },
        { q: 'What size should a WiFi QR code be on a table tent?', a: 'Between 30 and 60 mm wide. Guests scan from about 30 to 60 cm away, and the ten-to-one rule puts the minimum at one tenth of that distance. Forty millimetres is a reliable default for A6 cards.' },
        { q: 'Why does my WiFi QR code scan but fail to connect?', a: 'Usually the SSID or password does not match exactly, or a special character was not escaped. Semicolons, commas, colons, quotes and backslashes each need a preceding backslash. Check the raw payload text character by character against your router settings.' },
      ],
      relatedTools: ['qr-code', 'merge-pdf'],
      relatedPosts: ['qr-code-for-print', 'qr-code-size-for-print', 'qr-code-on-business-card'],
    },
    {
      slug: 'qr-code-size-for-print',
      cluster: 'qr-codes',
      title: 'What size should a QR code be? The distance rule',
      metaTitle: 'What Size Should a QR Code Be? Distance Rule',
      metaDescription:
        'The 10:1 distance rule with a real size table for business cards, flyers, posters and billboards, plus module size, minimum millimetres and pixels at 300 DPI.',
      published: '2026-03-09',
      updated: '2026-08-11',
      readMinutes: 6,
      intent: 'informational',
      primaryKeyword: 'qr code size for print',
      secondaryKeywords: ['minimum qr code size', 'qr code distance rule', 'qr code size chart mm', 'qr code dpi for printing', 'qr code module size'],
      entities: ['QR Code', 'ISO/IEC 18004', 'DPI', 'A4', 'business card', 'billboard', 'Denso Wave'],
      answer:
        'Use the 10:1 rule: a QR code must be at least one tenth as wide as the distance it is scanned from. A code read at 30 cm needs to be 3 cm wide; one read from 3 metres needs 30 cm. The absolute floor for any printed code is 2 cm.',
      body: [
        { t: 'p', x: 'There is exactly one number to remember about QR code sizing, and everything else is arithmetic around it.' },
        { t: 'quote', x: 'Minimum code width = scanning distance ÷ 10' },
        { t: 'p', x: 'That is the 10:1 rule, and it comes from the field of view a typical camera needs to resolve the individual modules. A business card is read from about 20 cm, so the code needs to be 2 cm wide. A poster read from 2 metres needs a 20 cm code. A code on a motorway billboard read from 30 metres needs to be 3 metres across, which is usually the moment a client decides against a billboard QR code.' },
        { t: 'h2', x: 'The size table' },
        {
          t: 'table',
          caption: 'Typical scanning distances and the minimum QR code width each one demands.',
          head: ['Where it goes', 'Read from', 'Minimum width', 'Recommended width'],
          rows: [
            ['Business card', '20 cm / 8 in', '20 mm / 0.8 in', '20-25 mm / 0.8-1 in'],
            ['Product label, packaging', '25 cm / 10 in', '25 mm / 1 in', '25-30 mm / 1-1.2 in'],
            ['Flyer, leaflet, brochure', '30 cm / 12 in', '30 mm / 1.2 in', '30-40 mm / 1.2-1.6 in'],
            ['Restaurant menu, table tent', '40-60 cm / 16-24 in', '40 mm / 1.6 in', '40-50 mm / 1.6-2 in'],
            ['A4 wall notice, indoor sign', '1 m / 3 ft', '100 mm / 4 in', '100-120 mm / 4-4.7 in'],
            ['A2 poster at eye level', '1.5 m / 5 ft', '150 mm / 6 in', '150-200 mm / 6-8 in'],
            ['Shop window decal', '2 m / 6.5 ft', '200 mm / 8 in', '250 mm / 10 in'],
            ['Trade show banner', '3 m / 10 ft', '300 mm / 12 in', '350-400 mm / 14-16 in'],
            ['Vehicle wrap', '5 m / 16 ft', '500 mm / 20 in', '600 mm / 24 in'],
            ['Billboard', '30 m / 100 ft', '3 m / 10 ft', 'Do not use a QR code here'],
          ],
        },
        { t: 'warn', x: 'The recommended column exists because the 10:1 rule is a floor, not a target. It assumes a steady hand, decent light and a reasonably modern camera. Adding 20 to 30 percent buys you dim restaurants, older phones and people who scan while walking.' },
        { t: 'h2', x: 'Why the rule works: module size' },
        { t: 'p', x: 'The rule is really about the **module**, the smallest black or white square in the grid. A camera needs several sensor pixels per module to decode reliably, which in print terms means each module should be at least **0.5 mm** wide, and never below 0.4 mm.' },
        { t: 'p', x: 'How many modules you have depends on how much data you encode. A version 1 symbol is 21 modules square; each version adds four, up to version 40 at 177 modules square. Short payloads make sparse, forgiving codes; long ones make dense, fragile codes.' },
        {
          t: 'table',
          caption: 'How payload length drives the grid, at error correction level M.',
          head: ['What you encode', 'Roughly', 'Grid', 'Width at 0.5 mm modules'],
          rows: [
            ['Short link, e.g. example.com/x', '15 characters', 'Version 1, 21 x 21', '10.5 mm'],
            ['Normal URL', '40 characters', 'Version 3, 29 x 29', '14.5 mm'],
            ['URL with tracking parameters', '90 characters', 'Version 5, 37 x 37', '18.5 mm'],
            ['WiFi payload with a long password', '60 characters', 'Version 4, 33 x 33', '16.5 mm'],
            ['Full vCard with address', '350 characters', 'Version 11, 61 x 61', '30.5 mm'],
            ['Long plain text', '1,000 characters', 'Version 21, 101 x 101', '50.5 mm'],
          ],
        },
        { t: 'p', x: 'Read that last row again. A thousand characters of text needs a 50 mm code just to reach the minimum module size, which is why encoding a whole paragraph is a bad idea. Encode a short URL and let the page hold the content. The same logic applies on a card: a link beats a [full vCard](/blog/qr-codes/qr-code-on-business-card) when space is tight.' },
        { t: 'h2', x: 'Pixels, DPI and what to hand the printer' },
        { t: 'p', x: 'If you are supplying a raster file rather than vector, the conversion is `pixels = millimetres × DPI ÷ 25.4`. Commercial print is 300 DPI; large-format banners and vehicle wraps are usually 100 to 150 DPI because nobody stands close to them.' },
        {
          t: 'table',
          caption: 'Pixel dimensions needed for a given printed size.',
          head: ['Printed width', 'At 300 DPI', 'At 600 DPI', 'At 150 DPI (large format)'],
          rows: [
            ['20 mm', '236 px', '472 px', '118 px'],
            ['30 mm', '354 px', '709 px', '177 px'],
            ['50 mm', '591 px', '1,181 px', '295 px'],
            ['100 mm', '1,181 px', '2,362 px', '591 px'],
            ['200 mm', '2,362 px', '4,724 px', '1,181 px'],
            ['500 mm', '5,906 px', '11,811 px', '2,953 px'],
          ],
        },
        { t: 'note', x: 'Every number in that table becomes irrelevant if you export SVG, which is why the [QR code generator](/tools/qr-code) offers it first. Use the pixel table only when a system refuses vector, such as a template that accepts PNG uploads only.' },
        { t: 'h2', x: 'Working out your own size' },
        {
          t: 'steps',
          items: [
            { h: 'Measure the real scanning distance', x: 'Not the distance you imagine. Stand where a customer stands, hold a phone the way a customer holds it, and measure.' },
            { h: 'Divide by ten', x: 'That is your absolute minimum symbol width, excluding the quiet zone.' },
            { h: 'Add 25 percent', x: 'This is your working size. It covers poor light, older cameras and scanning at an angle.' },
            { h: 'Add the quiet zone', x: 'Four blank modules on each side. On a 40 mm code that is roughly 5 mm of clear space all round, so reserve 50 mm in the layout.' },
            { h: 'Check the module size', x: 'Divide your working width by the grid size. If the answer is under 0.5 mm, shorten the payload or make the code bigger.' },
            { h: 'Proof at final size', x: 'Print one, scan it at the real distance with an old phone, then commit. The full checklist is in [making a QR code that scans](/blog/qr-codes/qr-code-for-print).' },
          ],
        },
        { t: 'cta', tool: 'qr-code', x: 'Generate a code at any size as SVG, PNG or a print-ready PDF, free and in your browser.' },
        { t: 'h2', x: 'Angle, motion and light' },
        { t: 'p', x: 'The 10:1 rule assumes the phone is held roughly square to the code. Decoding degrades past about 30 degrees of tilt, so a code on a sloped table tent or a shelf edge should be sized as if it were 20 to 30 percent further away. Anything scanned in motion, on an escalator or from a bus, needs to be larger still, and codes on moving vehicles do not work at all. Codes people scan while seated, such as a [WiFi card on a table](/blog/qr-codes/wifi-qr-code), are the easy case.' },
      ],
      faqs: [
        { q: 'What is the minimum size for a QR code?', a: 'Twenty millimetres, about 0.8 inches, for anything held in the hand. Below that, individual modules fall under the 0.4 mm that consumer printing and phone cameras can resolve, and scan success drops sharply even in good light.' },
        { q: 'What is the 10:1 rule for QR codes?', a: 'The code must be at least one tenth as wide as the distance it is scanned from. Scanned at 30 cm, it needs to be 3 cm wide. Scanned at 3 metres, 30 cm wide. Add another 25 percent for real-world lighting and older phones.' },
        { q: 'What DPI should a printed QR code be?', a: 'Three hundred DPI for standard commercial printing, and 100 to 150 DPI for large-format banners viewed from a distance. Vector SVG sidesteps the question entirely, because it has no fixed resolution and prints sharp at any size.' },
        { q: 'Does a longer URL make the QR code bigger?', a: 'It makes it denser, not automatically bigger. More characters mean more modules in the same square, so each module shrinks. To keep modules above 0.5 mm you must either enlarge the code or shorten the URL, and shortening is usually easier.' },
        { q: 'Do QR codes work on billboards?', a: 'Rarely. At a 30 metre viewing distance the rule demands a 3 metre code, and drivers cannot safely scan anything anyway. Use a short, memorable URL on a billboard and save QR codes for print people can hold still.' },
      ],
      relatedTools: ['qr-code', 'jpg-to-pdf'],
      relatedPosts: ['qr-code-for-print', 'qr-code-on-business-card', 'best-image-format-for-print'],
    },
    {
      slug: 'qr-code-on-business-card',
      cluster: 'qr-codes',
      title: 'How to put a QR code on a business card or flyer',
      metaTitle: 'How to Put a QR Code on a Business Card',
      metaDescription:
        'Add a QR code to a business card or flyer: vCard versus a link, size and placement, bleed and margins, printing at 300 DPI and the mistakes that kill scans.',
      published: '2026-04-06',
      updated: '2026-08-25',
      readMinutes: 7,
      intent: 'howto',
      primaryKeyword: 'qr code on business card',
      secondaryKeywords: ['vcard qr code', 'business card qr code size', 'qr code flyer design', 'qr code bleed and margins', 'print qr code 300 dpi'],
      entities: ['vCard', 'MECARD', 'CMYK', 'Adobe InDesign', 'Canva', 'Moo', 'Vistaprint', 'ISO 216'],
      answer:
        'Encode a vCard for contact details or a short URL for a landing page, size the code at 20 to 25 mm, keep 5 mm of clear space around it and away from the trim edge, and supply vector artwork at 300 DPI with the modules in 100% black. Proof one card before ordering.',
      body: [
        { t: 'p', x: 'A QR code on a card is a small design problem with many ways to go wrong: too small, too close to the edge, printed over a photograph, or pointing at a homepage nobody wanted. Here is the whole job, from what to encode to what to send the printer.' },
        { t: 'h2', x: 'Decide what the code should do' },
        { t: 'p', x: 'There are three sensible payloads for a card, and picking the wrong one is the costliest mistake here because it stays invisible until the cards arrive.' },
        {
          t: 'table',
          caption: 'Three payloads for a business card, compared.',
          head: ['Payload', 'What happens when scanned', 'Best for', 'Cost'],
          rows: [
            ['vCard 3.0', 'Phone offers to create a contact with every field pre-filled', 'Anyone who wants to be saved to a phone book on the spot', 'Dense code, 200-400 characters. Needs 25 mm or more.'],
            ['MECARD', 'Same, but a more compact syntax', 'Tight layouts where a vCard will not fit', 'Slightly weaker support on iOS than vCard.'],
            ['Short URL', 'Opens a page you control', 'Portfolios, booking links, anything you may want to change later', 'Sparse code, scans from further away. Needs the page to stay live.'],
          ],
        },
        { t: 'p', x: 'A vCard is frozen the moment it is printed. A URL is editable forever but dies if you let the domain lapse. For most people the answer is a vCard on the card and a URL on the flyer, because flyers are reprinted and cards are kept for years.' },
        { t: 'h2', x: 'The vCard format' },
        { t: 'p', x: 'A vCard is plain text with one field per line. Version 3.0 has the widest scanner support; version 4.0 is newer but some phone readers still handle it poorly.' },
        { t: 'code', x: 'BEGIN:VCARD\nVERSION:3.0\nN:Rahman;Ayesha;;;\nFN:Ayesha Rahman\nORG:Northwind Studio\nTITLE:Creative Director\nTEL;TYPE=CELL:+8801711000000\nEMAIL:ayesha@example.com\nURL:https://example.com\nEND:VCARD' },
        {
          t: 'ul',
          items: [
            '`N` is the structured name: family, given, middle, prefix, suffix, separated by semicolons.',
            '`FN` is the display name and is the only name field some readers show. Always include both.',
            'Use the **full international phone format** with a country code, or the number will not dial from abroad.',
            'Every extra field makes the code denser. Address blocks and photos in particular can double the module count, so leave them out unless you need them.',
          ],
        },
        { t: 'note', x: 'The [QR code generator](/tools/qr-code) has a **vcard** tab that builds this for you from name, organisation, phone, email and website, and shows the raw payload underneath so you can check it before downloading.' },
        { t: 'h2', x: 'Size, placement and margins' },
        { t: 'p', x: 'Business cards are read at roughly 20 cm, so the [10:1 rule](/blog/qr-codes/qr-code-size-for-print) puts the minimum at 20 mm. A vCard payload is dense, so 22 to 25 mm is the practical range. On an 85 x 55 mm card, a 25 mm code takes a meaningful bite out of the layout, which is why the back of the card is usually the right home for it.' },
        {
          t: 'table',
          caption: 'Card and flyer dimensions with the space a QR code needs.',
          head: ['Piece', 'Trim size', 'Bleed', 'Safe margin', 'QR size', 'Reserve in layout'],
          rows: [
            ['Business card (international)', '85 x 55 mm', '3 mm all round', '3-5 mm', '20-25 mm', '35 mm square'],
            ['Business card (US)', '3.5 x 2 in (88.9 x 50.8 mm)', '0.125 in', '0.125-0.2 in', '0.8-1 in', '1.4 in square'],
            ['A6 flyer / postcard', '105 x 148 mm', '3 mm', '5 mm', '30-40 mm', '50 mm square'],
            ['A5 flyer', '148 x 210 mm', '3 mm', '5 mm', '35-45 mm', '55 mm square'],
            ['A4 leaflet / poster', '210 x 297 mm', '3 mm', '8-10 mm', '40-60 mm', '70 mm square'],
          ],
        },
        { t: 'warn', x: 'The **reserve** column is the code plus its four-module quiet zone plus a safety gap from the trim. Never place a QR code inside the bleed area or within 5 mm of the trim edge: guillotine tolerance on a commercial press is 1 to 2 mm per cut, and a shaved quiet zone is an unscannable code across the whole run.' },
        { t: 'h2', x: 'Preparing the artwork' },
        {
          t: 'steps',
          items: [
            { h: 'Generate the code as SVG', x: 'Open the [generator](/tools/qr-code), pick the vcard or url tab, fill it in, drag the quiet zone slider to 4, and download SVG.' },
            { h: 'Place it, do not paste a screenshot', x: 'Import the SVG into InDesign, Illustrator, Affinity or Canva. A screenshot of the preview is a low-resolution raster and will print soft.' },
            { h: 'Set the modules to 100% K', x: 'One black plate cannot misregister against itself. Four-colour rich black can shift by a fraction of a millimetre on press and blur every module edge.' },
            { h: 'Give it white, not paper texture', x: 'The light modules and the quiet zone should be a plain light field. A photograph, a gradient or a heavy paper texture underneath reduces local contrast.' },
            { h: 'Add a two-word label', x: 'People do not scan unlabelled codes. "Save my contact" or "Book a call" measurably raises scan rates over a bare square.' },
            { h: 'Export the print PDF at 300 DPI', x: 'Include bleed and crop marks if the printer asks for them, and embed all fonts.' },
            { h: 'Proof one card at final size', x: 'Print a single card on the closest paper you have, cut it to size, and scan it with an old phone from 20 cm. Only then place the order.' },
          ],
        },
        { t: 'cta', tool: 'qr-code', x: 'Build a vCard or URL QR code and download it as SVG, PNG or a print-ready PDF.' },
        { t: 'h2', x: 'Mistakes that kill scans on printed cards' },
        {
          t: 'ol',
          items: [
            '**Too small.** Anything under 20 mm on a card is a gamble. Under 15 mm it is a decoration.',
            '**No quiet zone.** Text or a rule running right up to the modules stops the scanner locating the symbol.',
            '**Placed over a photo.** Dark parts of the image merge with the dark modules.',
            '**Inverted for style.** White modules on a dark brand colour looks great and fails on older hardware scanners.',
            '**Gloss lamination.** A spot-lit glossy card throws a highlight across the code. Ask for matte, or a matte patch over the code area.',
            '**Spot UV or foil over the code.** Both destroy contrast. Keep effects outside the quiet zone.',
            '**Linking to the homepage.** Send people to the page the card promises. A generic landing page wastes the scan.',
            '**A free short link that expires.** If the shortener shuts down, every card you handed out is dead. Redirect through your own domain.',
            '**Never proofed.** Scanning the file on your monitor proves nothing about ink on card stock.',
          ],
        },
        { t: 'tip', x: 'On a flyer, put the code in the lower right of the front panel. That is where a right-handed reader holds the sheet, and it keeps the code clear of the fold on a folded leaflet.' },
        { t: 'p', x: 'If you are assembling the print pack yourself, [combine the front and back artwork into one PDF](/blog/convert-to-pdf/images-to-pdf) before sending, and check it against the shop’s upload limit with [compress](/tools/compress-pdf). The underlying scan rules are all in [making a QR code that scans off paper](/blog/qr-codes/qr-code-for-print).' },
      ],
      faqs: [
        { q: 'What size should a QR code be on a business card?', a: 'Twenty to twenty-five millimetres, roughly 0.8 to 1 inch. Cards are scanned from about 20 cm, and the 10:1 rule sets 20 mm as the floor. A vCard payload is dense, so lean towards 25 mm if the layout allows.' },
        { q: 'Should a business card QR code hold a vCard or a link?', a: 'A vCard if you want people to save your details instantly and never change them. A link if the destination may change or you want to track scans. vCards are frozen once printed; links can be redirected forever, provided you own the domain.' },
        { q: 'How far from the edge of the card should the QR code sit?', a: 'At least 5 mm from the trim edge, on top of the four-module quiet zone the code already needs. Commercial guillotines have 1 to 2 mm of tolerance per cut, and any trimming into the quiet zone breaks the whole print run.' },
        { q: 'Can I print a QR code in my brand colour?', a: 'The modules should stay dark and desaturated against a near-white background. A deep navy or charcoal usually works; mid-tone brand colours, inverted codes, red modules and gradients do not. Keep the brand colour for the frame, label and card background.' },
        { q: 'Why does my QR code work in the design file but not on the printed card?', a: 'Almost always a raster image that was scaled up, gloss lamination throwing glare, or the quiet zone lost at the trim. Place vector SVG, ask for matte finish over the code, and keep 5 mm of clear space from the edge.' },
      ],
      relatedTools: ['qr-code', 'flatten-pdf'],
      relatedPosts: ['qr-code-for-print', 'qr-code-size-for-print', 'wifi-qr-code'],
    },
  ],
}
