import type { Cluster } from '../types'

export const savePaperInk: Cluster = {
  slug: 'save-paper-ink',
  name: 'Saving paper and ink',
  title: 'How to print for less: ink, paper and the settings that matter',
  metaTitle: 'How to Save Ink and Paper When Printing',
  metaDescription:
    'Cut the cost of every print job: draft mode, greyscale, ink-efficient fonts, double-sided printing without a duplex unit, scaling, and the real cost per page.',
  intro:
    'Printing is one of the few household and office costs where the price per unit is almost entirely under your control and almost nobody looks at it. The same document can cost eighteen cents or two dollars ninety depending on four settings, none of which are hidden and all of which your printer remembers once you set them. These guides cover the ink side, the paper side, and the habits that stop pages being printed at all.',
  answer:
    'The four settings that matter most are duplex, greyscale, draft quality and pages per sheet. Applied together they typically cut the cost of a document by 70 to 90 percent. Set them as your printer defaults rather than per job, and use print preview and page ranges to avoid printing pages nobody reads.',
  primaryKeyword: 'how to save ink and paper when printing',
  entities: ['Adobe Acrobat Reader', 'Microsoft Word', 'HP EconoMode', 'Epson EcoTank', 'Garamond', 'Century Gothic', 'A4', 'FSC', 'Energy Star'],
  icon: '♻',
  tools: ['compress-pdf', 'delete-pages', 'organize-pdf', 'pdf-reader'],
  posts: [
    {
      slug: 'save-ink-when-printing',
      cluster: 'save-paper-ink',
      title: 'How to save ink when printing',
      metaTitle: 'How to Save Ink When Printing: 9 Real Fixes',
      metaDescription:
        'Cut ink and toner use by half: draft mode, true black-only greyscale, ink-efficient fonts, dropping images and backgrounds, and cartridge choices that pay.',
      published: '2026-01-09',
      updated: '2026-08-23',
      readMinutes: 8,
      intent: 'howto',
      primaryKeyword: 'how to save ink when printing',
      secondaryKeywords: ['save toner printing', 'draft mode printing', 'ink efficient fonts', 'print in black ink only', 'reduce printer ink cost'],
      entities: ['HP EconoMode', 'Epson EcoTank', 'Canon MegaTank', 'Garamond', 'Century Gothic', 'Times New Roman', 'Adobe Acrobat Reader', 'Ecofont'],
      answer:
        'Set draft quality and black ink only as your printer defaults, turn off background graphics, remove decorative images, and use a narrow serif font like Garamond at 11pt. Together these typically cut ink use by half or more on ordinary documents, without changing anything about how readable the page is.',
      body: [
        { t: 'p', x: 'Printer ink is famously expensive per millilitre, so the only defence is putting less of it on the paper. Nine changes below, in rough order of how much they save for how little you give up.' },
        { t: 'h2', x: '1. Draft quality for anything you are not handing to a stranger' },
        { t: 'p', x: 'Draft mode makes fewer passes with fewer nozzles, or lays down a thinner layer of toner. HP calls it **EconoMode**, Brother **Toner Save**, Epson and Canon **Draft** or **Fast**. Expect roughly a third less ink on an inkjet and around half on a laser.' },
        { t: 'p', x: 'It looks slightly lighter and softer, which for a reading copy or an internal report is an invisible cost. HP does caution against running EconoMode permanently on a laser, because the developer unit wears differently, so keep normal quality for the jobs that matter.' },
        { t: 'h2', x: '2. Black ink only, not just greyscale' },
        { t: 'p', x: 'The setting most people get wrong. On an inkjet, **Grayscale** often does not stop the printer using colour: it mixes cyan, magenta and yellow into a richer composite black, so a document that looks entirely black quietly drains three cartridges. You want **Black ink only** or **Print using black cartridge only**.' },
        { t: 'warn', x: 'Many inkjets refuse to print at all when a colour cartridge is empty, even in black and white, because the maintenance routine needs every head present. Black-ink-only is what stops you reaching that point.' },
        { t: 'h2', x: '3. Turn off background graphics' },
        { t: 'p', x: 'In a browser print dialog, **Background graphics** is off by default and should stay off. It keeps solid colour blocks, dark hero panels, zebra striping and section tints off your paper — the difference between an article and a black rectangle on a dark-mode site.' },
        { t: 'h2', x: '4. Remove the images, or shrink them' },
        { t: 'p', x: 'A full-width photograph is worth ten pages of text in ink, and on most web pages the images are decorative. In the [web page printer](/print) the Style menu has an image setting: choose half-size or None and the page count falls with the ink.' },
        { t: 'cta', tool: 'pdf-to-text', x: 'Want the words and nothing else? Extract the text from a PDF and print that instead.' },
        { t: 'h2', x: '5. Choose a font that uses less ink' },
        { t: 'p', x: 'Fonts differ measurably in ink per page. The effect is real but smaller than headlines suggest, and there is a trap: some low-ink fonts are wide, so you save per letter and spend it on extra pages.' },
        {
          t: 'table',
          caption: 'Relative ink use per character for common fonts. Width matters as much as weight.',
          head: ['Font', 'Ink per character', 'Set width', 'Verdict'],
          rows: [
            ['Arial or Helvetica', 'Baseline', 'Baseline', 'The default on most documents, and the most expensive common choice'],
            ['Times New Roman', 'About 15% less', 'Narrower', 'Fewer pages and less ink. A safe default'],
            ['Garamond', 'About 20-25% less', 'Narrow; set it a point larger to match', 'The classic ink-saving pick, and it reads well'],
            ['Century Gothic', 'About 30% less', 'Noticeably wider', 'Less ink per letter, more pages. Often a net loss'],
            ['Ecofont Vera Sans', 'About 25% less', 'Similar to Arial', 'Punches tiny holes in each glyph. Invisible below about 11pt'],
            ['Anything set in bold', '15-25% more', 'Wider', 'Reserve bold for headings, not for body text or tables'],
          ],
        },
        { t: 'p', x: 'The best-known claim here came from a 2014 school science project estimating that the United States federal government could save over a hundred million dollars a year by switching to Garamond. The methodology was fairly criticised, but the direction is right.' },
        { t: 'h2', x: '6. Drop a point size' },
        { t: 'p', x: 'Ink coverage scales roughly with the square of the type size. 12pt to 11pt is about 16 percent less ink for the same words, and nobody notices. 12pt to 10pt is 30 percent less, fine for reference material and too far for an older reader. Size table in [fitting more on a page](/blog/save-paper-ink/fit-more-on-a-page).' },
        { t: 'h2', x: '7. Set it once, as the default' },
        {
          t: 'steps',
          items: [
            { h: 'Open your printer settings', x: 'Windows: **Settings → Printers & scanners** → your printer → **Printing preferences**. macOS: set the options in any print dialog, then **Save Current Settings as Preset** and make it the default.' },
            { h: 'Set the quality to Draft or EconoMode', x: 'It is usually on the first tab, labelled Quality, Print Quality or Paper/Quality.' },
            { h: 'Set the colour mode to black only', x: 'Look for Grayscale plus a **Black ink only** or **Black cartridge only** sub-option. Ticking greyscale alone is not enough on most inkjets.' },
            { h: 'Turn on two-sided printing', x: 'If your printer has a duplex unit, make it the default here. It halves your paper for good. See [printing double-sided](/blog/save-paper-ink/print-double-sided).' },
            { h: 'Apply, then confirm from a different app', x: 'Print one page from another program. Driver defaults are per printer, but some apps carry their own overrides.' },
          ],
        },
        { t: 'tip', x: 'These are defaults, not a cage. Every print dialog still offers high quality and colour for the one job in twenty that needs it. The point is that the cheap setting is the one you never have to remember.' },
        { t: 'h2', x: '8. Buy ink better' },
        {
          t: 'table',
          caption: 'Typical running costs with manufacturer supplies.',
          head: ['Printer type', 'Mono page', 'Colour page', 'Notes'],
          rows: [
            ['Mono laser', '1.5-4 cents', 'n/a', 'Cheapest for text. High-yield toner drops it further'],
            ['Colour laser', '2-5 cents', '8-15 cents', 'Good for charts and diagrams, mediocre for photographs'],
            ['Inkjet, standard cartridges', '4-8 cents', '15-25 cents', 'The XL cartridge is almost always cheaper per page'],
            ['Inkjet, refillable tank', '0.2-0.5 cents', '1-2 cents', 'EcoTank, MegaTank, Smart Tank. Costly to buy, near-free to run'],
            ['Ink subscription', 'A flat monthly fee', 'Same', 'Cheap only near your full page allowance'],
          ],
        },
        {
          t: 'ul',
          items: [
            'Ignore the first **low ink** warning. It fires early, and there is often 15 to 20 percent left.',
            'Buy **XL or high-yield** cartridges: more up front, much less per page.',
            'Above about a thousand pages a year, a **refillable tank printer** or mono laser repays its price quickly.',
            'Print **something every week or two**. An idle inkjet clogs, and the head-cleaning cycle uses more ink than the printing you skipped.',
          ],
        },
        { t: 'h2', x: '9. Print fewer pages in the first place' },
        { t: 'p', x: 'No setting beats not printing. Look at the preview, find the pages you need, and enter a range like `2-3`. If a PDF carries ten pages of appendices you will never open, delete them once.' },
        { t: 'cta', tool: 'delete-pages', x: 'Strip the pages you will never read out of a PDF before it reaches the printer.' },
        { t: 'h2', x: 'What it adds up to' },
        { t: 'p', x: 'Take a twenty-page report with colour figures on an inkjet. As it arrives — full quality, colour, single-sided, images in — it is twenty sheets and roughly $2.40. In draft, black only, images out, duplexed, it is ten sheets and about 30 cents: same words, eight times the cost.' },
        { t: 'p', x: 'The next levers are structural: [double-sided printing](/blog/save-paper-ink/print-double-sided) halves the sheets, [fitting more on a page](/blog/save-paper-ink/fit-more-on-a-page) shrinks the count, and [printing less overall](/blog/save-paper-ink/eco-friendly-printing) covers the habits.' },
      ],
      faqs: [
        { q: 'Does printing in greyscale actually save colour ink?', a: 'Not always. Many inkjets mix cyan, magenta and yellow to make a richer composite black even in greyscale mode. You need the separate "black ink only" or "black cartridge only" option in the driver to genuinely stop colour ink being used.' },
        { q: 'Which font uses the least ink?', a: 'Narrow, light serif faces such as Garamond and Times New Roman use noticeably less than Arial. Century Gothic uses less ink per character but is wide enough that it often adds pages, cancelling out the saving. Avoid bold body text entirely.' },
        { q: 'Is draft mode bad for my printer?', a: 'No for inkjets. On lasers, HP advises against running EconoMode permanently because the developer unit wears unevenly, so keep normal quality available for jobs that matter. For everyday documents, draft is fine and saves roughly a third to a half of the ink.' },
        { q: 'How much ink is left when the printer says low?', a: 'Usually 15 to 20 percent, sometimes more. The warning is deliberately conservative. Keep printing until the output visibly fades or streaks, and have the replacement on the shelf rather than in the printer.' },
        { q: 'Why does my printer refuse to print in black when a colour cartridge is empty?', a: 'Most inkjets need every head present for their maintenance routine, and some drivers block printing entirely. Setting black-ink-only as the default reduces how often colour cartridges empty, which is the practical way to avoid the problem.' },
      ],
      relatedTools: ['pdf-to-text', 'delete-pages'],
      relatedPosts: ['fit-more-on-a-page', 'eco-friendly-printing', 'print-double-sided'],
    },
    {
      slug: 'print-double-sided',
      cluster: 'save-paper-ink',
      title: 'How to print double-sided, including without a duplex printer',
      metaTitle: 'How to Print Double-Sided (No Duplex Needed)',
      metaDescription:
        'Print on both sides with or without a duplex unit: long edge versus short edge, manual odd and even pages, and how to stop sheets printing upside down.',
      published: '2026-02-25',
      updated: '2026-07-16',
      readMinutes: 8,
      intent: 'howto',
      primaryKeyword: 'how to print double sided',
      secondaryKeywords: ['manual duplex printing', 'flip on long edge or short edge', 'print odd and even pages', 'double sided printing upside down', 'print booklet at home'],
      entities: ['Adobe Acrobat Reader', 'Microsoft Word', 'Apple Preview', 'Google Chrome', 'Microsoft Edge', 'Google Docs', 'A4', 'US Letter'],
      answer:
        'If your printer has a duplex unit, tick "Print on both sides" and choose Flip on long edge for portrait documents. Without one, print the odd pages, put the stack back in the tray, then print the even pages in reverse order. Test on four pages before committing to a long document.',
      body: [
        { t: 'p', x: 'Double-sided printing halves your paper for free, and it is a checkbox. The only confusing parts are which edge to flip on, and what to do when your printer has no duplex unit.' },
        { t: 'h2', x: 'If your printer has a duplex unit' },
        { t: 'p', x: 'Look for **Print on both sides of paper** in the print dialog on Windows, or **Two-Sided** on macOS. If it is greyed out, either the printer genuinely lacks the hardware or the driver has duplex disabled — check the printer properties before assuming.' },
        { t: 'p', x: 'Then pick the binding edge, which is where everyone goes wrong. The rule is about the physical paper, not about what you are reading:' },
        {
          t: 'table',
          caption: 'The flip rule. The long edge of A4 or Letter paper is the tall side when the page is portrait.',
          head: ['Document orientation', 'Choose', 'macOS calls it', 'Result'],
          rows: [
            ['Portrait (most documents)', 'Flip on long edge', 'Long-Edge binding', 'Opens like a book. The correct default'],
            ['Portrait, bound at the top', 'Flip on short edge', 'Short-Edge binding', 'Turns upward like a notepad'],
            ['Landscape (slides, wide tables, two-up)', 'Flip on short edge', 'Short-Edge binding', 'Opens like a book held sideways'],
            ['Landscape, bound at the top', 'Flip on long edge', 'Long-Edge binding', 'Turns upward'],
          ],
        },
        { t: 'warn', x: 'The most common duplex mistake is printing a landscape document, such as two pages per sheet or a set of slides, with the portrait default of long-edge binding. Every second sheet then reads upside down. If you have flipped the page to landscape for any reason, flip the binding setting too.' },
        { t: 'h2', x: 'If your printer has no duplex unit' },
        { t: 'p', x: 'Manual duplex is a two-pass job: print one side of every sheet, put the stack back in the tray, print the other side. The difficulty is that two independent things can be wrong — which way up you reload the stack, and which order the second pass runs in — and the same symptom can come from either.' },
        {
          t: 'steps',
          items: [
            { h: 'Print a four-page test first', x: 'Never diagnose this on a fifty-page document. Take any four-page file, or set the range to `1-4`.' },
            { h: 'Print the odd pages', x: 'Set the odd/even control (see the table below) to odd pages only. You get sheets carrying pages 1 and 3.' },
            { h: 'Reload without reordering', x: 'Take the output stack, do not shuffle it, and put it straight back into the tray. Write the word TOP in pencil on the leading edge of the first sheet so you can see afterwards what actually happened.' },
            { h: 'Print the even pages in reverse', x: 'Set the range to even pages only and turn on reverse order. Most printers deliver pages face down and stacked in reverse, so the even pass has to run backwards to line up.' },
            { h: 'Read the result and adjust one variable', x: 'If page 2 is on the back of page 1 but upside down, you reloaded with the wrong face or the wrong edge leading: flip the stack the other way next time. If page 2 landed on the back of page 3, the order was wrong: toggle reverse order. Change one thing, not both.' },
            { h: 'Write the recipe on a sticky note', x: 'Once it works, the answer is the same for that printer forever. Two lines on a note taped to the printer saves this whole process next time.' },
          ],
        },
        {
          t: 'table',
          caption: 'Where the odd/even and reverse controls live.',
          head: ['App', 'Odd and even pages', 'Reverse order'],
          rows: [
            ['Adobe Acrobat Reader', 'More Options → **Odd pages only** / **Even pages only**', 'Tick **Reverse pages** in the same panel'],
            ['macOS print sheet (Preview, Safari, Word)', 'Paper Handling → **Pages to Print**', 'Paper Handling → **Page Order** → Reverse'],
            ['Microsoft Word (Windows)', 'Print → the range dropdown → **Only Odd Pages** / **Only Even Pages**', 'File → Options → Advanced → Print → **Print pages in reverse order**'],
            ['Chrome or Edge PDF viewer', 'None. Type a range: `1,3,5,7,9`', 'None. Type the even pages backwards: `10,8,6,4,2`'],
            ['Google Docs', 'None. Download as PDF and use a reader', 'n/a'],
            ['Many Windows drivers', 'Print on both sides **manually** in Printing Preferences', 'The driver prompts you to reload and handles order itself'],
          ],
        },
        { t: 'tip', x: 'If your PDF viewer has no odd/even control, extract the odd pages into their own file once and print each half normally. It is more reliable than typing long comma-separated ranges, and you can reuse the split for the next copy.' },
        { t: 'cta', tool: 'extract-pages', x: 'Split a document into odd and even halves when your viewer has no odd/even setting.' },
        { t: 'h2', x: 'Paper matters more than you think' },
        {
          t: 'ul',
          items: [
            'Standard **80gsm** office paper (24lb bond in US terms is a little heavier) shows through when both sides carry dense text. It is usable, but the back of the page is visible.',
            '**90 to 100gsm** is the sweet spot for double-sided reports and handouts. It costs more per sheet, and you are buying half as many sheets.',
            'Lightweight **70 to 75gsm** paper is for single-sided internal drafts. Do not duplex it: the show-through is bad and older printers jam.',
            'On an inkjet, heavy ink coverage makes paper curl and the second side can smear. Let the first pass dry for a minute before reloading.',
          ],
        },
        { t: 'h2', x: 'Odd page counts and blank sheets' },
        { t: 'p', x: 'A document with an odd number of pages ends on a half-used sheet, and some drivers waste a whole sheet at the end of a manual duplex run. If you are printing several documents in one job, or you want a chapter to start on a right-hand page, insert deliberate blank pages so the breaks land where you want them rather than where the arithmetic puts them.' },
        { t: 'cta', tool: 'organize-pdf', x: 'Insert blank pages or reorder a document so the double-sided breaks land in the right places.' },
        { t: 'h2', x: 'Booklets, if you want to go further' },
        { t: 'p', x: 'Acrobat Reader has a **Booklet** option that imposes pages two-up on landscape sheets in saddle-stitch order: fold the stack, staple the spine, get a small book. The page count must be a multiple of four, so add blanks. Without duplex, print the fronts, reload and print the backs — and remember landscape means short edge.' },
        { t: 'h2', x: 'What it saves' },
        { t: 'p', x: 'Duplex halves your sheets, which is roughly a cent a page in paper and a great deal more in storage and weight. On a 24-page academic paper it turns twelve sheets into six; combined with [two pages per sheet](/blog/students-research/print-journal-articles) it turns twenty-four pages into six sheets. In an office printing 150,000 pages a year, defaulting to duplex saves around 150 reams of paper. Set it as the printer default and the saving happens whether anyone remembers or not, which is covered in [saving ink](/blog/save-paper-ink/save-ink-when-printing) and [printing less overall](/blog/save-paper-ink/eco-friendly-printing).' },
      ],
      faqs: [
        { q: 'Should I flip on long edge or short edge?', a: 'Long edge for portrait documents, which is what you want almost always: the sheets open like a book. Short edge for landscape documents such as slides or two-pages-per-sheet layouts, and for anything you want to bind along the top.' },
        { q: 'How do I print double-sided without a duplex printer?', a: 'Print the odd pages, put the output stack straight back into the tray without reordering it, then print the even pages with reverse order turned on. Test on a four-page document first and note down what worked for your printer.' },
        { q: 'Why is every second page upside down?', a: 'You used the wrong binding edge, or you reloaded the stack the wrong way round. On a landscape document the correct choice is short edge, not the portrait default of long edge. Change one variable at a time and reprint four pages.' },
        { q: 'Which paper weight is best for double-sided printing?', a: '90 to 100gsm. Standard 80gsm shows through under dense text and 70 to 75gsm is too thin to duplex at all. Since duplexing halves the number of sheets you buy, the heavier paper often costs no more in total.' },
        { q: 'Can I print double-sided from a phone?', a: 'Sometimes. AirPrint and Mopria both expose a two-sided option when the printer reports a duplex unit, usually under Options in the share sheet. Manual duplex is not practical from a phone, because there is no odd/even control.' },
      ],
      relatedTools: ['organize-pdf', 'extract-pages'],
      relatedPosts: ['save-ink-when-printing', 'fit-more-on-a-page', 'print-journal-articles'],
    },
    {
      slug: 'fit-more-on-a-page',
      cluster: 'save-paper-ink',
      title: 'How to fit more on a printed page without making it unreadable',
      metaTitle: 'How to Fit More on a Printed Page',
      metaDescription:
        'Scale, margins, line spacing and pages per sheet compared, with a minimum readable size table so you know how far to push a document before it breaks.',
      published: '2026-03-05',
      updated: '2026-08-07',
      readMinutes: 8,
      intent: 'howto',
      primaryKeyword: 'how to fit more on a printed page',
      secondaryKeywords: ['print scale 80 percent', 'reduce margins for printing', 'multiple pages per sheet', 'minimum readable font size print', 'fit spreadsheet on one page'],
      entities: ['Microsoft Word', 'Microsoft Excel', 'Google Chrome', 'Adobe Acrobat Reader', 'A4', 'US Letter', 'Robert Bringhurst', 'Google Docs'],
      answer:
        'Cut the margins first, since it is free: moving from one inch to half an inch adds about 28 percent more text area on A4. Then drop the scale to 90 or 80 percent, and only then consider two pages per sheet. Keep body text at 9pt or larger for anything you will read continuously.',
      body: [
        { t: 'p', x: 'Every lever that fits more on a sheet costs you something in readability, but they do not cost the same amount. Margins are nearly free. Scaling is cheap. Pages-per-sheet is expensive. Apply them in that order and you can usually halve a document before anyone notices.' },
        { t: 'h2', x: 'Start with the margins, because they cost nothing' },
        { t: 'p', x: 'Microsoft Word ships with one-inch margins on every side. On A4 that leaves a text area of 15.9 by 24.6cm. Switching to the built-in **Narrow** preset of half an inch gives you 18.5 by 27.1cm, which is **28 percent more text area** for no change in type size at all. A twenty-page document becomes about sixteen.' },
        { t: 'p', x: 'The catch is binding. If the document will be hole-punched or stapled, keep at least 20mm on the bound edge. Word has a **Gutter** setting under Layout → Margins → Custom Margins for exactly this: it adds space on the inside edge only.' },
        { t: 'h2', x: 'Then scale' },
        { t: 'p', x: 'Browsers and PDF readers both offer a scale control, usually as a **Custom** percentage from 10 to 200. Because you are shrinking in two dimensions, the content per sheet grows with the square: at 90 percent you fit about 1.23 times as much, at 80 percent about 1.56 times.' },
        {
          t: 'table',
          caption: 'What each lever buys on a 20-sheet document. They do not simply add up — apply them in order and re-check the preview.',
          head: ['Change', 'Sheets saved', 'Readability cost'],
          rows: [
            ['Margins from 1 inch to 0.5 inch', 'About 4', 'None, unless you need a binding margin'],
            ['Scale 100% to 90%', 'About 4', 'Barely perceptible'],
            ['Scale 100% to 80%', 'About 7', 'Noticeable, still comfortable for most adults'],
            ['Body text 12pt to 11pt', 'About 3', 'None for most readers'],
            ['Line spacing 1.15 to 1.0, no space after paragraphs', 'About 2', 'Lines get harder to track. Keep some leading'],
            ['Two pages per sheet', '10', 'Large. 11pt body text lands near 7pt'],
            ['Two pages per sheet plus duplex', '15', 'Same, and you lose the blank back for notes'],
          ],
        },
        { t: 'warn', x: 'Do not stack scale and pages-per-sheet. Two-up already scales each page to about 65 percent; setting 80 percent scale on top of it gives you 52 percent, which turns 11pt body text into 5.7pt. Pick one or the other.' },
        { t: 'h2', x: 'How small is too small' },
        { t: 'p', x: 'Point size is a measure of the type body, not of the letters, so the practical number is the x-height: the height of a lowercase letter without an ascender. That is what your eye actually reads.' },
        {
          t: 'table',
          caption: 'Approximate x-heights for a typical serif face, and what each size is realistically good for.',
          head: ['Point size', 'x-height', 'Reads like', 'Use for'],
          rows: [
            ['12pt', 'About 2.2mm', 'A large-print book', 'Anything an older reader will use, or poor lighting'],
            ['11pt', 'About 2.0mm', 'A standard report', 'The safe default for documents read cover to cover'],
            ['10pt', 'About 1.8mm', 'A newspaper', 'Long documents in good light'],
            ['9pt', 'About 1.6mm', 'A textbook footnote', 'The practical floor for continuous reading'],
            ['8pt', 'About 1.4mm', 'A product label', 'Reference material you scan rather than read'],
            ['7pt', 'About 1.25mm', 'Terms and conditions', 'Appendices, data tables, skimming only'],
            ['6pt or below', 'Under 1.1mm', 'A medicine leaflet', 'Not readable for most adults without magnification'],
          ],
        },
        { t: 'note', x: 'Age changes this table. From about forty onwards, presbyopia makes close focus harder, and anything under 11pt becomes work rather than reading. If you do not know who will read the document, 11pt is the honest floor.' },
        { t: 'h2', x: 'Line length is the lever nobody uses' },
        { t: 'p', x: 'Typographers have converged on 45 to 75 characters per line as the comfortable range, with about 66 as the ideal. Shrink the type on a full-width A4 page and you go the wrong way: 9pt across an 18.5cm measure gives well over a hundred characters a line, and the eye loses its place returning to the left margin. The smaller type is not what makes it hard to read; the line length is.' },
        { t: 'p', x: 'So if you are going below about 10pt on a full sheet, set the text in **two columns**. You get the density you were after and a line length that still works. In Word it is Layout → Columns → Two.' },
        { t: 'h2', x: 'The order to apply them' },
        {
          t: 'steps',
          items: [
            { h: 'Open print preview and read the page count', x: 'That is your baseline. Everything below is measured against it.' },
            { h: 'Cut the margins', x: 'Word: Layout → Margins → Narrow. Browsers: the **Margins** dropdown → Minimum. Free density, no readability cost.' },
            { h: 'Turn off headers and footers', x: 'In a browser, **Headers and footers** off removes the title, URL, date and page number your browser adds, which sometimes recovers a whole line per page.' },
            { h: 'Drop the scale to 90 percent', x: 'Check the preview. If it still reads comfortably, try 80. Below 80 the type is doing the work that margins should have done.' },
            { h: 'Tighten the spacing', x: 'Word defaults to 1.08 line spacing with 8pt after every paragraph. Set spacing to 1.0 and space-after to 0, and add a first-line indent instead so paragraphs are still distinguishable.' },
            { h: 'Only now consider pages per sheet', x: 'Two-up is a step change, not an adjustment. It is right for reading copies of academic papers and wrong for anything you will annotate.' },
            { h: 'Look at the preview one more time', x: 'Check the last page. Documents that end with two orphaned lines are the easiest ones to shorten by a whole sheet.' },
          ],
        },
        { t: 'h2', x: 'Spreadsheets are their own problem' },
        { t: 'p', x: 'A spreadsheet does not reflow, so scaling is the only lever. In Excel, use **Page Layout → Scale to Fit** and set **Width** to 1 page while leaving Height on Automatic. That keeps all your columns on one sheet and lets the rows run over several pages, which is almost always what you want. Set **Print Titles** to repeat the header row so page four still tells you what the columns are, and switch to landscape before you start shrinking.' },
        { t: 'cta', tool: 'excel-to-pdf', x: 'Convert a spreadsheet to PDF and check the pagination before you commit paper to it.' },
        { t: 'h2', x: 'The cheapest density trick is not printing it' },
        { t: 'p', x: 'Before optimising the layout, look at what is in the document. Cover pages, revision histories, blank separators, appendices nobody reads and a table of contents for an eight-page report are all pure paper. Cutting four pages from a twenty-page document beats every setting on this page and costs nothing in readability.' },
        { t: 'cta', tool: 'delete-pages', x: 'Remove the pages nobody reads before you start shrinking the ones they do.' },
        { t: 'p', x: 'Once the layout is as tight as it should go, the remaining savings are in [double-sided printing](/blog/save-paper-ink/print-double-sided) and [ink settings](/blog/save-paper-ink/save-ink-when-printing). For slide decks specifically, handout mode does this job better than any scale control — see [printing lecture slides](/blog/students-research/print-lecture-slides).' },
      ],
      faqs: [
        { q: 'What is the smallest readable font size for printing?', a: 'About 9pt for text you will read continuously, and 7 to 8pt for reference material you only scan. Below 6pt most adults cannot read comfortably without magnification. If your audience includes older readers, treat 11pt as the floor.' },
        { q: 'Is it better to reduce margins or reduce the font size?', a: 'Reduce the margins first. Going from one-inch to half-inch margins gives about 28 percent more text area with no change to the type at all. Only shrink the type once the margins are as small as your binding allows.' },
        { q: 'How do I fit a wide spreadsheet on one page?', a: 'In Excel, Page Layout → Scale to Fit, set Width to 1 page and leave Height on Automatic. Switch to landscape first, and turn on Print Titles so the header row repeats on every page rather than only the first.' },
        { q: 'Does printing at 80 percent scale look bad?', a: 'No. At 80 percent, 12pt text prints at roughly 9.6pt, which is comfortable for most adults in good light. The bigger risk is the line length: at that size a full-width A4 line exceeds a hundred characters, which is genuinely tiring. Use two columns.' },
        { q: 'Can I combine two pages per sheet with a scale reduction?', a: 'You can, but you should not. Two-up already scales each page to about 65 percent. Adding 80 percent scale on top gives 52 percent, taking 11pt body text down to about 5.7pt. Choose one lever, not both.' },
      ],
      relatedTools: ['excel-to-pdf', 'delete-pages'],
      relatedPosts: ['save-ink-when-printing', 'print-lecture-slides', 'print-double-sided'],
    },
    {
      slug: 'eco-friendly-printing',
      cluster: 'save-paper-ink',
      title: 'How to print less and waste less',
      metaTitle: 'How to Print Less and Waste Less: 10 Habits',
      metaDescription:
        'Ten habits that cut printing waste: preview discipline, page ranges, a PDF-first workflow, recycled paper, cartridge recycling and the real cost per page.',
      published: '2026-04-29',
      updated: '2026-08-30',
      readMinutes: 8,
      intent: 'listicle',
      primaryKeyword: 'how to reduce printing waste',
      secondaryKeywords: ['eco friendly printing tips', 'paperless office habits', 'recycled printer paper', 'printer cartridge recycling', 'cost per page printing'],
      entities: ['FSC', 'HP Planet Partners', 'Epson', 'Canon', 'Brother', 'Adobe Acrobat Reader', 'A4', 'Energy Star'],
      answer:
        'The largest single win is changing your printer defaults to duplex and greyscale, because it applies to every job without anyone remembering. After that, look at print preview before every job, print page ranges rather than whole documents, and give yourself a PDF-first folder that you print from only after 24 hours.',
      body: [
        { t: 'p', x: 'Most printing waste is not a decision. It is a default nobody changed, a preview nobody opened, and a stack at a shared printer nobody collected. Ten habits, ordered by saving against effort.' },
        { t: 'h2', x: '1. Change the defaults once' },
        { t: 'p', x: 'The highest-leverage item here, because it works on the days you are not thinking about it. Set duplex, greyscale and draft as printer defaults in the operating system, not per job.' },
        {
          t: 'steps',
          items: [
            { h: 'Windows', x: 'Settings → **Printers & scanners** → your printer → **Printing preferences**. Set two-sided, black-ink-only and draft quality. Apply.' },
            { h: 'macOS', x: 'Open any print dialog, set two-sided, black and white and draft, then choose **Save Current Settings as Preset**, name it, and set it as the default preset.' },
            { h: 'Shared office printers', x: 'Ask whoever manages the queue to set server-side defaults. One change beats a memo to fifty people, and it survives new laptops.' },
            { h: 'Leave the override obvious', x: 'Full colour and best quality are still one dialog away. You are changing the path of least resistance, not removing an option.' },
          ],
        },
        { t: 'h2', x: '2. Open print preview every single time' },
        { t: 'p', x: 'Preview is where you find the eleven-page email thread, the blank final sheet, the appendix you did not want and the page about to print as a black rectangle. Three seconds, and it stops five to ten percent of jobs entirely.' },
        { t: 'h2', x: '3. Print ranges, not documents' },
        { t: 'p', x: 'Almost nobody needs all forty pages. Find the pages that carry what you want and type `12-15`. If the document recurs, delete the dead pages once and keep the short version.' },
        { t: 'cta', tool: 'delete-pages', x: 'Cut the appendices and cover sheets out of a document you print regularly.' },
        { t: 'h2', x: '4. Work PDF-first, with a 24-hour rule' },
        { t: 'p', x: 'Save to PDF, put it in a folder called "to print", and revisit tomorrow. Much of what you were certain you needed on paper was a passing impulse. What survives 24 hours is worth a sheet; the rest stays searchable and weightless. [Paper versus PDF](/blog/print-web-pages/print-web-page-to-pdf-vs-printer) covers the call.' },
        { t: 'cta', tool: 'pdf-reader', x: 'Read it on screen first. Most documents never need to leave the file.' },
        { t: 'h2', x: '5. Print in batches' },
        { t: 'p', x: 'One job of forty pages beats ten of four: no banner sheets between jobs, one trip, nothing left in the tray. Merge a reading list or a set of reports into one file and print once.' },
        { t: 'h2', x: '6. Never bin a cartridge' },
        { t: 'p', x: 'Every major manufacturer runs a free prepaid take-back scheme: HP Planet Partners, and equivalents from Canon, Epson and Brother. Office supply chains take them in store. Widely cited estimates put hundreds of millions of cartridges in landfill each year. The programme costs you an envelope.' },
        { t: 'h2', x: '7. Buy the right paper, not the most virtuous-sounding one' },
        {
          t: 'table',
          caption: 'Paper choices for everyday printing.',
          head: ['Paper', 'Typical weight', 'Good for', 'Watch out for'],
          rows: [
            ['Standard office white', '80gsm', 'Everything', 'Show-through when you duplex dense text'],
            ['Lightweight', '70-75gsm', 'Internal drafts, high volume', 'Jams in older printers. Do not duplex it'],
            ['Duplex-friendly', '90-100gsm', 'Double-sided reports and handouts', 'Costs more per sheet, but you buy half as many'],
            ['100% post-consumer recycled', '80gsm', 'Almost all internal printing', 'Lower brightness, around 92 ISO against 96. Fine for text, dull for photographs'],
            ['FSC-certified virgin', '80gsm', 'Client-facing documents', 'Certification is about forestry practice, not about using less paper'],
          ],
        },
        { t: 'note', x: 'The arithmetic favours using less over buying better. Commonly cited estimates put one A4 sheet at several litres of water and a few grams of carbon dioxide. Halving your volume beats upgrading the paper you print twice as much of.' },
        { t: 'h2', x: '8. Fix the shared-printer problem' },
        { t: 'p', x: 'Every office has a tray of abandoned printouts: jobs sent twice, sent to the wrong floor, or forgotten. Secure release, where the job prints only when you tap a badge at the device, typically removes a tenth to a fifth of the volume, because accidental jobs expire. Failing that, put a recycling tray beside the printer.' },
        { t: 'h2', x: '9. Reuse the single-sided misprints' },
        { t: 'p', x: 'Keep a tray of one-sided paper for drafts and notes. It costs nothing, uses paper already made, and is the only step here your printer need not know about.' },
        { t: 'h2', x: '10. Cut the clutter before it reaches the paper' },
        { t: 'p', x: 'Web pages are the worst offenders: a 600-word article routinely prints as nine sheets of navigation, adverts and related-story grids. Cleaned, it is two. See [printing a web page without ads](/blog/print-web-pages/print-web-page-without-ads), or use the [web page printer](/print).' },
        { t: 'h2', x: 'The maths, on a real office' },
        { t: 'p', x: 'Twenty people printing thirty pages each on a working day is 600 a day and roughly 150,000 a year. At an all-in 3.5 cents a page, about $5,250 before the printer lease.' },
        {
          t: 'table',
          caption: 'Order-of-magnitude effects on 150,000 pages a year.',
          head: ['Change', 'What it removes', 'Annual effect'],
          rows: [
            ['Duplex by default', 'Half the sheets', '75,000 sheets, about 150 reams and 375kg of paper'],
            ['Greyscale by default', 'Colour on documents that never needed it', 'Often the largest single line item on a colour device'],
            ['Draft quality for internal work', 'Roughly a third of the toner', 'A few hundred dollars of consumables'],
            ['Print preview before every job', '5-10% of jobs never sent', '7,500 to 15,000 pages'],
            ['Secure release at shared printers', 'Abandoned and duplicate jobs', '10-20% of volume at a busy device'],
            ['Page ranges instead of whole documents', 'The pages nobody reads', 'Highly variable, and frequently the biggest win of all'],
          ],
        },
        { t: 'p', x: 'Note the shape of that table: every large number comes from a default or a habit, not a product. You do not need a new printer to halve your printing.' },
        { t: 'h2', x: 'The one-page version' },
        {
          t: 'ol',
          items: [
            'Set duplex, greyscale and draft as your printer defaults today.',
            'Open print preview before every job, without exception.',
            'Print page ranges, never whole documents by reflex.',
            'Save to PDF first and print tomorrow, if you still want to.',
            'Clean web pages before printing them.',
            'Batch small jobs into one.',
            'Buy 90gsm if you duplex, recycled 80gsm if you do not.',
            'Post every empty cartridge back on the free scheme.',
            'Keep a scrap tray of one-sided misprints.',
            'Clear the abandoned-printouts tray weekly and recycle it.',
          ],
        },
        { t: 'p', x: 'The detail behind each of these lives in [saving ink](/blog/save-paper-ink/save-ink-when-printing), [printing double-sided](/blog/save-paper-ink/print-double-sided) and [fitting more on a page](/blog/save-paper-ink/fit-more-on-a-page).' },
      ],
      faqs: [
        { q: 'What is the single biggest way to reduce printing waste?', a: 'Setting duplex and greyscale as the printer defaults in the operating system rather than choosing them per job. It halves paper immediately and applies to everyone and every application without anybody having to remember.' },
        { q: 'Is recycled paper worse for my printer?', a: 'Modern 80gsm post-consumer recycled paper runs fine in laser and inkjet printers. It is slightly less bright, around 92 ISO against 96, which is invisible on text and noticeable on photographs. Very cheap recycled stock can shed more dust, so buy a known brand.' },
        { q: 'Where can I recycle printer cartridges?', a: 'Every major manufacturer runs a free prepaid take-back programme, including HP Planet Partners and equivalents from Canon, Epson and Brother. Large office supply retailers also accept them in store, sometimes for a small store credit.' },
        { q: 'What does one printed page actually cost?', a: 'Roughly 2.5 to 5 cents all in on a mono laser, and 15 to 25 cents on an inkjet printing colour with manufacturer cartridges. Refillable tank printers get under a cent. Add about a cent per sheet for paper on top of the ink or toner.' },
        { q: 'Is it always greener to read on screen than to print?', a: 'Usually, but not always. A page you read once on a device you already own is greener than a printed sheet. A long document you would otherwise read on a laptop for three hours is closer to a draw. The clear waste is the printout nobody reads.' },
      ],
      relatedTools: ['pdf-reader', 'delete-pages'],
      relatedPosts: ['save-ink-when-printing', 'print-double-sided', 'print-web-page-to-pdf-vs-printer'],
    },
  ],
}
