import type { Cluster } from '../types'

export const signPdf: Cluster = {
  slug: 'sign-pdf',
  name: 'Signing PDFs',
  title: 'How to sign a PDF: signatures, forms and what actually counts',
  metaTitle: 'Sign a PDF Free: Signatures, Forms and the Law',
  metaDescription:
    'Sign a PDF in your browser: draw, type or upload a signature, fill in form fields, flatten the result, and understand when an electronic signature is binding.',
  intro:
    'Print, sign, scan, email is a four-step ritual that produces a crooked grey photograph and needs a printer you probably do not have. All of it can be done on screen instead: place a signature image on the page, type into the form fields, add the date, and flatten the file so nothing can be nudged afterwards. These guides cover how, how to make a signature that does not look like a scan, and what US and EU law says about the result.',
  answer:
    'To sign a PDF without printing it, open the file in a signing tool, create a signature by drawing, typing or uploading a transparent PNG, drag it onto the signature line, add the date, then flatten and download. In most countries this carries the same legal weight as ink on paper.',
  primaryKeyword: 'how to sign a pdf',
  entities: ['ESIGN Act', 'UETA', 'eIDAS', 'Adobe Acrobat', 'DocuSign', 'AcroForm', 'Preview (macOS)', 'PNG'],
  icon: '✍',
  tools: ['sign-pdf', 'flatten-pdf', 'pdf-reader', 'jpg-to-pdf'],
  posts: [
    {
      slug: 'how-to-sign-a-pdf',
      cluster: 'sign-pdf',
      title: 'How to sign a PDF without printing it',
      metaTitle: 'How to Sign a PDF Without Printing It',
      metaDescription:
        'Sign a PDF on screen in under a minute. Draw, type or upload your signature, place it on the line, add the date, then flatten the file so it cannot be moved.',
      published: '2026-01-29',
      updated: '2026-08-21',
      readMinutes: 6,
      intent: 'howto',
      primaryKeyword: 'how to sign a pdf',
      secondaryKeywords: ['sign pdf online free', 'add signature to pdf', 'sign a pdf without printing', 'electronic signature on pdf', 'draw signature on pdf'],
      entities: ['Adobe Acrobat Reader', 'Preview (macOS)', 'Microsoft Edge', 'DocuSign', 'Apple Pencil', 'PNG', 'AcroForm', 'ESIGN Act'],
      answer:
        'Open the PDF in a signing tool, create your signature by drawing it with a mouse or finger, typing it in a handwriting font, or uploading a transparent PNG. Drag it onto the signature line, resize it to about the height of the surrounding text, add the date, then flatten and download.',
      body: [
        { t: 'p', x: 'Print, sign, scan is still the default for a lot of people, and it produces the worst version of the document: a grey, slightly rotated photograph of a page that is three times the original file size and no longer searchable. Signing on screen takes about a minute and leaves the document intact.' },
        { t: 'h2', x: 'Three ways to make the mark' },
        { t: 'p', x: 'Every signing tool offers the same three options, and they are not equally good.' },
        {
          t: 'table',
          caption: 'How to produce the signature itself.',
          head: ['Method', 'How it looks', 'Best when'],
          rows: [
            ['Draw with a mouse', 'Wobbly and obviously drawn', 'You need something in the next thirty seconds'],
            ['Draw with a finger or stylus', 'Close to your real hand', 'You are on a phone, a tablet or a trackpad'],
            ['Type it in a script font', 'Neat, clearly not handwriting', 'Internal forms, timesheets, low-stakes approvals'],
            ['Upload a PNG of your real signature', 'Identical to ink on paper', 'Contracts, offers, anything a client will see'],
          ],
        },
        { t: 'p', x: 'The uploaded PNG is the one worth setting up once. It takes five minutes, it works in every tool afterwards, and it is the only option that looks like you actually signed. [How to create a clean signature image](/blog/sign-pdf/create-a-signature-image) covers the whole process, including getting the background properly transparent.' },
        { t: 'h2', x: 'Signing the document' },
        {
          t: 'steps',
          items: [
            { h: 'Open the PDF', x: 'Drop the file onto the [PDF signing tool](/tools/sign-pdf). It opens in your browser and nothing is uploaded, which matters when the document is an employment contract or a tenancy agreement.' },
            { h: 'Create your signature', x: 'Choose **Draw**, **Type** or **Upload**. If you upload, use a PNG with a transparent background so the signature sits on the line rather than in a white box.' },
            { h: 'Place it on the page', x: 'Drag the signature onto the signature line. Drop it so the baseline of your writing sits on the printed rule, not floating above it, and let the descenders cross below slightly the way real ink does.' },
            { h: 'Size it sensibly', x: 'A signature that is roughly two to three times the height of the body text reads as natural. Anything taller looks pasted on. On a standard form, that is usually 150 to 250 px wide on screen.' },
            { h: 'Add the date and any initials', x: 'Use a text box for the date, matched roughly to the form’s font size. Many documents also need initials in the footer of every page, or a printed name under the signature.' },
            { h: 'Flatten and download', x: 'Turn on **Flatten** before you export. This merges the signature into the page content so it can no longer be selected, dragged or deleted by whoever opens the file next.' },
          ],
        },
        { t: 'cta', tool: 'sign-pdf', x: 'Sign a PDF in your browser. Draw, type or upload a signature, then flatten and download.' },
        { t: 'h2', x: 'Why flattening matters' },
        { t: 'p', x: 'A signature added as an annotation is a separate object floating over the page. Anyone who opens the file in Acrobat, Preview or even a browser can click it, drag it somewhere else, or press Delete. Flattening bakes it into the page content stream, at which point it behaves exactly like ink: still visible, no longer an object.' },
        { t: 'p', x: 'The same applies to filled-in form fields. An unflattened form is a live form, and the next person to open it can retype your answers. See [filling in and signing a PDF form](/blog/sign-pdf/fill-and-sign-a-form) for how the two interact.' },
        { t: 'warn', x: 'Flattening is one-way. Once a form is flattened the fields are gone and the answers cannot be edited, so keep an unflattened copy if you might need to revise it. Flatten the copy you send, not the copy you keep.' },
        { t: 'h2', x: 'Where the signature line is not obvious' },
        { t: 'p', x: 'Some documents arrive as a flat scan with no fields and no clear line, or as a photograph of a page. Two fixes:' },
        {
          t: 'ul',
          items: [
            'If it is a **scan of a printed form**, place the signature freely over the image. There are no fields to fill, so a text box is the only way to add typed information. Consider [running OCR](/blog/ocr-scanned-documents/how-to-ocr-a-scanned-pdf) first so the recipient can at least search the document.',
            'If it arrived as **JPG or HEIC photos** rather than a PDF, [convert the images to a PDF](/tools/jpg-to-pdf) first so the whole thing is one file and the pages stay in order.',
          ],
        },
        { t: 'h2', x: 'What the built-in apps can do' },
        {
          t: 'table',
          head: ['Tool', 'Signing support', 'Notes'],
          rows: [
            ['Preview (macOS)', 'Markup toolbar → Sign', 'Captures a signature via trackpad or camera and stores it for reuse. Very good.'],
            ['Adobe Acrobat Reader', 'Fill & Sign', 'Free tier. Recent versions push you towards a cloud account for some features.'],
            ['Microsoft Edge', 'Draw only', 'The freehand Draw tool works, but there is no reusable signature.'],
            ['iOS and iPadOS Markup', 'Share → Markup → Signature', 'Best with an Apple Pencil. Syncs saved signatures across devices.'],
            ['Google Chrome', 'None built in', 'Use a browser tool.'],
            ['DocuSign and similar', 'Full audit trail', 'Overkill for one form, appropriate for negotiated contracts.'],
          ],
        },
        { t: 'h2', x: 'Is this actually valid?' },
        { t: 'p', x: 'In the United States, the ESIGN Act and state adoptions of UETA give an electronic signature the same legal effect as ink for most commercial and consumer agreements. In the European Union, eIDAS says a signature cannot be denied legal effect merely because it is electronic. There are real exceptions — wills, some property transfers, certain court filings — and higher-assurance signature types exist for high-value work. [Are electronic signatures legally binding?](/blog/sign-pdf/electronic-signature-legally-binding) covers the detail.' },
        { t: 'note', x: 'For most everyday documents — a rental application, a school form, a supplier agreement, an offer letter — a placed signature image plus a date is exactly what the other side expects and will accept. Save the heavier certificate-based tooling for the cases that genuinely need it.' },
        { t: 'h2', x: 'After signing' },
        { t: 'p', x: 'Two habits worth keeping. First, check the file size: a signed contract should still be a few hundred kilobytes, and if it has ballooned to 15 MB, something re-rasterised the pages and it is worth compressing before emailing. Second, check what the file says about you — PDF metadata carries author names, software versions and edit timestamps that you may not want to hand over.' },
      ],
      faqs: [
        { q: 'How do I sign a PDF without Adobe Acrobat?', a: 'Use a browser-based signing tool, Preview on macOS, or Markup on iOS. All three let you place a signature image on the page and export a signed file, with no Acrobat licence and no account required.' },
        { q: 'Is a drawn or typed signature legally valid?', a: 'In most jurisdictions, yes, for ordinary commercial agreements. What matters legally is intent to sign and consent to transact electronically, not how the mark was produced. Some document types are excluded, so check anything unusual.' },
        { q: 'How do I stop someone from moving my signature after I sign?', a: 'Flatten the document before sending it. Flattening merges annotations and form values into the page content, so the signature can no longer be selected, dragged or deleted in any PDF editor.' },
        { q: 'What size should a signature be on a PDF?', a: 'Roughly two to three times the height of the surrounding body text, which on a typical form is 150 to 250 pixels wide. Sit the baseline of the writing on the printed line rather than floating above it.' },
        { q: 'Can I sign a PDF on my phone?', a: 'Yes. On iOS use Share → Markup → Signature, which lets you sign with a finger or an Apple Pencil and saves the signature for reuse. On Android, a browser signing tool works in Chrome without installing anything.' },
      ],
      relatedTools: ['sign-pdf', 'flatten-pdf'],
      relatedPosts: ['create-a-signature-image', 'fill-and-sign-a-form', 'electronic-signature-legally-binding'],
    },
    {
      slug: 'electronic-signature-legally-binding',
      cluster: 'sign-pdf',
      title: 'Are electronic signatures legally binding?',
      metaTitle: 'Are Electronic Signatures Legally Binding?',
      metaDescription:
        'What the ESIGN Act, UETA and eIDAS actually say about electronic signatures, which documents are excluded, and what makes a signature hold up if challenged.',
      published: '2026-02-25',
      updated: '2026-08-11',
      readMinutes: 8,
      intent: 'informational',
      primaryKeyword: 'are electronic signatures legally binding',
      secondaryKeywords: ['esign act explained', 'ueta electronic signature', 'eidas qualified signature', 'is a typed signature legal', 'electronic signature exceptions'],
      entities: ['ESIGN Act', 'UETA', 'eIDAS', 'Uniform Law Commission', 'European Union', 'Electronic Signatures and Records Act', 'Law Commission of England and Wales', 'Uniform Commercial Code'],
      answer:
        'Yes, in most cases. In the US the ESIGN Act and state UETA adoptions give electronic signatures the same legal effect as ink for most agreements. In the EU, eIDAS says a signature cannot be denied validity merely for being electronic. Wills, certain property and family-law documents remain excluded.',
      body: [
        { t: 'note', x: 'This article is general information about how electronic signature law is structured. It is not legal advice, it is not a substitute for a lawyer, and it cannot account for your jurisdiction, your industry or the specific document in front of you. For anything high-value, regulated or contested, get advice from a qualified lawyer in the relevant country.' },
        { t: 'p', x: 'The law caught up with this a long time ago. The United States passed federal legislation in 2000 and the European Union has had a single regulation since 2016. The practical question now is almost never "is an electronic signature allowed" but "can I prove who signed and that they meant to".' },
        { t: 'h2', x: 'The United States: ESIGN and UETA' },
        { t: 'p', x: 'Two overlapping frameworks apply.' },
        {
          t: 'ul',
          items: [
            '**ESIGN Act** — the Electronic Signatures in Global and National Commerce Act, signed in 2000, is federal law. It provides that a signature, contract or record may not be denied legal effect solely because it is in electronic form, in transactions affecting interstate or foreign commerce.',
            '**UETA** — the Uniform Electronic Transactions Act, drafted by the Uniform Law Commission in 1999, is a model law that states adopt individually. It has been enacted in 49 states plus the District of Columbia, Puerto Rico and the US Virgin Islands. New York is the exception and instead has its own Electronic Signatures and Records Act.',
          ],
        },
        { t: 'p', x: 'ESIGN defines an electronic signature broadly: an electronic sound, symbol or process attached to or logically associated with a record and executed or adopted by a person with the intent to sign it. That covers a typed name, a drawn mark, a clicked "I agree" button and a certificate-based digital signature alike. The mechanism is not what makes it valid — intent is.' },
        { t: 'h3', x: 'What ESIGN does not cover' },
        { t: 'p', x: 'The statute carves out specific categories, broadly those where a physical original or a witness has traditionally been required:' },
        {
          t: 'ul',
          items: [
            'Wills, codicils and testamentary trusts.',
            'Adoption, divorce and other matters of family law.',
            'Most of the Uniform Commercial Code, other than the sales and leases articles.',
            'Court orders, notices and other official court documents.',
            'Notices of utility service cancellation.',
            'Notices of default, foreclosure, eviction or repossession relating to a primary residence.',
            'Cancellation of health or life insurance benefits.',
            'Product recall notices affecting health or safety, and documents required to accompany hazardous materials in transport.',
          ],
        },
        { t: 'p', x: 'ESIGN also adds a consumer-protection layer: where a law requires a record to be given to a consumer in writing, the consumer must affirmatively consent to receiving it electronically, and be told how to withdraw consent and what software they need.' },
        { t: 'h2', x: 'The European Union: eIDAS and its three tiers' },
        { t: 'p', x: 'Regulation (EU) No 910/2014, universally called eIDAS, has applied across the member states since July 2016 and was amended in 2024 to add the European Digital Identity Wallet. Its central principle, in Article 25, is non-discrimination: a signature cannot be denied legal effect or admissibility as evidence solely because it is electronic, or because it is not a qualified signature.' },
        {
          t: 'table',
          caption: 'The three eIDAS signature levels.',
          head: ['Level', 'What it requires', 'Typical use'],
          rows: [
            ['Simple (SES)', 'Data in electronic form attached to or logically associated with other data and used to sign', 'Internal approvals, low-risk agreements, clickwrap'],
            ['Advanced (AdES)', 'Uniquely linked to and capable of identifying the signatory, created under their sole control, and tamper-evident afterwards', 'Commercial contracts, HR documents, most B2B work'],
            ['Qualified (QES)', 'An advanced signature made on a qualified signature creation device using a qualified certificate from a listed trust service provider', 'Anything the law requires to be a handwritten signature'],
          ],
        },
        { t: 'p', x: 'The practical difference is Article 25(2): a qualified electronic signature has the equivalent legal effect of a handwritten signature. Simple and advanced signatures remain valid and admissible, but their weight is a question of evidence rather than one settled by the regulation.' },
        { t: 'p', x: 'In the United Kingdom, section 7 of the Electronic Communications Act 2000 makes electronic signatures admissible, and the Law Commission of England and Wales confirmed in 2019 that an electronic signature can validly execute documents, including deeds, provided the usual formalities are met. Deeds still need a physically present witness.' },
        { t: 'h2', x: 'What actually makes a signature hold up' },
        { t: 'p', x: 'Disputes almost never turn on whether electronic signatures are legal. They turn on evidence. Five things carry the weight:' },
        {
          t: 'ol',
          items: [
            '**Intent to sign.** The signer must have meant the mark as a signature. A name typed into a "your name" field on a web form is weaker than a name typed into a box labelled "sign here".',
            '**Consent to transact electronically.** Explicit for consumer disclosures under ESIGN; implied by conduct in most business dealings.',
            '**Attribution.** Some link between the signature and the person: an email account, a verified phone number, an ID check, a certificate.',
            '**Integrity.** Evidence that the document has not changed since signing. This is what tamper-evident and certificate-based signatures buy you.',
            '**Retention.** The signed record must be accurately reproducible by everyone entitled to it. Keep the final PDF, not a screenshot of it.',
          ],
        },
        { t: 'p', x: 'This is why an audit trail matters more than the look of the signature. A cursive image proves nothing on its own; a timestamped log of who opened the file, from where, and when they signed, proves a great deal.' },
        { t: 'h2', x: 'When you still need a notary or a witness' },
        { t: 'p', x: 'Notarisation is a separate requirement and survives all of the above. Documents that commonly still need it include deeds transferring real property, powers of attorney, affidavits and some estate documents. Many US states now authorise remote online notarisation, where the notary appears over audio-video link and applies a digital seal, though the rules vary by state.' },
        { t: 'warn', x: 'Do not assume a rule from one country applies in another. Sector rules can be stricter than the general law: pharmaceutical records under FDA 21 CFR Part 11, financial services, healthcare consent and public procurement all add requirements on top of ESIGN or eIDAS.' },
        { t: 'h2', x: 'A practical rule of thumb' },
        {
          t: 'table',
          head: ['Document', 'Usually fine with', 'Consider stronger'],
          rows: [
            ['Internal approval, timesheet, policy acknowledgement', 'Typed or drawn signature', 'No'],
            ['Supplier agreement, NDA, offer letter', 'Signature image plus flattening', 'Audit-trail platform if large'],
            ['Lease, loan or high-value contract', 'Audit-trail platform', 'Advanced or qualified signature'],
            ['Deed, will, property transfer', 'Nothing electronic by default', 'Lawyer and notary or witness'],
            ['Anything regulated (health, finance, pharma)', 'Check the sector rule first', 'Qualified signature where required'],
          ],
        },
        { t: 'p', x: 'For the everyday cases in the first two rows, [signing the PDF in your browser](/blog/sign-pdf/how-to-sign-a-pdf), [filling the fields properly](/blog/sign-pdf/fill-and-sign-a-form) and [flattening](/tools/flatten-pdf) is the whole job. Keep the flattened file and the covering email, and you have a reasonable record.' },
        { t: 'cta', tool: 'sign-pdf', x: 'Sign and flatten a document in your browser, with nothing uploaded to a server.' },
      ],
      faqs: [
        { q: 'Is a typed signature legally binding?', a: 'Under the ESIGN Act definition, a typed name can be a valid electronic signature if it was executed or adopted with intent to sign. It is weaker evidence than a certificate-based signature, so context and audit trail matter more.' },
        { q: 'Which documents cannot be signed electronically in the US?', a: 'ESIGN excludes wills, codicils and testamentary trusts, family law matters such as adoption and divorce, court documents, most of the Uniform Commercial Code, and certain notices including foreclosure, eviction and insurance cancellation.' },
        { q: 'What is the difference between an electronic and a digital signature?', a: 'Electronic signature is the legal concept: any mark made with intent to sign. Digital signature is one technical method, using a cryptographic certificate to bind the signer to the document and make later changes detectable.' },
        { q: 'Does an electronic signature need to look like handwriting?', a: 'No. Neither ESIGN nor eIDAS requires a cursive appearance. A handwritten look is a convention that reassures the reader, but the legal test is intent to sign and the evidence connecting the signer to the record.' },
        { q: 'Are electronic signatures valid internationally?', a: 'Most major economies recognise them, but the frameworks differ and some require a qualified or certificate-based signature for particular document types. For cross-border contracts, agree the signing method in advance and take local advice.' },
      ],
      relatedTools: ['sign-pdf', 'flatten-pdf'],
      relatedPosts: ['how-to-sign-a-pdf', 'fill-and-sign-a-form', 'are-online-pdf-tools-safe'],
    },
    {
      slug: 'create-a-signature-image',
      cluster: 'sign-pdf',
      title: 'How to create a clean signature image with a transparent background',
      metaTitle: 'Make a Transparent Signature PNG in 5 Minutes',
      metaDescription:
        'Turn a signature on paper into a clean transparent PNG. Pen and paper setup, phone photo tips, contrast and threshold settings, and the pixel size to aim for.',
      published: '2026-03-19',
      updated: '2026-07-24',
      readMinutes: 5,
      intent: 'howto',
      primaryKeyword: 'transparent signature image',
      secondaryKeywords: ['signature png transparent background', 'how to make a signature image', 'scan signature for documents', 'remove white background from signature'],
      entities: ['PNG', 'Adobe Photoshop', 'GIMP', 'Preview (macOS)', 'JPEG', 'Continuity Camera', 'Microsoft Paint', 'iPhone'],
      answer:
        'Sign a sheet of unlined white paper with a black pen, photograph it in flat daylight, crop tight, raise the contrast until the paper is pure white, then delete the white to alpha and export as PNG-24. Aim for around 1000 px wide so it stays sharp when printed.',
      body: [
        { t: 'p', x: 'A signature image done properly takes five minutes once, and then works in every PDF you ever sign. Done badly it produces the thing everyone recognises immediately: a grey rectangle sitting on top of the form, edges visible, slightly the wrong shade of white.' },
        { t: 'h2', x: 'Capture: paper beats a mouse' },
        { t: 'p', x: 'Drawing with a mouse never looks right. Sign on paper and photograph it, or capture directly on a touchscreen with a stylus. The paper route gives the best result because it is literally your handwriting at its natural speed.' },
        {
          t: 'steps',
          items: [
            { h: 'Use the right pen and paper', x: 'Plain unlined white paper and a black gel or felt-tip pen, around 0.7 mm. Ballpoint lines are thin and grey, which threshold badly. Blue ink also works but converts less cleanly.' },
            { h: 'Sign it several times', x: 'Sign four or five times across the sheet. You will pick the best one, and you almost never like the first.' },
            { h: 'Photograph it flat', x: 'Daylight near a window, no flash, no direct sun. Hold the phone parallel to the paper, not at an angle, and let your body shadow fall away from the page. Tap to focus on the ink.' },
            { h: 'Crop tight', x: 'Crop to the signature plus a small margin. Everything you leave in is background you will have to remove later.' },
            { h: 'Raise the contrast until the paper disappears', x: 'In any photo editor, push contrast and pull the white point down until the paper is pure white and the ink is solid black. In Photoshop or GIMP, **Levels** with the white input slider moved left does this precisely.' },
            { h: 'Delete the white to transparency', x: 'GIMP: **Colors → Color to Alpha**, target white. Photoshop: **Select → Color Range**, pick the white, then delete on an unlocked layer. Preview on macOS: the Instant Alpha tool in Markup.' },
            { h: 'Export as PNG', x: 'Save as PNG-24 with alpha. Never JPG, which has no transparency and will reintroduce a white box.' },
          ],
        },
        { t: 'warn', x: 'Do not save the finished signature as a JPG. JPEG has no alpha channel, so the transparency is discarded and the file comes back with a solid white rectangle around your signature — plus compression halos along every stroke.' },
        { t: 'h2', x: 'How big should it be?' },
        { t: 'p', x: 'Size it for the worst case, which is printing. A signature occupies roughly 2 to 3 inches on a printed form, and print wants 300 pixels per inch, so 900 to 1000 pixels wide is the target. Storing it larger costs nothing meaningful and lets you scale down cleanly; storing it at 200 px means it will look soft the first time someone prints the contract.' },
        {
          t: 'table',
          caption: 'Signature image sizing.',
          head: ['Use', 'Width in pixels', 'Notes'],
          rows: [
            ['Screen-only PDF, email signature', '400 - 600', 'Small file, fine on a display'],
            ['General purpose, recommended', '900 - 1200', 'Prints at 300 DPI across 3 to 4 inches'],
            ['Large-format or archival', '1800+', 'Overkill for most documents'],
            ['Too small', 'Under 300', 'Visibly pixelated as soon as it is printed'],
          ],
        },
        { t: 'p', x: 'The same 300 DPI logic applies to everything else you put on a page — see [what resolution you need for printing](/blog/pdf-images/best-image-format-for-print) if you want the arithmetic.' },
        { t: 'h2', x: 'Capture methods compared' },
        {
          t: 'table',
          head: ['Method', 'What you need', 'Quality'],
          rows: [
            ['Phone photo of paper', 'Paper, black pen, daylight', 'Best. Real handwriting, full resolution.'],
            ['Flatbed scanner at 600 DPI', 'A scanner', 'Excellent and evenly lit, but slower.'],
            ['Preview on macOS, camera mode', 'A Mac with a webcam', 'Very good. Holds the paper up to the camera and cuts it out for you.'],
            ['Preview on macOS, trackpad mode', 'A Mac', 'Decent with practice. Signing on glass is awkward.'],
            ['iPad or iPhone with Apple Pencil', 'An Apple Pencil', 'Very good, and pressure sensitivity helps.'],
            ['Mouse in a signing tool', 'Nothing', 'Poor. Recognisably drawn with a mouse.'],
          ],
        },
        { t: 'tip', x: 'macOS Preview will do the whole capture and cut-out in one step: **Tools → Annotate → Signature → Create Signature → Camera**, then hold the signed paper up to the webcam. It removes the background automatically and stores the result for reuse across Preview and Mail.' },
        { t: 'h2', x: 'Checking the result' },
        { t: 'p', x: 'Open the finished PNG in a viewer that shows a checkerboard behind transparency, then check three things: the background is genuinely transparent rather than white, the strokes are solid black rather than dark grey, and the edges are smooth rather than jagged. Jagged edges usually mean the file was saved as PNG-8, which supports only a single fully transparent colour instead of a real alpha channel.' },
        { t: 'p', x: 'The real test is to place it on a document with a coloured or shaded background. Any leftover halo shows up immediately there, and nowhere else.' },
        { t: 'cta', tool: 'sign-pdf', x: 'Upload your finished PNG once and reuse it on every document you sign.' },
        { t: 'h2', x: 'Storing it safely' },
        { t: 'warn', x: 'A signature PNG is a reusable copy of your signature. Anyone with the file can place it on any document. Keep it in an encrypted folder or a password manager rather than a shared drive, do not email it to anyone, and do not post a signed document publicly at full resolution — a signature is easy to extract from a published PDF, as [extracting images from a PDF](/blog/pdf-images/extract-images-from-pdf) shows.' },
        { t: 'p', x: 'For the same reason, [flatten documents before sending them](/blog/sign-pdf/how-to-sign-a-pdf). A flattened signature is much harder to lift cleanly than an annotation object sitting in its own layer.' },
      ],
      faqs: [
        { q: 'How do I remove the white background from a signature?', a: 'Raise the contrast until the paper is pure white, then delete white to alpha: Color to Alpha in GIMP, Select → Color Range in Photoshop, or Instant Alpha in macOS Preview. Save the result as PNG-24.' },
        { q: 'What size should a signature image be?', a: 'Around 900 to 1200 pixels wide. That prints cleanly at 300 DPI across three or four inches. Below 300 pixels the signature looks pixelated as soon as the document is printed.' },
        { q: 'Can I use a JPG for my signature?', a: 'Not if you want a transparent background. JPEG has no alpha channel, so the signature arrives inside a white box, and JPEG compression adds visible halos along the strokes. Always use PNG.' },
        { q: 'What pen should I use for a signature I am going to scan?', a: 'A black gel or felt-tip pen around 0.7 mm on unlined white paper. Thick, solid strokes survive thresholding. Ballpoint lines are too thin and grey, and often break up when you push the contrast.' },
        { q: 'Is it safe to keep a signature image on my computer?', a: 'Treat it like a credential. Anyone holding the file can apply it to any document, so store it encrypted, avoid shared drives and email attachments, and flatten documents before sending so the signature cannot easily be lifted back out.' },
      ],
      relatedTools: ['sign-pdf', 'jpg-to-pdf'],
      relatedPosts: ['how-to-sign-a-pdf', 'fill-and-sign-a-form', 'pdf-to-png-transparent'],
    },
    {
      slug: 'fill-and-sign-a-form',
      cluster: 'sign-pdf',
      title: 'How to fill in and sign a PDF form',
      metaTitle: 'How to Fill In and Sign a PDF Form',
      metaDescription:
        'Fill in a PDF form on screen, whether it has real fields or is a flat scan. How to tell which kind you have, type on either, and flatten so nothing changes.',
      published: '2026-04-15',
      updated: '2026-08-02',
      readMinutes: 7,
      intent: 'howto',
      primaryKeyword: 'how to fill in a pdf form',
      secondaryKeywords: ['fill and sign pdf', 'type on a pdf that has no fields', 'pdf form fields not working', 'flatten pdf form', 'editable pdf form'],
      entities: ['AcroForm', 'XFA', 'Adobe Acrobat', 'Adobe LiveCycle Designer', 'Preview (macOS)', 'Google Chrome', 'Microsoft Edge', 'PDF'],
      answer:
        'First find out which kind of form you have. If clicking a blank produces a text cursor, it is an interactive AcroForm: type into the fields and tab between them. If nothing happens, it is a flat scan, so add free text boxes on top instead. Flatten the file afterwards either way.',
      body: [
        { t: 'p', x: 'Two documents can look identical and behave completely differently. One has real form fields built into it and fills in like a web form. The other is a photograph of a piece of paper with no interactivity at all. Everything about the workflow depends on which one you were sent.' },
        { t: 'h2', x: 'Work out which kind you have' },
        { t: 'p', x: 'Open the file and click on a blank where an answer should go.' },
        {
          t: 'ul',
          items: [
            'A **blinking text cursor appears** and you can type: it is an interactive AcroForm. Pressing Tab jumps to the next field, which is the quickest confirmation.',
            '**Nothing happens** and the pointer stays an arrow: it is a flat page. Either it was scanned, or it was exported to PDF without the fields.',
            'A banner appears saying the document **requires Adobe Acrobat**: it is an XFA form, built in LiveCycle Designer. Browsers and most viewers cannot render these.',
          ],
        },
        { t: 'p', x: 'In Adobe Acrobat there is a definitive check: **More → Form Options → Highlight Existing Fields**, which paints every fillable field pale blue. If nothing turns blue, there are no fields to find.' },
        {
          t: 'table',
          caption: 'The two kinds of PDF form.',
          head: ['', 'Interactive form (AcroForm)', 'Flat page or scan'],
          rows: [
            ['Clicking a blank', 'Gives a text cursor', 'Does nothing'],
            ['Tab key', 'Moves between fields', 'Does nothing'],
            ['How to fill it', 'Type directly into the field', 'Place free text boxes on top'],
            ['Alignment', 'Automatic, inside the field', 'Manual, you position each box'],
            ['Checkboxes', 'Click to tick', 'Type an X, or draw one'],
            ['Searchable text', 'Yes', 'Only after OCR'],
            ['Can be reset or refilled', 'Yes, until flattened', 'Not applicable'],
          ],
        },
        { t: 'h2', x: 'Filling an interactive form' },
        {
          t: 'steps',
          items: [
            { h: 'Open it in a real PDF viewer', x: 'Use the [browser PDF reader](/tools/pdf-reader) or a desktop viewer. Some previewers — inline mail attachments in particular — render the page but ignore the form layer entirely.' },
            { h: 'Tab through every field first', x: 'Before typing anything, press Tab repeatedly to see how many fields exist and where they are. Forms routinely hide fields in the margins or on a second page.' },
            { h: 'Fill in the text fields', x: 'Type normally. If text disappears as you type, the field has a character limit or a fixed font size set by the author and your answer is too long for the box.' },
            { h: 'Handle checkboxes and radio buttons', x: 'Click a checkbox to toggle it. Radio buttons in one group are mutually exclusive — selecting one clears the rest, which is intended behaviour, not a bug.' },
            { h: 'Add the signature', x: 'If there is a dedicated signature field, click it. If not, place a signature image on the line as described in [how to sign a PDF](/blog/sign-pdf/how-to-sign-a-pdf).' },
            { h: 'Flatten before sending', x: 'Export with **Flatten** enabled so the answers become part of the page instead of remaining editable form values.' },
          ],
        },
        { t: 'cta', tool: 'sign-pdf', x: 'Fill in the blanks, drop your signature on the line, then flatten and download.' },
        { t: 'h2', x: 'Typing on a flat PDF' },
        { t: 'p', x: 'When there are no fields, you are placing text on top of an image. It works fine; it just needs a little care to avoid looking obviously pasted on.' },
        {
          t: 'ol',
          items: [
            'Zoom to about 150 percent so you can position boxes precisely against the printed rules.',
            'Add a text box and drag it over the blank. Set the baseline of the text to sit on the printed line, not above it.',
            'Match the size roughly to the form. Most printed forms use 9 to 11 pt, so a text box at 10 pt looks right.',
            'Use a plain sans-serif face. Trying to match a scanned form’s typeface almost always looks worse than a neutral one.',
            'For checkboxes, type a capital X or place a small tick image. Do not try to draw one freehand.',
            'Work down the page in order so you do not miss a blank, then zoom out and check the whole sheet before exporting.',
          ],
        },
        { t: 'tip', x: 'If the scan is crooked, straighten it before you start. Text boxes aligned to a rotated form look wrong at every zoom level, and the same deskewing improves OCR — see [getting better OCR results](/blog/ocr-scanned-documents/improve-ocr-accuracy).' },
        { t: 'h2', x: 'Common problems' },
        {
          t: 'table',
          head: ['Symptom', 'Cause', 'Fix'],
          rows: [
            ['Fields visible in Acrobat, invisible in a browser', 'XFA form', 'Open in Acrobat, or ask the sender for an AcroForm or flat version'],
            ['Typing replaces text instead of inserting', 'Overtype mode, or a fixed-length field', 'Click into the field, press End, then type'],
            ['Text shrinks as you type', 'Auto-size font on a small field', 'Expected behaviour. Abbreviate, or use a text box beside the field'],
            ['Answers vanish when reopened', 'Viewer saved a copy without form data', 'Use Save As from a real PDF viewer, and flatten'],
            ['Recipient sees an empty form', 'They opened it in a viewer that ignores form values', 'Flatten before sending. This solves it permanently'],
            ['Cannot type at all, but text is selectable', 'Flat PDF made from a text document', 'Use text boxes on top'],
          ],
        },
        { t: 'h2', x: 'Flattening, and why every form needs it' },
        { t: 'p', x: 'Form values live in a separate layer from the page. Until you flatten, they are data attached to fields, which means three things can go wrong: another viewer may not render them, the recipient can edit them, and a printer may print the blank form instead of your answers. Flattening writes the values into the page content and removes the fields, ending all three problems at once.' },
        { t: 'p', x: 'Run the [flatten tool](/tools/flatten-pdf) on the finished file if your form filler does not offer it directly. Keep an unflattened copy for yourself in case you need to revise an answer, because the operation cannot be undone.' },
        { t: 'note', x: 'A flattened form is still not the same as a locked document. Flattening stops casual editing of fields and annotations; it does not prevent someone from editing the page content in a full PDF editor. For genuine tamper evidence you need a certificate-based digital signature — see [are electronic signatures legally binding](/blog/sign-pdf/electronic-signature-legally-binding).' },
        { t: 'h2', x: 'Before you send it back' },
        { t: 'p', x: 'Check the page count, confirm every page that needed initials has them, and open the exported file fresh to see what the recipient will see. If the form was a scan and the recipient may need to search it, [running OCR](/tools/ocr-pdf) first is a courtesy that costs nothing.' },
      ],
      faqs: [
        { q: 'How do I type on a PDF that has no form fields?', a: 'Add free text boxes on top of the page. Zoom to about 150 percent, drop a box over each blank, set it to roughly 10 pt, and align the text baseline to the printed rule. Flatten when you are finished.' },
        { q: 'Why can I not fill in this PDF form in my browser?', a: 'It is most likely an XFA form built in Adobe LiveCycle Designer, which only Adobe Acrobat renders properly. Open it in Acrobat, or ask the sender for a standard AcroForm or a flat version you can type over.' },
        { q: 'Why does the recipient see my form as blank?', a: 'The form values were saved in the field layer and their viewer ignored it. Flatten the document before sending, which merges your answers into the page so every viewer and printer shows them.' },
        { q: 'How do I stop someone editing my answers?', a: 'Flatten the file. That converts field values into page content and removes the fields, so the answers cannot be retyped in any ordinary viewer. It cannot be undone, so keep an unflattened copy.' },
        { q: 'Can I fill in a PDF form on a phone?', a: 'Yes. Interactive forms work in most mobile PDF viewers, and browser-based tools handle both interactive and flat forms. Adding text boxes to a flat scan is fiddly on a small screen but perfectly possible.' },
      ],
      relatedTools: ['sign-pdf', 'flatten-pdf'],
      relatedPosts: ['how-to-sign-a-pdf', 'create-a-signature-image', 'electronic-signature-legally-binding'],
    },
  ],
}
