import type { Cluster } from '../types'

export const slidesPdf: Cluster = {
  slug: 'slides',
  name: 'Slide decks and PDF',
  title: 'Slide decks and PDF, in both directions',
  metaTitle: 'Slides and PDF: Convert, Print and Hand Out',
  metaDescription:
    'Convert PowerPoint to PDF and back, print a deck as handouts several slides per sheet, and design slides that still read once they are on paper in greyscale.',
  intro:
    'A deck and a PDF are two different kinds of object. A .pptx is a set of instructions that PowerPoint reassembles on whatever machine opens it, which is why fonts move and text overflows on somebody else\'s laptop. A PDF is the finished picture, one page per slide, with every glyph and colour already decided. These four guides cover sending a deck as a PDF, rebuilding an editable deck out of a PDF when the original is gone, printing a deck as handouts instead of burning a sheet per slide, and designing slides that still work once the colour has been taken away.',
  answer:
    'Convert a deck to PDF when you are sending it, because fonts and layout stop moving and the reader needs no presentation software. Convert a PDF back to a deck when you need the words editable and the original is lost, accepting that the result is a reconstruction. Print decks as handouts, three or six slides to a sheet.',
  primaryKeyword: 'powerpoint to pdf',
  entities: ['Microsoft PowerPoint', 'PPTX', 'Apple Keynote', 'Google Slides', 'LibreOffice Impress', 'Adobe Acrobat', 'A4', 'Microsoft Print to PDF'],
  icon: '▤',
  tools: ['ppt-to-pdf', 'pdf-to-ppt', 'jpg-to-pdf', 'compress-pdf'],
  posts: [
    {
      slug: 'convert-powerpoint-to-pdf',
      cluster: 'slides',
      title: 'How to convert a PowerPoint deck to PDF',
      metaTitle: 'How to Convert PowerPoint to PDF',
      metaDescription:
        'Send a deck as PDF so the fonts and layout stay put. What survives the conversion, what does not, and how to include speaker notes if you need them.',
      published: '2026-02-19',
      updated: '2026-08-30',
      readMinutes: 6,
      intent: 'howto',
      primaryKeyword: 'convert powerpoint to pdf',
      secondaryKeywords: ['ppt to pdf', 'pptx to pdf converter', 'save powerpoint as pdf', 'convert slides to pdf', 'powerpoint to pdf with notes'],
      entities: ['Microsoft PowerPoint', 'PPTX', 'Apple Keynote', 'Google Slides', 'LibreOffice Impress', 'Microsoft Print to PDF', 'Calibri'],
      answer:
        'Upload the .pptx to a PowerPoint to PDF converter and download the PDF: every slide becomes one page at the deck\'s own aspect ratio. Fonts and layout are fixed in place, so the reader sees what you saw. Animations, transitions and embedded video do not survive, and speaker notes are left out unless you ask for them.',
      body: [
        { t: 'p', x: 'A .pptx file is a package of XML, images and font references that PowerPoint reassembles on the machine that opens it. That reassembly is where decks go wrong. A font you have and the reader does not gets substituted, and every text box using it reflows, so a title that fitted on one line arrives on two and pushes the subtitle off the slide. A PDF is the finished picture instead. Each slide is baked into a page with the glyphs, positions and colours already decided, so there is nothing left to reassemble and nothing left to guess.' },
        { t: 'h2', x: 'What a PDF fixes, and what it costs' },
        {
          t: 'table',
          caption: 'The same 24-slide deck, sent two ways.',
          head: ['', 'Sent as .pptx', 'Sent as PDF'],
          rows: [
            ['Fonts', 'Substituted if the reader does not have them', 'Embedded, identical everywhere'],
            ['Layout', 'Can reflow and overflow its boxes', 'Fixed, the same on every machine'],
            ['Opens in', 'PowerPoint, Keynote, Impress or Slides, each rendering it slightly differently', 'Any browser, phone or reader, nothing to install'],
            ['Animations and transitions', 'Play', 'Gone. Only the final state of each slide remains'],
            ['Embedded video and audio', 'Play', 'A still frame at best'],
            ['Recipient editing it', 'Easy, including by accident', 'Hard, which is usually the point'],
            ['Speaker notes', 'In the notes pane', 'Left out unless you export the notes layout'],
            ['Size of a photo-heavy deck', 'Around 48 MB', 'Around 9 to 15 MB'],
          ],
        },
        { t: 'h2', x: 'Converting the deck' },
        {
          t: 'steps',
          items: [
            { h: 'Finish the deck first', x: 'A conversion is a snapshot. Any edit afterwards means converting again, so leave this until the content is settled and the typos are gone.' },
            { h: 'Upload the file', x: 'Open [PowerPoint to PDF](/tools/ppt-to-pdf) and drop in the .pptx or .ppt. This one is a server tool: the file is uploaded over a secure connection, converted on our server, and deleted the moment it finishes.' },
            { h: 'Wait for the job', x: 'A 30-slide deck takes a few seconds. Files up to 100 MB are accepted and each job gets two minutes, which is ample unless every slide is a full-bleed photograph.' },
            { h: 'Check two slides, not all of them', x: 'Open the PDF and compare the title slide and whichever slide has the most text in the tightest box. Font substitution shows up in those two before anywhere else.' },
            { h: 'Check the page count', x: 'You want one page per slide. If a 24-slide deck produced 26 pages, you had two slides you thought were hidden, or a build that exported as separate states.' },
            { h: 'Send the PDF, keep the .pptx', x: 'The PDF is the copy that goes out. The deck stays with you, because the PDF is not a source file you can edit your way back into easily.' },
          ],
        },
        { t: 'cta', tool: 'ppt-to-pdf', x: 'Turn a .pptx into a PDF that looks the same on every machine.' },
        { t: 'note', x: 'Server conversions are metered. Free accounts get 5 a month, Pro and Lifetime get 300, and API keys get 5,000. Browser tools such as [compress PDF](/tools/compress-pdf) and [images to PDF](/tools/jpg-to-pdf) do not count against any of that, because nothing is uploaded in the first place.' },
        { t: 'h2', x: 'What does not survive the conversion' },
        {
          t: 'ul',
          items: [
            '**Animations and builds.** A slide that reveals four bullets one at a time becomes one page with all four bullets showing. If the build carried the meaning, split it into four slides before you convert.',
            '**Slide transitions.** Wipes, fades and pushes are properties of playback rather than of the slide, so there is nothing on the page to record them.',
            '**Embedded video and audio.** You get the poster frame if the deck had one, a blank rectangle if it did not. Put the video link on the slide as visible text so a reader of the PDF can still find it.',
            '**Trigger and hover actions.** Anything that needed a click in order to happen does not happen.',
            '**Speaker notes**, by default. There is a way round that, below.',
            '**Some hyperlinks.** Most converters keep them. A URL typed as text that PowerPoint auto-linked is more reliable than a link attached to a shape or a picture, so if a link matters, write the address out where the reader can see it.',
          ],
        },
        { t: 'warn', x: 'A slide whose text overflows its box in PowerPoint overflows in the PDF too, except that now you cannot nudge it. Conversion records the layout, it does not repair it. Fix the slide in PowerPoint and convert again.' },
        { t: 'h2', x: 'Speaker notes, and why they are normally left out' },
        { t: 'p', x: 'Notes are not part of the slide. They live on a separate layout called the notes master, which puts a shrunken picture of the slide at the top of a portrait page and the notes text underneath. A straight conversion exports the slide layout only. That is exactly what you want when the deck is going to an audience, and exactly what you do not want when it is going to somebody presenting on your behalf.' },
        { t: 'p', x: 'To get the notes into a PDF, use PowerPoint\'s own print dialogue instead: **File → Print**, click the button reading **Full Page Slides**, choose **Notes Pages**, and set the destination to Microsoft Print to PDF on Windows or Save as PDF on a Mac. You get one portrait page per slide with the notes below it. That is a different document from the deck, so decide which one the recipient actually needs rather than sending both and hoping.' },
        { t: 'tip', x: 'Before a deck leaves your organisation, [strip the metadata](/blog/privacy/remove-metadata-from-pdf). A .pptx carries the author name, the company field and the revision count, and converting to PDF copies all of it straight across into the new file.' },
        { t: 'h2', x: 'Keynote, Google Slides and Impress' },
        {
          t: 'ul',
          items: [
            '**Apple Keynote**: File → Export To → PDF. The image quality selector matters more than it looks. Good re-compresses photographs hard, Best keeps them close to the originals and produces a much larger file.',
            '**Google Slides**: File → Download → PDF Document. Notes are excluded. For a version with notes, go to File → Print preview first and pick a layout that includes them.',
            '**LibreOffice Impress**: File → Export as PDF, which exposes more controls than the others, including whether to export hidden slides and whether to embed the fonts.',
            '**A .key or .odp** that has to become a PDF on a machine without the application that made it: convert it to .pptx in its own application first, then convert that.',
          ],
        },
        { t: 'h2', x: 'Size, and what to do about it' },
        { t: 'p', x: 'A deck built from phone photographs produces a large PDF, because the photographs are large. Twenty-four slides with a full-bleed image on each lands somewhere between 15 and 60 MB, past what most mail servers will accept as an attachment. Run the output through [compress PDF](/tools/compress-pdf), which works entirely inside your browser and uploads nothing. A photo-heavy deck typically comes down by 60 to 80 per cent at a quality nobody notices on a screen. [Reducing a PDF for email](/blog/compress/reduce-pdf-file-size-for-email) has the target numbers for each mail service.' },
        { t: 'p', x: 'If the deck is going to paper rather than to a screen, converting it is only half the job. A PDF prints one slide per sheet by default, which turns 24 slides into 24 sheets of mostly margin. [Printing slide handouts](/blog/slides/print-slide-handouts) covers the settings that put the same deck on four.' },
      ],
      faqs: [
        { q: 'How do I convert a PowerPoint to PDF?', a: 'Upload the .pptx to a converter and download the result, or use File → Export in PowerPoint itself. Either way you get one PDF page per slide with the fonts embedded, so the layout no longer depends on what software the reader has.' },
        { q: 'Do animations work in a PDF?', a: 'No. A PDF page is a static picture, so a four-step build becomes one page with all four steps showing. If each step needs to appear separately, duplicate the slide and remove the animation, so the deck has four real slides that convert to four pages.' },
        { q: 'How do I include speaker notes in the PDF?', a: 'Use File → Print, change Full Page Slides to Notes Pages, and choose the PDF destination. That produces a portrait page per slide with the notes underneath. A normal conversion exports the slide layout only, which never contains the notes.' },
        { q: 'Why do my fonts look different after converting?', a: 'They should not. If they do, the deck used a font the converter could not embed, usually because of the font\'s own licensing restrictions, and a substitute was used. Switch the deck to a widely available font family, or convert on a machine that has the font installed.' },
        { q: 'Is my deck kept on the server after conversion?', a: 'No. The file is uploaded over a secure connection, converted, and deleted the moment the job finishes. Free accounts get 5 server conversions a month, Pro and Lifetime 300, and API keys 5,000, with a 100 MB limit per file.' },
      ],
      relatedTools: ['ppt-to-pdf', 'compress-pdf', 'pdf-to-ppt'],
      relatedPosts: ['print-slide-handouts', 'slides-that-print-well', 'word-to-pdf'],
    },
    {
      slug: 'convert-pdf-to-powerpoint',
      cluster: 'slides',
      title: 'How to convert a PDF back into an editable deck',
      metaTitle: 'How to Convert a PDF to PowerPoint',
      metaDescription:
        'Turn a PDF back into an editable .pptx. What the converter can rebuild, what it cannot, and how to judge in two minutes whether tidying up beats rebuilding.',
      published: '2026-03-12',
      updated: '2026-09-02',
      readMinutes: 7,
      intent: 'howto',
      primaryKeyword: 'convert pdf to powerpoint',
      secondaryKeywords: ['pdf to pptx', 'editable pdf to powerpoint', 'pdf to slides converter', 'recover a lost powerpoint file', 'pdf to ppt online'],
      entities: ['Microsoft PowerPoint', 'PPTX', 'Adobe Acrobat', 'Apple Keynote', 'Google Slides', 'OCR', 'Slide Master'],
      answer:
        'Upload the PDF to a PDF to PowerPoint converter and you get a .pptx with one slide per page, where each block of text has become a real text box positioned where it sat on the page. It is a reconstruction, not a recovery: fonts, grouped graphics and multi-column layouts need tidying. Worth it for text-heavy decks, rarely worth it for design-heavy ones.',
      body: [
        { t: 'p', x: 'A PDF does not contain slides. It contains pages, and a page is a list of drawing instructions: put this glyph at this coordinate in this font at this size, draw this line here, paint this image into that rectangle. Nothing in the file says "this is a title" or "these six lines are one bullet list". A converter reads the coordinates and infers the structure backwards, which is why the honest description of the output is a good first draft rather than your original deck.' },
        { t: 'h2', x: 'What comes back, and in what condition' },
        {
          t: 'table',
          caption: 'Reconstruction quality, element by element.',
          head: ['In the PDF', 'In the converted .pptx', 'Cleanup needed'],
          rows: [
            ['A heading on one line', 'A text box holding that text', 'Rarely, sometimes a nudge'],
            ['A bullet list', 'A text box, often one box per bullet', 'Merge them and re-apply the list style'],
            ['Body text in two columns', 'Two or more boxes, occasionally split mid-sentence', 'Usually, and this is the tedious part'],
            ['A photograph', 'The image, at its embedded resolution and position', 'None'],
            ['A chart built in PowerPoint', 'A picture, or a pile of loose lines and shapes', 'It is no longer a chart. Rebuild it to change the data'],
            ['A logo drawn as vectors', 'Grouped shapes, or one flat image', 'Ungroup and check nothing has shifted'],
            ['A table', 'Text boxes plus separate lines for the rules', 'Yes, rebuild it as a real table'],
            ['A scanned page', 'One image per slide, with no text at all', 'Run OCR on the PDF before converting'],
          ],
        },
        { t: 'h2', x: 'Converting, step by step' },
        {
          t: 'steps',
          items: [
            { h: 'Trim the PDF first', x: 'Do not convert 80 pages to rescue 6. [Extract the pages](/tools/extract-pages) you actually need into a small PDF. It converts faster, it costs one job instead of one huge one, and there is far less to tidy afterwards.' },
            { h: 'Check the PDF has real text', x: 'Try selecting a sentence in any reader. If the cursor will not grab it, the page is a photograph of text and the converter has nothing to rebuild. Run [OCR](/tools/ocr-pdf) over it first, then convert the searchable version.' },
            { h: 'Upload it', x: 'Open [PDF to PowerPoint](/tools/pdf-to-ppt) and drop the file in. This is a server tool: the file is uploaded over a secure connection, converted on our server, and deleted the moment it finishes. Free accounts get 5 server conversions a month, Pro and Lifetime 300, and API keys 5,000, with a 100 MB ceiling per file.' },
            { h: 'Set the slide size before you touch anything', x: 'A PDF page is measured in points and a deck in inches at a fixed ratio, so an A4 page arrives as a portrait slide rather than a 16:9 one. Fix it in **Design → Slide Size** now, because doing it later rescales everything you have just tidied.' },
            { h: 'Judge it in slide sorter view', x: '**View → Slide Sorter**, then thirty seconds of looking. You are counting how many slides need real work, not reading them.' },
            { h: 'Fix the master, not the slides', x: 'If every slide has the same problem, a wrong background or a title in the wrong place, correct it once in **View → Slide Master** rather than forty times by hand.' },
            { h: 'Repair the text', x: 'Merge split bullets, re-apply your own text styles, and delete the empty boxes the converter left behind for page furniture such as running headers and page numbers.' },
          ],
        },
        { t: 'cta', tool: 'pdf-to-ppt', x: 'Rebuild an editable deck from a PDF, one slide per page.' },
        { t: 'h2', x: 'When converting wins, and when rebuilding wins' },
        { t: 'p', x: 'The decision rule is about where the value in the deck actually sits. If the value is in the words, convert, because you are recovering typing and typing is what takes the hours. If the value is in the design, rebuild, because you will spend longer undoing the converter\'s guesses than you would placing the elements yourself in a template you already own.' },
        {
          t: 'ul',
          items: [
            '**Convert** a 40-slide text-heavy training deck whose source left the building with the person who wrote it.',
            '**Convert** someone else\'s slides when you need three of them, want the text selectable, and intend to restyle it anyway.',
            '**Rebuild** a 10-slide pitch deck. Ten slides in your own template takes roughly as long as cleaning up ten converted ones and looks considerably better at the end.',
            '**Rebuild** anything where a chart needs new numbers. A converted chart is a picture, and you cannot change the data behind a picture.',
            '**Neither**, if you only need to show the PDF. Present it full screen, or place one page image per slide, which [turning a PDF into slides](/blog/from-pdf/pdf-to-powerpoint) covers in detail.',
          ],
        },
        { t: 'note', x: 'Ask for the original before you convert anything. Decks are exported to PDF far more often than they are genuinely lost, and the .pptx is usually sitting in a shared drive or an old email thread. Two minutes of asking beats an hour of tidying, and people forget to try.' },
        { t: 'h2', x: 'Fonts, the part that surprises everyone' },
        { t: 'p', x: 'The PDF carries its fonts inside it, often as a subset containing only the glyphs the document actually used. A .pptx does not embed fonts by default, it names them. So the converted deck asks your copy of PowerPoint for a typeface you may not have, PowerPoint substitutes the nearest thing it can find, line lengths change, and boxes that fitted stop fitting. Nothing has gone wrong; the file format simply stores fonts a different way.' },
        { t: 'p', x: 'The fix is not to hunt down the exact font. Choose the closest one you do have, apply it through the slide master so it lands everywhere at once, then check the three slides with the tightest text. Chasing an exact match is usually a licensing problem you cannot solve, in service of a difference the audience will not see.' },
        { t: 'warn', x: 'A converted deck inherits the source document\'s metadata, including the original author\'s name and their organisation. Check **File → Info** before you present it as your own work, and clear anything that should not travel with it.' },
        { t: 'h2', x: 'What no converter can invent' },
        {
          t: 'ul',
          items: [
            '**Animations and transitions.** They were never written into the PDF, so there is nothing to bring back.',
            '**Speaker notes.** Unless the PDF was exported as notes pages, in which case the notes arrive as ordinary body text sitting on the slide, which is worse than useless and needs cutting out.',
            '**Chart data.** The numbers were turned into shapes at export time and the shapes do not remember them.',
            '**Layer and grouping structure.** What was a neat group of eight shapes in the original is eight loose shapes now, in roughly the right places.',
            '**Anything that was hidden.** Hidden slides were not exported to the PDF, so they do not come back either.',
          ],
        },
        { t: 'h2', x: 'A sensible finishing pass' },
        { t: 'p', x: 'Work in this order and you will not redo anything: slide size, then slide master, then per-slide text, then graphics, then a read-through. Text first and graphics second matters, because fixing a text box often moves the picture beside it, whereas moving a picture rarely disturbs the text.' },
        { t: 'p', x: 'Then make the call honestly. If more than roughly a third of the slides still need real work after ten minutes, start again in your own template with the converted deck open alongside as a source of text to copy. That is still much faster than retyping, which was the entire point of converting.' },
      ],
      faqs: [
        { q: 'Can I convert a PDF into an editable PowerPoint?', a: 'Yes, with a server-side converter. Text becomes real text boxes positioned where the words sat on the page, and images come across as images. It is a reconstruction, so multi-column layouts, tables and charts need tidying before the deck is presentable.' },
        { q: 'Why is my converted chart not editable?', a: 'Because it is not a chart any more. When the original deck was exported to PDF, the chart was rendered into lines, shapes and text at fixed positions, and the underlying numbers were left behind. To change the data you have to rebuild the chart from the values.' },
        { q: 'Does the converted deck keep the original fonts?', a: 'It keeps the font names, not the fonts. PDFs embed typefaces, .pptx files reference them, so PowerPoint substitutes anything you do not have installed. Apply a font you do have through the slide master, then check the slides with the tightest text boxes.' },
        { q: 'Can I convert a scanned PDF to PowerPoint?', a: 'Not usefully, not as it stands. A scan is a photograph of a page, so the converter finds no text and gives you one picture per slide. Run OCR over the PDF first to add a real text layer, then convert the searchable copy.' },
        { q: 'How many conversions can I run?', a: 'Free accounts get 5 server conversions a month, Pro and Lifetime 300, and API keys 5,000. Files up to 100 MB are accepted and each job runs for up to two minutes. Browser tools such as compressing a PDF do not use any of that allowance.' },
      ],
      relatedTools: ['pdf-to-ppt', 'extract-pages', 'ocr-pdf'],
      relatedPosts: ['convert-powerpoint-to-pdf', 'pdf-to-powerpoint', 'pdf-to-word'],
    },
    {
      slug: 'print-slide-handouts',
      cluster: 'slides',
      title: 'How to print slide handouts without wasting a stack of paper',
      metaTitle: 'How to Print Slide Handouts (Multiple per Page)',
      metaDescription:
        'Print a deck as handouts with three or six slides per sheet instead of one. The layout options compared, plus the notes lines version students actually use.',
      published: '2026-04-08',
      updated: '2026-08-19',
      readMinutes: 7,
      intent: 'howto',
      primaryKeyword: 'print slide handouts',
      secondaryKeywords: ['print multiple slides on one page', 'powerpoint handouts 6 slides per page', 'print powerpoint with notes lines', 'print pdf slides per sheet', 'save paper printing slides'],
      entities: ['Microsoft PowerPoint', 'A4', 'Adobe Acrobat Reader', 'Google Chrome', 'macOS', 'Microsoft Windows', 'Handout Master'],
      answer:
        'Print handouts from the PowerPoint print dialogue, not the slide layout menu: set Full Page Slides to Handouts and choose 3 or 6 slides per page. Three per page puts notes lines beside each slide; six fits a 24-slide deck on four sheets instead of twenty-four. Convert to PDF first if the printing is happening on a machine that is not yours.',
      body: [
        { t: 'p', x: 'One slide per sheet is the default, and it is the wrong default for nearly every reason anyone prints a deck. A 16:9 slide on A4 portrait occupies about half the page and the rest is margin. Print 24 slides that way and you have spent 24 sheets delivering roughly 12 sheets of content, most of it title text set at 40 point that nobody needed to read that large on paper.' },
        { t: 'h2', x: 'The handout layouts, and what each one is for' },
        {
          t: 'table',
          caption: 'A 24-slide deck printed on A4, by layout.',
          head: ['Layout', 'Sheets', 'Slide width on the page', 'Use it for'],
          rows: [
            ['1 per page', '24', 'About 19 cm', 'A single slide with a dense diagram or a table people must actually read'],
            ['2 per page', '12', 'About 17 cm', 'Design reviews and anything built out of screenshots'],
            ['3 per page', '8', 'About 11 cm, with ruled notes lines beside it', 'Training and lectures. The most useful layout by a distance'],
            ['4 per page', '6', 'About 9 cm, two across and two down', 'Reference copies and anything going on a wall'],
            ['6 per page', '4', 'About 9 cm, two across and three down', 'A deck you are skimming, circulating or filing'],
            ['9 per page', '3', 'About 6 cm, three across', 'A contact sheet. Titles just about survive, body text does not'],
            ['Notes pages', '24', 'Half the page, notes underneath', 'The presenter\'s own copy, or a stand-in\'s'],
          ],
        },
        { t: 'tip', x: 'Four per page and six per page give the same slide width on A4, because both put two slides across the sheet. Six only uses the vertical space you were leaving blank anyway. If you were about to choose four, choose six and save two sheets in every six for no loss of legibility at all.' },
        { t: 'h2', x: 'Printing handouts, step by step' },
        {
          t: 'steps',
          items: [
            { h: 'Open the print dialogue, not the View menu', x: 'In PowerPoint: **File → Print**. The layout setting lives here, behind the button reading **Full Page Slides**. The Handout Master under the View menu only controls headers, footers and the date, it does not choose the layout.' },
            { h: 'Pick the layout', x: 'Click **Full Page Slides** and choose from the Handouts column: 1, 2, 3, 4, 6 or 9 slides per page. The preview updates immediately, so you can see how small the text becomes before you commit any paper to it.' },
            { h: 'Set the colour mode', x: 'Same dialogue, the **Color** button at the bottom. **Pure Black and White** drops fills to white and keeps text black, which saves a startling amount of toner on a dark-themed deck. **Grayscale** keeps the tones. Compare both in the preview.' },
            { h: 'Turn on double-sided', x: 'Print on Both Sides, flipping on the long edge for portrait handouts. Six per page plus duplex takes a 24-slide deck down to two sheets of paper.' },
            { h: 'Save it as a PDF instead of printing', x: 'Choose the PDF destination in the same dialogue. The handout layout is now baked into a file you can email, and the recipient cannot accidentally print it one slide per sheet.' },
            { h: 'Read the page count before you press print', x: 'The dialogue tells you. If it still says 24 after you chose six per page, the layout did not apply, which almost always means it was set in the Handout Master rather than here.' },
          ],
        },
        { t: 'cta', tool: 'ppt-to-pdf', x: 'Convert the deck to PDF first so the handout leaves as a fixed file.' },
        { t: 'note', x: 'Converting a deck is a server job: the file is uploaded over a secure connection, converted on our server, and deleted the moment it finishes. Free accounts get 5 of those a month, Pro and Lifetime 300, and API keys 5,000. Compressing the resulting PDF runs inside your browser and uploads nothing, so it never touches that allowance.' },
        { t: 'h2', x: 'Handouts when all you have is a PDF' },
        { t: 'p', x: 'If the deck reached you as a PDF, you do not get PowerPoint\'s handout menu, but you get the same result from the operating system\'s print dialogue. A converted deck is one slide per page, so several pages per sheet is exactly several slides per sheet.' },
        {
          t: 'ul',
          items: [
            '**Windows**, in Adobe Acrobat Reader or Edge: **Print → Multiple → Pages per sheet**, then choose 2, 4, 6, 9 or 16 and a page order.',
            '**macOS**, in any application: **File → Print**, expand the dialogue, choose **Layout** from the pop-up menu and set **Pages per Sheet**. Add a border if the slides have white backgrounds, otherwise they run into each other on the sheet.',
            '**Google Chrome**, printing a PDF: **Print → More settings → Pages per sheet**, offering 1, 2, 4, 6, 9 and 16.',
            '**A folder of slide images** rather than a PDF: build one with [images to PDF](/tools/jpg-to-pdf), which runs in your browser and uploads nothing, then print that several to a sheet.',
          ],
        },
        { t: 'p', x: 'The rest of the settings that matter here, margins, scaling and page order, are in [fitting more on a page](/blog/save-ink/fit-more-on-a-page).' },
        { t: 'warn', x: 'Pages per sheet shrinks the whole page, including the white margin around each slide, so you lose more than the arithmetic suggests. Nine to a sheet on A4 leaves each slide about 6 cm wide with its own margin inside that, which is how 18 point body text ends up nearer 4 point on paper. Read the preview, not the page count.' },
        { t: 'h2', x: 'The printed deck is not the presented deck' },
        { t: 'p', x: 'A handout is a different document with a different job, and the cheapest improvement you can make to one is deciding what to leave out of it. Before you print:' },
        {
          t: 'ul',
          items: [
            'Cut the slides that existed only for the room: the agenda you talked through, the section dividers, the thank-you slide, the build you already flattened.',
            'Use **Slide Show → Hide Slide** rather than deleting. Hidden slides stay out of the handout as well as out of the presentation, and you still have them.',
            'If the deck ends with 12 appendix slides nobody will discuss, type `1-18` in the range box instead of printing all 30.',
            'Add handout page numbers through **Insert → Header & Footer → Notes and Handouts**. That is a separate tab from slide numbering, and it numbers the sheet, which is what people call out in a room.',
            'Three per page with notes lines beats six per page whenever the audience is expected to write. Nobody annotates a 9 cm slide.',
          ],
        },
        { t: 'h2', x: 'Emailing the handout instead of printing it' },
        { t: 'p', x: 'A handout PDF built from a photo-heavy deck is still carrying full-resolution photographs, six to a page, and reaches 30 MB without trying. Run it through [compress PDF](/tools/compress-pdf), which works entirely inside your browser. At 150 DPI the images are still far finer than a 9 cm printed slide can show, and the file typically drops by two thirds.' },
        { t: 'cta', tool: 'compress-pdf', x: 'Shrink the handout PDF before you send it to thirty people.' },
        { t: 'p', x: 'One last check before a print run of any size: whether the deck itself survives paper at all. Dark backgrounds, hairline fonts and colour-coded charts are all fine on a projector and all fail in greyscale at 9 cm wide. [Designing a deck that prints well](/blog/slides/slides-that-print-well) covers what to change, and ten minutes there is worth more than any print setting.' },
      ],
      faqs: [
        { q: 'How do I print multiple slides on one page?', a: 'In PowerPoint, go to File → Print, click the button reading Full Page Slides, and choose a handout layout of 1, 2, 3, 4, 6 or 9 slides per page. The preview on the right shows exactly how small the text becomes before you print anything.' },
        { q: 'What is the best handout layout for a lecture?', a: 'Three per page. It is the only layout with ruled notes lines beside each slide, the slide is still about 11 cm wide, and a 24-slide deck fits on eight sheets. Six per page is better only when nobody is expected to write on it.' },
        { q: 'How do I print PDF slides several to a sheet?', a: 'Use the print dialogue rather than the PDF itself. On Windows choose Multiple, then Pages per sheet. On macOS expand the print dialogue and pick Layout, then Pages per Sheet. In Chrome it is under More settings, Pages per sheet.' },
        { q: 'Do handouts include the speaker notes?', a: 'No. Handout layouts show slides only, and the three-per-page layout gives blank lines rather than your notes. For the notes themselves choose Notes Pages in the same menu, which prints one portrait page per slide with the notes underneath.' },
        { q: 'How do I stop handouts using so much colour?', a: 'In the print dialogue, set Color to Grayscale or to Pure Black and White. Pure Black and White drops background fills to white entirely, which matters most on a dark-themed deck where each sheet would otherwise be almost solid toner.' },
      ],
      relatedTools: ['ppt-to-pdf', 'compress-pdf', 'jpg-to-pdf'],
      relatedPosts: ['slides-that-print-well', 'convert-powerpoint-to-pdf', 'fit-more-on-a-page', 'print-lecture-slides'],
    },
    {
      slug: 'slides-that-print-well',
      cluster: 'slides',
      title: 'How to design a deck that still works on paper',
      metaTitle: 'Designing Slides That Print Well in Greyscale',
      metaDescription:
        'Dark backgrounds drain toner, thin fonts break up, and colour-coded charts become identical greys. What to change in a deck before it goes to a printer.',
      published: '2026-05-21',
      updated: '2026-08-25',
      readMinutes: 7,
      intent: 'informational',
      primaryKeyword: 'slides that print well',
      secondaryKeywords: ['slide design for printing', 'presentation greyscale printing', 'dark background slides printing', 'font size for printed slides', 'accessible chart colours'],
      entities: ['Microsoft PowerPoint', 'A4', 'Apple Keynote', 'Google Slides', 'Toner', 'ISO 19752', 'Grayscale view'],
      answer:
        'Design for the worst case: greyscale, on paper, at a quarter of the size. That means light backgrounds, text no smaller than 18 point, fonts with real stroke weight, and charts that separate by pattern or label rather than by colour alone. Check it by printing one slide in black and white before you commit the deck.',
      body: [
        { t: 'p', x: 'A projector emits light. Paper reflects it. That one difference explains nearly every way a deck fails when it is printed. White on a screen is the brightest thing in the room, whereas white on paper is only the paper, and the darkest thing an office laser can produce is closer to a very dark grey than to black. The usable contrast range collapses from something like 1000 to 1 down to about 30 to 1, and everything you designed near the edges of that range collapses with it.' },
        { t: 'h2', x: 'The things that break, and what to do instead' },
        {
          t: 'table',
          caption: 'What happens to a slide on the way to a printed handout.',
          head: ['On the projector', 'On paper, in greyscale', 'What to do instead'],
          rows: [
            ['White text on a dark navy background', 'A solid grey block that drains the cartridge and smudges when handled', 'Dark text on white, or a light variant of the theme for the printed copy'],
            ['A hairline display font at 100 weight', 'Strokes thin out and break up at small sizes', 'Regular or medium weight, nothing lighter'],
            ['Five series in five brand colours', 'Five greys, three of them indistinguishable', 'Label each series on the chart itself, or vary the line style'],
            ['A pale grey caption at 12 point', 'Effectively invisible six slides to a sheet', '14 point minimum, in a grey no lighter than about 40 per cent'],
            ['A full-bleed photo with text over it', 'A grey photo with grey text on top', 'Put the text on a solid panel rather than directly on the image'],
            ['Red for "at risk", green for "done"', 'Two nearly identical mid-greys', 'Add a word or a symbol. Anything that is not only colour'],
          ],
        },
        { t: 'h2', x: 'Backgrounds, and the toner arithmetic' },
        { t: 'p', x: 'A dark theme is the most expensive single design decision you can make about a deck that will be printed. A full-page dark background on A4 covers roughly 600 square centimetres in toner. Cartridge yields are quoted against a standard 5 per cent page coverage, and a dark slide runs at 80 or 90 per cent. That is not a modest overrun. You will get a small fraction of the rated page count, and the printer will run slower while doing it, because it has to fuse far more toner into every sheet.' },
        { t: 'p', x: 'You do not have to redesign anything. Duplicate the deck, apply a light background once in **View → Slide Master** so it changes on every slide at the same time, and print the duplicate. It takes about a minute, and the printed copy wanted it anyway. If even that is too much, the print dialogue\'s **Pure Black and White** setting drops fills to white and keeps text black, which gets most of the way for free. [Saving ink when printing](/blog/save-ink/save-ink-when-printing) goes further into where the toner actually goes.' },
        { t: 'h2', x: 'Type that survives being shrunk' },
        { t: 'p', x: 'Handouts are usually printed three or six to a sheet, so the slide lands on paper at roughly a third or a quarter of the size you designed it at. An 18 point body line printed six to a sheet is about 5 point on the page, right at the bottom of what most people read comfortably and below what anyone reads in a dim room. The rule is not a font size, it is a ratio: whatever you set, divide it by the number of slides across the sheet and ask whether you would read the result.' },
        {
          t: 'ul',
          items: [
            '**18 point is the floor** for anything you expect to be read, and 24 point is the safe answer.',
            '**Avoid hairline and ultra-light weights.** They are designed to look luminous on a backlit screen. On paper they thin out, and on a worn drum they break into dashes.',
            '**Avoid grey body text.** Light grey on white loses more contrast in printing than anything else on the slide. Set body text to black and build hierarchy with size and weight instead.',
            '**Be careful with condensed fonts.** They shrink better than you expect on width and worse than you expect on legibility, because the counters, the enclosed spaces inside letters such as e and a, fill in with toner.',
            '**Never let colour carry emphasis on its own.** Bold survives greyscale, a brand blue does not.',
          ],
        },
        { t: 'h2', x: 'Charts, the worst offender by far' },
        { t: 'p', x: 'A five-series line chart separated only by colour is the single most common thing in a deck that becomes literally unreadable on paper. Standard chart palettes are chosen for hue separation rather than lightness separation, so a medium blue, a medium green and a medium red convert to greys within a few per cent of one another. The reader can see that there are five lines. They cannot tell which is which, and the legend is no help because the legend is colour too.' },
        {
          t: 'ul',
          items: [
            'Label the lines directly, at the right-hand end of each line, instead of using a legend. This is better on a projector as well, because it removes a lookup from the audience\'s job.',
            'Vary the line style: solid, dashed, dotted. Three styles at two weights gives six distinguishable series using no colour at all.',
            'For bar charts, vary the fill pattern, or outline some bars instead of filling them.',
            'For maps and heat scales, use one hue at different lightnesses. A single-hue scale converts to greyscale correctly by definition, because lightness was already doing the work.',
            'Anyone with red-green colour blindness, roughly one man in twelve, is reading your projected chart the same way the printer is reading it. Fixing this for print fixes it for them.',
          ],
        },
        { t: 'tip', x: 'PowerPoint has a preview built for exactly this. **View → Grayscale**, or **Black and White**, redraws the whole deck as it will print, and the ribbon then offers per-object overrides: right-click any picture and choose a setting such as Light Grayscale or White. It is the fastest audit of a deck you can run, and almost nobody knows it is there.' },
        { t: 'h2', x: 'The things that vanish entirely' },
        {
          t: 'ul',
          items: [
            '**Animated builds.** All four bullets appear at once. If the build was holding back an answer, the handout gives it away on the way in.',
            '**Video.** A poster frame at best. Write the link on the slide as visible text.',
            '**Hyperlink colour.** A blue underlined phrase prints as a grey underlined phrase. If the address matters, spell it out.',
            '**Objects parked off the slide.** They do not print, which is convenient, though they are still inside the file and still inside the PDF you send.',
            '**Slide numbers**, half the time. Slide numbers live on the slide layout and handout layouts number the sheet instead, so switch both on if anyone will be calling out a number.',
          ],
        },
        { t: 'h2', x: 'A five-minute check before you print thirty copies' },
        {
          t: 'ol',
          items: [
            'Switch to **View → Grayscale** and page through the deck once, full screen, without reading it. You are looking for slides that turn into grey soup.',
            'Take the busiest slide and the darkest slide and print those two. On the actual printer, not in the preview: cheap lasers are darker and coarser than any preview suggests.',
            'Hold the sheet at arm\'s length. If you cannot read the body text there, nobody in the third row can read it on the screen either.',
            'Convert the finished deck with [PowerPoint to PDF](/tools/ppt-to-pdf) so the file that reaches the printer is the one you checked, whatever machine it is printed from.',
            'Print one sheet of the handout layout you actually intend to use, at the number of slides per sheet you actually intend to use, and read that before committing the run.',
          ],
        },
        { t: 'note', x: 'Converting is a server job: the deck is uploaded over a secure connection, converted on our server, and deleted as soon as it finishes. Free accounts get 5 server conversions a month, Pro and Lifetime 300, and API keys 5,000, with a 100 MB limit per file and two minutes per job.' },
        { t: 'cta', tool: 'ppt-to-pdf', x: 'Lock the deck into a PDF so the printed copy matches what you checked.' },
        { t: 'p', x: 'None of this produces a duller deck. A slide that reads on paper also reads at the back of a long room, in a room with the blinds open, and on a phone, which is where a great many decks are actually read. Design for the worst case and the best case comes free. When the deck is ready, [print it as handouts](/blog/slides/print-slide-handouts) rather than one slide to a sheet.' },
      ],
      faqs: [
        { q: 'What font size should slides be if they will be printed?', a: 'Treat 18 point as the floor and 24 point as the safe answer. Handouts are usually printed three or six to a sheet, which shrinks the slide to a third or a quarter of its design size, so 18 point body text arrives on paper at around 5 point.' },
        { q: 'Why do my charts look wrong printed in black and white?', a: 'Chart palettes are built for hue separation, not lightness separation, so a medium blue, green and red convert to almost the same grey. Label series directly on the chart, or vary line style and fill pattern, so the difference does not depend on colour.' },
        { q: 'Should I avoid dark backgrounds on slides?', a: 'If the deck will be printed, yes. A dark A4 page runs at 80 to 90 per cent toner coverage against the 5 per cent that cartridge yields assume, so you get a fraction of the rated pages. Duplicate the deck and apply a light master for the printed copy.' },
        { q: 'How can I preview how a deck will print?', a: 'Use View → Grayscale, or Black and White, in PowerPoint. It redraws every slide as the printer will render it and lets you override individual pictures. Then print the two worst slides on the real printer, because cheap lasers are coarser than any preview.' },
        { q: 'Is it better to print the deck or the PDF?', a: 'Print the PDF. Converting first fixes the fonts and layout into the file, so the output does not depend on what software or typefaces the printing machine happens to have, which matters most when someone else is doing the printing.' },
      ],
      relatedTools: ['ppt-to-pdf', 'compress-pdf'],
      relatedPosts: ['print-slide-handouts', 'convert-powerpoint-to-pdf', 'save-ink-when-printing', 'best-image-format-for-print'],
    },
  ],
}
