import type { Cluster } from '../types'

export const watermarkPdf: Cluster = {
  slug: 'watermark-page-numbers',
  name: 'Watermarks, page numbers and stamps',
  title: 'How to watermark, number and stamp a PDF properly',
  metaTitle: 'Add Watermarks & Page Numbers to a PDF',
  metaDescription:
    'Add a watermark, page numbers, headers or footers to a PDF free in your browser. Opacity, rotation, placement and margin settings that actually look right.',
  intro:
    'A mark on a page does one of three jobs: it warns a reader (DRAFT, CONFIDENTIAL), it helps a reader navigate (page numbers, headers, file references), or it records an action (received, approved, signed). These guides cover all three, with the exact opacity, rotation and margin numbers that make a mark readable without burying the text underneath. They also cover the thing most guides skip: what a watermark does not protect you from.',
  answer:
    'To mark a PDF, add a watermark for a visual warning, page numbers for navigation, and a header or footer for identifying details such as a company name or file reference. All three are drawn onto the existing pages, so they change how the file looks without changing the underlying text.',
  primaryKeyword: 'add watermark to pdf',
  entities: ['PDF', 'Adobe Acrobat', 'Helvetica', 'DRAFT', 'CONFIDENTIAL', 'Bates numbering', 'ISO 32000', 'Microsoft Word'],
  icon: '🖋',
  tools: ['add-watermark', 'page-numbers', 'flatten-pdf', 'edit-metadata'],
  posts: [
    {
      slug: 'add-watermark-to-pdf',
      cluster: 'watermark-page-numbers',
      title: 'How to add a watermark to a PDF',
      metaTitle: 'How to Add a Watermark to a PDF (Free)',
      metaDescription:
        'Add a DRAFT or CONFIDENTIAL watermark to any PDF in your browser. The right opacity, rotation and placement, plus why a watermark is not real security.',
      published: '2026-01-27',
      updated: '2026-08-14',
      readMinutes: 6,
      intent: 'howto',
      primaryKeyword: 'how to add a watermark to a pdf',
      secondaryKeywords: ['add draft watermark to pdf', 'confidential watermark pdf', 'pdf watermark free', 'watermark pdf online', 'tiled watermark pdf'],
      entities: ['PDF', 'Adobe Acrobat', 'DRAFT', 'CONFIDENTIAL', 'Helvetica', 'opacity', 'content stream', 'LibreOffice'],
      answer:
        'To add a watermark to a PDF, open the file in a watermark tool, type the text you want such as DRAFT or CONFIDENTIAL, set opacity to around 15 percent and rotation to 45 degrees, choose centred or tiled placement, then apply it to every page and save the result.',
      body: [
        { t: 'p', x: 'A watermark is a piece of text or an image drawn across every page of a document, behind or in front of the content, usually pale and usually diagonal. Its job is to change how a reader treats the page: this is a draft, do not quote it; this is confidential, do not forward it; this is a sample, do not use it in production.' },
        { t: 'p', x: 'Adding one takes about thirty seconds. Getting one that reads clearly without making the text underneath unreadable takes knowing four numbers: opacity, rotation, size and placement.' },
        { t: 'h2', x: 'Add a watermark in your browser' },
        {
          t: 'steps',
          items: [
            { h: 'Open the tool', x: 'Go to [Add watermark](/tools/add-watermark) and drop your PDF onto the page. The file is processed in the browser tab, so nothing is uploaded.' },
            { h: 'Type the watermark text', x: 'Keep it to one or two words. **DRAFT**, **CONFIDENTIAL**, **SAMPLE**, **COPY** and **NOT FOR DISTRIBUTION** are the standard ones. Longer strings have to be set smaller, which defeats the purpose.' },
            { h: 'Set opacity to 10-20 percent', x: 'Below 10 percent the mark disappears on a laser printer. Above 30 percent it competes with the body text. Fifteen percent is the safe default for grey; use 12 percent for red, which reads darker.' },
            { h: 'Set rotation to 45 degrees', x: 'A diagonal mark crosses the text at an angle, so no single line of body text is obscured for its whole length. Zero degrees looks tidier on screen but hides more words.' },
            { h: 'Choose centred or tiled', x: 'One large centred mark for a warning. A tiled grid of small marks when you want the mark to survive someone cropping or screenshotting part of the page.' },
            { h: 'Apply to the right pages', x: 'All pages is the default. If you are marking a covering page only, enter a page range such as `1` before you apply.' },
            { h: 'Save the file', x: 'Download the marked copy. Keep the original unmarked file — removing a watermark cleanly afterwards is harder than making a fresh copy.' },
          ],
        },
        { t: 'cta', tool: 'add-watermark', x: 'Add a text watermark to every page of a PDF, free and in your browser.' },
        { t: 'h2', x: 'The settings that matter' },
        {
          t: 'table',
          caption: 'Watermark settings and the values that work in practice.',
          head: ['Setting', 'Recommended', 'Why'],
          rows: [
            ['Opacity', '10-20% (15% default)', 'Visible on paper, still lets 11pt body text read cleanly through it.'],
            ['Rotation', '45° (or -45°)', 'Crosses lines of text at an angle instead of running along one line and burying it.'],
            ['Font size', '60-90pt centred, 18-28pt tiled', 'A centred mark should span roughly two-thirds of the page width.'],
            ['Colour', 'Mid grey #808080, or red #C00000 for CONFIDENTIAL', 'Grey stays neutral in greyscale printing. Red signals urgency but prints as dark grey.'],
            ['Opacity', 'Around 0.25', 'The mark is drawn over the page, so low opacity is what keeps body text readable. Raise it only when the mark must be impossible to miss.'],
            ['Placement', 'Centred for warnings, tiled for reuse control', 'Tiling survives cropping; a single centred mark does not.'],
          ],
        },
        { t: 'h3', x: 'Tiled or centred?' },
        { t: 'p', x: 'A centred watermark is a message to a cooperative reader. A tiled watermark is a deterrent against reuse: if someone crops a figure out of your report, the crop still carries part of a mark. Tiling costs readability, so use 8-12 percent opacity when you tile, and keep the tile text short — a name or a domain rather than a sentence.' },
        { t: 'h2', x: 'Text watermark or image watermark?' },
        {
          t: 'ul',
          items: [
            '**Text** stays crisp at any zoom, adds a couple of kilobytes, and can be searched for later. Best for status words.',
            '**Image** is right for a logo or a signature block. Export a PNG with a transparent background at roughly 1000px wide, then let the tool scale it down; a small image scaled up looks blurred on paper.',
            '**Both** is common on client deliverables: a pale logo tiled behind the content, plus one large DRAFT across the middle.',
          ],
        },
        { t: 'note', x: 'A text watermark is added to the page content, which means text extraction tools will report the watermark word alongside your real text. If you are running OCR or feeding the file to a search index later, expect DRAFT to appear on every page of the extracted text.' },
        { t: 'h2', x: 'A watermark is not security' },
        { t: 'warn', x: 'A watermark is a label, not a lock. It does not stop anyone reading, copying, printing or forwarding the file. Anyone with a PDF editor can select the watermark object and delete it in a few clicks, because it is just another drawing instruction on the page.' },
        { t: 'p', x: 'This matters because people substitute a watermark for a control it cannot provide. If the requirement is genuinely "this person must not read this", a watermark is the wrong tool. Work through what you actually need:' },
        {
          t: 'table',
          head: ['What you need', 'What actually does it'],
          rows: [
            ['Warn a reader that a document is provisional', 'A watermark — this is exactly its job'],
            ['Discourage casual reuse of your images or copy', 'A tiled watermark, plus a visible copyright line'],
            ['Stop someone opening the file at all', 'Encryption with an open password — see [password protecting a PDF](/blog/pdf-privacy/password-protect-pdf)'],
            ['Remove sensitive words from the file entirely', 'Real redaction — see [redacting a PDF properly](/blog/pdf-privacy/redact-pdf-properly)'],
            ['Prove a document is genuine and unaltered', 'A digital signature'],
          ],
        },
        { t: 'p', x: 'You can make a watermark harder to remove by [flattening the file](/tools/flatten-pdf) afterwards, which merges layers and form fields into the page content. That defeats a casual "click and delete" attempt. It does not defeat anyone determined, and it also makes your own text non-editable, so only flatten the copy you are sending out.' },
        { t: 'tip', x: 'For per-recipient tracking, put the recipient name in the tiled watermark itself — a faint repeated "Issued to A. Khan, 14 March 2026" across the page. If a copy leaks, the mark tells you which copy it was. This is the one case where a watermark genuinely changes behaviour.' },
        { t: 'h2', x: 'What to write on the mark' },
        {
          t: 'ul',
          items: [
            '**DRAFT** — content may still change. Pair it with a version number in the [footer](/blog/watermark-page-numbers/add-header-footer-pdf).',
            '**CONFIDENTIAL** — internal or contractual restriction on sharing.',
            '**FOR REVIEW ONLY** — clearer than DRAFT when you want comments back by a date.',
            '**SAMPLE** or **SPECIMEN** — for template documents that must never be mistaken for a real certificate or invoice.',
            '**SUPERSEDED** — for archived versions, so an old copy in someone\'s downloads folder does not get used.',
          ],
        },
        { t: 'p', x: 'Once the mark is on, most documents also want [page numbers](/blog/watermark-page-numbers/add-page-numbers-to-pdf) so a reader can refer to "the table on page 7" without counting sheets.' },
      ],
      faqs: [
        { q: 'How do I add a DRAFT watermark to a PDF for free?', a: 'Open the file in a browser-based watermark tool, type DRAFT, set opacity to about 15 percent and rotation to 45 degrees, and apply it to all pages. No account or installation is needed, and the file never leaves your computer.' },
        { q: 'Can I remove a watermark from a PDF?', a: 'Often yes. A watermark added as a separate object can be selected and deleted in a PDF editor. If the page has been flattened or converted to an image, removing the mark cleanly is much harder and usually damages the text underneath.' },
        { q: 'Does a watermark stop people copying my PDF?', a: 'No. A watermark is a visual label with no enforcement behind it. It does not block copying, printing, forwarding or text selection. Use encryption for access control and real redaction for removing sensitive content.' },
        { q: 'What opacity should a PDF watermark be?', a: 'Between 10 and 20 percent for grey text, with 15 percent as a good default. Red or dark colours read heavier, so drop them to around 12 percent. Anything above 30 percent makes body text noticeably harder to read on paper.' },
        { q: 'Can I watermark only some pages of a PDF?', a: 'Yes. Most tools accept a page range, so you can mark pages 2 to 10 and leave a cover page clean, or mark an appendix only. Enter the range before applying, since the operation is applied in one pass.' },
      ],
      relatedTools: ['add-watermark', 'flatten-pdf'],
      relatedPosts: ['add-page-numbers-to-pdf', 'watermark-vs-stamp', 'redact-pdf-properly'],
    },
    {
      slug: 'add-page-numbers-to-pdf',
      cluster: 'watermark-page-numbers',
      title: 'How to add page numbers to a PDF',
      metaTitle: 'How to Add Page Numbers to a PDF',
      metaDescription:
        'Add page numbers to a PDF in your browser: pick a position and margin, use a "1 of 12" format, set a starting number, and skip a cover page cleanly.',
      published: '2026-02-18',
      updated: '2026-07-30',
      readMinutes: 6,
      intent: 'howto',
      primaryKeyword: 'how to add page numbers to a pdf',
      secondaryKeywords: ['add page numbers to pdf free', 'pdf page numbering', 'page x of y pdf', 'bates numbering pdf', 'start numbering on page 2'],
      entities: ['PDF', 'Adobe Acrobat', 'Bates numbering', 'Helvetica', 'A4', 'US Letter', 'Microsoft Word', 'roman numerals'],
      answer:
        'To add page numbers to a PDF, open it in a page numbering tool, pick a position such as bottom centre, choose a format such as "1 of 12", set the starting number, and say how many opening pages to leave unnumbered. The numbers are drawn onto each page and cannot shift later.',
      body: [
        { t: 'p', x: 'Page numbers in a PDF are not automatic. Unless the original document had them before it was exported, the file is just a stack of pages with no idea what order a human thinks they are in. Add them and three things get easier: printing double-sided without losing your place, referring to a page in an email, and putting a dropped stack back together.' },
        { t: 'h2', x: 'Add numbers in your browser' },
        {
          t: 'steps',
          items: [
            { h: 'Open the numbering tool', x: 'Go to [Page numbers](/tools/page-numbers) and drop the PDF in. Everything runs locally in the tab.' },
            { h: 'Pick a position', x: 'Bottom centre is the safe default. Bottom outer corner is the right choice for anything printed double-sided and bound.' },
            { h: 'Choose a format', x: 'Plain `7`, `Page 7`, or `7 of 24`. The last one tells a reader immediately whether the document is complete.' },
            { h: 'Skip the cover', x: 'If page 1 is a title page, set **Leave first N pages unnumbered** to 1. The cover stays clean and the next sheet becomes number 1.' },
            { h: 'Set the starting number', x: 'Separate from the above. If this PDF is chapter two of a longer document that ended on page 40, start at 41 so the combined set reads continuously.' },
            { h: 'Check the margin', x: 'The number should sit inside the paper margin, not on top of your text. Around 36 points, which is half an inch, from the bottom edge works for most documents.' },
            { h: 'Apply and download', x: 'Look at pages 1, 2 and the last page before you print anything. Those three catch almost every mistake.' },
          ],
        },
        { t: 'cta', tool: 'page-numbers', x: 'Number every page of a PDF, with a cover-page skip and a custom starting number.' },
        { t: 'h2', x: 'Where to put the number' },
        {
          t: 'table',
          caption: 'Page number position by document type.',
          head: ['Position', 'Best for', 'Watch out for'],
          rows: [
            ['Bottom centre', 'Reports, essays, anything single-sided', 'Collides with a centred footnote or a company footer'],
            ['Bottom outer corner', 'Double-sided and bound documents', 'Needs a tool that alternates left and right by page parity'],
            ['Bottom right', 'Contracts, submissions, filings', 'Can be clipped by a printer with a large unprintable margin'],
            ['Top right', 'Manuscripts, legal exhibits', 'Fights with a running header, so pick one or the other'],
            ['Top centre', 'Rarely a good choice', 'Reads as a title on the first glance at each page'],
          ],
        },
        { t: 'note', x: 'PDF measures in points: 72 points to an inch. A4 is 595 x 842 points, US Letter is 612 x 792 points. A 36 point margin is half an inch on both, which is why that number appears as a default everywhere. Most consumer printers cannot print within about 12 points of the paper edge, so never set the margin below 18.' },
        { t: 'h2', x: 'The "1 of 12" format' },
        { t: 'p', x: 'A bare number tells a reader where they are. A "1 of 12" tells them whether anything is missing, which is why it is standard on faxed and posted documents, invoices, and anything handed across a desk. Use it whenever the document may be printed and separated from its file.' },
        { t: 'p', x: 'One trap: the total counts the pages in this file, not the pages in the logical document. If you number a 12-page file and then [merge it](/blog/merge-pdf/how-to-merge-pdf-files) with an 8-page appendix, every page still says "of 12" and now half of them are wrong. Merge first, number second. Always.' },
        { t: 'h2', x: 'Skipping a cover page' },
        { t: 'p', x: 'Two different settings are involved and they are easy to confuse:' },
        {
          t: 'table',
          head: ['Setting', 'What it controls', 'Example'],
          rows: [
            ['First page to number', 'Which sheet gets the first printed number', 'Set to 2 so the cover is left blank'],
            ['Starting number', 'What that first printed number says', 'Set to 1 so the second sheet reads "1"'],
            ['Both together', 'Cover unnumbered, body starting at 1', 'First page to number 2, starting number 1'],
            ['Continuation file', 'Numbering that carries on from an earlier PDF', 'First page to number 1, starting number 41'],
          ],
        },
        { t: 'p', x: 'For a document with front matter — a title page, a contents page, an executive summary — the traditional convention is roman numerals (i, ii, iii) on the front matter and arabic numerals restarting at 1 on the first page of the body. In a PDF tool this means two passes: number pages 2-5 as roman, then number page 6 onward as arabic starting at 1.' },
        { t: 'h2', x: 'Bates numbering for legal and discovery work' },
        { t: 'p', x: 'Bates numbering is page numbering with a fixed prefix and a fixed digit count, applied across a whole production set so that every page in a case has a unique identifier: `SMITH-000001`, `SMITH-000002`, and so on. The digit count is padded so the numbers sort correctly as text.' },
        {
          t: 'ul',
          items: [
            'Agree the prefix and the digit width with the other side before you produce anything. Six or seven digits is usual.',
            'Number the combined production, not each file separately, or you will have a hundred pages all claiming to be 000001.',
            'Place it bottom right, outside the text block, so it never covers evidence.',
            'Never renumber a set that has already been served. Add a new range instead.',
          ],
        },
        { t: 'h2', x: 'When numbers land on top of your text' },
        { t: 'p', x: 'This happens when the source document has no bottom margin to spare — dense slides, scanned pages trimmed close, or a report that already has a footer. Three fixes, in order:' },
        {
          t: 'ol',
          items: [
            'Move the number to a corner that is empty. Bottom right is usually freer than bottom centre.',
            'Increase the margin to 45-54 points so the number sits lower, and check that your printer can reach it.',
            'Scale the page content down. Printing at 96 percent scale creates a clear band at the bottom of every page, and at that ratio nobody notices the difference in text size.',
          ],
        },
        { t: 'tip', x: 'Numbering a scanned document works the same way, but the number is drawn as real text on top of an image. That means the number is searchable even when the rest of the page is not — a genuinely useful side effect when you are looking for a specific exhibit.' },
        { t: 'p', x: 'If you also need a document title or date on every page, add that as a [header or footer](/blog/watermark-page-numbers/add-header-footer-pdf) in the same pass rather than numbering twice.' },
      ],
      faqs: [
        { q: 'How do I add page numbers to a PDF for free?', a: 'Use a browser-based page numbering tool: drop the file in, choose a position and format, set the starting number, and download the result. It runs on your own machine, so there is no upload, no account and no watermark on the output.' },
        { q: 'How do I start page numbering on page 2 of a PDF?', a: 'Set "Leave first N pages unnumbered" to 1 and "Start at" to 1. The cover is left blank and the second sheet prints as page 1, which is the standard convention for a report with a title page.' },
        { q: 'Can I use a "Page 1 of 10" format?', a: 'Yes. Choose the "X of Y" format and the tool fills in the total from the page count of the file you loaded. Merge every part of the document together before numbering, or the total will be wrong on every page.' },
        { q: 'Will page numbers cover my existing footer?', a: 'They can. Move the number to a free corner, increase the margin to 45 points, or scale the page content to about 96 percent to open a clear band along the bottom edge before numbering.' },
        { q: 'Can page numbers be removed from a PDF afterwards?', a: 'They can be deleted in a PDF editor if the file was not flattened, since the number is a separate drawing object. It is far simpler to keep the original unnumbered file and renumber a fresh copy when the document changes.' },
      ],
      relatedTools: ['page-numbers', 'merge-pdf'],
      relatedPosts: ['add-header-footer-pdf', 'add-watermark-to-pdf', 'how-to-merge-pdf-files'],
    },
    {
      slug: 'add-header-footer-pdf',
      cluster: 'watermark-page-numbers',
      title: 'How to add a header or footer to a PDF',
      metaTitle: 'How to Add a Header or Footer to a PDF',
      metaDescription:
        'Add a company name, date or file reference to every page of a PDF. Margin settings, what belongs in a header or footer, and how to avoid covering text.',
      published: '2026-03-09',
      updated: '2026-08-02',
      readMinutes: 6,
      intent: 'howto',
      primaryKeyword: 'how to add a header or footer to a pdf',
      secondaryKeywords: ['add footer to pdf', 'pdf header text', 'add company name to every pdf page', 'add date to pdf pages', 'running header pdf'],
      entities: ['PDF', 'Adobe Acrobat', 'Microsoft Word', 'ISO 8601', 'Helvetica', 'US Letter', 'A4', 'LibreOffice'],
      answer:
        'To add a header or footer to a PDF, open it in a header and footer tool, type the text for the left, centre and right positions, set a margin of about 36 points from the paper edge, then apply it to the pages you want. Headers and footers are drawn onto each page as real text.',
      body: [
        { t: 'p', x: 'A header or footer answers the question a loose sheet of paper cannot: what is this, who produced it, and when. On a document that will be printed, filed, forwarded or photocopied, that line at the top or bottom of the page does more work than anything else you can add.' },
        { t: 'h2', x: 'What belongs where' },
        { t: 'p', x: 'The convention across publishing, legal and corporate documents is fairly consistent, and following it means readers find things without looking:' },
        {
          t: 'table',
          caption: 'Standard header and footer contents.',
          head: ['Position', 'Typical content', 'Example'],
          rows: [
            ['Header left', 'Document or chapter title', 'Q3 Operations Review'],
            ['Header right', 'Organisation or client name', 'Northwind Logistics'],
            ['Header centre', 'Classification, if any', 'CONFIDENTIAL'],
            ['Footer left', 'File reference or version', 'OPS-2026-11 v3'],
            ['Footer centre', 'Page number', '7 of 24'],
            ['Footer right', 'Date of issue', '2026-03-09'],
          ],
        },
        { t: 'p', x: 'Six fields is the maximum before the page starts to look like a form. Most documents only need three: title, page number, date. Add a fourth only when someone will actually use it.' },
        { t: 'h2', x: 'Adding one in the browser' },
        {
          t: 'steps',
          items: [
            { h: 'Open the file', x: 'Drop the PDF into the [page numbers and headers tool](/tools/page-numbers). Processing happens in the tab, so a confidential document stays on your machine.' },
            { h: 'Fill the fields you need', x: 'Left, centre and right are separate boxes for the header and again for the footer. Leave the ones you do not need empty rather than padding them with spaces.' },
            { h: 'Set the font size to 8-10pt', x: 'A header is reference information, not content. At 9pt Helvetica it reads clearly on paper and stays visually subordinate to 11pt body text.' },
            { h: 'Set the margin', x: 'Around 36 points, half an inch, from the top or bottom edge. Never below 18 points, because most printers cannot print in the outer 12 points of the sheet.' },
            { h: 'Choose the page range', x: 'Skip the cover page if it has its own title block. A header repeating the title directly under a large title looks like a mistake.' },
            { h: 'Preview pages 1, 2 and the last', x: 'Then download. Those three pages reveal collisions, wrong dates and cover-page problems.' },
          ],
        },
        { t: 'cta', tool: 'page-numbers', x: 'Add a header, footer and page numbers to every page in one pass.' },
        { t: 'h2', x: 'Avoiding overlap with the content' },
        { t: 'warn', x: 'Header and footer text is drawn on top of whatever is already on the page. Nothing reflows to make room. If the source document has no spare margin, your new header will sit across the first line of text, and it will do it on all 40 pages at once.' },
        { t: 'p', x: 'Check before you commit. Open the PDF, look at where the text block starts, and measure the gap:' },
        {
          t: 'ol',
          items: [
            'Most word processor exports leave a 1 inch (72 point) margin top and bottom. That is plenty — put the header at 36 points and it lands in clean space.',
            'Slides exported to PDF and marketing documents often run content to within 20 points of the edge. There is no safe band; scale the pages down before adding anything.',
            'Scanned pages vary sheet to sheet, because the scan itself is not perfectly aligned. Use the tightest page as your reference, not the first one.',
            'Documents that already have a footer need your text in a different horizontal slot, not a different vertical one.',
          ],
        },
        { t: 'tip', x: 'When there is genuinely no room, scale the page content to 94-96 percent before adding the header. This shrinks the printed area slightly and opens a clear band at both edges. At 96 percent, 11pt text becomes about 10.6pt, which nobody detects by eye.' },
        { t: 'h2', x: 'Dates: pick a format and freeze it' },
        { t: 'p', x: 'A date in a footer is a static piece of text, printed once when you apply it. It does not update when the file is reopened, which is exactly what you want on a document of record.' },
        {
          t: 'ul',
          items: [
            'Use **ISO 8601** — `2026-03-09` — for anything that will be sorted, filed or read internationally. It removes the 03/09 ambiguity between March and September entirely.',
            'Use a written month — `9 March 2026` — for documents going to clients or the public, where readability matters more than sortability.',
            'Label what the date means when it is not obvious: `Issued 2026-03-09` or `Valid until 2026-06-30`.',
            'Never put a generated timestamp on a document you will reissue. Two copies with different times in the footer look like two different documents.',
          ],
        },
        { t: 'h2', x: 'File references that pay for themselves' },
        { t: 'p', x: 'The most useful thing in a footer is usually not the date but the reference: a short code that ties the printed sheet back to the file it came from. A pattern like `OPS-2026-11 v3` tells you the owning team, the year, the sequence and the revision. When someone waves a page at you in a meeting, you can find the source in seconds.' },
        { t: 'p', x: 'Pair the reference with a version marker and a [DRAFT watermark](/blog/watermark-page-numbers/add-watermark-to-pdf) while the document is still moving, and drop the watermark for the final issue while keeping the reference. That way the printed archive shows which copies were provisional.' },
        { t: 'h2', x: 'What a header cannot do' },
        {
          t: 'table',
          head: ['Goal', 'Header or footer?', 'Better option'],
          rows: [
            ['Identify the document on a loose printed sheet', 'Yes, this is the core use', '—'],
            ['Mark a document as confidential', 'Partly — it is easy to miss', 'Add a watermark as well'],
            ['Prevent forwarding or copying', 'No', 'Encryption, and accept its [real limits](/blog/pdf-privacy/password-protect-pdf)'],
            ['Record who authored the file', 'Yes, visibly', 'Also check the hidden [document metadata](/blog/pdf-privacy/remove-metadata-from-pdf)'],
            ['Hide something already on the page', 'No, never', '[Proper redaction](/blog/pdf-privacy/redact-pdf-properly)'],
          ],
        },
        { t: 'note', x: 'Text added as a header is real, selectable, searchable text. That is useful: search a folder for a file reference and every printed-to-PDF copy comes back. It also means the header contents are extracted along with your document text, so do not put anything in a header you would not want in a text dump of the file.' },
        { t: 'p', x: 'Finish by adding [page numbers](/blog/watermark-page-numbers/add-page-numbers-to-pdf) in the same pass, and check the result at 100 percent zoom rather than fit-to-window — small text is where zoom lies to you.' },
      ],
      faqs: [
        { q: 'How do I add a company name to every page of a PDF?', a: 'Put it in the header right field of a header and footer tool, set the font to 9pt, apply to all pages, and download. It is drawn onto each page as real text, so it prints and searches like any other text in the file.' },
        { q: 'Why does my new header cover the existing text?', a: 'Header text is drawn over the page rather than pushing content down. The source document has no spare top margin. Either increase the margin so the header sits closer to the edge, or scale the page content to about 95 percent to open a clear band first.' },
        { q: 'Does the date in a PDF footer update automatically?', a: 'No. The date is written once as static text when you apply the footer, which is the right behaviour for a document of record. If you reissue the document, reapply the footer with the new date.' },
        { q: 'Can I add a header to only some pages?', a: 'Yes. Enter a page range before applying. Skipping the cover page is the most common case, since a header repeating the title under a large title block looks like an error.' },
        { q: 'What font size should a PDF header be?', a: 'Between 8 and 10 points, with 9pt as a reliable default. It stays legible on paper while remaining clearly subordinate to 11 or 12 point body text, which is what a reference line should be.' },
      ],
      relatedTools: ['page-numbers', 'add-watermark'],
      relatedPosts: ['add-page-numbers-to-pdf', 'add-watermark-to-pdf', 'remove-metadata-from-pdf'],
    },
    {
      slug: 'watermark-vs-stamp',
      cluster: 'watermark-page-numbers',
      title: 'Watermark, stamp, or redaction? Choosing the right mark',
      metaTitle: 'Watermark vs Stamp vs Redaction Explained',
      metaDescription:
        'Watermarks warn, stamps record an action, and redaction removes content for good. A comparison so you never use a visual mark where you need real removal.',
      published: '2026-04-06',
      updated: '2026-08-19',
      readMinutes: 5,
      intent: 'comparison',
      primaryKeyword: 'watermark vs stamp pdf',
      secondaryKeywords: ['difference between watermark and stamp', 'pdf stamp vs watermark', 'watermark or redaction', 'approved stamp pdf', 'visual mark vs redaction'],
      entities: ['PDF', 'Adobe Acrobat', 'Bates numbering', 'GDPR', 'redaction', 'digital signature', 'ISO 32000'],
      answer:
        'A watermark warns every reader about the whole document. A stamp records a specific action on a specific page, such as approved or received. Redaction removes content from the file permanently. Only redaction changes what the file contains; the other two only change how it looks.',
      body: [
        { t: 'p', x: 'Three marks, three completely different jobs, and one expensive way to confuse them: reaching for a visual mark when the requirement was actually removal. Data has leaked from court filings, published reports and corporate disclosures because somebody drew a black rectangle and assumed the words underneath had gone.' },
        { t: 'h2', x: 'The three in one table' },
        {
          t: 'table',
          caption: 'Watermark, stamp and redaction compared.',
          head: ['', 'Watermark', 'Stamp', 'Redaction'],
          rows: [
            ['Purpose', 'Set the status of the whole document', 'Record an action at a point in time', 'Remove content permanently'],
            ['Scope', 'Every page, or a page range', 'One spot on one page, usually', 'Specific words, figures or regions'],
            ['Typical text', 'DRAFT, CONFIDENTIAL, SAMPLE', 'APPROVED, RECEIVED, PAID, VOID', 'Nothing — the content is gone'],
            ['Appearance', 'Large, pale, diagonal, behind text', 'Small, opaque, often coloured, on top', 'Solid black box, or blank space'],
            ['Changes the file content?', 'Adds a mark', 'Adds a mark', 'Deletes the original content'],
            ['Reversible?', 'Yes, by anyone with an editor', 'Yes, by anyone with an editor', 'No, if done correctly'],
            ['Legal weight', 'Notice only', 'Evidence of a process step', 'Compliance control'],
            ['Fails when', 'Treated as access control', 'Treated as a signature', 'Faked with a drawn rectangle'],
          ],
        },
        { t: 'h2', x: 'Watermark: a warning to a cooperative reader' },
        { t: 'p', x: 'A watermark changes how a reader treats the document, and nothing else. It is the right choice when the risk you are managing is misunderstanding rather than misuse: a draft quoted as final, a template mistaken for a real certificate, an old version resurfacing after a policy change.' },
        { t: 'p', x: 'It works because it is unmissable and applies to every page, so a single sheet torn out of the stack still carries the warning. It fails the moment anyone treats it as protection. Anyone with a PDF editor deletes the object in two clicks. See [adding a watermark](/blog/watermark-page-numbers/add-watermark-to-pdf) for the settings that make one readable.' },
        { t: 'h2', x: 'Stamp: a record that something happened' },
        { t: 'p', x: 'A stamp is small, opaque and specific. It says a thing was done to this document: received on this date, approved by this person, paid, void, superseded. Its ancestor is the rubber stamp on a paper file, and it inherits the same convention — a stamp usually carries a date, often a name, and sits in a margin rather than across the content.' },
        {
          t: 'ul',
          items: [
            '**Dynamic stamps** in desktop editors fill in the current date, time and user name automatically. Useful for volume, but the name comes from the local application profile, so it proves who was logged in, not who agreed.',
            '**Approval stamps** are a workflow marker, not a legal signature. If a stamp needs to bind someone, use a [digital signature](/blog/sign-pdf/how-to-sign-a-pdf) instead, which cryptographically ties an identity to the exact bytes of the document.',
            '**Received stamps** are the most defensible use: they record an internal fact — this arrived on our desk on this date — which is exactly what a stamp is good at.',
          ],
        },
        { t: 'note', x: 'A stamp and a watermark are technically the same thing: content drawn onto the page. The difference is entirely convention — size, opacity, position and intent. Tools separate them because the settings you want are different, not because the file format treats them differently.' },
        { t: 'h2', x: 'Redaction: the only one that removes anything' },
        { t: 'warn', x: 'Drawing a black rectangle over text does not redact it. The text stays in the file underneath the box, and anyone can recover it by selecting the area and pressing copy, or by running a text extraction tool. The box is decoration drawn over the top.' },
        { t: 'p', x: 'Real redaction removes the underlying content from the file. In desktop tools this is a two-stage operation: mark the regions, then apply, at which point the text objects are deleted and replaced with a filled rectangle. In a browser toolkit, the reliable equivalent is to cover the regions and then rasterise each page to an image, which destroys the text layer entirely. Either way, you then verify by trying to select the text — the full method is in [how to redact a PDF properly](/blog/pdf-privacy/redact-pdf-properly).' },
        { t: 'h2', x: 'Choosing in ten seconds' },
        {
          t: 'table',
          head: ['If your sentence is…', 'You want'],
          rows: [
            ['"Readers should know this is not final"', 'A watermark'],
            ['"Every page should carry our name and a reference"', 'A [header or footer](/blog/watermark-page-numbers/add-header-footer-pdf)'],
            ['"This was approved on Tuesday by the finance team"', 'A stamp'],
            ['"I need to prove this document has not been altered"', 'A digital signature'],
            ['"Nobody outside the team may open this"', 'Encryption — with its [honest limits](/blog/pdf-privacy/password-protect-pdf)'],
            ['"These three names must not appear in the file"', 'Redaction, verified'],
            ['"Nobody should know which laptop made this"', 'Stripping the [metadata](/blog/pdf-privacy/remove-metadata-from-pdf)'],
          ],
        },
        { t: 'h2', x: 'Combining them' },
        { t: 'p', x: 'Real documents usually need two or three. A regulatory response might be redacted for third-party personal data, watermarked CONFIDENTIAL, footered with a file reference and issue date, and Bates numbered for the production set. The order matters: redact first, because rasterising pages afterwards would also flatten your marks and make later corrections impossible, then add marks, then number.' },
        {
          t: 'ol',
          items: [
            'Redact and verify. Confirm the text is genuinely unrecoverable before anything else touches the file.',
            'Merge every part of the document into its final shape.',
            'Add the watermark and any stamps.',
            'Add headers, footers and page numbers last, so the totals are correct.',
            'Strip the metadata on the outgoing copy, and keep the unmarked original somewhere safe.',
          ],
        },
        { t: 'cta', tool: 'add-watermark', x: 'Start with a watermark — free, in the browser, nothing uploaded.' },
        { t: 'p', x: 'The single rule worth remembering: a watermark and a stamp change what a reader sees, and redaction changes what the file contains. If the consequence of being wrong is a disclosure, only the third one counts.' },
      ],
      faqs: [
        { q: 'What is the difference between a watermark and a stamp in a PDF?', a: 'A watermark is large, pale and applied to every page to set the status of the whole document. A stamp is small, opaque and applied to one spot to record a specific action, such as approved or received, usually with a date.' },
        { q: 'Is a black box over text the same as redaction?', a: 'No. A drawn rectangle sits on top of the text, which remains in the file and can be recovered by copy and paste or by a text extraction tool. Real redaction deletes the underlying content, and must always be verified afterwards.' },
        { q: 'Does an APPROVED stamp count as a signature?', a: 'Not on its own. A stamp is a workflow marker with no cryptographic link to a person, and anyone with an editor can add or remove it. For a binding approval, use a digital signature that ties an identity to the exact contents of the file.' },
        { q: 'Should I watermark a document that is also encrypted?', a: 'Often yes. Encryption controls who can open the file; the watermark tells whoever legitimately opened it how to treat what they are reading. They solve different problems and work well together.' },
        { q: 'In what order should I redact, watermark and number a document?', a: 'Redact and verify first, then merge the document into its final shape, then add watermarks and stamps, then headers, footers and page numbers. Doing it in that order keeps page totals correct and keeps corrections possible.' },
      ],
      relatedTools: ['add-watermark', 'flatten-pdf'],
      relatedPosts: ['add-watermark-to-pdf', 'redact-pdf-properly', 'password-protect-pdf'],
    },
  ],
}
